### ISSUE TITLE
--quiet and --verbose

### ISSUE THREAD

**Issue by ptalmeida** [sherlock-project/sherlock#100]
Currently `--quiet` and `--verbose` are opposites, where --quiet is the default option. 

Given the number of websites covered by Sherlock, should `--quiet` be altered so that it is not the opposite of verbose but an option that displays only websites where the username has been found? 

This way no options remains as it is, `-v` as it is, and `-q` as described above.

**Comment by hoadlck** [comment]
The ```--quiet``` option is really intended to be related to debugging verbosity.  That being said, having a command line option to only show the sites that are found could be covered with a new set of options.  Maybe something like ```--list-found``` and ```--list-all```?  Where the ```--list-all``` would be the default.  Maybe "print" would be better than "list"?

The text file does only have the list of sites that have been found already.  Though the csv will always show everything.

**Comment by QingChongNotAnAsian** [comment]
My [pull request](https://github.com/TheYahya/sherlock/pull/178) adds that functionality, but by a silly name of '--nonotfound'. I like the --print-found, and I will implement it as soon as I can.

**Comment by sdushantha** [comment]
closing this as it has been fixed in #178
