### ISSUE TITLE
__main__ issue

### ISSUE THREAD

**Issue by diegoperales13212145** [sherlock-project/sherlock#1004]
## Checklist

- [ x] I'm reporting a bug in Sherlock's functionality
- [ x] The bug I'm reporting is not a false positive or a false negative
- [ x] I've verified that I'm running the latest version of Sherlock
- [ x] I've checked for similar bug reports including closed ones
- [ x] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

After about 3 successful tries it stopped working. I didn't even close the terminal between the times it worked and the times it hasn't. If it's not sherlock what could it be?

**Comment by RPwnage** [comment]
Could you be more specific? What stopped working?

**Comment by diegoperales13212145** [comment]
Sherlock stopped outputting usernames and instead keep outputting: can't find '__main__' module in '/Users/diegoperales/sherlock'
I checked to see if the file was missing and it is there. I moved it to see what message it would give and it gave a completely different error.

**Comment by diegoperales13212145** [comment]
> Could you be more specific? What stopped working?

Sherlock stopped outputting usernames and instead keep outputting: can't find 'main' module in '/Users/diegoperales/sherlock'
I checked to see if the file was missing and it is there. I moved it to see what message it would give and it gave a completely different error.

**Comment by sdushantha** [comment]
You forgot to `cd` into the `sherlock/` directory. That is why the "main" module cannot be found because it is located in the sub directory which is also called `sherlock`
