### ISSUE TITLE
i cant run with python3


### ISSUE THREAD

**Issue by dhinesh993** [sherlock-project/sherlock#1008]
## Checklist

- [ ] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE

**Comment by igosad** [comment]
hello 
are you getting this error ? 
`/usr/bin/python3: can't find '__main__' module in 'sherlock'`

**Comment by igosad** [comment]
Maybe try to share the error code or more info about the problem.

**Comment by Danger2099** [comment]
في أحد، 14 مارس، 2021 في 2:24 م، كتب igosad ***@***.***>:

**Comment by RealFinalCode** [comment]
If you reference to the following command: "python3 -m pip install -r requirements.txt".
You don't need to run the command with python3 you can also use python as long as you have installed python 3.
You can check your version with "python --version".

**Comment by sdushantha** [comment]
This is an issue with your environment and not Sherlock it self. Closing.
