### ISSUE TITLE
Account does not exist

### ISSUE THREAD

**Issue by Sherlockcxk** [sherlock-project/sherlock#1010]
Once I enter a long, nonsense user name, which is "adjfhjuefhujrqehfhdbdfjvndfjgre", but it still give me an URL in mobile.twitter.com ([](https://mobile.twitter.com/adjfhjuefhujrqehfhdbdfjvndfjgre)). When I enter the page, though it says the account does not exist, the status code show 202 instead of 404 not found.
![Capture](https://user-images.githubusercontent.com/74444486/111214278-62dae280-8597-11eb-9fff-bfe43ed937ef.PNG)

**Comment by suhaskv1** [comment]
This is a false positive right? I got similar results with arbitrary usernames with twitter, as well as other sites listed as false positives in the issues section

**Comment by RealFinalCode** [comment]
#1034

**Comment by sdushantha** [comment]
Duplicate of #1034 as @RealFinalCode stated. Closing.
