### ISSUE TITLE
Could not open requirements file: [Errno 2] No such file or directory: 'requirments.txt'

### ISSUE THREAD

**Issue by Stefanqw2** [sherlock-project/sherlock#1015]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE

**Comment by Stefanqw2** [comment]
I try to install sherlock on 3 difernet divicees and the same problem

**Comment by igosad** [comment]
did you change the working directory to sherlock ?
using `cd sherlock
`

**Comment by Ryannnkl** [comment]
there are two directories, "sherlock" to enter the project and "sherlock" for the python code, the requirements.txt file is in the first

```bash
git clone https://github.com/sherlock-project/sherlock.git

cd sherlock

python3 -m pip install -r ./requirements.txt

# and

cd sherlock

python3 sherlock user123
```
