### ISSUE TITLE
Adding Keywords to username search.

### ISSUE THREAD

**Issue by AayushBoliya** [sherlock-project/sherlock#1023]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

Ability to add Keywords with the usernames, as usernames could also be combination of DOB or Some other number and name, increasing number of possible usernames. By adding search keywords such as age, profession etc. that could or couldn't exist on the site, the chances of finding the person accurately increases.

**Comment by sdushantha** [comment]
I like your idea but we have no plans on adding support for this. Sherlock has the support for searching through a list of usernames from a given file. There are many wordlist generators out there which can are meant for creating password lists, but you can use it to create usernames. Then pass the file with the generated usernames to Sherlock.
