### ISSUE TITLE
Sherlock API (rework architecture)

### ISSUE THREAD

**Issue by IJustDev** [sherlock-project/sherlock#1026]
## Checklist

- [X] I'm reporting a feature request
- [X] I've checked for similar feature requests including closed ones

## Description

I want to use Sherlock in my project but the current architecture doesn't allow running Sherlock and retrieve the results. 
This would at first hand require a pip package.

**Comment by soxoj** [comment]
I suggest you pay attention to the sherlock fork called [maigret](https://github.com/soxoj/maigret). It distributed through pip package, has a simple API ([example](https://github.com/soxoj/maigret-tg-bot)), supports more sites and additional features.

**Comment by snooppr** [comment]
Please ignore "Maigret".  It is a pirated tool that illegally used the [Snoop Project](https://github.com/snooppr/snoop) database.  The attacker licensed Snoop, but with the intention of creating his pirated tool by including the Snoop database.  I have learned about libel on the Internet and confirm that what I have said is true.

More about pirate, for example, [here](https://github.com/BlackArch/blackarch/issues/2848#issuecomment-739153757)

[Pirate](https://gitlab.com/soxoj) records (blocked for copyright infringement)
