### ISSUE TITLE
A problem occured while checking for an update: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by inheritorr** [sherlock-project/sherlock#1030]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE
E:\Sherlock\sherlock\sherlock>python sherlock.py qwerty
A problem occured while checking for an update: check_hostname requires server_hostname
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  check_hostname requires server_hostname

**Comment by sdushantha** [comment]
This is an issue with your environment and not Sherlock itself.
