### ISSUE TITLE
Trailing commajson(519)[545, 4] File: removed_sites.json  

### ISSUE THREAD

**Issue by RealEnt3** [sherlock-project/sherlock#1033]
537 ` },`
538`  "Ebay": {`
539 `    "errorMsg": "<title>eBay Profile - error</title>",`
540 `    "errorType": "message",`
541 `    "url": "https://www.ebay.com/usr/{}",`
542 `    "urlMain": "https://www.ebay.com/",`
543 `    "username_claimed": "blue",`
544 `    "username_unclaimed": "noonewouldeverusethis7"`
545 `  },`
546 `}`

removed_sites.json

Trailing commajson(519)[545, 4]

**Comment by RealFinalCode** [comment]
Your error is that you have an trailing comma in line 545 which is not allowed at the last object.
