### ISSUE TITLE
False positive twitter

### ISSUE THREAD

**Issue by SVijayB** [sherlock-project/sherlock#1034]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

Returned a false positive when I tried the username `adjfhjuefhujrqehfhdbdfjvndfjgre`. Tried various other cases and got similar false-positive results.

**Comment by michaelmano** [comment]
Ill add some more information, going to https://twitter.com/testtesttesttest shows no account however going to https://twitter.com/testtesttesttestasdasdasdas shows the page not existing.

**Comment by sdushantha** [comment]
I removed Twitter in ac5b42c5bf283d689e272b47734419e2b469659d for now to further prevent false positive results while running Sherlock. But we must find a way to check for usernames.

**Comment by SVijayB** [comment]
Lessgooo, thanks @sdushantha!
