### ISSUE TITLE
could only install using "python" instead of "python3"

### ISSUE THREAD

**Issue by katarinads** [sherlock-project/sherlock#1037]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

Do i have to update python to use standard " python3 -m pip install -r requirements.txt" line?

**Comment by RealFinalCode** [comment]
**Your question is not regarding Sherlock!** But anyway...
You don't have to update Python. You can see which version you are using with the following Command "python --version".

**Comment by 404oops** [comment]
If it says 2 then you need to install Python 3. You can find instructions on how to install it if you're clueless.

**Comment by C4l1b3r** [comment]
Install pipenv and run it that way

**Comment by sdushantha** [comment]
This question is regarding Python and not Sherlock. Closing.
