### ISSUE TITLE
SHERLOCK // PYTHON ERROR

### ISSUE THREAD

**Issue by dxrknightmare13** [sherlock-project/sherlock#1038]
First i get the error for Sherlock telling me __Main__ isnt detected in Sherlock folder then
 i think i fixed that. But i aslo get this message when trying to use Sherlock  :~:

 Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/sherlock/__main__.py", line 30, in <module>
    sherlock.main()
AttributeError: module 'sherlock' has no attribute 'main'   

How do i fix this?

**Comment by ataboiT8** [comment]
1 are you on the right verison of python and 2 make sure u have everthing installed like from and import things

**Comment by kutakizukari** [comment]
Sounds like you're on a fresh install?

If you're on Ubuntu, run these before running the install scripts:

sudo apt update && sudo apt upgrade -y

sudo reboot

apt-get install pip

**Comment by 404oops** [comment]
uhhhhhhhhhhhh you're wrong on this

what you should do is: 

`sudo apt update; sudo apt upgrade; sudo apt install python3-pip`

and restart
