### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by miles190** [sherlock-project/sherlock#1046]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE

**Comment by hoadlck** [comment]
No content to question?  Not sure if this is a bot account, or just someone new...  But, no need to leave this open.

**Comment by miles190** [comment]
Hi I want to know how to install the sherlock project ? I dont know how?

**Comment by RealFinalCode** [comment]
Go to the main page of sherlock: https://github.com/sherlock-project/sherlock

If you scroll a little bit down you will find a Installation section.

If you ran into some issue using python3 try using python. It seems like on some pcs the python executable is named diffrently.
