### ISSUE TITLE
cd sherlock

### ISSUE THREAD

**Issue by Marwan7677** [sherlock-project/sherlock#1051]
## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by slayer321** [comment]
what is the bug?

**Comment by HadesStyx** [comment]
I think we're on maras @slayer321

**Comment by slayer321** [comment]
sorry, but what do you mean by maras?
