### ISSUE TITLE
ไม่สามารถทำได้ เลยคะ เพราะหนูโดน แฮ้กมานานแล้ว รู้ติดตามคุกคามมาตลอด มีข้อผิดพลาด ตลอด  สกัดไว้หมด มีการปลอมแปลงเครือข่าย  พอร์ตภายนอกไม่มี  ปัญหาซึ่งหนูไมาสามารถแก้ไขอะไรได้เลย จะขอให่ช่วย หนูด้วย

### ISSUE THREAD

**Issue by Dragonball39** [sherlock-project/sherlock#1061]
คะ

## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by prithvi2k2** [comment]
SPAM!

**Comment by hoadlck** [comment]
Google translate says that this is Thai:

> I can't do it at all because I have been hacked for a long time. Known to keep track of all the threats, always have errors, are all extracted, network spoofing no external port Problems which I can't solve at all, will you please help me?

I don't understand exactly what the problem is, but it sounds like an environmental issue: not a problem with Sherlock itself.
