### ISSUE TITLE
Alltrails false positive

### ISSUE THREAD

**Issue by skhaz** [sherlock-project/sherlock#1067]
## Checklist

- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a seperate issue for each site)

## Description

* https://www.alltrails.com/members/adasaaakzzzzzzzzsdsdsdasdadadasqe22aasd

**Comment by sdushantha** [comment]
Site has been dealt with in a73afe674ece1750c7859be63a72fbd04fe7ea9d
