### ISSUE TITLE
Anobii false positive

### ISSUE THREAD

**Issue by skhaz** [sherlock-project/sherlock#1068]
## Checklist

- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a seperate issue for each site)

## Description

https://www.anobii.com/adasaaakzzzzzzzzsdsdsdasdadadasqe22aasd/profile

**Comment by sdushantha** [comment]
Site has been dealt with in 28b04ddf559864799f418967d40a44bdbf1461d3
