### ISSUE TITLE
beta.cent.co false positive

### ISSUE THREAD

**Issue by skhaz** [sherlock-project/sherlock#1069]
## Checklist

- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a seperate issue for each site)

## Description

https://beta.cent.co/@adasaaakzzzzzzzzsdsdsdasdadadasqe22aasd

**Comment by sdushantha** [comment]
I removed the site because there is not way of checking if a username exists on Cent
