### ISSUE TITLE
chess.com false positive

### ISSUE THREAD

**Issue by skhaz** [sherlock-project/sherlock#1070]
## Checklist

- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a seperate issue for each site)

## Description

https://www.chess.com/member/adasaaakzzzzzzzzsdsdsdasdadadasqe22aasd

**Comment by sdushantha** [comment]
Fixed in da7a9572f443554ddf50b32927cb8f13d953bd03
