### ISSUE TITLE
liveleak.com false positive

### ISSUE THREAD

**Issue by skhaz** [sherlock-project/sherlock#1071]
## Checklist

- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a seperate issue for each site)

## Description

https://www.liveleak.com/c/adasaaakzzzzzzzzsdsdsdasdadadasqe22aasd

**Comment by sdushantha** [comment]
This has been fixed. The reason for the false positive was because they changed the name of their site to Itemfix.com
