### ISSUE TITLE
namemc.com false positive

### ISSUE THREAD

**Issue by skhaz** [sherlock-project/sherlock#1072]
## Checklist

- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a seperate issue for each site)

## Description

https://namemc.com/profile/adasaaakzzzzzzzzsdsdsdasdadadasqe22aasd

**Comment by sdushantha** [comment]
Fixed in aaff63e2a72acd45284fe79e66ce44af28ebfee8
