### ISSUE TITLE
producthunt.com false positive

### ISSUE THREAD

**Issue by skhaz** [sherlock-project/sherlock#1073]
## Checklist

- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a seperate issue for each site)

## Description

https://www.producthunt.com/@adasaaakzzzzzzzzsdsdsdasdadadasqe22aasd

**Comment by sdushantha** [comment]
Fixed in a4df5010f49044eb1f1713057e8914e6a5a104b3
