### ISSUE TITLE
quizlet.com false positive

### ISSUE THREAD

**Issue by skhaz** [sherlock-project/sherlock#1074]
## Checklist

- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a seperate issue for each site)

## Description

https://quizlet.com/adasaaakzzzzzzzzsdsdsdasdadadasqe22aasd

**Comment by sdushantha** [comment]
Quizlet does not have any false positives:
![image](https://user-images.githubusercontent.com/27065646/123539437-11b3c080-d73a-11eb-948e-83955b1a9315.png)
