### ISSUE TITLE
steamid.uk false positive

### ISSUE THREAD

**Issue by skhaz** [sherlock-project/sherlock#1075]
## Checklist

- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a seperate issue for each site)

## Description

https://steamid.uk/profile/adasaaakzzzzzzzzsdsdsdasdadadasqe22aasd

**Comment by sdushantha** [comment]
Site has been dealt with in 5352036e80253594ce79859c9310fa947e88c4b0
