### ISSUE TITLE
tiktok.com false positve

### ISSUE THREAD

**Issue by skhaz** [sherlock-project/sherlock#1076]
## Checklist

- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a seperate issue for each site)

## Description

https://tiktok.com/@adasaaakzzzzzzzzsdsdsdasdadadasqe22aasd

**Comment by sdushantha** [comment]
TikTok does not have any false positives on my end:
![image](https://user-images.githubusercontent.com/27065646/123540096-8dfbd300-d73d-11eb-9f3c-260370ca4048.png)
