### ISSUE TITLE
www.eyeem.com false positive

### ISSUE THREAD

**Issue by contributorpw** [sherlock-project/sherlock#1077]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a seperate issue for each site)

## Description

user@buggyyaggi.net

Related #813

**Comment by sdushantha** [comment]
Eyeem seems to not have any issues on my end:
![image](https://user-images.githubusercontent.com/27065646/123539992-dbc40b80-d73c-11eb-9f50-ea5e513f3a2b.png)
