### ISSUE TITLE
Same for email?

### ISSUE THREAD

**Issue by KC38** [sherlock-project/sherlock#1079]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Can you add an email search as well? Would be really nice to see what services are associated with my email.

**Comment by sdushantha** [comment]
I dont have plans on adding support for email lookups anytime soon. In the mean time take a look at https://github.com/megadose/holehe

**Comment by KC38** [comment]
Thanks a lot! Both are great projects.
