### ISSUE TITLE
Replit not working with Sherlock 

### ISSUE THREAD

**Issue by Rxann** [sherlock-project/sherlock#1088]
## Checklist

> - [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description
<!--
Provide a detailed description of the bug that you have found in Sherlock.
Provide the version of Sherlock you are running.
<!--

I am running the newest version version of Sherlock and I am trying to run the project on replit and it is not running.I have tried  cloning the project and running, nothing worked. Also, I suggest that Sherlock is turned into a replit app.

**Comment by Rxann** [comment]
I accidently didn't add the text so I am going to do it here: I am trying to use Sherlock on replit and it is not working. I have tried all methods and nothing works. I also tried cloning the git repo to replit. Also, I would love sherlock to turn into a replit app.

**Comment by prithvi2k2** [comment]
Use console or shell in forked repl and execute the following commands:
 ```
python -m pip install -r requirements.txt
```

and that's all, it will be up and running for that instance, use the following commands after installing required packages...
To search for only one user:
```
python sherlock user123
```

To search for more than one user:
```
python sherlock user1 user2 user3
```

**Comment by prithvi2k2** [comment]
@Rxann I don't think this is a bug, it's working as expected for me, just install required packages and run it

**Comment by Rxann** [comment]
Alright Thank you so much!
