### ISSUE TITLE
Crypto Tab

### ISSUE THREAD

**Issue by dikaio** [sherlock-project/sherlock#1090]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE

Was curious why does this project need to have the service Crypto Tab Browser (https://zihihu.com) running in the background?

**Comment by hoadlck** [comment]
It does not.  Why do you think that it does?

**Comment by dikaio** [comment]
Hi @hoadlck. My apologize, yesterday when I fired up sherlock for the first time the app little snitch caught an outbound connection to `zhihu.com` but looking further into this it was trigged by python, installed via asdf. I will raise the question there.

![ss](https://user-images.githubusercontent.com/869535/121095263-dc542c80-c7a4-11eb-8199-f9efcf6d8bbe.png)
