### ISSUE TITLE
https://www.facebook.com/profile.php?id=100056660483428

### ISSUE THREAD

**Issue by omerali99** [sherlock-project/sherlock#1092]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by prithvi2k2** [comment]
Issues can't be more worsley reported than this!
