### ISSUE TITLE
14 false positives

### ISSUE THREAD

**Issue by Oakchris1955** [sherlock-project/sherlock#1094]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [ ] I've checked for similar site support requests including closed ones
- [ ] I've checked for pull requests attempting to fix this false positive
- [ ] I'm only reporting **one** site (create a separate issue for each site)

## Description

Username: Random characters, 23905875ekjrgcfn8own

Sites that provide a false positive:

- AllTrails
- Anobii
- Cent
- Chess
- Kali community
- LiveLeak
- NameMC (Minecraft.net skins)
- ProductHunt
- Quizlet
- Steamid
- Telegram
- Twitter
- YouTube
- babyblogRU

**Comment by Oakchris1955** [comment]
Note: They are now 12

**Comment by prithvi2k2** [comment]
LiveLeak is no more, I opened a PR at #1098 <<--Refer this

**Comment by prithvi2k2** [comment]
> Username: Random characters, 23905875ekjrgcfn8own

**Status (View #1098 for details):**

Checkmarks indicate successful solutions 
- [ ] AllTrails
- [x] Anobii
- [x] Cent
- [x] Chess
- [x] Kali community
- [x] LiveLeak
- [ ] NameMC (Minecraft.net skins)
- [x] ProductHunt
- [ ] Quizlet
- [ ] Steamid
- [ ] Telegram
- [ ] Twitter
- [ ] YouTube
- [ ] babyblogRU

**Comment by prithvi2k2** [comment]
> Note: They are now 12

@Oakchris1955 which of the two sites are fixed?

**Comment by Oakchris1955** [comment]
> EDIT: how can they be fixed automatically, there aren't any commits in that scope.

I don't know
> @Oakchris1955 which of the two sites are fixed?

Quizlet and Telegram

**Comment by adde88** [comment]
Alot of the same websites are producing false-positives for me as well.

**Comment by sdushantha** [comment]
I have dealt* with all of these sites in the commits made today.

*dealt != fixed

Sites such as YouTube and Twitter have been removed due to false positives, but I'll prioritise them when I try to add sites back to `data.json` from the removed site list.
