### ISSUE TITLE
Free form text search on the profiles

### ISSUE THREAD

**Issue by VatsalJagani** [sherlock-project/sherlock#1096]
## Checklist
- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description
Sherlock is a wonderful tool to search for usernames. But in general, in-term to search user on social media accounts you should be able to search account with free form text like "<First Name> <Last Name>". Or even better if we can free form search other information like college, city, friend names, etc.

### Possible Implementation
* We could either use selenium based driver to search with first-name and last-name with general search feature of the social media site.
* Or we could use API based search if available for the social media.
* Once we get list of user, checkout all those matched profile to and make a free form search with other details (like college, city, friend names, etc) and generate best match in sorted order.

**Comment by prithvi2k2** [comment]
Contributions are welcome!

**Comment by sdushantha** [comment]
Great idea! Unfortunately we have not plans on implementing this to Sherlock as this is something that can be done with Sherlock wrapped in a script. If this is something you really want, you can always create a script which created the possible usernames and then pass them to Sherlock.
