### ISSUE TITLE
h

### ISSUE THREAD

**Issue by olivercloseoff6969** [sherlock-project/sherlock#1101]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by Oakchris1955** [comment]
Spam?
