### ISSUE TITLE
RESULTS DOES NOT INCLUDE INSTGRAM 

### ISSUE THREAD

**Issue by moraddart5** [sherlock-project/sherlock#1114]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by tmak2002** [comment]
Instagram is removed see here:
https://github.com/sherlock-project/sherlock/commit/684401c0a1bd467b127ac1346a23ed7ad2902075

**Comment by xortio** [comment]
> Instagram is removed see here:
> [684401c](https://github.com/sherlock-project/sherlock/commit/684401c0a1bd467b127ac1346a23ed7ad2902075)

how to get instagram in the search list

**Comment by JDR11** [comment]
Instagram readded in:
039debb

**Comment by SethFalco** [comment]
Like stated above, Instagram was readded! 🎉 
I'll close this issue.
