### ISSUE TITLE
python3: can't open file 'sherlock.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by anderpro** [sherlock-project/sherlock#1115]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by RealFinalCode** [comment]
are you in the right directory?

**Comment by ThinkerDesigns** [comment]
the directory has been changed to <your dir>/sherlock/sherlock/sherlock.py

**Comment by plutoMOB** [comment]
> the directory has been changed to /sherlock/sherlock/sherlock.py

How do I fix it then?

**Comment by ThinkerDesigns** [comment]
just clone the git 
cd sherlock/
./sherlock/sherlock.py

> > the directory has been changed to /sherlock/sherlock/sherlock.py
> 
> How do I fix it then?

**Comment by Hakem1972** [comment]
> just clone the git 
> 
> cd sherlock/
> 
> ./sherlock/sherlock.py
> 
> 
> 
> > > the directory has been changed to /sherlock/sherlock/sherlock.py
> 
> > 
> 
> > How do I fix it then?
> 
> 
> 
>

**Comment by Hakem1972** [comment]
> just clone the git 
> 
> cd sherlock/
> 
> ./sherlock/sherlock.py
> 
> 
> 
> > > the directory has been changed to /sherlock/sherlock/sherlock.py
> 
> > 
> 
> > How do I fix it then?
> 
> 
> 
>

**Comment by Hakem1972** [comment]
> just clone the git 
> 
> cd sherlock/
> 
> ./sherlock/sherlock.py
> 
> 
> 
> > > the directory has been changed to /sherlock/sherlock/sherlock.py
> 
> > 
> 
> > How do I fix it then?
> 
> 
> 
>

**Comment by Hakem1972** [comment]
> > just clone the git 
> > 
> > cd sherlock/
> > 
> > ./sherlock/sherlock.py
> > 
> > 
> > 
> > > > the directory has been changed to /sherlock/sherlock/sherlock.py
> > xxxxqrt
> > > 
> > 
> > > How do I fix it then?
> > 
> > 
> > 
> > 
> 
>

**Comment by Hakem1972** [comment]
> just clone the git 
> 
> cd sherlock/
> 
> ./sherlock/sherlock.py
> 
> 
> 
> > > the directory has been changed to /sherlock/sherlock/sherlock.py
> 
> > 
> 
> > How do I fix it then?
> 
> 
> 
>

**Comment by Hakem1972** [comment]
> 
> 
> 
> 
> 
> 
> ## Checklist
> 
> 
> 
> 
> 
> - [x] I'm reporting a bug in Sherlock's functionality
> 
> - [ ] The bug I'm reporting is not a false positive or a false negative
> 
> - [ ] I've verified that I'm running the latest version of Sherlock
> 
> - [ ] I've checked for similar bug reports including closed ones
> 
> - [ ] I've checked for pull requests that attempt to fix this bug
> 
> 
> 
> ## Description
> 
> 
> 
> 
> 
> WRITE DESCRIPTION HERE
> 
> 
1
python3 ./sherlock.py USERNAME

**Comment by Hakem1972** [comment]
> just clone the git 
> 
> cd sherlock/
> 
> ./sherlock/sherlock.py
> 
> 
> 
> > > the directory has been changed to /sherlock/sherlock/sherlock.py
> 
> > 
> 
> > How do I fix it then?
> 
> 
> 
> 

1
python3 ./sherlock.py USERNAME

**Comment by Hakem1972** [comment]
> > just clone the git 
> > 
> > cd sherlock/
> > 
> > ./sherlock/sherlock.py
> > 
> > 
> > 
> > > > the directory has been changed to /sherlock/sherlock/sherlock.py
> > 
> > > 
> > 
> > > How do I fix it then?
> > 
> > 
> > 
> > 
> 
> 1
> python3 ./sherlock.py USERNAME
> 
Xxxxqrt

**Comment by Hakem1972** [comment]
> > just clone the git 
> > 
> > cd sherlock/
> > 
> > ./sherlock/sherlock.py
> > 
> > 
> > 
> > > > the directory has been changed to /sherlock/sherlock/sherlock.py
> > 
> > > 
> > 
> > > How do I fix it then?
> > 
> > 
> > 
> > 
> 
> 1
> python3 ./sherlock.py USERNAME
> 
>  Xxxxqry

**Comment by Hakem1972** [comment]
> > > just clone the git 
> > > 
> > > cd sherlock/
> > > 
> > > ./sherlock/sherlock.py
> > > 
> > > 
> > > 
> > > > > the directory has been changed to /sherlock/sherlock/sherlock.py
> > > 
> > > > 
> > > 
> > > > How do I fix it then?
> > > 
> > > 
> > > 
> > > 
> > 
> > 1
> > python3 ./sherlock.py USERNAME
> > 
> >  Xxxxqrt
> 
>

**Comment by Hakem1972** [comment]
> the directory has been changed to <your dir>/sherlock/sherlock/sherlock.py

**Comment by Hakem1972** [comment]
Xxxxart

**Comment by Hakem1972** [comment]
> Xxxxart

**Comment by Hakem1972** [comment]
> > > just clone the git 
> > > 
> > > cd sherlock/
> > > 
> > > ./sherlock/sherlock.py
> > > 
> > > 
> > > 
> > > > > the directory has been changed to /sherlock/sherlock/sherlock.py
> > > 
> > > > 
> > > 
> > > > How do I fix it then?
> > > 
> > > 
> > > 
> > > 
> > 
> > 1
> > python3 ./sherlock.py USERNAME
> > 
> 
> 
> python ./sherlock.py --print-found USER_NAME1

**Comment by Hakem1972** [comment]
> > just clone the git 
> > 
> > cd sherlock/
> > 
> > ./sherlock/sherlock.py
> > 
> > 
> > 
> > > > the directory has been changed to /sherlock/sherlock/sherlock.py
> > 
> > > 
> > 
> > > How do I fix it then?
> > 
> > 
> > 
> > 
> 
> 1
> python3 ./sherlock.py USERNAME
> 
>  Xxxxqry

**Comment by TheGuyDangerous** [comment]
you aren't in the right directory 
/sherlock/sherlock/sherlock.py
type cd Sherlock
ls
cd sherlock
//and then proceed
python3 sherlock.py username

**Comment by izederf** [comment]
for me it worked python3.9 sherlock.py username, but first use sudo apt-get update and sudo apt-get upgrade first and then use python3.9 sherlock.py username

**Comment by RadinhoDePilha** [comment]
First execute the installation described in the main page.
Second, inside the folder sherlock that you cloned, you can execute 
`ls`
It will show the archives and folders inside your directory
If it gave you a list with the file 'sherlock.py', so simply execute:
`python3 sherlock.py USERNAME`
And it will work

If the 'ls' gave you a list like:
`CODE_OF_CONDUCT.md
CONTRIBUTING.md
docker-compose.yml
Dockerfile
images
LICENSE
README.md
removed_sites.json
removed_sites.md
requirements.txt
sherlock
site_list.py
sites.md`
Execute:
`python3 sherlock USERNAME`
