### ISSUE TITLE
?

### ISSUE THREAD

**Issue by verinova771** [sherlock-project/sherlock#1118]
## Checklist

- [ ] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE

**Comment by Oakchris1955** [comment]
Spam bot?
