### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by SuperSandro2000** [sherlock-project/sherlock#1120]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

It would be great for downstream packaging if you would tag releases with git.

**Comment by mjsir911** [comment]
Yeah :+1: from me as well (would package for gentoo)

**Comment by ppfeister** [comment]
Closing as project does in fact now use tagged releases

Not quite semver yet, but close enough
