### ISSUE TITLE
Sherlock gets stuck after searching Duolingo

### ISSUE THREAD

**Issue by mutilenka** [sherlock-project/sherlock#1121]
## Checklist

- [x] Don't really know if it is a bug (I'm not tech savvy : )) )
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

Sherlock starts its search, everything goes fine until it finishes going through duolingo. I've read the site list, apparently it's stuck at ebay. I don't know the reason why it does that. Removing ebay from its searchlist is a perfectly fine option as well, if a fix is impossible but how do we remove it?

**Comment by Oakchris1955** [comment]
try with the option `--timeout 3`

**Comment by sdushantha** [comment]
The method @Oakchris1955 mentioned should work, but many changes have been made to the data.json so you should not be experiencing any lag now :)
