### ISSUE TITLE
FP: ok.ru

### ISSUE THREAD

**Issue by netoeuler** [sherlock-project/sherlock#1122]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

WRITE DESCRIPTION HERE
Checking my Twitter handle, which is netonightmare, one of the results was:
[+] OK: https://ok.ru/netonightmare

But looking at this URL, the HTTP status is 404 and a page indicating that this page does not exists is showed.

![Screenshot from 2021-08-15 14-17-56](https://user-images.githubusercontent.com/3870633/129486757-51a1cbdc-fab5-4e65-8af4-c8c4fee49155.png)

![Screenshot from 2021-08-15 14-18-39](https://user-images.githubusercontent.com/3870633/129486785-c7f20ab1-0421-4563-99e8-4821681084cb.png)

**Comment by Oakchris1955** [comment]
This is a fake positive. It happens often and I don't think you can do anything for it except reporting it

**Comment by sdushantha** [comment]
ok.ru does seems to not return any false positives. Will be closing this.
