### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by hogan777** [sherlock-project/sherlock#1126]
Ran the tool using Python from the command line..

python3 sherlock.py usernameXXX

I am getting the below error.. Python version is Python 3.9.2

Traceback (most recent call last):
  File "/home/kali/sherlock/sherlock/sherlock.py", line 20, in <module>
    from requests_futures.sessions import FuturesSession
ModuleNotFoundError: No module named 'requests_futures'

**Comment by sdushantha** [comment]
This is an issue with your environment and not Sherlock
