### ISSUE TITLE
Append files instead of replacement

### ISSUE THREAD

**Issue by greaturchin** [sherlock-project/sherlock#1128]
## Checklist
- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description
When I repeat queries for the same username I would like to append the output file rather than replace it. Better yet, add dates when rows are added, and add status such as "new", "changed", "gone" or whatever.

**Comment by noobyogi0010** [comment]
@greaturchin Can I work on this enhancement?

**Comment by sdushantha** [comment]
I personally dont this feature is needed. When you run Sherlock multiple times, you tend to get the same results so appending the results to the same file would not have much use.
