### ISSUE TITLE
Deepin Linux: sherlock can't work

### ISSUE THREAD

**Issue by Parrothhq** [sherlock-project/sherlock#1133]
I have met this problem:

A problem occured while checking for an update: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/sherlock.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f195c6fc320>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/resources/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f195c70f780>: Failed to establish a new connection: [Errno 111] Connection refused'))

What's going on? I could use it yesterday, everything was okay. However, when I restart my computer and run sherlock, it went like this. How can I deal with it?

**Comment by Parrothhq** [comment]
I've run a command yesterday:
sudo apt autoremove

**Comment by sdushantha** [comment]
This is an issue on your side and not an issue with Sherlock. It might be helpful to check on Stackoverflow or Reddit.
