### ISSUE TITLE
False positive on `guns.ru`

### ISSUE THREAD

**Issue by bb1950328** [sherlock-project/sherlock#1138]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

`sherlock.py` says it found my username (bb1950328) on guns.ru but I never created an account there and the link <https://forum.guns.ru/forummisc/blog/bb1950328> returns HTTP status 200 and an empty page. I can replace my username with any string in the link and it returns the same empty page so that might be the issue.

**Comment by sdushantha** [comment]
This site does return any false positives
![image](https://user-images.githubusercontent.com/27065646/140311544-9adb107b-a4be-4c79-88a9-e755d748c6fb.png)
