### ISSUE TITLE
can i customize the tool to look into websites that i choose ?

### ISSUE THREAD

**Issue by unknwon11** [sherlock-project/sherlock#1145]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE

**Comment by unknwon11** [comment]
i want the tool to search in instgram and snapchat , can i do that ?

**Comment by dimitrismistriotis** [comment]
Readme:

```
  --site SITE_NAME      Limit analysis to just the listed sites. Add multiple
                        options to specify more than one site.
```

**Comment by JDR11** [comment]
> Readme:
> 
> ```
>   --site SITE_NAME      Limit analysis to just the listed sites. Add multiple
>                         options to specify more than one site.
> ```

I believe this would still be limited to the sites in the site list.

**Comment by JDR11** [comment]
Someone correct me if I'm wrong but if you copy the data.json (which is at sherlock/resources/data.json) and add your site you wish to check, according to the format there, and use
>   --json JSON_FILE, -j JSON_FILE
                        Load data from a JSON file or an online, valid, JSON
                        file.

This should make sherlock query the site as it parses sites to search into an object from data.json.

**Comment by sdushantha** [comment]
Yes, you are correct
