### ISSUE TITLE
Being a bully is about as cool as jumping in a stump grinder. You should try it. Giddylinux & kekkodance I only wish to be as smart as you 🙄

### ISSUE THREAD

**Issue by Piratechik28** [sherlock-project/sherlock#1148]
## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by kekkodance** [comment]
this guy tried to sherlock shit on github

**Comment by GiddyLinux** [comment]
> this guy tried to sherlock shit on github

lmao
