### ISSUE TITLE
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

### ISSUE THREAD

**Issue by venumthekiller8** [sherlock-project/sherlock#1156]
## Checklist

- [yes ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by AlexIsOK** [comment]
run the `python3` command without arguments to bring up the microsoft store to install it (version 3.9), then run the command you wanted.

**Comment by Sulxl** [comment]
29
