### ISSUE TITLE
False Positive - OnlyFans

### ISSUE THREAD

**Issue by Mariotutal** [sherlock-project/sherlock#1174]
## Checklist
- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description
Username: Random characters, **mnbvvzxczxc.gsdfgsdfg785485614fsadf**
### Dependencies version:

![image](https://user-images.githubusercontent.com/11722299/139787505-79711f9b-d6eb-412f-a777-c111e59bea77.png)

### Executed line
`$python3 sherlock mnbvvzxczxc.gsdfgsdfg785485614fsadf`

![image](https://user-images.githubusercontent.com/11722299/139787586-8175d68e-41fd-4db5-99aa-a569bd8d17c3.png)

**Comment by BarrySchutte** [comment]
I'm getting the same results. OnlyFans keeps showing up on every result.

**Comment by HadetTheUndying** [comment]
From all the testing I've done a few sites will generate an extension to bait you into thinking your friend uses it when you search their site so you'll register. Onlyfans specifically in this case. I'm sure we could make a workaround for this but it might not be worth the extra time.

**Comment by sdushantha** [comment]
I found an API endpoint which allows us to check for users was able to fix it in #1175:
```
https://onlyfans.com/api2/v2/users/USERNAME_HERE
```
