### ISSUE TITLE
Google Cloud Shell: This is an invalid repo for Open in Cloud Shell

### ISSUE THREAD

**Issue by obfuscatedgenerated** [sherlock-project/sherlock#1180]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug (I have found one but it has no issue to go with it #1139)

## Description

I followed the link on the README to Google Cloud Shell but the page has an error saying "This is an invalid repo for Open in Cloud Shell". I'm on iOS (Mobile) and I would assume the Sherlock version would be latest if it was on the link.

**Comment by obfuscatedgenerated** [comment]
However I noticed that replit DOES work, so shouldn't be removed as in the PR.

**Comment by JDR11** [comment]
Issue resolved in #1139

**Comment by obfuscatedgenerated** [comment]
Why was replit removed?

**Comment by JDR11** [comment]
It appears that @alexlokotochek had issues with the replit link so removed it as well.
