### ISSUE TITLE
1337x.to many false positives

### ISSUE THREAD

**Issue by obfuscatedgenerated** [sherlock-project/sherlock#1181]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

Username to replicate: obfuscatedgenerated (any other username will probably trigger it too)

I am on replit so the results may be different. Every username I tried returned 1337x.to as positive. There is always the chance the someone has registered all of the usernames I tried but I cannot check them due to network blocking.

(Please note that with the username I provided there may also be the false positives of instagram and quizlet, but issues and PRs do already exist for those)

**Comment by sdushantha** [comment]
It seems like the site when down.

https://downforeveryoneorjustme.com/1337x.to

So I have removed it in #1186
