### ISSUE TITLE
why I have this error

### ISSUE THREAD

**Issue by sloom95** [sherlock-project/sherlock#1183]
A problem occured while checking for an update: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/sherlock.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8428d10760>: Failed to establish a new connection: [Errno -2] Name or service not known'))
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/resources/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8428d105e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by sdushantha** [comment]
This is an error on your side and nothing wrong with Sherlock.
