### ISSUE TITLE
Change output and disable sites

### ISSUE THREAD

**Issue by MrSnippyMrk2** [sherlock-project/sherlock#1184]
## Checklist

- [x ] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

Is their a way for me to change the output into a different folder?
as well as disabling what sites it looks at?

**Comment by JDR11** [comment]
Output can be given by the --folderoutput arguement. See here:
> usage: sherlock [-h] [--version] [--verbose] [--folderoutput FOLDEROUTPUT]
                [--output OUTPUT] [--tor] [--unique-tor] [--csv]
                [--site SITE_NAME] [--proxy PROXY_URL] [--json JSON_FILE]
                [--timeout TIMEOUT] [--print-all] [--print-found] [--no-color]
                [--browse] [--local]
                USERNAMES [USERNAMES ...]

For modifying what sites Sherlock checks please see #1145.

**Comment by SethFalco** [comment]
Closing this as the answer is covered above.
Using `--output` and `--site` or `--json` you can specify which sites you want to check.

In future, I recommend you try doing the `--help` command first to see command-line options!
