### ISSUE TITLE
i dont know how to set it up please help or contact

### ISSUE THREAD

**Issue by Myshiro** [sherlock-project/sherlock#1199]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [x] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE

**Comment by JDR11** [comment]
Have you checked the installation section of the README?
