### ISSUE TITLE
Tests fail/take too long to complete

### ISSUE THREAD

**Issue by bartwalczak1** [sherlock-project/sherlock#1200]
## Checklist

- [x ] I'm reporting a bug in Sherlock's functionality
- [x ] The bug I'm reporting is not a false positive or a false negative
- [x ] I've verified that I'm running the latest version of Sherlock
- [x ] I've checked for similar bug reports including closed ones
- [ x] I've checked for pull requests that attempt to fix this bug

## Description

I've just run tests locally and I'm getting 28 failures. Also, tests take about 262s to complete.

```
Ran 13 tests in 262.932s
from which:
FAILED (failures=28, skipped=6)


(venv) PS C:\github\sherlock> python sherlock --version 
sherlock 0.14.0
Python HTTP for Humans.:  2.26.0
Python:  3.9.7
```

Also can you document how 100% test coverage can be achieved?
I've tried with coverage and here are the results
```
(venv) PS C:\github\sherlock\sherlock> coverage report
Name                Stmts   Miss  Cover
---------------------------------------
notify.py              60     41    32%
result.py              22      5    77%
sherlock.py           264    133    50%
sites.py               56     20    64%
tests\__init__.py       0      0   100%
tests\all.py           61      0   100%
tests\base.py          71      3    96%
---------------------------------------
TOTAL                 534    202    62%
```
I guess it's due to the failing tests...

**Comment by caam0000** [comment]
try "--timeout 10"

**Comment by sdushantha** [comment]
This has now been fixed :+1:
