### ISSUE TITLE
Inaccurate Results 

### ISSUE THREAD

**Issue by TheDeath1510** [sherlock-project/sherlock#1220]
## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE
After using the tool for a search, multiple results appears which some are indeed accurate but I tried multiple different searches and everything has an only fans account that shows in the results but after some manual searches, there's no only fans account as shown in the results, it did happen with some other social media platforms like Instagram but not always meanwhile the only fans always show up, both if right or wrong

**Comment by sdushantha** [comment]
These are false positives that have been fixed in the past week. Sherlock should be returning correct results now :)
