### ISSUE TITLE
Codecademy false positive

### ISSUE THREAD

**Issue by nrhint** [sherlock-project/sherlock#1225]
## Checklist

- [ x] I'm reporting a website that is returning **false positive** results
- [ x] I've checked for similar site support requests including closed ones
- [ x] I've checked for pull requests attempting to fix this false positive
- [ x] I'm only reporting **one** site (create a separate issue for each site)
[611b4e6d0d92e2fb09b3346f0fbb5edc.txt](https://github.com/sherlock-project/sherlock/files/7796768/611b4e6d0d92e2fb09b3346f0fbb5edc.txt)

## Description

Username: 611b4e6d0d92e2fb09b3346f0fbb5edc (The md5 sum of the sites.md)

Going to the link that is found it comes up with a page that says the user does not exist. Having looked at a few other issues this might also be an anti-scraping mechanism that has been set up by the site.

**Comment by sdushantha** [comment]
Seems to be working without an issue
![image](https://user-images.githubusercontent.com/27065646/179830872-ecefc929-e08b-4619-a135-c4d78c24a4d8.png)
