### ISSUE TITLE
"" is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Futhallah** [sherlock-project/sherlock#1229]
Hey,
So I am trying to download sherlock on Windows 10 and already have Python 3.8 installed. I copy the instructions from the clipboard
# clone the repo
$ git clone https://github.com/sherlock-project/sherlock.git

# change the working directory to sherlock
$ cd sherlock

# install the requirements
$ python3 -m pip install -r requirements.txt
but when I press enter I just get a bunch of messages saying how either "$" or "#" isn't recognized as an internal or external command. I tried both the normal command prompt and the admin one but that doesn't do anything. I have also moved around the zip folder thinking that would change something but it didn't
Thank you in advance.

**Comment by Arnav-2004** [comment]
Hello, @Futhallah you don't need to include `$` itself when you type the command in Command Prompt.

**Comment by SethFalco** [comment]
Closing this since the solution is already covered in the comment above. 👍🏾
