### ISSUE TITLE
Flutter/Dart frontend for quick search

### ISSUE THREAD

**Issue by ghost** [sherlock-project/sherlock#1236]
Hi @DigitallyBorn ,

Hope you are all well and happy new year !

I deeply thinking that a flutter client for searching usernames would be just awesome.

Also, it could store with hive db, previous search, favourites, settings panel to exclude some websites to scan.

Thanks for any insights or inputs on that idea.

Cheers,
Luc

**Comment by samrath-sudesh-acharya** [comment]
I would like to work on this enhancement;could you assign it to me

**Comment by im-still-thinking** [comment]
I would like to work on this. Could you assign it to me?
