### ISSUE TITLE
Cloud shell

### ISSUE THREAD

**Issue by Mivdac** [sherlock-project/sherlock#1238]
## Checklist

- [ ] I'm requesting support for a new site
- [ ] I've checked for similar site support requests including closed ones
- [ ] I've checked that the site I am requesting has not been removed in the past and is not documented in [removed_sites.md](https://github.com/sherlock-project/sherlock/blob/master/removed_sites.md)
- [ ] The site I am requesting support for is not a pornographic website
- [ ] I'm only requesting support of **one** website (create a separate issue for each site)

## Description

URL:

**Comment by JDR11** [comment]
First, could you please complete the checklist.
Also, could you provide a URL to the site you are requesting support for. There are multiple sites with cloud shell products.

**Comment by sdushantha** [comment]
Closing this because it is incomplete
