### ISSUE TITLE
Python Packaging using Python-Poetry

### ISSUE THREAD

**Issue by stranger-danger-zamu** [sherlock-project/sherlock#1241]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

Currently Sherlock is never properly installed to the system or packaged into a python wheel. Instead it's pushed to a virutalenv or to the system python and still called via the sherlock.py script.

By using proper packaging, Sherlock can easily be packaged to be installed and become a command to be run from the command line. [Poetry](https://python-poetry.org/docs/) is a dependency management tool for Python which can be used to build python wheels and correctly set the console_script options allowing wheels to be installed as CLI tools.

**Comment by akaye47** [comment]
Leave me alone, unsubscribe me, whatever

From: stranger-danger-zamu ***@***.***>
Date: Thursday, January 27, 2022 at 4:44 PM
To: sherlock-project/sherlock ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sherlock-project/sherlock] Python Packaging using Python-Poetry (Issue #1241)
Checklist

  *   I'm reporting a feature request
  *   I've checked for similar feature requests including closed ones

Description

Currently Sherlock is never properly installed to the system or packaged into a python wheel. Instead it's pushed to a virutalenv or to the system python and still called via the sherlock.py script.

By using proper packaging, Sherlock can easily be packaged to be installed and become a command to be run from the command line. Poetry<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpython-poetry.org%2Fdocs%2F&data=04%7C01%7C%7C9f60e3ccc58345ee108d08d9e1de2692%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637789166524451970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FjS2oJyDpCV%2BDcWFc%2FFqbRjLaq1oPQF1yMX9eRfvo%2FM%3D&reserved=0> is a dependency management tool for Python which can be used to build python wheels and correctly set the console_script options allowing wheels to be installed as CLI tools.

**Comment by HighnessAtharva** [comment]
a much needed feature

**Comment by ppfeister** [comment]
Closing as resolved by #2111
