### ISSUE TITLE
Proxy : JavaScript

### ISSUE THREAD

**Issue by abhijithvijayan** [sherlock-project/sherlock#125]
Nice work on the project.
How do you pass the CORS issue?

I'm building the JavaScript fork of this project at https://github.com/abhijithvijayan/sherlock.

I have to now use a CORS proxy to get it right.

**Comment by crock** [comment]
@abhijithvijayan 
You can make all the requests server-side and then you won't run into a CORS issue. Some sites will require parsing the HTML as simply checking the status code for a 404 is not a sole solution for all services.

Take a look at my similar project for inspiration...
https://github.com/checker/api

**Comment by abhijithvijayan** [comment]
> @abhijithvijayan
> You can make all the requests server-side and then you won't run into a CORS issue. Some sites will require parsing the HTML as simply checking the status code for a 404 is not a sole solution for all services.
> 
> Take a look at my similar project for inspiration...
> https://github.com/checker/api

I actually parse the html too in my project with the `errorMessage`.
