### ISSUE TITLE
search argument for user names with spaces

### ISSUE THREAD

**Issue by nbmepik19** [sherlock-project/sherlock#1255]
Does Sherlock search for usernames with spaces in between first and last name? I've tried first_last but I am curious if there's documentation regarding this question.

i.e. python3 sherlock Bill Gates                     vs python3 sherlock BillGates or python3 sherlock Bill_Gates

Regards

**Comment by JDR11** [comment]
As with many other command line applications, arguements with spaces within can be placed between quotation marks.
i.e. `python3 sherlock "Bill Gates"`

**Comment by rama25** [comment]
quotation works perfectly if username has space in between
`python sherlock "username"`
to get info from one particular site then use the following command, eg twitter
`python -u sherlock.py --site twitter "name space"`
