### ISSUE TITLE
No Module Named

### ISSUE THREAD

**Issue by MuffinIsHacking** [sherlock-project/sherlock#1267]
no module named 'requests_failures'

""
 python3 sherlock.py
Traceback (most recent call last):
  File "sherlock.py", line 21, in <module>
    from requests_futures.sessions import FuturesSession
ModuleNotFoundError: No module named 'requests_futures'
 
""

**Comment by sdushantha** [comment]
Please install the requirements like I have mentioned in the README.md file.
```
python3 -m pip install -r requirements.txt
```
