### ISSUE TITLE
Check multiple similar usernames

### ISSUE THREAD

**Issue by TheYahya** [sherlock-project/sherlock#1284]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

It's good to search similar usernames. for example when searching for `user{?}name` we should also check for: `_`, `-` and `.`
1. `username`
2. `user.name`
3. `user-name`
4. `user_name`

**Comment by aristosgi** [comment]
I can work on it.

**Comment by PxINKY** [comment]
when inputting sherlock {username} just add more,
example: sherlock PxINKY P_xINKY Px_INKY > pink.txt

no need to make a feature if you can just write 3 more words

**Comment by SethFalco** [comment]
Closing this as it's been PR-ed and merged already.
* https://github.com/sherlock-project/sherlock/pull/1298

**Comment by SethFalco** [comment]
Actually sorry, I realize there is no documentation on this in the README. 🤔 
I'll reopen it, later someone (probably me) can go document it.

**Comment by JennPI** [comment]
Three more days

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 4, 2022 at 2:14 PM, ***@***.***> wrote:   


when inputting sherlock {username} just add more,
example: sherlock PxINKY P_xINKY Px_INKY > pink.txt

no need to make a feature if you can just write 3 more words
