### ISSUE TITLE
sherlock as a  REST API

### ISSUE THREAD

**Issue by senthilnayagam** [sherlock-project/sherlock#129]
feature request:
has anyone built a rest api using Sherlock, 

I would love a simple API using flask or chalice and instructions to deploying on AWS Lambda .

**Comment by TheYahya** [comment]
Hi @senthilnayagam 
My plan is create it after modulation of sherlock #112, and then use sherlock as core module of the api; In that way codebase would be much simpler and clear. 
And I will be appreciated to have your help.

**Comment by crock** [comment]
@senthilnayagam 

I have built an open-source REST API centered around social media username checking. You may use my [hosted version](https://api.getpenguin.com) in your applications or self-host. 

@TheYahya 
I'm always accepting PRs to the repo, it is built using Node. 
https://github.com/checker/api

**Comment by TheYahya** [comment]
Look good @crock 
like @senthilnayagam mention above, till sherlock become a pipy module, Having api would be difficult, But soon I will merge #112 ☺️

**Comment by sdushantha** [comment]
I am currently developing a newer version of Sherlock that will be modular so that it can be available on PyPi, have an Python and web API and possibly a web interface. Therefore I will be closing this as this is not something I will be doing with the current version of Sherlock
