### ISSUE TITLE
error showing while executing the code for searching accounts

### ISSUE THREAD

**Issue by Ramlakahn** [sherlock-project/sherlock#1292]
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  name 'requests' is not defined

**Comment by Ramlakahn** [comment]
someone please help how to get rid of this issue

**Comment by MoMMde** [comment]
This means you don't have the `requests` package installed.
Try
```
pip install requests
```

https://pypi.org/project/requests/

**Comment by Ramlakahn** [comment]
still the same problem

**Comment by Ramlakahn** [comment]
@d57montes please tell how to resolve  this

**Comment by Ramlakahn** [comment]
Hey brother I have already installed the pip requests but after running the code it is still showing the same please tell what to do Sent from Mail for Windows From: MoritzSent: 09 April 2022 12:56 AMTo: sherlock-project/sherlockCc: Ramlakahn; AuthorSubject: Re: [sherlock-project/sherlock] error showing while executing the code for searching accounts (Issue #1292) This means you don't have the requests package installed.Trypip install requestshttps://pypi.org/project/requests/—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sdushantha** [comment]
This has been fixed in c309032168a103f81acc7a1d42eef83a294f5cf3

Thank you for letting us know about this issue :+1:
