### ISSUE TITLE
tech support(couldnt find a template that said it)

### ISSUE THREAD

**Issue by Tier6194** [sherlock-project/sherlock#1294]
im kinda new to this thing and when i tried running my username it said ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  name 'requests' is not defined
idk if im doing something wrong i followed all the setup instructions so can someone help?

**Comment by dngrzone** [comment]
Can confirm this is happening as well. Python3.10.4  archlinux.

**Comment by dngrzone** [comment]
Found a temporary fix.

Navigate to the sites.py file and under
        import json

add import requests

**Comment by Tier6194** [comment]
> 

ok what do i import specifically cuz i dont wanna nuke this file by accident
