### ISSUE TITLE
name 'requests' is not defined

### ISSUE THREAD

**Issue by xiantez** [sherlock-project/sherlock#1297]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  name 'requests' is not defined

**Comment by CRM-BOTS** [comment]
I am experiencing this bug as well.

**Comment by kree-star** [comment]
same here

**Comment by kree-star** [comment]
it seems the problem appeared in the last 12 hours...i guess someone changed the code recently?

**Comment by horserunning** [comment]
Same here both on Kali and MacOS

**Comment by blackribbit** [comment]
experencing in kali.

**Comment by sdushantha** [comment]
@xiantez @blackribbit @horserunning @kree-star @CRM-BOTS 
This issue seems to have been fixed now in c309032168a103f81acc7a1d42eef83a294f5cf3

**Comment by xiantez** [comment]
> 

Sounds good, ill give it a go

**Comment by kree-star** [comment]
aight cool...just have to remove and reinstall the sherlock package...anddd voila
