### ISSUE TITLE
Apply different rules for different networks usernames

### ISSUE THREAD

**Issue by TheJavaGuy** [sherlock-project/sherlock#13]
Almost all social networks have some rules for valid usernames. For example, Facebook says it must be between 5 and 50 characters and can contain dot. Twitter says it must be between 1 and 15 characters and can contain dot and underscore. Pinterest says it must be between 3 and 30 characters, no dots, no underscores (only alphanumerics).

Unfortunately sherlock doesn't take any of these into account and it can be misleading for user (for example, he might think that username is taken but it is, in fact, illegal).

**Comment by sdushantha** [comment]
> Unfortunately sherlock doesn't take any of these into account and it can be misleading for user (for example, he might think that username is taken but it is, in fact, illegal).
That is very true. 

A way we could fix that is to use a regex for each of the networks. I am not good with regex but, I guess we can learn on the go :smile: 

When I think about it, I kinda feel like we should make a seperate file for each social network. Just like youtube-dl. In youtube-dl each site has its own extractor.

https://github.com/rg3/youtube-dl/

**Comment by hoadlck** [comment]
I wonder how well the user name requirements are documented for each site?  I found an place [here](https://github.com/shinnn/github-username-regex) that had the requirements for GitHub's user name. There are quite a few requirements.

I don't think that the regular expressions will be very hard: it is the research to find the exact requirements.

**Comment by hoadlck** [comment]
I added the infrastructure to be able to specify a unique regular expression pattern for each site with pull request #16 .  

The regular expression for GitHub itself is correct, but I am not sure about all of the rest.

**Comment by sdushantha** [comment]
Closing this because this is being done now. It is very difficult to come up with a regex for some sites because they do no provide us any information about what they username criteria is. We currently have 16 sites which has a regex check.
