### ISSUE TITLE
SmugMug

### ISSUE THREAD

**Issue by ThisLimn0** [sherlock-project/sherlock#1303]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Look for SmugMug profiles.

404 Example:
https://skabilpi432nkxyz.smugmug.com/

200 Example: 
https://winchester.smugmug.com/

if found link can be enhanced by adding an /browse to the profile URL.

**Comment by bolshoytoster** [comment]
@ThisLimn0 I've opened a PR: #1309
