### ISSUE TITLE
Add TM-Ladder Back

### ISSUE THREAD

**Issue by cens6r** [sherlock-project/sherlock#1306]
## Checklist
- [x] I'm reporting a website that is returning **false negative** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false negative
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

TM-Ladder was removed in 2021-11-30 due to false positives caused by rate-limits, as of now (4/17/2022) this issue has been resolved and the site is working properly.

Claimed Username: https://en.tm-ladder.com/blue_rech.php

Unclaimed Username: https://en.tm-ladder.com/noonewouldeverusethis_rech.php

**Comment by SethFalco** [comment]
The issue has not been resolved:

![image](https://user-images.githubusercontent.com/22801583/167243536-65ea576f-9c4a-45b5-95b2-4b5dc3b87a51.png)

If we make a request there too many times, for example someone runs the script with multiple usernames, or just runs the script fairly often, it still has that error which creates a false-positive or false-negative.

I don't think this will be added back until a neutral response is added.

I'm going to close this issue in favor of this:
* https://github.com/sherlock-project/sherlock/issues/1189

As the only pending website on it was TM-Ladder anyway.

**Comment by SethFalco** [comment]
I'll just close this as there's no action that we can take. It's documented in the JSON file anyway so in future we could perhaps check it out again but there's no need to track it in an issue.
