### ISSUE TITLE
causes.com false positive

### ISSUE THREAD

**Issue by Omicron166** [sherlock-project/sherlock#1316]
## Checklist

- [ ] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [ ] I'm only reporting **one** site (create a separate issue for each site)

## Description

The website shows not found in the browser but sherlock detects it as positive

url: https://www.causes.com/Omicron166

**Comment by sdushantha** [comment]
Are you sure this is correct? It doesnt look like Sherlock has ever supported causes.com. I doubled check by looking through the data.json and removed_sites.json file

**Comment by Omicron166** [comment]
well, if you want, i can add screenshots to future false positive issues
