### ISSUE TITLE
gab.com false positive

### ISSUE THREAD

**Issue by Omicron166** [sherlock-project/sherlock#1318]
## Checklist

- [ ] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [ ] I'm only reporting **one** site (create a separate issue for each site)

## Description

False positive for https://gab.com/Omicron166

**Comment by AlexIsOK** [comment]
I'm the one who made the pr for gab.  It was working when I made it, but they must've done something to patch it.  I'll look at it.
