### ISSUE TITLE
minds.com false positive

### ISSUE THREAD

**Issue by Omicron166** [sherlock-project/sherlock#1320]
## Checklist

- [ ] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [ ] I'm only reporting **one** site (create a separate issue for each site)

## Description

false positive for url https://www.minds.com/Omicron166/

**Comment by j4asper** [comment]
This issue seems to have been resolved, i can't get the false positive result.

**Comment by sdushantha** [comment]
fixed in c61dac391c1d8c3408a3d11f74620239152c084e
