### ISSUE TITLE
Noonewilleverusethis

### ISSUE THREAD

**Issue by akaye47** [sherlock-project/sherlock#1322]
I don't like putting numbers in my screen name so if I can't have it this way, I can use one of my other 4 GitHub logins 🤷‍♀️

Is that ok? Who's social media accounts were you looking for anyway? Why didn't you just ask them?

**Comment by tinewq** [comment]
good ideal

**Comment by hKQwHW** [comment]
> Who's social media accounts were you looking for anyway? Why didn't you just ask them?

Private investigators, corporate fraud departments, law enforcement, etc. tend to use OSINT to identify someone.

**Comment by jamieu187** [comment]
My cheated piece of shit husband soon to be ex

**Comment by hKQwHW** [comment]
I can't tell what you're talking about, but if you're using this to stalk your ex, go away.

**Comment by BlaviButcher** [comment]
I use it to mess with gamers and refer to them by their real name
