### ISSUE TITLE
eBay false positive

### ISSUE THREAD

**Issue by SIMULATAN** [sherlock-project/sherlock#1323]
## Checklist
- [X] I'm reporting a website that is returning **false positive** results
- [X] I've checked for similar site support requests including closed ones
- [X] I've checked for pull requests attempting to fix this false positive
- [X] I'm only reporting **one** site (create a separate issue for each site)

## Description
HTTP requests to an user account on ebay always return the HTTP code 200, even if the account wasn't found.
See this:
![image](https://user-images.githubusercontent.com/63104422/165686566-44558e35-daa5-4eed-a87e-6e26786939bf.png)

This happens to both [ebay.com](https://www.ebay.com/usr/somerandomtestuser) and [ebay.de](https://www.ebay.de/usr/somerandomtestuser)

**Comment by sebastianjnuwu** [comment]
Truth!

**Comment by hKQwHW** [comment]
I have this issue as well.
