### ISSUE TITLE
Code error line 196 21 & 20.

### ISSUE THREAD

**Issue by chuckcarne** [sherlock-project/sherlock#1331]
Yo i tried to run the stuff normally it worked before and it gave me this error:

raceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/Clinets/sherlock/sherlock/__main__.py", line 21, in <module>
    import sherlock
  File "/home/charles/sherlock/sherlock/sherlock.py", line 20, in <module>
    from requests_futures.sessions import FuturesSession
ModuleNotFoundError: No module named 'requests_futures'

**Comment by bslisowski** [comment]
pip install requests-futures

**Comment by chuckcarne** [comment]
got this code now 

pip install requests-futures
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests-futures in /home/charles/.local/lib/python3.10/site-packages (1.0.0)
Requirement already satisfied: requests>=1.2.0 in /usr/lib/python3/dist-packages (from requests-futures) (2.25.1)

**Comment by bslisowski** [comment]
try installing sherlock again

**Comment by chuckcarne** [comment]
1 step ahead didn't work

**Comment by hKQwHW** [comment]
> got this code now
> 
> pip install requests-futures Defaulting to user installation because normal site-packages is not writeable Requirement already satisfied: requests-futures in /home/charles/.local/lib/python3.10/site-packages (1.0.0) Requirement already satisfied: requests>=1.2.0 in /usr/lib/python3/dist-packages (from requests-futures) (2.25.1)

You may have multiple versions of Python installed. Use python -m pip and then pip, see which one works
