### ISSUE TITLE
OnlyFans False Negative

### ISSUE THREAD

**Issue by Ryah** [sherlock-project/sherlock#1342]
## Checklist

- [x] I'm reporting a website that is returning **false negative** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false negative
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

OnlyFans is reporting "Not Found" to any username I throw at it, even ones who are known to have one.
Here's an example using Belle Delpine. Username is copied straight out of the OF url.

![image](https://user-images.githubusercontent.com/14987609/168403162-b9719ee1-369d-4e83-b868-1ade75a2776f.png)

**Comment by sdushantha** [comment]
This issue has been fixed :+1:
