### ISSUE TITLE
clone the repo
$ git clone https://github.com/sherlock-project/sherlock.git

# change the working directory to sherlock
$ cd sherlock

# install the requirements
$ python3 -m pip install -r requirements

### ISSUE THREAD

**Issue by Druza1** [sherlock-project/sherlock#1347]
## Checklist

- [ ] I'm reporting a feature request
- [ ] I've checked for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

**Comment by zSheem** [comment]
cant click on anything
