### ISSUE TITLE
Sgerqk

### ISSUE THREAD

**Issue by Sherak000** [sherlock-project/sherlock#1369]
## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## `Descriptionhttps://github.com/sherlock-project/sherlock.git

WRITE DESCRIPTION HERE
https://github.com/sherlock-project/sherlock.git

**Comment by DavidEl03** [comment]
Template ignored and no description provided
