### ISSUE TITLE
python3 -m pip install -r requirements.txt

### ISSUE THREAD

**Issue by l6xl** [sherlock-project/sherlock#1370]
## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by l6xl** [comment]
python3 -m pip install -r requirements.txt

**Comment by AlertSubject** [comment]
Template ignored and no description provided
