### ISSUE TITLE
Important 

### ISSUE THREAD

**Issue by MR-EHAB11** [sherlock-project/sherlock#1371]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by pablodz** [comment]
???

**Comment by MR-EHAB11** [comment]
> ???

I am sorry for what...? asked...

**Comment by MR-EHAB11** [comment]
> Dummy issue, you can delete this.

Why......?

**Comment by DavidEl03** [comment]
Because you didnt add any content, your issue still has the "WRITE DESCRIPTION HERE"
