### ISSUE TITLE
python3 -m pip install -r requirements.txt

### ISSUE THREAD

**Issue by sultan22qq** [sherlock-project/sherlock#1387]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by SolonRubens** [comment]
Could you provide some more information about the issue?

**Comment by DavidEl03** [comment]
Template ignored and no description provided
