### ISSUE TITLE
How to download the app Sherlock

### ISSUE THREAD

**Issue by Alexandrew1901** [sherlock-project/sherlock#1389]
Can Android phone use Sherlock app?

**Comment by SolonRubens** [comment]
Generally Sherlock is "only" a Python-File, so if you manage to run Python on your phone it would be possible.
For practical reasons I wouldn't recommend it tho

**Comment by z1nc0r3** [comment]
@Alexandrew1901 You can use **Termux** or any python shell to run this script. Just download the project.

**Comment by sdushantha** [comment]
@Alexandrew1901 I did a quick search on YouTube and found this video which may help you: https://www.youtube.com/watch?v=4S4jYVa2sMU
