### ISSUE TITLE
False Positive allmylinks.com

### ISSUE THREAD

**Issue by Cvar1984** [sherlock-project/sherlock#1402]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

i tried searching my username and i found that this was false positive https://allmylinks.com/Cvar1984

**Comment by sdushantha** [comment]
Seems to be working fine now
![image](https://user-images.githubusercontent.com/27065646/179361440-bd25e96b-0642-4d10-9616-b5b9af3e604e.png)

**Comment by jonbesga** [comment]
Is giving again a false positive as of `Sherlock v0.15.0`
