### ISSUE TITLE
PCPartPicker false positive

### ISSUE THREAD

**Issue by skybird23333** [sherlock-project/sherlock#1403]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

My username `skybird23333` had a false positive on PCPartPicker. It appeared that the user page now [requires an account](https://pcpartpicker.com/user/skybird23333) and therefore would appear as if the request was successful.

This also applied to a test name I used, `testnameighigqe`.

**Comment by ObfuscatedFuture** [comment]
Yea just to add to this you can still access the URL when logged in but without being logged in you get redirected to the login page when requesting any /user/ url
