### ISSUE TITLE
i followed the instruction of the following video https://www.youtube.com/watch?v=OZ9kJ5ogfMI&ab_channel=MattyMcTech but for me it does not show "requirement.txt" it just shows requirement and its not working for me how do i fix it i did all the things what he said still nothing

### ISSUE THREAD

**Issue by PSabdullah** [sherlock-project/sherlock#1410]
![Screenshot 2022-07-17 201703](https://user-images.githubusercontent.com/58355280/179404919-567c6b75-c07c-419f-a652-774f618e0047.png)

**Comment by sdushantha** [comment]
As you see, non of the files in the screenshot has an extension. This is because you have altered the settings of File Explorer to not show the file extension even though they actually exist.

Closing because this is an issue with your system and not Sherlock.
