### ISSUE TITLE
Error connecting to these sites

### ISSUE THREAD

**Issue by JassonCordones** [sherlock-project/sherlock#1417]
## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

The following sites give an Error connecting message when doing a lookup no matter the username:

- Atom Discussions
- Gam1ng
- OGUsers
- Otzovik
- radio_echo_msk

I checked and some of them are down. I think they should be removed.

**Comment by sdushantha** [comment]
fixed in #1421
