### ISSUE TITLE
Serach stuck at Oracle

### ISSUE THREAD

**Issue by SaintKlover** [sherlock-project/sherlock#1422]
## Checklist

- [ x] I'm reporting a bug in Sherlock's functionality
- [ x] The bug I'm reporting is not a false positive or a false negative
- [ x] I've verified that I'm running the latest version of Sherlock
- [ x] I've checked for similar bug reports including closed ones
- [ x] I've checked for pull requests that attempt to fix this bug

## Description

Hello,

I tested this program out, and while good, I have ran into an issue.

While searching, It gets stuck at Oracle.  Is this a known issue with a fix?

Thanks!

**Comment by gwo0d** [comment]
I will look into this issue, and submit a PR if necessary.

**Comment by sdushantha** [comment]
Sherlock no longer hangs. This must have been due to some issue on your side
