### ISSUE TITLE
Bug  / Do not search all sites

### ISSUE THREAD

**Issue by lokokoijo** [sherlock-project/sherlock#1424]
hey how is everything ?
I tested the tool and noticed that the same user that I put the system does not search all sites like twitter
I tested it with my own name and the system doesn't find my twitter let alone my tiktok
Would this be a bug? I tried updating the list of sites in sites_list.py

**Comment by Nullpython3950** [comment]
Mee too

**Comment by Nullpython3950** [comment]
It doesn't show my YouTube profile

**Comment by xtekky** [comment]
TikTok does not like scraping, so it patched status code check, a solution would be implementing a special script using api's.

**Comment by ax00z** [comment]
@lokokoijo @Nullpython3950
Ran a JSON test file that has 25 official twitter usernames and 25 for tiktok. It's working perfectly...

Use this with your username, it restricts to a specific website (name only):
`py -m sherlock [YOUR_USERNAMES] --site [ANY_WEBSITES (TWITTER/TIKTOK)]`

**Comment by sdushantha** [comment]
Twitter seems to work as of 20.08.2022
