### ISSUE TITLE
Make --print-found work with all file types

### ISSUE THREAD

**Issue by ArkhamCookie** [sherlock-project/sherlock#1431]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

Allow `--print-found` option to have the option of being outputted with different file types.

**Example:** `python3 sherlock username  --print-found --csv `

This would output the normal .csv file with only the found accounts.

**Comment by acrulopez** [comment]
I will work on this

**Comment by Guri-X** [comment]
Hi @acrulopez, are you still working on this?

**Comment by acrulopez** [comment]
> Hi @acrulopez, are you still working on this?

Yes! I have just made a PR

**Comment by acrulopez** [comment]
> Hi @acrulopez, are you still working on this?

Yes! I have done the changes. I will make a PR asap

**Comment by ArkhamCookie** [comment]
Thanks guys, I appreciate you.  :)
