### ISSUE TITLE
sherlock does nothing

### ISSUE THREAD

**Issue by AustinRhoads** [sherlock-project/sherlock#1441]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

when I run:
python3 sherlock.py my-username
nothing happens it just hangs.
with the apt-get install version I ran:
sherlock my-username 
With the same result
After finding a similar issue I ran under the same conditions with:
sherlock my-username --timeout 10
Same exact results.
Python version is  3.10.5

**Comment by joeyagreco** [comment]
I ran into a similar issue.

Make sure you're in the correct directory.

For instance: `C:\sherlock\sherlock`

and then run: `sherlock.py username`

The README.md file should be updated to reflect this.

**Comment by sdushantha** [comment]
You dont have to go into `sherlock/sherlock/` in order to run Sherlock. You can be in `sherlock/` and run it without an issue as long as you dont use the `.py` extension in the command.

Example:
If you are in `sherlock/`, you run `python3 sherlock username`
If you are in `sherlock/sherlock/`, you run `python3 sherlock.py username`

But in the instructions in the README.md tells the users to `cd sherlock` in order to install the needed dependencies. So I think its fine to assume that they are still in that directory when they go to the next step which the Usage, where you're told to run `python3 sherlock username`

**Comment by AustinRhoads** [comment]
Hey guys, thanks so much for your input. I was in the sherlock/sherlock/ directory when I ran:
`python3 sherlock.py my-username`
 but I also installed it with:
 `sudo apt-get install sherlock`
which would put it in my bin directory meaning I can just call it from any directory without the .py:
`sherlock my-username`
But just to be safe I ran it all three ways mentioned.
In `sherlock/`
`python3 sherlock myusername`
in `sherlock/sherlock/`
`python3 sherlock.py myusername`
and in any directory
`sherlock myusername`


All three had the exact same result which was after I run the command it stalled until I `CTRL + C` keyboard inturrupted which returned this:

`   File "/home/networkaush/Desktop/sherlock/sherlock/__main__.py", line 22, in <module>
    sherlock.main()
  File "/home/networkaush/Desktop/sherlock/sherlock/sherlock.py", line 563, in main
    r = requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1043, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock. Connect(sa)`

**Comment by sdushantha** [comment]
> but I also installed it with:
> sudo apt-get install sherlock

Are you using Kali Linux? Because its only possible to install Sherlock using `apt` on Kali Linux.

Based on the error message you have provided it seems like its en environment problem and not a problem with Sherlock itself.

**Comment by AustinRhoads** [comment]
Yes I'm using kali.

**Comment by sdushantha** [comment]
Try looking at this, seems like there are many who've had similar issues: https://stackoverflow.com/questions/67159193/stuck-in-process-sock-connectsa-or-making-connections

**Comment by AustinRhoads** [comment]
Thats funny I tried that before and didn't work but did it again just for shnits and giggles and viola! Why doesn't anything ever work the first time lol Thanks! For those with similar problems try running:
`sudo sysctl net.ipv6.conf.all.disable_ipv6=1`
you can always enable ipv6 again later with 
`sudo sysctl net.ipv6.conf.all.disable_ipv6=0`
