### ISSUE TITLE
satsis.info very slow because it doesn't exist

### ISSUE THREAD

**Issue by bi0ax** [sherlock-project/sherlock#1443]
## Checklist

- [x] I'm reporting a website that is returning **false negative** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false negative
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

WRITE DESCRIPTION HERE
I've tried making my own "sherlock.py" with python using the websites from data.json. I've got it working, but I noticed that a website, which is satsis.info, slows the program down considerably. This is because the website doesn't even exist.

**Comment by sdushantha** [comment]
![image](https://user-images.githubusercontent.com/27065646/187073639-34d4de10-57a6-4b80-8396-cea29282bd1c.png)

It does exist, might just be a little slow on your end. You can always use the `--timeout` which is stated in the help message when running `python sherlock --help`
