### ISSUE TITLE
False positiv on Gurushots.com

### ISSUE THREAD

**Issue by Warriermaple** [sherlock-project/sherlock#1447]
## Checklist

- [ x] I'm reporting a website that is returning **false positive** results
- [ x] I've checked for similar site support requests including closed ones
- [ x] I've checked for pull requests attempting to fix this false positive
- [ x] I'm only reporting **one** site (create a separate issue for each site)

## Description

When browsing to Guruhosts.com/{random username that won't exist}/photos you end up on an error page that in the html is written as a 404 but is actually a 200 when looking in dev-tools or burpsuite. This seems to cause the false positive.

**Comment by spmedia** [comment]
Also known as a "soft 404" where it returns a 200 status.

Easily fixed by updating it like below to use message instead of status

  "GuruShots": {
    "errorMsg": "This page doesn't exist",
    "errorType": "message",
    "url": "https://www.hexrpg.com/userinfo/{}",
    "urlMain": "https://www.hexrpg.com/",
    "username_claimed": "blue",
    "username_unclaimed": "noonewouldeverusethi"

**Comment by sdushantha** [comment]
@spmedia feel free to create a PR
