### ISSUE TITLE
The following sites are reporting false positives

### ISSUE THREAD

**Issue by JassonCordones** [sherlock-project/sherlock#1456]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [] I'm only reporting **one** site (create a separate issue for each site)

## Description

WRITE DESCRIPTION HERE
The following sites are reporting false positives:
 https://gurushots.com
 https://robertsspaceindustries.com
 https://forums.whonix.org

**Comment by spmedia** [comment]
Fix the GuruShots one by doing this

https://github.com/sherlock-project/sherlock/issues/1447#issuecomment-1232285092

**Comment by mossfarmer** [comment]
Problem is fixed now
