### ISSUE TITLE
Disclaimer about NSFW Websites being pinged

### ISSUE THREAD

**Issue by aswinunni01** [sherlock-project/sherlock#1475]
## Checklist

- [ x] I'm reporting a feature request
- [x ] I've checked for similar feature requests including closed ones

## Description

I just cloned the project and tried running it. I had no idea it would ping NSFW websites, which could be illegal to access on some Networks (Like work networks). So I think adding a disclaimer in the Readme about them being part of the sites pinged will be a good idea. Or else, an `--nsfw` flag in the command itself so that people who require it can search those websites.

If you find this issue valid enough, I will be happy to work on it as well.

**Comment by DualityStudios** [comment]
This is a good idea - is there a way I can help?

**Comment by sawanmsis** [comment]
Opened a Pull Request to:
Remove NSFW sites to be run by default.
Can still be included by adding the --nsfw or -n flag

**Comment by DualityStudios** [comment]
Nice job.
Thanks for your help.

**Comment by sawanmsis** [comment]
Thanks all. Free to contibute a little more. Any ideas , let me know. 


issue looks good to close.

**Comment by sdushantha** [comment]
Been added in #1477 thanks to @sawanmsis
