### ISSUE TITLE
Getting false positive response in kooapp profile

### ISSUE THREAD

**Issue by keder-code-hash** [sherlock-project/sherlock#1493]
## Checklist

- [ x] I'm reporting a website that is returning **false positive** results
- [ x] I've checked for similar site support requests including closed ones
- [ x] I've checked for pull requests attempting to fix this false positive
- [ x] I'm only reporting **one** site (create a separate issue for each site)

## Description

I checked for keder-code-hash. This user doest not exist
<img width="365" alt="Screenshot 2022-10-02 185251" src="https://user-images.githubusercontent.com/53966650/193456358-919a3dfc-ee06-4a59-a311-95585deb21a1.png">
 in kooapp but it is returning true.

**Comment by gwo0d** [comment]
I will look into this and submit a PR if necessary.

**Comment by sdushantha** [comment]
fixed in #1494 thanks to @keder-code-hash
