### ISSUE TITLE
Add Support for Google Developers

### ISSUE THREAD

**Issue by arnavgupta2003** [sherlock-project/sherlock#1504]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Google Developers is Google's site for software development tools and platforms, application programming interfaces, 
and technical resources.
The sherlock module lacks support for Google Developers

**Comment by sdushantha** [comment]
Added in #1506
