### ISSUE TITLE
Alexa.com rank fetching

### ISSUE THREAD

**Issue by ptalmeida** [sherlock-project/sherlock#155]
Regarding #152 and #153, which has already been merged, and for future reference on this feature.

The reason why `--rank` option is used instead of fetching the rank for every website every time site_list.py is used:

- Amazon has a paid API which we don't use, and abusing this workaround could lead to serious problems.
- There is also a hard limit of 500 requests, which this database may reach very soon, that would render the usage of this program useless. 

This is also why the addition of a timestamp regarding the last update was removed [in this commit](https://github.com/TheYahya/sherlock/pull/146/commits/40fc51fc320a2636c0dff5cf72d6a23da57c00ff). The idea is for the rank to be updated individually, as there's no need to regularly re-fetch ranks for the whole database.

**Comment by hoadlck** [comment]
I am going to close this issue. It will still be available in the archive if we ever get above the 500 limit...

Thanks.
