### ISSUE TITLE
Few errors in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by dev-32** [sherlock-project/sherlock#1561]
There are around 2-3 grammar error that can be improved to make it more interactive. !!
<img width="780" alt="Screenshot 2022-10-16 at 11 00 08 AM" src="https://user-images.githubusercontent.com/99115141/196019922-192cf60f-15bf-4f49-a15b-680cfbe5ffaa.png">
<img width="661" alt="Screenshot 2022-10-16 at 11 00 26 AM" src="https://user-images.githubusercontent.com/99115141/196019925-7840b264-bce7-4983-915f-6b968e1fdf90.png">

**Comment by Hardikg13** [comment]
Hi, can I be assigned this issue, I will try to fix it soon

**Comment by sdushantha** [comment]
fixed
