### ISSUE TITLE
Categorizing sites.md (suggestion)

### ISSUE THREAD

**Issue by ducheharsh** [sherlock-project/sherlock#1573]
## Short Description
Sorting and categorizing the sites.md list into sub-groups such as chess, socials, developers, e-commerce, etc
## Advantages
- [x] Easy Navigation
- [x] Category-based search
- [x] Informative

**Comment by sdushantha** [comment]
Great idea! But at the moment we don't need a feature like this. A rewrite of Sherlock is work in progress so we might add this feature in the new version :)
