### ISSUE TITLE
Add --list-sites argument to list all supported sites

### ISSUE THREAD

**Issue by guiszk** [sherlock-project/sherlock#1578]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

I propose adding a `--list-sites` argument to output the name of all websites on `sites.md`. I can implement this, if you'd like!

**Comment by slimkaki** [comment]
Can anyone assign this issue to me, or can I just work on this?

**Comment by tze-min** [comment]
This would be really useful! :D

**Comment by slimkaki** [comment]
@guiszk Are you working on this? If not, can I be assigned to this issue?

**Comment by guiszk** [comment]
Already coded it! I'll make a PR as soon as I can.

**Comment by sdushantha** [comment]
This feature would be unnecessary as we have the `sites.md` file which contains the list along with the links to the homepage
