### ISSUE TITLE
Improvement to YouTube checking method

### ISSUE THREAD

**Issue by crock** [sherlock-project/sherlock#158]
I've done a detailed write-up on how YouTube custom urls work that anyone can read here.
https://www.linkedin.com/pulse/de-mystifying-youtube-custom-urls-alex-crocker/

Once we get a standard system down for modularization, I'll make a PR with changes to the checking method for YouTube.

**Comment by sdushantha** [comment]
Youtube has been added back and works perfectly fine now :)
