### ISSUE TITLE
Updating Wiki for Adding Sites To Sherlock

### ISSUE THREAD

**Issue by rskbansal** [sherlock-project/sherlock#1588]
## Description
The example given in the [Respone URL](https://github.com/sherlock-project/sherlock/wiki/Adding-Sites-To-Sherlock#response-url) section is that of ***Canva***, which now returns a `404` Status for unclaimed usernames instead of a `301/302` Status.

## Proposed Changes
Sites like ***CodeChef*** shall be provided as an example, as it returns a `302` Status for unclaimed usernames and redirects to the Home Page, as it is described in the [Respone URL](https://github.com/sherlock-project/sherlock/wiki/Adding-Sites-To-Sherlock#response-url) section.

**Comment by sdushantha** [comment]
Closing this as Reponse URL has been removed from the Wiki. Sherlock no longer uses this
