### ISSUE TITLE
Fix this error please

### ISSUE THREAD

**Issue by Dstar001** [sherlock-project/sherlock#1591]
[end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
~/sherlock $

**Comment by louay-rouabeh** [comment]
type:  pip install numpy 

ps: if it didn't work you can refer to this page https://stackoverflow.com/questions/70565965/error-failed-building-wheel-for-numpy-error-could-not-build-wheels-for-numpy

**Comment by abedaton** [comment]
This has nothing to do with this project, it's a problem with your installation of Numpy
