### ISSUE TITLE
How to fix numpy error

### ISSUE THREAD

**Issue by Dstar001** [sherlock-project/sherlock#1597]
~/sherlock/sherlock $ python3 sherlock.py hi
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/sherlock/sherlock/sherlock.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by nkilm** [comment]
@Dstar001 Your system/environment does not have `pandas` installed. 

If you running the project locally then follow these steps,
- Create a Virtual Environment [help](https://www.geeksforgeeks.org/python-virtual-environment/)
- After activating the virtual environment, install packages - `pip install -r requirements.txt`
- Run the project
Done✅

**Comment by rskbansal** [comment]
If you are facing issues with missing modules, just install them manually(if required)
```
pip install pandas
```

> ~/sherlock/sherlock $ python3 sherlock.py hi Traceback (most recent call last): File "/data/data/com.termux/files/home/sherlock/sherlock/sherlock.py", line 12, in import pandas as pd ModuleNotFoundError: No module named 'pandas'

**Comment by rskbansal** [comment]
> ~/sherlock/sherlock $ python3 sherlock.py hi Traceback (most recent call last): File "/data/data/com.termux/files/home/sherlock/sherlock/sherlock.py", line 12, in import pandas as pd ModuleNotFoundError: No module named 'pandas'

If you are facing issues with missing modules, just install them manually(if required)
```
pip install pandas
```

**Comment by Qb3129** [comment]
Unsubscribe
