### ISSUE TITLE
False Negative for twitter search

### ISSUE THREAD

**Issue by Cr7pt0nic** [sherlock-project/sherlock#1601]
False negative when trying to scan usernames on that have attached twitters. This could lead to false reports and would be greatly appreciated if it's fixed. This is for every username I've tried that have valid accounts but show up as false negatives for example holiday8993

**Comment by rskbansal** [comment]
Yup, I tried searching for the username, but it doesn't return any results  from Twitter. But surprisingly, if you check out the result from Periscope, it redirects to Twitter as it has been closed recently. So maybe revising the `data.json` file and removing Periscope may fix the issue!<br>
![image](https://user-images.githubusercontent.com/45748739/199022501-a57ea082-cc5c-46ea-9270-b4763da28310.png)

**Comment by rskbansal** [comment]
> False negative when trying to scan usernames on that have attached twitters. This could lead to false reports and would be greatly appreciated if it's fixed. This is for every username I've tried that have valid accounts but show up as false negatives for example holiday8993

Yup, I tried searching for the username, but it doesn't return any results  from Twitter. But surprisingly, if you check out the result from Periscope, it redirects to Twitter as it has been closed recently. So maybe revising the `data.json` file and removing Periscope may fix the issue!<br>
![image](https://user-images.githubusercontent.com/45748739/199022501-a57ea082-cc5c-46ea-9270-b4763da28310.png)

**Comment by kensim48** [comment]
Found the issue.
Twitter's url_probe's url, [nitter.net](nitter.net) currently has an expired certificate.
![image](https://user-images.githubusercontent.com/22837632/199034857-68d25280-1d2a-4e77-ab53-0c51ef1634e5.png)

This causes `request_future`'s SSLError to be raised and causing all Twitter usernames to be flagged as not found.

**Comment by kensim48** [comment]
Removing the "urlProbe" in `data.json` and running with the local flag, i.e. `python sherlock holiday8993 --local` will temporarily solve the issue until cert is renewed.

```json
"Twitter": {
    "errorMsg": "<div class=\"error-panel\"><span>User ",
    "errorType": "message",
    "regexCheck": "^[a-zA-Z0-9_]{1,15}$",
    "url": "https://twitter.com/{}",
    "urlMain": "https://twitter.com/",
    "username_claimed": "blue",
    "username_unclaimed": "noonewouldeveru"
  }
```

**Comment by Qb3129** [comment]
Unsubscribe
