### ISSUE TITLE
Fuzzy search on names to categorize profiles into similar buckets

### ISSUE THREAD

**Issue by shvms** [sherlock-project/sherlock#1625]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

I believe adding a possible fuzzy search on actual name might help categorize profiles based on similar people. For example, `catsnip` might be username of multiple people across different platforms but a simple name comparison or fuzzy search on name can help categorize the profiles into similar bucket.
I am not sure if the owners of this repo has this planned or not or if it is not in the vision. Otherwise, I would love to contribute on this.

**Comment by sdushantha** [comment]
Great idea! But at the moment we don't need a feature like this. A rewrite of Sherlock is work in progress so we might add this feature in the new version
