### ISSUE TITLE
--browse/-b is not handled

### ISSUE THREAD

**Issue by Morrious** [sherlock-project/sherlock#1639]
## Checklist

- [ x] I'm reporting a bug in Sherlock's functionality
- [ x] The bug I'm reporting is not a false positive or a false negative
- [ x] I've verified that I'm running the latest version of Sherlock
- [ x] I've checked for similar bug reports including closed ones
- [ x] I've checked for pull requests that attempt to fix this bug

## Description

Running latest version 0.14.0
Documentation indicates using `--browse` will open links in default browser. Looking in `sherlock/sherlock.py`, the argument is captured, but nothing is done with it.

The below commit from early 2020 has the browse functionality added, but it has been since removed from the codeset at some point:
https://github.com/sherlock-project/sherlock/commit/d7597ef62000ce25d8b42af1a9851d1d8a1700dd

**Comment by sdushantha** [comment]
fixed
