### ISSUE TITLE
Sherlock hangs after ThemeForest

### ISSUE THREAD

**Issue by TheAlmightyDada** [sherlock-project/sherlock#1644]
Hello, 

I have tried multiple usernames and Sherlock seems to hang after checking ThemeForest on all of them 
![image](https://user-images.githubusercontent.com/24527440/208458209-e1161399-1275-46c5-bf15-c1039404ea98.png)

I am using the newest Parrot OS iso on a virtual machine.

**Comment by sdushantha** [comment]
Append `--timeout 10` to the command you ran. The site after ThemeForest might slow at responding on your end. Everything works fine after testing Sherlock from multiple IP
