### ISSUE TITLE
no support for "legal usernames"

### ISSUE THREAD

**Issue by ronbonmon** [sherlock-project/sherlock#1647]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE
I am a supernoob so pardon my lack of correct code terms or usage etc. I just wanted to point out a high amount of usernames begin with a "@" these days. When inputting certain sites, it comes back with illegal formatted username - i realized those sites are the ones that require the @username123 to be input in this format. when adding the @ the username turns green(not sure what that means lol) and comes back as an error. Thoughts? is there a way to add the @ without it turning green and tossing the error?

**Comment by ronbonmon** [comment]
more of a functionality, than a bug. yelp

**Comment by jalajk24** [comment]
Can I work on this issue??

**Comment by ronbonmon** [comment]
yes
    On Sunday, January 29, 2023 at 02:24:12 p.m. CST, Jalaj Khare ***@***.***> wrote:  
 
 


Can I work on this issue??

**Comment by ronbonmon** [comment]
i wouldnt know where to start lol
    On Friday, February 3, 2023 at 11:41:13 p.m. CST, Ron Abrahms ***@***.***> wrote:  
 
  yes
    On Sunday, January 29, 2023 at 02:24:12 p.m. CST, Jalaj Khare ***@***.***> wrote:  
 
 


Can I work on this issue??

**Comment by sdushantha** [comment]
Sherlock includes the @ if it's needed for a site. As a user, you only need to specify the username without the @
