### ISSUE TITLE
Mask/Regex search feature

### ISSUE THREAD

**Issue by leana8959** [sherlock-project/sherlock#1651]
## Checklist
- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description
Is there a way to create masks/regex and search through all the possibilities?
For example, `.{0,2}[jJ]ames\.[Bb]ond.{0,2}"` would generate a list of possible names and test each of them, matching `JamesBond`, `jamesBond`, `__jamesbond`, etc.
Wild card with unlimited repetition would definitely be a problem, so we'd have to consider that.

Have a good day!

**Comment by roopeshsn** [comment]
I would like to work on this!

**Comment by RUGMJ** [comment]
For the time being you could make a bash script which reads the output of crunch (a world list generator) and then send each line to a new instance of Sherlock, the n all you have to do is merge all of the json files together

**Comment by jalajk24** [comment]
Is this still open? Can I work on this?

**Comment by sdushantha** [comment]
At the time being, this is not something I'd like to add to Sherlock. But as @RUGMJ mentioned, using a word list generator and passing it to Sherlock is a great way of doing this :ok:
