### ISSUE TITLE
Support for removed site: Codeforces

### ISSUE THREAD

**Issue by a-r-r-o-w** [sherlock-project/sherlock#1654]
I do not think this issue fits under the criteria for Issue Template "Site Support Request" and so have opened a blank issue.

The support for [Codeforces](https://codeforces.com/) was removed in [this](https://github.com/sherlock-project/sherlock/commit/bd90ac174c35d0776962b44171730127ea20140b) commit due to false positives. I would like to request the support again with a proposed fix to the false positive issue.

There have been a few PRs in the past (#1602, #1394, #903) that add/fix support for Codeforces. I believe #1602 _might_ work but I cannot tell for sure. An alternative, and arguably more correct, way to support the site would be to use the Codeforces API that returns status `200` for valid users and status `400` for invalid users.

I've tested adding the following to `data.json` and can verify that it works without any false positives (none that I know of):

```
"Codeforces": {
  "errorType": "status_code",
  "url": "https://codeforces.com/api/user.info?handles={}",
  "urlMain": "https://codeforces.com/",
  "username_claimed": "tourist",
  "username_unclaimed": "noonewouldeverusethis7"
}
```

I would like to open a PR for the same if the proposed solution can be reviewed/tested.

**Comment by sdushantha** [comment]
Thank you for putting time and effort into this. Feel free to create a PR and I will take look at it as soon as possible :)

**Comment by a-r-r-o-w** [comment]
Cheers! I've opened #1661 and can confirm that it works in all cases I've tried. There don't seem to be false positives that were possible when support was dropped.

Also, thanks for creating sherlock! It's been of great use to me and I learnt quite a bit understanding how it works.

**Comment by a-r-r-o-w** [comment]
The PR has been merged, thanks!
