### ISSUE TITLE
Error while trying to even install numpy

### ISSUE THREAD

**Issue by Onionbread35** [sherlock-project/sherlock#1665]
error: subprocess-exited-with-error

  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [271 lines of output]
      Running from numpy source directory.                    setup.py:67: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result                                                 of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.                                               It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html                                   

        import numpy.distutils.command.sdist
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_common.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/_pcg64.pyx
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/bit_generator.pyx
      Processing numpy/random/mtrand.pyx
      Cythonizing sources
      INFO: blas_opt_info:
      INFO: blas_armpl_info:
      INFO: customize UnixCCompiler
      INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: blas_mkl_info:
      INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: blis_info:
      INFO:   libraries blis not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_info:
      INFO:   libraries openblas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: accelerate_info:
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_blas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_blas_info:
      INFO:   libraries satlas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_blas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_blas_info:
      INFO:   libraries f77blas,cblas,atlas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      /data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/system_info.py:2077: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        if self._calc_info(blas):
      INFO: blas_info:
      INFO:   libraries blas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      /data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/system_info.py:2077: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        if self._calc_info(blas):
      INFO: blas_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      /data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/system_info.py:2077: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        if self._calc_info(blas):
      INFO:   NOT AVAILABLE
      INFO:
      non-existing path in 'numpy/distutils': 'site.cfg'
      INFO: lapack_opt_info:
      INFO: lapack_armpl_info:
      INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_mkl_info:
      INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_lapack_info:
      INFO:   libraries openblas not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_clapack_info:
      INFO:   libraries openblas,lapack not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: flame_info:
      INFO:   libraries flame not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas,tatlas not found in /data/data/com.termux/files/usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_info:
      INFO:   libraries satlas,satlas not found in /data/data/com.termux/files/usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /data/data/com.termux/files/usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_info:
      INFO:   libraries f77blas,cblas,atlas not found in /data/data/com.termux/files/usr/lib
      INFO: <class 'numpy.distutils.system_info.atlas_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_info:
      INFO:   libraries lapack not found in ['/data/data/com.termux/files/usr/lib']
      INFO:   NOT AVAILABLE
      INFO:
      /data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/system_info.py:1902: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO: lapack_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      /data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/system_info.py:1902: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO:   NOT AVAILABLE
      INFO:
      INFO: numpy_linalg_lapack_lite:
      INFO:   FOUND:
      INFO:     language = c
      INFO:
      Warning: attempted relative import with no known parent package
      /data/data/com.termux/files/usr/lib/python3.11/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building py_modules sources
      creating build
      creating build/src.linux-aarch64-3.11
      creating build/src.linux-aarch64-3.11/numpy
      creating build/src.linux-aarch64-3.11/numpy/distutils
      INFO: building library "npymath" sources
      WARN: Could not locate executable armflang
      WARN: Could not locate executable gfortran
      WARN: Could not locate executable f95
      WARN: Could not locate executable ifort
      WARN: Could not locate executable ifc
      WARN: Could not locate executable lf95
      WARN: Could not locate executable pgfortran
      WARN: Could not locate executable nvfortran
      WARN: Could not locate executable f90
      WARN: Could not locate executable f77
      WARN: Could not locate executable fort
      WARN: Could not locate executable efort
      WARN: Could not locate executable efc
      WARN: Could not locate executable g77
      WARN: Could not locate executable g95
      WARN: Could not locate executable pathf95
      WARN: Could not locate executable nagfor
      WARN: Could not locate executable frt
      WARN: don't know how to compile Fortran code on platform 'posix'
      creating build/src.linux-aarch64-3.11/numpy/core
      creating build/src.linux-aarch64-3.11/numpy/core/src
      creating build/src.linux-aarch64-3.11/numpy/core/src/npymath
      INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_internal.h
      INFO:   adding 'build/src.linux-aarch64-3.11/numpy/core/src/npymath' to include_dirs.
      INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/ieee754.c
      INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_complex.c
      INFO: None - nothing done with h_files = ['build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_internal.h']
      INFO: building library "npyrandom" sources
      INFO: building extension "numpy.core._multiarray_tests" sources
      creating build/src.linux-aarch64-3.11/numpy/core/src/multiarray
      INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/multiarray/_multiarray_tests.c
      INFO: building extension "numpy.core._multiarray_umath" sources
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-goe15s6p/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-goe15s6p/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-goe15s6p/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-goe15s6p/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 479, in <module>
          setup_package()
        File "setup.py", line 471, in setup_package
          setup(**metadata)
        File "/data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-goe15s6p/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/data/data/com.termux/files/usr/lib/python3.11/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/lib/python3.11/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-goe15s6p/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/data/data/com.termux/files/usr/lib/python3.11/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.11/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/command/build.py", line 62, in run
          old_build.run(self)
        File "/data/data/com.termux/files/usr/lib/python3.11/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/lib/python3.11/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.11/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/command/build_src.py", line 144, in run
          self.build_sources()
        File "/data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/command/build_src.py", line 161, in build_sources
          self.build_extension_sources(ext)
        File "/data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/command/build_src.py", line 318, in build_extension_sources
          sources = self.generate_sources(sources, ext)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/distutils/command/build_src.py", line 378, in generate_sources
          source = func(extension, build_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/core/setup.py", line 506, in generate_config_h
          check_math_capabilities(config_cmd, ext, moredefs, mathlibs)
        File "/data/data/com.termux/files/usr/tmp/pip-install-uc8hi5p2/numpy_0f93abc54da747c3833d8fbd6cec679c/numpy/core/setup.py", line 192, in check_math_capabilities
          raise SystemError("One of the required function to build numpy is not"
      SystemError: One of the required function to build numpy is not available (the list is ['sin', 'cos', 'tan', 'sinh', 'cosh', 'tanh', 'fabs', 'floor', 'ceil', 'sqrt', 'log10', 'log', 'exp', 'asin', 'acos', 'atan', 'fmod', 'modf', 'frexp', 'ldexp', 'expm1', 'log1p', 'acosh', 'asinh', 'atanh', 'rint', 'trunc', 'exp2', 'copysign', 'nextafter', 'strtoll', 'strtoull', 'cbrt', 'log2', 'pow', 'hypot', 'atan2', 'creal', 'cimag', 'conj']).
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

**Comment by sukhrajbrar** [comment]
I am also getting this issue

**Comment by sdushantha** [comment]
This seems like an error with your env. and not Sherlock itself
