### ISSUE TITLE
python3 sherlock.py errno2

### ISSUE THREAD

**Issue by Nonom2** [sherlock-project/sherlock#1668]
## Checklist

- [x ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

hello I get an error after writing (python3 sherlock.py @user) after press enter they say python3 can't open file errno2 no such file or directory
![sherlock](https://user-images.githubusercontent.com/120130629/213699942-c0bbd841-d3be-47ff-9136-d0f1b5b4d420.png)

**Comment by sdushantha** [comment]
The command you have executed is incorrect. The following command is the correct one:
```command
python3 sherlock username
```

So with out `.py` and without the `@` before the username
