### ISSUE TITLE
Error on Dockerhub image 

### ISSUE THREAD

**Issue by renantmagalhaes** [sherlock-project/sherlock#1680]
## Checklist

- [X] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

There's two "errors" on my end.

1. The latest image on dockerhub(theyahya/sherlock) is from 10 months ago, with version 0.14.0 and not 0.14.2
2. Running the example provided in the README.md I got the following error
```
docker run theyahya/sherlock user123
Update Available!
You are running version 0.14.0. Version 0.14.2 is available at https://git.io/sherlock
ERROR:  Problem parsing json contents at 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  Missing attribute 'username_unclaimed'.
```
This file was modified 2 days ago, maybe the problem is there ?

**Comment by hanamurayuki** [comment]
Same here.
$ `python3 sherlock.py user123`
```
ERROR:  Problem parsing json contents at 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  Missing attribute 'username_unclaimed'.
```

**Comment by PrizeGotti** [comment]
Getting the same message whatever way I try to launch Sherlock.

**Comment by sdushantha** [comment]
Forgot to do a version bump. I have made the change in the latest commit. Now everyone should get an message alerting that a new version is available for download :+1:  
This is something I forgot to do when we dropped the default unclaimed usernames

**Comment by PandaFym** [comment]
to fix this issue, delete your sherlock folder, and re-download it 

git clone https://github.com/sherlock-project/sherlock.git 
cd sherlock
pip3 install -r requirements.txt 

I did a test run, 

[*] Checking username user on:

[+] 3dnews: http://forum.3dnews.ru/member.php?username=user
[+] 7Cups: https://www.7cups.com/@user
[+] 9GAG: https://www.9gag.com/u/user
[+] About.me: https://about.me/user
[+] Airliners: https://www.airliners.net/user/user/profile/photos
[+] AllMyLinks: https://allmylinks.com/user
[+] Anilist: https://anilist.co/user/user/
[+] Apple Developer: https://developer.apple.com/forums/profile/user
[+] Apple Discussions: https://discussions.apple.com/profile/user
[+] Archive of Our Own: https://archiveofourown.org/users/user

hopefully this helped
