### ISSUE TITLE
Missing attribute

### ISSUE THREAD

**Issue by ovanderz** [sherlock-project/sherlock#1682]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

There seems to be a missing attribute in the json file. I keep getting this error:
ERROR:  Problem parsing json contents at 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  Missing attribute 'username_unclaimed'.

**Comment by harrcc31** [comment]
Had the same issue, but deleted the sherlock directory and updated to the new version(Version 0.14.3 I believe), and the issue went away.

**Comment by sdushantha** [comment]
@ovanderz Please install the newest version of the Sherlock as a major change in the data.json file was made :)
