### ISSUE TITLE
Unable to install requirements

### ISSUE THREAD

**Issue by DIGI41** [sherlock-project/sherlock#1701]
- [ x] I'm reporting a bug in Sherlock's functionality
- [x ] The bug I'm reporting is not a false positive or a false negative
- [ x] I've verified that I'm running the latest version of Sherlock
- [ x] I've checked for similar bug reports including closed ones
- [x ] I've checked for pull requests that attempt to fix this bug

Honestly i don't even understand what is happening, i downloaded it on kali linux this morning and it worked very well, but now when i downloaded it on termux (i also did it before) and i keep getting this error and i can't even locate the main problem, so here is everything

~/sherlock $ pip3 install -r requirements.txt
Collecting certifi>=2019.6.16                     Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)                                      Collecting colorama>=0.4.1
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)                                      Collecting PySocks>=1.7.0
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting requests>=2.22.0
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)                                         Collecting requests-futures>=1.0.0
  Using cached requests_futures-1.0.0-py2.py3-none-any.whl (7.4 kB)                             Collecting stem>=1.8.0
  Using cached stem-1.8.1.tar.gz (2.9 MB)         Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done  Collecting torrequest>=0.1.0
  Using cached torrequest-0.1.0.tar.gz (1.5 kB)   Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas>=1.0.0                          Using cached pandas-1.5.3.tar.gz (5.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error           
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [304 lines of output]                           Collecting setuptools>=51.0.0
        Using cached setuptools-67.4.0-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting Cython<3,>=0.29.32
        Using cached Cython-0.29.33-py2.py3-none-any.whl (987 kB)
      Collecting oldest-supported-numpy>=2022.8.16
        Using cached oldest_supported_numpy-2022.11.19-py3-none-any.whl (4.9 kB)
      Collecting numpy==1.23.2
        Using cached numpy-1.23.2.tar.gz (10.7 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'                                Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: numpy
        Building wheel for numpy (pyproject.toml): started
        Building wheel for numpy (pyproject.toml): finished with status 'error'                         error: subprocess-exited-with-error

        × Building wheel for numpy (pyproject.toml) did not run successfully.                           │ exit code: 1                                  ╰─> [274 lines of output]
            setup.py:71: RuntimeWarning: NumPy 1.23.2 may not yet support Python 3.11.                        warnings.warn(                                Running from numpy source directory.            setup.py:86: DeprecationWarning:
                                                              `numpy.distutils` is deprecated since NumPy 1.23.0, as a result                                 of the deprecation of `distutils` itself. It will be removed for
              Python >= 3.12. For older Python versions it will remain present.                               It is recommended to use `setuptools < 60.0` for those Python versions.                         For more details, see:
                https://numpy.org/devdocs/reference/distutils_status_migration.html                                                                                                                           import numpy.distutils.command.sdist                                                          Processing numpy/random/_bounded_integers.pxd.in                                                Processing numpy/random/bit_generator.pyx
            Processing numpy/random/_common.pyx             Processing numpy/random/_mt19937.pyx            Processing numpy/random/_sfc64.pyx              Processing numpy/random/_pcg64.pyx              Processing numpy/random/mtrand.pyx              Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/_generator.pyx                                                          Processing numpy/random/_philox.pyx
            Cythonizing sources                             INFO: blas_opt_info:
            INFO: blas_armpl_info:
            INFO: customize UnixCCompiler
            INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blas_mkl_info:
            INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blis_info:
            INFO:   libraries blis not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_info:
            INFO:   libraries openblas not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: accelerate_info:
            INFO:   NOT AVAILABLE
            INFO:
            INFO: atlas_3_10_blas_threads_info:
            INFO: Setting PTATLAS=ATLAS                     INFO:   libraries tatlas not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE                           INFO:
            INFO: atlas_3_10_blas_info:
            INFO:   libraries satlas not found in ['/data/data/com.termux/files/usr/lib']                   INFO:   NOT AVAILABLE
            INFO:                                           INFO: atlas_blas_threads_info:                  INFO: Setting PTATLAS=ATLAS
            INFO:   libraries ptf77blas,ptcblas,atlas not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE                           INFO:                                           INFO: atlas_blas_info:
            INFO:   libraries f77blas,cblas,atlas not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE                           INFO:                                           /data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/system_info.py:2077: UserWarning:
                Optimized (vendor) Blas libraries are not found.                                                Falls back to netlib Blas library which has worse performance.                                  A better performance should be easily gained by switching
                Blas library.                                 if self._calc_info(blas):                     INFO: blas_info:
            INFO:   libraries blas not found in ['/data/data/com.termux/files/usr/lib']                     INFO:   NOT AVAILABLE
            INFO:                                           /data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/system_info.py:2077: UserWarning:                                                   Blas (http://www.netlib.org/blas/) libraries not found.                                         Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [blas]) or by setting                                    the BLAS environment variable.
              if self._calc_info(blas):                     INFO: blas_src_info:                            INFO:   NOT AVAILABLE
            INFO:                                           /data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/system_info.py:2077: UserWarning:                                                   Blas (http://www.netlib.org/blas/) sources not found.                                           Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [blas_src]) or by setting                                the BLAS_SRC environment variable.                                                            if self._calc_info(blas):                     INFO:   NOT AVAILABLE
            INFO:                                           non-existing path in 'numpy/distutils': 'site.cfg'
            INFO: lapack_opt_info:                          INFO: lapack_armpl_info:                        INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']            INFO:   NOT AVAILABLE                           INFO:
            INFO: lapack_mkl_info:                          INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE                           INFO:                                           INFO: openblas_lapack_info:
            INFO:   libraries openblas not found in ['/data/data/com.termux/files/usr/lib']                 INFO:   NOT AVAILABLE
            INFO:                                           INFO: openblas_clapack_info:                    INFO:   libraries openblas,lapack not found in ['/data/data/com.termux/files/usr/lib']                                                          INFO:   NOT AVAILABLE
            INFO:                                           INFO: flame_info:                               INFO:   libraries flame not found in ['/data/data/com.termux/files/usr/lib']                    INFO:   NOT AVAILABLE                           INFO:
            INFO: atlas_3_10_threads_info:                  INFO: Setting PTATLAS=ATLAS                     INFO:   libraries tatlas,tatlas not found in /data/data/com.termux/files/usr/lib                INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
            INFO:   NOT AVAILABLE                           INFO:                                           INFO: atlas_3_10_info:
            INFO:   libraries satlas,satlas not found in /data/data/com.termux/files/usr/lib
            INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>                                     INFO:   NOT AVAILABLE
            INFO:                                           INFO: atlas_threads_info:                       INFO: Setting PTATLAS=ATLAS
            INFO:   libraries ptf77blas,ptcblas,atlas not found in /data/data/com.termux/files/usr/lib
            INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>                                  INFO:   NOT AVAILABLE
            INFO:                                           INFO: atlas_info:                               INFO:   libraries f77blas,cblas,atlas not found in /data/data/com.termux/files/usr/lib                                                          INFO: <class 'numpy.distutils.system_info.atlas_info'>                                          INFO:   NOT AVAILABLE                           INFO:
            INFO: lapack_info:                              INFO:   libraries lapack not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE                           INFO:                                           /data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/system_info.py:1902: UserWarning:
                Lapack (http://www.netlib.org/lapack/) libraries not found.                                     Directories to search for the libraries can be specified in the                                 numpy/distutils/site.cfg file (section [lapack]) or by setting
                the LAPACK environment variable.              return getattr(self, '_calc_info_{}'.format(name))()
            INFO: lapack_src_info:                          INFO:   NOT AVAILABLE                           INFO:
            /data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/system_info.py:1902: UserWarning:                                                   Lapack (http://www.netlib.org/lapack/) sources not found.
                Directories to search for the sources can be specified in the                                   numpy/distutils/site.cfg file (section [lapack_src]) or by setting                              the LAPACK_SRC environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()                                          INFO:   NOT AVAILABLE
            INFO:                                           INFO: numpy_linalg_lapack_lite:                 INFO:   FOUND:
            INFO:     language = c                          INFO:     define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
            INFO:                                           Warning: attempted relative import with no known parent package
            /data/data/com.termux/files/usr/lib/python3.11/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'                   warnings.warn(msg)                            running bdist_wheel
            running build                                   running config_cc                               INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options                                                       running config_fc
            INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options                                                      running build_src                               INFO: build_src
            INFO: building py_modules sources
            creating build                                  creating build/src.linux-aarch64-3.11                                                           creating build/src.linux-aarch64-3.11/numpy
            creating build/src.linux-aarch64-3.11/numpy/distutils                                           INFO: building library "npymath" sources                                                        WARN: Could not locate executable armflang                                                      WARN: Could not locate executable gfortran
            WARN: Could not locate executable f95
            WARN: Could not locate executable ifort
            WARN: Could not locate executable ifc
            WARN: Could not locate executable lf95
            WARN: Could not locate executable pgfortran
            WARN: Could not locate executable nvfortran
            WARN: Could not locate executable f90
            WARN: Could not locate executable f77
            WARN: Could not locate executable fort
            WARN: Could not locate executable efort                                                         WARN: Could not locate executable efc                                                           WARN: Could not locate executable g77
            WARN: Could not locate executable g95                                                           WARN: Could not locate executable pathf95                                                       WARN: Could not locate executable nagfor
            WARN: Could not locate executable frt                                                           WARN: don't know how to compile Fortran code on platform 'posix'                                creating build/src.linux-aarch64-3.11/numpy/core
            creating build/src.linux-aarch64-3.11/numpy/core/src                                            creating build/src.linux-aarch64-3.11/numpy/core/src/npymath                                    INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_internal.h
            INFO:   adding 'build/src.linux-aarch64-3.11/numpy/core/src/npymath' to include_dirs.                                                           INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/ieee754.c
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_complex.c
            INFO: None - nothing done with h_files = ['build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_internal.h']
            INFO: building library "npyrandom" sources                                                      INFO: building extension "numpy.core._multiarray_tests" sources                                 creating build/src.linux-aarch64-3.11/numpy/core/src/multiarray
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/multiarray/_multiarray_tests.c
            INFO: building extension "numpy.core._multiarray_umath" sources
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>                                                 main()
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-3k2dkntn/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 230, in build_wheel
                return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-3k2dkntn/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
                self.run_setup()                              File "/data/data/com.termux/files/usr/tmp/pip-build-env-3k2dkntn/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup                                           self).run_setup(setup_script=setup_script)                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-3k2dkntn/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup                                           exec(compile(code, __file__, 'exec'), locals())                                               File "setup.py", line 493, in <module>
                setup_package()                               File "setup.py", line 485, in setup_package                                                       setup(**metadata)
              File "/data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/core.py", line 169, in setup                                                return old_setup(**new_attr)
                       ^^^^^^^^^^^^^^^^^^^^^                  File "/data/data/com.termux/files/usr/tmp/pip-build-env-3k2dkntn/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 153, in setup                                                 return distutils.core.setup(**attrs)                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                          File "/data/data/com.termux/files/usr/lib/python3.11/distutils/core.py", line 148, in setup
                dist.run_commands()                           File "/data/data/com.termux/files/usr/lib/python3.11/distutils/dist.py", line 966, in run_commands
                self.run_command(cmd)
              File "/data/data/com.termux/files/usr/lib/python3.11/distutils/dist.py", line 985, in run_command                                                 cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-3k2dkntn/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')                     File "/data/data/com.termux/files/usr/lib/python3.11/distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/lib/python3.11/distutils/dist.py", line 985, in run_command                                                 cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/command/build.py", line 62, in run
                old_build.run(self)                           File "/data/data/com.termux/files/usr/lib/python3.11/distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)                    File "/data/data/com.termux/files/usr/lib/python3.11/distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/lib/python3.11/distutils/dist.py", line 985, in run_command                                                 cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()                          File "/data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/command/build_src.py", line 161, in build_sources                           self.build_extension_sources(ext)                                                             File "/data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/command/build_src.py", line 318, in build_extension_sources                 sources = self.generate_sources(sources, ext)                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/distutils/command/build_src.py", line 378, in generate_sources                        source = func(extension, build_dir)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                           File "/data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/core/setup.py", line 513, in generate_config_h
                check_math_capabilities(config_cmd, ext, moredefs, mathlibs)                                  File "/data/data/com.termux/files/usr/tmp/pip-install-izf5yusp/numpy_74c5da85d7e24b52bc8cd5cd67b5ebe5/numpy/core/setup.py", line 176, in check_math_capabilities
                raise SystemError("One of the required function to build numpy is not"                      SystemError: One of the required function to build numpy is not available (the list is ['sin', 'cos', 'tan', 'sinh', 'cosh', 'tanh', 'fabs', 'floor', 'ceil', 'sqrt', 'log10', 'log', 'exp', 'asin', 'acos', 'atan', 'fmod', 'modf', 'frexp', 'ldexp']).                                        [end of output]
                                                        note: This error originates from a subprocess, and is likely not a problem with pip.            ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects                                             [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.          error: subprocess-exited-with-error
                                                × pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output

I already tried : - updating and upgrading Python and pip
                           - MATHLIB="m" pip3 install numpy
                           - pip3 install numpy
                           - pip install setuptools==65.0.1

**Comment by SkyCreedPH** [comment]
same issue

**Comment by SkyCreedPH** [comment]
but mine failed for numpy

**Comment by sdushantha** [comment]
This is an environment issue and not an issue with Sherlock, therefore I will be closing this issue
