### ISSUE TITLE
Facing an issue when i search for a user :  

### ISSUE THREAD

**Issue by HirenUpadhyay** [sherlock-project/sherlock#1720]

**Comment by HirenUpadhyay** [comment]
A problem occurred while checking for an update: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by sdushantha** [comment]
This is an issue with your enviornment where there is something wrong with your internet. This can be fixed by searching for an answer on Stackoverflow. Closing this as it is not an issue with Sherlock
