### ISSUE TITLE
new bug when running the program

### ISSUE THREAD

**Issue by fmihaif** [sherlock-project/sherlock#1727]
when i test the sherlock , it says "ERROR:  Problem parsing json contents at 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  Missing attribute 'username_unclaimed'." 
maybe the problem is from my pc but i dont know yet....needing some help!!!!!!!!!!

**Comment by sdushantha** [comment]
Reclone Sherlock and run the latest version, that should solve the issue :)
