### ISSUE TITLE
OnlyFans False Negative

### ISSUE THREAD

**Issue by ThePornHelper** [sherlock-project/sherlock#1744]
## Checklist

- [x] I'm reporting a website that is returning **false negative** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false negative
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

I'm getting a false negative for the OnlyFans site, I've tried fixing it by looking at issue #1342 but it does not work for me.

Here is what Sherlock prints:
``` 
python3 sherlock belledelphine --nsfw --print-all
[*] Checking username belledelphine on:
...
[-] OnlyFans: Not Found!
...
[*] Search completed with 105 results
```

This is what my sherlock.py file looks like for nsfw:
```
parser.add_argument("--nsfw", "-n",
                        action="store_true", default=False,
                        help="Include checking of NSFW sites from default list.")
```

This is what my data.json file looks like:
```
"OnlyFans": {
    "errorType": "status_code",
    "isNSFW": true,
    "url": "https://onlyfans.com/{}",
    "urlMain": "https://onlyfans.com/",
    "username_claimed": "theemilylynne",
    "username_unclaimed": "boombastic80085"
```
If you guys need more information let me know.

Thank You.

**Comment by ThePornHelper** [comment]
I have found a temporary fix to my problem. In order to get Sherlock to search for OnlyFans you need to add ` --local ` when running Sherlock. Also I had to change my data.json file a bit.

Here is what my data.json file looks like now:
```
"OnlyFans": {
    "errorType": "status_code",
    "url": "https://onlyfans.com/{}",
    "urlMain": "https://onlyfans.com/",
    "username_claimed": "theemilylynne",
    "username_unclaimed": "noonewouldeverusethis7"
```

This is what running Sherlock looks like for me:

Terminal Input:
` Python3 sherlock belledelphine --nsfw --local `

Output:
```
[*] Checking username belledelphine on:
...
[+] OnlyFans: https://onlyfans.com/belledelphine
...
[*] Search completed with 103 results
```

This is not a complete fix as I still get false positives. Ideally it would be better to have no false positives or false negatives but I would much rather have a false positive than a false negative.

**Comment by iamzewen** [comment]
I would suggest switching to Fansly as a way of checking for valid accounts. Their endpoint is: https://apiv2.fansly.com/api/v1/account?usernames=username

Positive hit example: https://apiv2.fansly.com/api/v1/account?usernames=amouranth

**Comment by w3Abhishek** [comment]
@ThePornHelper The issue has been resolved. OnlyFans is removed from supported site. Refer to this [PR](https://github.com/sherlock-project/sherlock/pull/1775).

You can now close this issue.
