### ISSUE TITLE
8tracks.com false positive

### ISSUE THREAD

**Issue by tosatur** [sherlock-project/sherlock#1762]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

8tracks.com seems to be coming up every time regardless of if the account is real or not.

False positive usernames:
- tosatur
- bigsean2296
- drewin8

**Comment by divyanash911** [comment]
Hey can you assign me this issue. I plan to create a webcrawler which will travel to the generated links and check if the page actually exists or not reducing false positives in the final output

**Comment by w3Abhishek** [comment]
@tosatur I just checked. It's not false positive.

On 8tracks website:
![image](https://user-images.githubusercontent.com/40134208/233176464-a227ce5b-3fd3-463e-8280-cf3d1f3dce4d.png)
![image](https://user-images.githubusercontent.com/40134208/233176721-39fd2ff2-710a-455c-9246-fe6e44ef8abf.png)

Checking with Sherlock:
![image](https://user-images.githubusercontent.com/40134208/233176965-b58802fc-f29a-42b4-a48b-67269b7b1bcd.png)

Kindly close this issue.

**Comment by 984mk** [comment]
Sorry iam seriously realy bad at this iam trying

**Comment by sk3lk0** [comment]
```
docker run sherlock:latest --site 8tracks asddasdsadasdasd
[*] Checking username asddasdsadasdasd on:

[+] 8tracks: https://8tracks.com/asddasdsadasdasd

[*] Search completed with 1 results
```

**Comment by sk3lk0** [comment]
looks like sherlock shows different result in docker and in terminal
