### ISSUE TITLE
the cloud shell is not showing 

### ISSUE THREAD

**Issue by KHA444** [sherlock-project/sherlock#1768]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by KHA444** [comment]
the cloud shell is not opening

**Comment by PwnedDev** [comment]
can you add more description? show us terminal output or logs, Thanks.

**Comment by akaye47** [comment]
snoozefest. how many times do I have to report this spam
________________________________

**Comment by sdushantha** [comment]
The cloudshell was removed a whlie ago from the Readme
