### ISSUE TITLE
Support for Instagram

### ISSUE THREAD

**Issue by javalsai** [sherlock-project/sherlock#1797]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

Support to detect Instagram accounts, I already found closed issues saying that it has false positives and was removed because of that, but couldn't find any usernames to check it out and I found a config that seems to work for it:
```json
{
  "Instagram": {
    "errorMsg": "This content is no longer available",
    "errorType": "message",
    "url": "https://www.instagram.com/{}/?__a=1",
    "urlMain": "https://www.instagram.com"
  }
}
```
The only issue I see with that config is that clicking on the generated link wouldn't show  the proper profile and would need to remove the `?__a=1` to do so. But it seems to do the work of detecting the account.

**EDIT**: I accidentally pressed ctrl and sent the uncompleted issue.

**Comment by mrT23** [comment]
Similar Issues:

1. [Instagram not found please make and update about it .](https://github.com/sherlock-project/sherlock/issues/977)

2. [Does Sherlock really supports Instagram?](https://github.com/sherlock-project/sherlock/issues/1816)

3. [story](https://github.com/sherlock-project/sherlock/issues/1807)

4. [Facebook account hack ](https://github.com/sherlock-project/sherlock/issues/1671)

**Comment by javalsai** [comment]
> Similar Issues:
> 
>     1. [Instagram not found please make and update about it .](https://github.com/sherlock-project/sherlock/issues/977)
> 
>     2. [Does Sherlock really supports Instagram?](https://github.com/sherlock-project/sherlock/issues/1816)
> 
>     3. [story](https://github.com/sherlock-project/sherlock/issues/1807)
> 
>     4. [Facebook account hack ](https://github.com/sherlock-project/sherlock/issues/1671)

I don't know if there has been any progress since I opened this issue, if I say something outdated please correct me.

But from the issues you've linked, #1671 and #1807 doesn't really have any content, in #1816 mentions that it was removed due to false positives, I'm issuing this recommendation that seems to work, and without knowing which are the false positives I can't test them. And in #977 it's said that it added Instagram support that seems to have been later removed as mentioned in #1816.

**Comment by mrT23** [comment]
@javalsai 
sorry for spamming a bit.
i tested a new tool that _automatically_ finds similar issues in a repo (https://github.com/Codium-ai/pr-agent/pull/282)
i wanted to test it on public repos, with lots of issues.

i think it did a decent job in finding a similar issue to what you opened.
This could aid in presenting similar previous issues for reference, and making sure there are no identical issues were already opened.

**Comment by javalsai** [comment]
@mrT23 
Don't worry, the response already looked automated and I completely understand doing so having in mind all of the spam that there is in these issues.

Don't worry about deleting the message I don't mind about it, tbh it did a quite good job in merging similar topics and linking them. I even think that it can help maintainers to find those other issues and close them if they consider.
