### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by Fridaygaruba** [sherlock-project/sherlock#1800]
## Checklist
 https://www.facebook.com/profile.php?id=100015455594893&mibextid=LQQJ4d

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description
 https://www.facebook.com/profile.php?id=100015455594893&mibextid=LQQJ4d

WRITE DESCRIPTION HERE

**Comment by Willie85** [comment]
> # clone the repo
$ git clone https://github.com/sherlock-project/sherlock.git

# change the working directory to sherlock
$ cd sherlock

# install the requirements
$ python3 -m pip install -r requirements.txt

**Comment by Willie85** [comment]
# clone the repo
$ git clone https://github.com/sherlock-project/sherlock.git

# change the working directory to sherlock
$ cd sherlock

# install the requirements
$ python3 -m pip install -r requirements.txt

**Comment by Willie85** [comment]
- name: markdownlint-cli2-action
  uses: DavidAnson/markdownlint-cli2-action@v11.0.0
