### ISSUE TITLE
Make Sherlock into an organizeation?

### ISSUE THREAD

**Issue by sdushantha** [sherlock-project/sherlock#182]
I was thinking it would be cool to make Sherlock into an organization. This would then allow us to make other projects building off Sherlock. For example, a web API #129

Its just a thought :)

**Comment by TheYahya** [comment]
It's good idea @sdushantha 
I just don't want to start web api, desktop app, etc before making `sherlock` a pypi module #152

**Comment by sdushantha** [comment]
>  I just don't want to start web api, desktop app, etc before making `sherlock` a pypi module #152
@TheYahya I do agree about that

I was thinking if we make `sherlock` as an organization, we could make a website about `sherlock` and the great part of having an organization is that we would get a custom subdomain 
(e.g. sherlock.github.io)

And would not need to use one of our sites
(e.g. sdushantha.github.io/sherlock.html)

I could start making the site, but not a web dev, so I dont think I will be able to make a good one. But, you know, there are many templates out there :)

**Comment by sdushantha** [comment]
@TheYahya thanks for creating @sherlock-project 😄

**Comment by TheYahya** [comment]
I just create the organization and invite you @sdushantha,
It would be great if you create a website about sherlock, I create a [repo](https://github.com/sherlock-project/website) for now.
I any recommendation if you have [in here](https://github.com/sherlock-project/api/issues/1)
And it would be great if you take a look at #152 ☺️
