### ISSUE TITLE
G2G false positive

### ISSUE THREAD

**Issue by Troughy** [sherlock-project/sherlock#1834]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

The username EDG_7_ is giving false positive on g2g.com

**Comment by sdushantha** [comment]
I've tested Sherlock from different IPs and G2G does not respond with False positives anymore

**Comment by Pietagorh** [comment]
I still get false positives for any valid username of length under 12 chars
