### ISSUE TITLE
authorstream false positive

### ISSUE THREAD

**Issue by Troughy** [sherlock-project/sherlock#1835]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

authorSTREAM seems to be down, checked with 2 different usernames, returned a false positive each time

**Comment by sdushantha** [comment]
I've tested Sherlock from different IPs and authorstream does not respond with False positives anymore
