### ISSUE TITLE
IRL.com has shut down

### ISSUE THREAD

**Issue by Troughy** [sherlock-project/sherlock#1838]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

Technically it's returning false positive results but it's because irl.com has shut down

**Comment by sdushantha** [comment]
Thank you for letting me know. Fixed in b47c458d6c0a30b1ca71a93590c14a992709370d now
