### ISSUE TITLE
usernames not found

### ISSUE THREAD

**Issue by SNIPERofEG** [sherlock-project/sherlock#1848]
## Checklist

- [ x] I'm reporting a bug in Sherlock's functionality
- [x ] The bug I'm reporting is not a false positive or a false negative
- [ x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

some websites that i have an account on don't show that i have the account like xboxgamertag and steamcommunity and there are some websites that are false positive 
please find a solution or if there was one please tell me

**Comment by theClawsmos** [comment]
Hi SNIPERofEG, I hope you are doing well.

Are you sure that xBox gamertags and Steam community accounts are in Sherlock? I'm new here so please correct me if I'm wrong, but I don't think Sherlock checks those. As for the false positives, I am sorry, I can not help 😔

**Comment by SNIPERofEG** [comment]
Well in the websites that it checks it has the xbox and steam usernames and if you used the --print-all you will see that it checks for the xbox and steam but i will try a proxy the next time i try it maybe the problem is at my own network

**Comment by theClawsmos** [comment]
Maybe 🤷🏻  Im not sure. It could be on your end 👍🏻

**Comment by ausward** [comment]
These should be a false negative issue, not a bug report. I see the steam URL in the data.json file also gives me false negatives. The xboxgamertags works for me if I go directly to the webpage in the data.json file, but sherlock doesn't show it, odd.

**Comment by theClawsmos** [comment]
I mean I dont have any of these except for Chess.com, Codecademy, Github, and Lichess so I cant really help, sorry.

**Comment by ausward** [comment]
it looks like #1815 might help fix the steam issue
