### ISSUE TITLE
issue with py -m pip install -r requirements.txt (windows)

### ISSUE THREAD

**Issue by Rac-crypto** [sherlock-project/sherlock#1866]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE
Hey , facing an issue when I try to run "py -m pip install -r requirements.txt"
i receive this error
Unable to create process using 'C:\Users\racha\AppData\Local\Microsoft\WindowsApps\python.exe  -m pip install -r requirements.txt': The system cannot find the file specified.
im really new at this, and it could be user error (honestly likely) so im sorry in advance

**Comment by shk0-0** [comment]
Got the same issue, mine says
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by ejsinfuego** [comment]
![image](https://github.com/sherlock-project/sherlock/assets/67304574/22208edc-e316-41b5-b25d-e198193db89b)

Just make sure you are doing the command on the right directory. Check the folder where "requirements.txt" stored and do the command on that folder.

**Comment by shk0-0** [comment]
Ah yes same, I followed another tutorial and did it on a VM using Kali as
well. Thanks for your response.

**Comment by sdushantha** [comment]
Since this is and issue with your environment and not Sherlock itself, I'll be closing this issue

**Comment by Alishbarana** [comment]
> Got the same issue, mine says ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

yes! i get the same and i am fully exhausted but not find any solution

**Comment by ppfeister** [comment]
@Alishbarana - [Reference the install section of the ReadMe](https://github.com/sherlock-project/sherlock?tab=readme-ov-file#installation) rather than a third party guide.

The requirements.txt file no longer exists and installing from source is not supported in any official capacity outside of contributing to the project.

Note that Windows doesn't have proper documentation yet, but the proper method for Windows is described in #2230.
