### ISSUE TITLE
Look 👀+ This repository is not meant to contain everything but only good quality stuff.

### ISSUE THREAD

**Issue by TheMotherMaryGroup** [sherlock-project/sherlock#1868]
![linux.png](https://github.com/sherlock-project/sherlock/assets/143231297/7212e5f1-7a34-4a3d-bbc3-714ab01aa354)

**Comment by TheMotherMaryGroup** [comment]
> ![linux.png](https://github.com/sherlock-project/sherlock/assets/143231297/7212e5f1-7a34-4a3d-bbc3-714ab01aa354)
> 
> 
> # - [ ] ~~```
```
Look 
```
```~~
[]()@

**Comment by hengkimly7575-cyber** [comment]
+ This repository is not meant to contain everything but only good quality stuff.
