### ISSUE TITLE
Fiverr false positive

### ISSUE THREAD

**Issue by rs-pro0** [sherlock-project/sherlock#1878]
## Checklist

- [ x] I'm reporting a website that is returning **false positive** results
- [ x] I've checked for similar site support requests including closed ones
- [ x] I've checked for pull requests attempting to fix this false positive
- [ x] I'm only reporting **one** site (create a separate issue for each site)

## Description

https://www.fiverr.com/fincali1979 is not a real fiverr account I checked for closed issues and fiverr is marked as fixed, but it doesn't work now

**Comment by Rohxn16** [comment]
Hey I want to work on this issue, is it still open?
