### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by muhammadrohan503** [sherlock-project/sherlock#1927]
![Untitled](https://github.com/sherlock-project/sherlock/assets/149036681/f0604225-5bb3-42ec-bd12-0125b45c62cc)
how to resolve this issue

**Comment by adityatripathi676** [comment]
### Solution:
Open your terminal in Desktop and then clone the repository using `"**git clone https://github.com/sherlock-project/sherlock.git**" `
then type `"**cd sherlock**"` 
then `"**ls**"` and check whether there is a file **requirements.txt**"
if you found it then type `"**python3 -m pip install -r requirements.txt**"` and you are good to do...
Now, To test the tool use the following command ```
"**python3 sherlock --help**"```. This command will open the help index of the tool.

**Comment by matheusfelipeog** [comment]
Thank you for opening this issue, @muhammadrohan503.

This can be caused in incorrect proxy settings.

Try these commands:

```bash
git config --global --unset http.proxy
git config --global --unset https.proxy
```

Also set user name and user email:

```bash
git config --global user.name "user name"
git config --global user.email "user email"
```

I hope this helps to resolve your error.

---

Also, check out:

- https://stackoverflow.com/questions/20370294/git-could-not-resolve-host-github-com-error-while-cloning-remote-repository-in
- https://stackoverflow.com/questions/61357091/unable-to-access-could-not-resolve-host
