### ISSUE TITLE
How to add instagram or facebook in sherlock dataset?

### ISSUE THREAD

**Issue by MuizzuddinRifqi** [sherlock-project/sherlock#1941]

**Comment by matheusfelipeog** [comment]
Thank you for opening this issue, @MuizzuddinRifqi ;)

Facebook and Instagram have already been added in the past and subsequently removed.

You can see the reason for removal in the following links:

- Facebook: [sherlock/removed_sites.md#facebook](https://github.com/sherlock-project/sherlock/blob/master/removed_sites.md#facebook)
- Instagram: [sherlock/removed_sites.md#instagram](https://github.com/sherlock-project/sherlock/blob/master/removed_sites.md#instagram)
