### ISSUE TITLE
--timeout error

### ISSUE THREAD

**Issue by alvaro2203** [sherlock-project/sherlock#1960]
## Checklist

- [X] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

## Question

im having the following error: sherlock: error: argument --timeout: invalid timeout_check value: '1'
What should I write as argument of --timeout?

**Comment by matheusfelipeog** [comment]
Thank you for opening this issue, @alvaro2203 😄 

I checked and found that the function responsible for validating and converting the value provided for the `--timeout` flag has an incorrect implementation.

I will fix this. Once fixed, you should update your local clone with:

```bash
git pull origin master
```

**Comment by matheusfelipeog** [comment]
Done ✅
