### ISSUE TITLE
Trouble with the "{%}" argument 

### ISSUE THREAD

**Issue by TryMyWagon** [sherlock-project/sherlock#1968]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

(Didn't know if this was better fit as a question or a bug, sry for the inconvenience)

I have sherlock set up in a docker container and everything works 100% fine (eg.1) EXCEPT for trying to use the {%} argument (eg.2), am i stupid and have the syntax wrong?, is this powershell interpretation issue? or is this a genuine bug.

eg.1 terminal functioning as intended

      PS C:\Windows\system32> docker run --rm -t mysherlock-image foobar
      [*] Checking username foobar on:
      
      [+] 7Cups: https://www.7cups.com/@foobar
      [+] 8tracks: https://8tracks.com/foobar
      [+] About.me: https://about.me/foobar
      [+] Academia.edu: https://independent.academia.edu/foobar
      [+] Airliners: https://www.airliners.net/user/foobar/profile/photos
      [+] AllMyLinks: https://allmylinks.com/foobar
      [+] Amino: https://aminoapps.com/u/foobar
      [+] Apple Developer: https://developer.apple.com/forums/profile/foobar
      PS C:\Windows\system32> ^C

eg.2 throwing big angry errors when using {%}
      
      PS C:\Windows\system32> docker run --rm -t mysherlock-image foo{%}bar
      usage: sherlock.py [-h] [--version] [--verbose] [--folderoutput FOLDEROUTPUT] [--output OUTPUT] [--tor] [--unique-tor] [--csv] 
      [-x    lsx] [--site SITE_NAME] [--proxy PROXY_URL] [--json JSON_FILE] [--timeout TIMEOUT] [--print-all] [--print-found]
      [--no-color] [--browse] [--local] [--nsfw]
      sherlock.py: error: unrecognized arguments: -encodedCommand JQA= bar -inputFormat xml text

I'm 99% sure i'm probably just stupid, and this is a me problem. but thought id post anyway just in case. 

*Latest build as of today*

**Comment by matheusfelipeog** [comment]
Hi @TryMyWagon, thanks for opening this issue.

You are not stupid. I checked, and you are right about the problem.

It seems we made a small error in the documentation, and we apologize for that. I will fix it. 😅

You should use `{?}` instead of `{%}`:

```bash
python sherlock user{?}name
```

or:

```bash
python sherlock 'user{?}name'
```

**Comment by matheusfelipeog** [comment]
> I will fix it.

Done ✅
