### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by obskyr** [sherlock-project/sherlock#2]
Running the program with a username that doesn't exist on any of the supported sites, you get 16 false positives:

* BLIP.fm
* CashMe
* Disqus
* Facebook
* Flickr
* Flipboard
* Foursquare
* GitHub
* GoodReads
* Gravatar
* Newgrounds
* SoundCloud
* Tumblr
* Unsplash
* VSCO
* iMGSRC.RU

In other words, the logic that determines whether a profile exists or not doesn't work correctly for those sites. Having a look at the current code structure, you might need to split the sites out into their own modules to get it to work satisfactorily – you'll need some more complicated logic for some of these sites (e.g. Tumblr, to pass the Oath GDPR gate).

**Comment by sdushantha** [comment]
I will try to fix this as quick as possible because if it returns wrong results, then Sherlock is not a reliable  :(

**Comment by anabh4569** [comment]
I got false positives on twitter, facebook, github, soundcloud, disqus, deviantart, flipboard, scribd, gravatar, imgsrc, cash.me, behance, goodreads, vsco, newgrounds, tripadvisor, blip.fm, bandcamp, slack, flickr, wordpress and unsplash for 2/3 different usernames.

**Comment by 2toxic** [comment]
I also have false positives on all sites, mentioned by @obskyr and three more:
* Keybase
* Slack
* WordPress

**Comment by rpural** [comment]
I'm still receiving false positives on several sites. Sherlock says account found, but when I try the link provided, I get a 404. It seems like the simple solution would be to check the status code returned in the http request.

https://www.github.com/rpnix
https://disqus.com/rpnix
https://rpnix.deviantart.com
https://slideshare.net/rpnix
https://bitbucket.org/rpnix
http://en.gravatar.com/rpnix
https://cash.me/rpnix
 https://vsco.co/rpnix
https://www.flickr.com/people/rpnix
https://www.quora.com/profile/rpnix
https://pixabay.com/en/users/rpnix
https://giphy.com/rpnix
https://www.taringa.net/rpnix

Some of these are specifically 404 responses, some are a page saying the id wasn't found and requesting you to sign up.

rpn01@R5057499  sherlock [master] 0 $ python3 sherlock.py --version
sherlock.py 0.1.0
Python HTTP for Humans.:  2.19.1
Python:  3.7.0
rpn01@R5057499  sherlock [master] 0 $

**Comment by crock** [comment]
@rpural Simply checking the HTTP status code that is returned is not a fool proof solution. Not all sites return a 404 when a user profile is not found. For example, Steam IDs and Steam groups do not. You literally have to parse the HTML for a particular string when checking Steam.

I have 3 years of experience building social media checkers. Check out my open-source Python checker if you have time. 
https://github.com/checker/cli

**Comment by 2toxic** [comment]
I found false negative, but I can't find where the bug lies. `python sherlock.py romanova` gives negative result in VK, but https://vk.com/romanova is existing profile.
Maybe reason for wrong result is that profile is hidden, but VK returns 200 and everything is ok.

I checked if it was problem with user agent, but sherlock's is not banned by vk and curl request returns 200.

**Comment by hoadlck** [comment]
I believe that all of these have been addressed as of now.  

The only case where we still have problems is in sites where Sherlock depends on error text, and the user ends up getting a different language.
