### ISSUE TITLE
Found a method for SnapChat

### ISSUE THREAD

**Issue by sdushantha** [sherlock-project/sherlock#200]
Hey guys!

I found a method to check for usernames on SnapChat.
I have made a script which does this. If anyone has time, feel free to take apart and add it to Sherlock.

The only problem is that this method is a little different from the normal way which Sherlock uses. :/

https://github.com/sdushantha/snapchat-username

If you have **any** questions just ask :)

**Comment by c-edw** [comment]
It would be nice to have in this tool for sure, but I don't it's a good idea to do it this way. You should be aware that you've included your authentication cookie in there, so other people can access your account. Even if this is a throwaway account, it's not really a proper way of doing it.

**Comment by sdushantha** [comment]
@c-edw Are you saying that if I have the `xsrf` token publuc, people can _hijack_ my  account?

**Comment by sdushantha** [comment]
Closing this because it is very unlikely that SnapChat can be implemented.
