### ISSUE TITLE
Error from stars over time in README

### ISSUE THREAD

**Issue by jcubic** [sherlock-project/sherlock#2008]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

The README shows an error:

![Przechwycenie obrazu ekranu_2024-02-19_14-21-47](https://github.com/sherlock-project/sherlock/assets/280241/75093e8b-1c8c-4f1c-9803-30bc1d97abed)

**Comment by idanarye** [comment]
Is this new? Could the attention from the EXE thing (which is, BTW, what brought me here. I don't care about stalking people) have generated enough new starts to break the chart?

**Comment by matheusfelipeog** [comment]
Thanks for opening this issue, @jcubic. It seems that this service indeed has some limitation, so I will replace it with [star history](https://star-history.com/).

**Comment by matheusfelipeog** [comment]
Done ✅
