### ISSUE TITLE
I am new to GitHub and I have lots to say

### ISSUE THREAD

**Issue by Phonfo** [sherlock-project/sherlock#2011]
I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it https://github.com/sherlock-project/sherlock#installation

WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS

**Comment by Phonfo** [comment]
take it as a joke 

original: https://www.reddit.com/r/github/s/BhVD6gIscZ

**Comment by EachenL** [comment]
lol

**Comment by EachenL** [comment]
looooooooooooooooooooooool

**Comment by BaronDJ** [comment]
😂That's ridiculous.

**Comment by Aran8276** [comment]
Ah yes https://github.com/sherlock-project/sherlock/labels/site%20support%20request is definitely the perfect label for this.

**Comment by itsTyrion** [comment]
> Ah yes https://github.com/sherlock-project/sherlock/labels/site%20support%20request is definitely the perfect label for this.

TIL you can reference labels in GitHub comments

**Comment by VenroyDEV** [comment]
we need an .exe now!!

**Comment by ebowwa** [comment]
lmao

**Comment by abskrj** [comment]
@Phonfo here you go, packed it into exe, though defender might flag it as virus. 

https://ufile.io/ov4vedeu

**Comment by Phonfo** [comment]
> @Phonfo here you go, packed it into exe, though defender might flag it as virus.
> 
> https://bit.ly/49muzaz

Thank you Smelly Nerd

**Comment by IOLOII** [comment]
SO WHY THE FUCK IS THERE CODE?  😂

**Comment by jzhao62** [comment]
coming from reddit

**Comment by Ant00000ny** [comment]
We need it on every appstore

**Comment by Mhyho** [comment]
Lmao Mr. Joker you seems not recognised this website is a FUCKING CODE HOSTING PLATFORM
It' not your right to have an exe for free

**Comment by khanhnd0408** [comment]
Reddit bring me here =))

**Comment by Ivan97** [comment]
hahaha

**Comment by thebigbone** [comment]
Stop wasting developer(s)'s time by opening bogus issues which does nothing but entertain this kind of behavior.

**Comment by Kapsyloffer** [comment]
Facts tho

**Comment by speckly** [comment]
GitHub, Inc. is a **_developer_** platform that allows developers to create, store, manage and share their code
https://en.m.wikipedia.org/wiki/GitHub

**Comment by IOLOII** [comment]
Now I see someone using this ”👎“ expression for all comments. It’s really interesting. Isn‘t it someone who is angry? Break the defense! 😹😹😹. Hahahahaha

 现在我看见有某人给所有的评论使用了这个“👎”表情，真的是好有意思，该不会是某人气急败坏了吧？破防了吧！😹😹😹。哈哈哈哈哈

![image](https://github.com/sherlock-project/sherlock/assets/34856171/5831b3eb-97be-4190-b232-0e1eadbef7d9)

**Comment by krizej** [comment]
> <@jacekpoz:jacekpoz.pl> sent an image.

I am new to Proprietary Software and I have lots to say
I DONT GIVE A FUCK ABOUT THE FUCKING EXE! i just want to check out the code for this stupid fucking application and build it 
WHY IS THERE NO CODE??? MAKE A FUCKING GITHUB REPO AND GIVE IT TO ME. these dumbufks think that everyone trusts them with privacy. well i don't.  I only know to `make all` and `make install`. SO WHY THE FUCK IS THERE NO CODE??? make a GITHUB REPO and give it to me. STUPID FUCKING SMELLY MEGACORPORATINOS

**Comment by wadecosta** [comment]
INSTALL GENTOO!

**Comment by danemadsen** [comment]
stupid smelly nerds and their stalker software

**Comment by thatstarryflow** [comment]
Bilibili bring me 😄

**Comment by whmsft** [comment]
The average Joe doesn't even know what a line of code is.

**Comment by abskrj** [comment]
Can anyone lock this thread??

**Comment by KRM0M0M0** [comment]
![@AC ~3$T1O BXH837XK`{ V](https://github.com/sherlock-project/sherlock/assets/143401106/b4a39fa8-306d-4880-af1d-33c538b9b171)
Do you play Genshin Impact, love?
