### ISSUE TITLE
Obfuscate the documentation

### ISSUE THREAD

**Issue by Wengiel31** [sherlock-project/sherlock#2013]
## Checklist
- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description
It has come to my attention that there are some people, that are not familiar with Python, yet they are trying to use this amazing tool. We should obfuscate the documentation to make sure they have the most fun when installing it, and using it is an adventure

**Comment by suobset** [comment]
Let's please stop with the joke Issues now. The Reddit post has been milked to death, and I am very certain the devs of Sherlock are so not having a good time with the constant spam. 

Jokes are good, but let's not overburden the devs behind the project <3

**Comment by matheusfelipeog** [comment]
See https://github.com/sherlock-project/sherlock/issues/2006#issuecomment-1981592479
