### ISSUE TITLE
JUST MAKE A FUCKING .EXE AND GIVE IT TO ME

### ISSUE THREAD

**Issue by Tomsen1410** [sherlock-project/sherlock#2019]
Stupid smelly nerds

\s

**Comment by leonidas1712** [comment]
Duplicate of #2006

**Comment by MGLSUDE** [comment]
You are so comfortable, and the author wants to eat. You think so. You take the money first.
你巴适了，人家作者要吃饭呢。你想的美，你先拿钱来吧。

**Comment by MGLSUDE** [comment]
fuck you.我可日你妈的吧。

**Comment by Tomsen1410** [comment]
> Duplicate of #2006 

Ah sorry, can be closed.

**Comment by ShobanChiddarth** [comment]
@leonidas1712 
> Duplicate of #2006

Technically, this is a duplicate of #2011

**Comment by IOLOII** [comment]
https://github.com/sherlock-project/sherlock/issues/2011

**Comment by jthoward64** [comment]
> > Duplicate of #2006
> 
> Ah sorry, can be closed.

You can close it as "not planned". Please do.

**Comment by Hunterrules0-0** [comment]
Extremely based GIGA issue request king. I salute you. Keep up the good fight champ
![gigachad-1013036224](https://github.com/sherlock-project/sherlock/assets/95697986/fbffda4e-ff21-4ece-a342-d778e4df2641)
