### ISSUE TITLE
cgtrader is returning false positives

### ISSUE THREAD

**Issue by thedaryltan** [sherlock-project/sherlock#2027]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description
cgtrader is returning a false positive on all usernames.

I believe the issue is that the data.json file identifies it as a errortype: Message but the current website has changed to return a 404 error instead.

On further testing, I found that even when I changed it to an errortype: message to try to address the false positives, it continues to have the same issue. From some of the data I see in Burpsuite, it seems like cgtrader may have cloudflare protection. If someone knows how to verify and confirm this then I suggest we remove cgtrader from the list of sites.

**Comment by SourGeckoo** [comment]
Same here. Also got false positives for Coders Rank.

**Comment by darylthetan** [comment]
> Same here. Also got false positives for Coders Rank.

Oh. I haven't encountered that. Does it happen for all usernames or just some specific examples?

**Comment by SourGeckoo** [comment]
the vast majority of usernames return a false positive, but not all. It's quite strange...

**Comment by orimandel** [comment]
Contently (https://username.contently.com) gives a false positive too

**Comment by chris3857** [comment]
https://github.com/aip-dev/google.aip.dev/compare/master...jgeewax-patch-2
[f.txt](https://github.com/sherlock-project/sherlock/files/14560249/f.txt)

**Comment by eduardogott** [comment]
I'm getting false positive on this:

[+] Archive.org: https://archive.org/details/@9278HG374G327G23B80
[+] BitCoinForum: https://bitcoinforum.com/profile/9278HG374G327G23B80
[+] CGTrader: https://www.cgtrader.com/9278HG374G327G23B80
[+] CNET: https://www.cnet.com/profiles/9278HG374G327G23B80/
[+] Euw: https://euw.op.gg/summoner/userName=9278HG374G327G23B80
[+] HEXRPG: https://www.hexrpg.com/userinfo/9278HG374G327G23B80
[+] Linktree: https://linktr.ee/9278HG374G327G23B80
[+] NationStates Nation: https://nationstates.net/nation=9278HG374G327G23B80
[+] NationStates Region: https://nationstates.net/region=9278HG374G327G23B80
[+] Oracle Community: https://community.oracle.com/people/9278HG374G327G23B80
[+] Polymart: https://polymart.org/user/9278HG374G327G23B80
[+] Slides: https://slides.com/9278HG374G327G23B80
[+] YandexMusic: https://music.yandex/users/9278HG374G327G23B80/playlists
[+] znanylekarz.pl: https://www.znanylekarz.pl/9278HG374G327G23B80
