### ISSUE TITLE
Add support to Discogs.

### ISSUE THREAD

**Issue by rfc-2549** [sherlock-project/sherlock#2035]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

Hello
Discogs it's not supported by sherlock. Please add support to look users in Discogs when the devs feel like supporting discogs.
Have a good day

**Comment by w3Abhishek** [comment]
Hey @rfc-2549,

Discogs is already supported by Sherlock.

@TheLastZombie added it with #209 PR. You can close your issue.

**Comment by rfc-2549** [comment]
Ight
