### ISSUE TITLE
SyntaxError - Line 78

### ISSUE THREAD

**Issue by bosslee** [sherlock-project/sherlock#204]
Fresh install on Debain 
Got this error 
```
  File "sherlock.py", line 78
    Fore.GREEN + f"] {title}" +
                            ^
SyntaxError: invalid syntax
```

**Comment by hoadlck** [comment]
What version of Python are you using?  This is normally because f-strings are only supported in 3.6+, and a user tries to run with an earlier version.

**Comment by hoadlck** [comment]
There were some things messed up on the master branch relating to f-strings which was recently fixed.  But, I think that you saw the error from an earlier version, and the issue was just the wrong version of Python.

If you are still having problems, then we can re-open this issue...

**Comment by D3faIt** [comment]
Also have this issue.

I'm on Debian 9 (stretch) using Python 3.5.3

**Comment by hoadlck** [comment]
Python 3.6 or greater is required.
