### ISSUE TITLE
`[-] {errstr} {err if verbose else var}` when testing

### ISSUE THREAD

**Issue by miaoski** [sherlock-project/sherlock#205]
Running on a Mac with Python3 in Virtualenv, `$ python3 -m unittest tests.all --buffer --verbose` gives the result (see attachment).

Notably there is a key error, which also happens when running normal queries, e.g., `python3 sherlock.py miaoski`:
```
[-] {errstr} {err if verbose else var}
Traceback (most recent call last):
  File "sherlock.py", line 615, in <module>
    main()
  File "sherlock.py", line 579, in main
    tor=args.tor, unique_tor=args.unique_tor, proxy=args.proxy, print_found_only=args.print_found_only)
  File "sherlock.py", line 348, in sherlock
    print_invalid(social_network, "Error!")
  File "sherlock.py", line 115, in print_invalid
    Fore.YELLOW + " {msg}").format(social_network))
KeyError: 'msg'
```
[test.log](https://github.com/sherlock-project/sherlock/files/3169887/test.log)

**Comment by miaoski** [comment]
Easy fix:
```
diff --git a/sherlock.py b/sherlock.py
index fc8f23d..98e33fa 100755
--- a/sherlock.py
+++ b/sherlock.py
@@ -112,7 +112,7 @@ def print_invalid(social_network, msg):
            Fore.RED + "-" +
            Fore.WHITE + "]" +
            Fore.GREEN + " {}:" +
-           Fore.YELLOW + " {msg}").format(social_network))
+           Fore.YELLOW + " {}").format(social_network, msg))
```

**Comment by hoadlck** [comment]
It looks like #198 was accidentally merged.  I backed out this PR and pushed the result to main.  I did not have time to do detailed testing, but the failures now seem to be the "normal" ones that happen because a site is slow to respond.  I need to run to work....

**Comment by hoadlck** [comment]
This should be fixed now.
