### ISSUE TITLE
In ubuntu is not working ?

### ISSUE THREAD

**Issue by Day21cyber** [sherlock-project/sherlock#2051]
## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by matheusfelipeog** [comment]
@Day21cyber Yes, it's working. Make sure you have all project dependencies installed in your environment for correct operation. Check our README.md file for further instructions; you'll find everything you need there.
