### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Profty166** [sherlock-project/sherlock#2073]
How do i download or install?

**Comment by Zachouille00** [comment]
I am new here I don't know how to,on YouTube they say to open in cloudshell but I personally don't have the option, anyone have a solution?

**Comment by matheusfelipeog** [comment]
Hi @Profty166 @Zachouille00, you can simply follow our [installation guide](https://github.com/sherlock-project/sherlock?tab=readme-ov-file#installation). There you'll find the necessary steps to install correctly, and below, you'll have the usage options.

**Comment by Zachouille00** [comment]
> Hi @Profty166 @Zachouille00, you can simply follow our [installation guide](https://github.com/sherlock-project/sherlock?tab=readme-ov-file#installation). There you'll find the necessary steps to install correctly, and below, you'll have the usage options.

Alright thanks! I'll try that out
