### ISSUE TITLE
Site support request

### ISSUE THREAD

**Issue by Paelor** [sherlock-project/sherlock#2091]
## Checklist

- [x] I'm requesting support for a new site
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked that the site I am requesting has not been removed in the past and is not documented in [removed_sites.md](https://github.com/sherlock-project/sherlock/blob/master/removed_sites.md)
- [x] The site I am requesting support for is not a pornographic website
- [x] I'm only requesting support of **one** website (create a separate issue for each site)

## Description

NAME: spells8
URL: https://spells8.com/
URL: https://forum.spells8.com/

**Comment by ppfeister** [comment]
You provided two URLs --

Presumably these two assets are linked? Same username on both, no matter what?

**Comment by Paelor** [comment]
It is the same website, you can register and setup username at either URL, but the username is used for both the main page and the forum. Main focus would be searching forum for specific username and or username variants to weed out copy accounts, users who are switching between multiple accounts, instead of being honest and true to one username. The last checked task reads "I'm only requesting support of one website (create a separate issue for each site)". As far as I'm concerned, I followed the directions correctly.. I only posted one website. The forum page and the main page are both under the domain spells8.com

**Comment by Paelor** [comment]
Thank you.

**Comment by ppfeister** [comment]
Awesome. Just wanted to confirm before linking.

I've added it to a pr. Not sure when it'll get merged, but it should be gtg
