### ISSUE TITLE
SHERLOCK// ERROR "string indices must be integers, not 'str'  "

### ISSUE THREAD

**Issue by merelez** [sherlock-project/sherlock#2108]
como puedo solucionar este error que me sale al querer usar sherlock, no se como solucionarlo la verdad

**Comment by ppfeister** [comment]
> This error is being presented as a result of a https://github.com/sherlock-project/sherlock/pull/2099 (the file that lists all the sites to check), which older versions apparently don't parse properly.
> 
> The easiest fix for now will be simply redownloading Sherlock so that you have the new code.
> 
> Alternatively, if you can't redownload right now, --local will tell it to use your local copy instead of the new one from online.

(from [here](https://github.com/sherlock-project/sherlock/issues/1989#issuecomment-2099605279))
