### ISSUE TITLE
False positives (Kick, LibraryThing)

### ISSUE THREAD

**Issue by ppfeister** [sherlock-project/sherlock#2113]
Kick and LibraryThing showing F+ for `ehjtohrtjh`

_(Issue is only for tracking purposes and so I don't forget -- will pr later)_

**Comment by sdushantha** [comment]
I did a false positive on both of those sites when I ran Sherlock inside a Fedora container. But upon running Sherlock on my computer, I only got false positives on LibraryThing. I'm unsure as to why Kick returned a false positive, but it looks like LibraryThing has bot protection

**Comment by ppfeister** [comment]
@sdushantha seems kick added cloudflare and there was a _slightly_ different fingerprint. adapted it. not sure about library thing anymore but is seems that it may have been temporary.
