### ISSUE TITLE
Safe removal of openpyxl dependency

### ISSUE THREAD

**Issue by ppfeister** [sherlock-project/sherlock#2114]
Beginning to package Sherlock.
There are a few dependencies that are of issue (each of which are hard blocks).

`openpyxl` in particular is not yet available and would require packaging. I've noticed however that this dependency doesn't _seem_ to actually be used anywhere. Are we safe to remove this package?

Assuming removal is safe, packing of sherlock will be a bit quicker.

Requesting input from @matheusfelipeog and @sdushantha

**Comment by matheusfelipeog** [comment]
Although it's not directly used by Sherlock, it is one of the [engines used by `pandas`](https://github.com/pandas-dev/pandas/blob/main/pandas/io/excel/_openpyxl.py) to generate the `.xlsx` file.

Install Sherlock in a clean virtual environment without having the `openpyxl` package defined in the requirements.txt file and run:

```zsh
python sherlock ppfeister --site GitHub --xlsx
```

You'll get:

```zsh
ModuleNotFoundError: No module named 'openpyxl'
```

**Comment by ppfeister** [comment]
Agh. I guess I'm going to have to package that one as well, then. I'll take care of that now.

Thanks for confirming!
