### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by D3faIt** [sherlock-project/sherlock#212]
Hi.

I get this error when running Sherlock:

```
python3 sherlock.py neilbreen -r --print-found
  File "sherlock.py", line 78
    Fore.GREEN + f"] {title}" +
                            ^
SyntaxError: invalid syntax
```

This applies to Python2, Python3, with/without arguments and sudo

**Comment by ll3N1GmAll** [comment]
I too am receiving this error. I am running with python3 as per the README.

**Comment by hoadlck** [comment]
Like the readme says, you have to have Python 3.6 or above.

This does keep happening.  I wonder if it is possible to have an explicit check about the Python version, and give an error message that the user is using the wrong version?  I see a [StackOverflow](https://stackoverflow.com/questions/1093322/how-do-i-check-what-version-of-python-is-running-my-script) description on how to do this.

**Comment by AlberickRL** [comment]
I'm having the same issue and I have python 3.6.9 installed and it's the same output when I try to any command with sherlock

`  File "sherlock.py", line 78
    Fore.GREEN + f"] {title}" +
                            ^
SyntaxError: invalid syntax `

**Comment by FaiqIftikhar** [comment]
Use: `python3 sherlock.py --help` and so on to work with it.

**Comment by hoadlck** [comment]
@AlberickRL Can you run Python with the --version option? For example, if the command you use to invoke Python is "python3", then execute "python3 --version".  I expect that you are running a different version than you expect.

**Comment by Vrikquek** [comment]
Hi, I'm having problems installing the repo for Sherlock it's giving a syntax error. I've got python 3 installed but yet it's giving an error.

 git clone https://github.com/sherlock-project/sherlock.git
File "<stdin>", line 1
 git clone https://github.com/sherlock-project/sherlock.git
         ^
SyntaxError: invalid syntax

**Comment by ll3N1GmAll** [comment]
The solution for me was as follows:
sudo apt install python 3.6

Then when running sherlock use this command format:
python3.6 sherlock.py --help

That should fix it for you even if you have a different version of python 3 as your default. This also prevents other programs that are dependent on a different version of python3 from being impacted.

**Comment by Artook10** [comment]
I am having an issue stating Import csv has a syntax error.

File "sherlock.py", line 10
    Import csv
             ^
SyntaxError: invalid syntax

**Comment by Artook10** [comment]
NM figured out the Import csv issue.

**Comment by Artook10** [comment]
But I now have this error.

Traceback (most recent call last):
  File "sherlock.py", line 22, in <module>
    from colorama import Fore, Style, init
ImportError: No module named 'colorama'

**Comment by AlberickRL** [comment]
> The solution for me was as follows:
> sudo apt install python 3.6
> 
> Then when running sherlock use this command format:
> python3.6 sherlock.py --help
> 
> That should fix it for you even if you have a different version of python 3 as your default. This also prevents other programs that are dependent on a different version of python3 from being impacted.

I tried this, but now i get this error 
`Traceback (most recent call last):
  File "sherlock.py", line 22, in <module>
    from colorama import Fore, Style, init
ModuleNotFoundError: No module named 'colorama'`

**Comment by AlberickRL** [comment]
> Use: `python3 sherlock.py --help` and so on to work with it.

same error 
` File "sherlock.py", line 78
    Fore.GREEN + f"] {title}" +
                            ^
SyntaxError: invalid syntax`

**Comment by FaiqIftikhar** [comment]
@AlberickRL can you check the version that you have use `python3 -V`

**Comment by Vrikquek** [comment]
hi, I'm still having problems running this command. it's not recognising the clone command it's saying syntax error.

![Capture](https://user-images.githubusercontent.com/52760319/61222009-acfc2880-a711-11e9-96f1-0cdaaf0204c5.JPG)

**Comment by hoadlck** [comment]
You are trying to clone the repository inside of the Python interpreter.  Git is not built into Python.  You need to open up a regular shell.

Do you have Git installed on your computer?

**Comment by Vrikquek** [comment]
@hoadlck I have Git installed on my computer and that command ran through nicely on the Git shell. Thank you. I have another problem with the third command it's saying the command is not found.

![Capture1](https://user-images.githubusercontent.com/52760319/61230644-55b28400-a722-11e9-9614-18b4a330404c.JPG)

**Comment by hoadlck** [comment]
I think that you are copying part of the prompt text from an example.  The text that you should type in is
```pip3 install -r requirements.txt```

**Comment by Vrikquek** [comment]
@hoadlck It seems not to recognise the command it's saying the command is not found. What am I doing wrong?

![Capture2](https://user-images.githubusercontent.com/52760319/61233695-0b80d100-a729-11e9-8e9b-3736cb8c5b82.JPG)

**Comment by hoadlck** [comment]
This has to do with your install of Python. It may be that your PATH is not setup properly.

It sounds like some people have had issues with pip not being installed by default.  Look at this
[Installing PIP](https://stackoverflow.com/questions/43304612/how-to-install-pip-on-python-3-6/47123768) entry on StackOverflow.

If this is just a PATH issue, look in the "Scripts" directory where you have Python installed.  If you do see pip or pip3 installed in there, then you can pass the entire path to get to pip.  Because people often have multiple installs of Python on their machines, an individual distribution is not added to the PATH.

**Comment by trungdiep** [comment]
![image](https://user-images.githubusercontent.com/36076337/62818334-5ea34380-bb70-11e9-8b72-b3fb13251601.png)

**Comment by AhmedSisy** [comment]
Also had the same issue i have python 3.7.2 
using the format `python3 sherlock.py --help` instead of `python sherlock.py --help` fixed it for me

**Comment by hoadlck** [comment]
This issue appears to be an environmental issue rather than a problem with Sherlock itself.  It also has been hanging out for some time.  So, I am closing it out now to remove the clutter.
