### ISSUE TITLE
sync-json-data workflow failure

### ISSUE THREAD

**Issue by ppfeister** [sherlock-project/sherlock#2140]
Reference job ran for 7811945
Likely incorrect file path

Issue created for tracking purposes.

**Comment by pandyah5** [comment]
My guess is you don't need the ../

For example this:
https://github.com/sherlock-project/sherlock/blob/945a364970852a477f0796a5569627c12a7bb470/devel/site-list.py#L7

Should be:
`with open("sherlock/resources/data.json", "r", encoding="utf-8") as data_file:`

**Comment by ppfeister** [comment]
That's my guess as well. Haven't gotten around to testing yet though as I'm stuck fixing segfaults on my svcman project (having _so_ much fun)

Don't let @sdushantha see this because I think `../` was my suggestion in a code review

**Comment by sdushantha** [comment]
Woops, I'll fix that today :sweat_smile:
