### ISSUE TITLE
Installation from sources

### ISSUE THREAD

**Issue by QU35T-code** [sherlock-project/sherlock#2156]
### Installation method

Built from source

### Description

You have removed the requirements.txt that allow installation from source !

### Steps to reproduce

Do a basic installation from sources. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
The requirements.txt file is not required now that Poetry is being used.

 `pip install .` should work as normal, with all dependencies found within the pyproject config.

If for some reason a requirements.txt file is required, perhaps for some sort of esoteric or niche workflow, then `poetry export --without-hashes -f requirements.txt --output requirements.txt` can be ran to generate the requirements.txt from the aforementioned config file Exclude the `--without-hashes` argument if you want checksums for integrity checks during those workflows.

If you're experiencing some sort of issue and `pip install .` isn't working, please let us know.

**Comment by sdushantha** [comment]
@ppfeister Thoughts on having some info about this in the docs? I'm certain we may receive more reports regarding this as people have been running `pip install -r requiremens.txt` for the past 5+ years when using Sherlock

**Comment by ppfeister** [comment]
@sdushantha On the one hand, the current documentation has no mention. It was written in a way that would allow for this. On the other hand, it doesn't explicitly state that it's _not_ required... I'm not opposed to adding something that says "no requirements required".

I can add a note tomorrow or the day after or something. Probably something to the effect of

> [!Note]
> With the use of Poetry, there is no need for a requirements.txt file. Dependencies are specified within the pyproject file, which is referenced by pip during the build process.
> 
> If needed for some workflow, this file can be generated dynamically via the following...
> ```bash
> poetry export --without-hashes -f requirements.txt --output requirements.txt
> ```

**Comment by ppfeister** [comment]
Updating closure state of issue

**Comment by sdushantha** [comment]
I'm in favor of having the note
