### ISSUE TITLE
Run error but could be user error

### ISSUE THREAD

**Issue by LordZelow** [sherlock-project/sherlock#2167]
### Installation method

Built from source

### Description

Followed the steps to clone the repository then ran  'sudo pip3 install sherlock-project' when running sherlock --help I receive the follow message: sherlock --help                   
Traceback (most recent call last):
  File "/usr/local/bin/sherlock", line 5, in <module>
    from sherlock import main
ImportError: cannot import name 'main' from 'sherlock' (/home/kali/.local/lib/python3.11/site-packages/sherlock/__init__.py)

This is a kali VM ran through Oracle Virtualbox 

### Steps to reproduce

Followed the steps to clone the repository then ran  'sudo pip3 install sherlock-project' when running sherlock --help I receive the follow message: sherlock --help                   
Traceback (most recent call last):
  File "/usr/local/bin/sherlock", line 5, in <module>
    from sherlock import main
ImportError: cannot import name 'main' from 'sherlock' (/home/kali/.local/lib/python3.11/site-packages/sherlock/__init__.py)

This is a kali VM ran through Oracle Virtualbox 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by azmatt** [comment]
Having the same issue.

**Comment by ppfeister** [comment]
I'm unable to go in depth right this second but @azmatt assuming you are also using sudo, have you tried without sudo?

`pip` should under normal circumstances not be ran with sudo, as those installs are meant to be user space by default. If the same error occurs for you when not root/not sudo, please let me know

**Comment by LordZelow** [comment]
Turns out for me, I screwed up my python install which caused the message I got. Sorry about the post.

**Comment by ppfeister** [comment]
Not a problem, @LordZelow !

Do you know what actually went wrong? Or it just somehow started working again?

**Comment by LordZelow** [comment]
For me I had to completely delete python then install it, then manually add the paths back. Then I installed sherlock again.
