### ISSUE TITLE
zsh: no matches found: test{?}test

### ISSUE THREAD

**Issue by pyrohedgehog** [sherlock-project/sherlock#2172]
### Installation method

Homebrew

### Description

{?} appears to prevent Sherlock from running at all

### Steps to reproduce

on MacOS, running Sherlock from brew install, adding wildcards prevents Sherlock from starting. 

```
        % sherlock test test{?}test test
zsh: no matches found: test{?}test
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matheusfelipeog** [comment]
Hi @pyrohedgehog

The zsh interprets the `?` in the command as a [globbing wildcard](https://en.wikipedia.org/wiki/Glob_(programming)). Enclose arguments that have the similar username checking character (`{?}`) in quotes:

```zsh
sherlock test 'test{?}test' test
```
