### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by Hjgkcgf35** [sherlock-project/sherlock#2198]
### Description

I had problems 
![17194188548984482685354609087698](https://github.com/sherlock-project/sherlock/assets/173940435/b0adebc9-b991-460e-b626-53f394ad1307)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hjgkcgf35** [comment]
Pls help to solve it

**Comment by ppfeister** [comment]
You aren't root so you need to run `apt install` via sudo. `sudo apt install sherlock`.
