### ISSUE TITLE
Docker Hub not getting updated

### ISSUE THREAD

**Issue by Jaakkonen** [sherlock-project/sherlock#221]
Docker image is now 6 months old and not updated. It's also missing description (which could link to the README.md)
```
# docker run theyahya/sherlock --version
sherlock.py 0.1.1
Python HTTP for Humans.:  2.21.0
Python:  3.7.2
```

Fix: Consider adding travis integration for Docker hub.

**Comment by Jaakkonen** [comment]
Here's travis' guide on Docker Hub deployment automation: https://docs.travis-ci.com/user/docker/

**Comment by sdushantha** [comment]
@TheYahya I think this something for you because it's your Docker Hub account.

**Comment by TheYahya** [comment]
Updated
