### ISSUE TITLE
Mac Install Issue

### ISSUE THREAD

**Issue by StevenMonty** [sherlock-project/sherlock#222]
Doing the pip3 install requirement.txt command results in this error:
```
 ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt
```
Any idea how to fix it? Thanks

**Comment by hoadlck** [comment]
Looks like you missed the ```-r``` option on the command line.  

The command is 
```pip3 install -r requirements.txt```

**Comment by hoadlck** [comment]
Looks like this was just a missing option on the command line. So, I am closing the issue.

**Comment by duncanxxx** [comment]
Hi, I'm trying to install Sherlock on Android using termux but I get error when I install 
pip3 install -r requirements.txt

" error: command 'arm-linux-androideabi-clang' failed with exit status 1
    ----------------------------------------
ERROR: Command "/data/data/com.termux/files/usr/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-h6re8a7a/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-ldgldbx4/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tm     "
