### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by hoochiemama** [sherlock-project/sherlock#2221]
### Installation method

PyPI (via pip)

### Description

After a git pull, attempted to run a query.

### Steps to reproduce

python3 sherlock.py username

### Additional information

Gerneates this error. This occured after updating the code. 

Traceback (most recent call last):
  File "/home/user1/tools/sherlock/sherlock/sherlock.py", line 27, in <module>
    from .__init__ import ( # noqa: E402
ImportError: attempted relative import with no known parent package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hoochiemama** [comment]
I'm a python newbie..so if this is something obvious I aplogize in advance.

**Comment by ppfeister** [comment]
Installation via PyPI (your selected method) doesn't require a clone. After running `pipx install sherlock-project` you can just run `sherlock user123`.

Running with `python3 sherlock ...` is no longer supported OOTB.

Let me know how it goes.

**Comment by hoochiemama** [comment]
All good here now! Thanks!
