### ISSUE TITLE
Requesting support for: Adding https://www.threads.net as a new site

### ISSUE THREAD

**Issue by kevin-fagan** [sherlock-project/sherlock#2234]
### Site URL

https://www.threads.net

### Additional info

A "threads" username can be found like such: `https://www.threads.net/@USERNAME`

Threads will return a 200 even if the user is not found. However, we can still detect if a user was not found based off the following error message: `Sorry, this page isn't available`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Whatup466** [comment]
Thank uSent from my iPhoneOn Jul 24, 2024, at 9:43 PM, Kevin Fagan ***@***.***> wrote:﻿
Site URL
https://www.threads.net
Additional info
A "threads" username can be found like such: ***@***.***
Threads will return a 200 even if the user is not found. However, we can still detect if a user was not found based off the following error message: Sorry, this page isn't available
Code of Conduct

 I agree to follow this project's Code of Conduct

**Comment by sdushantha** [comment]
@kevin-fagan We're currently trying to add support for Threads in #2225, but it seems to be not working properly. Feel free to contribute to the PR's thread

**Comment by kevin-fagan** [comment]
@sdushantha Awh, I see. Apologies, I did not see that open PR. This issue can be closed and I'll take a look at the one you have linked.

**Comment by Whatup466** [comment]
Could u check a what ap for me wan t to see if my girlSent from my iPhoneOn Jul 25, 2024, at 1:12 PM, Kevin Fagan ***@***.***> wrote:﻿
Closed #2234 as not planned.
