### ISSUE TITLE
python3 -m pip install -r requirements.txt

### ISSUE THREAD

**Issue by Aminser99** [sherlock-project/sherlock#2241]
### Installation method

PyPI (via pip)

### Description

i got this message after running that commande 
Defaulting to user installation because normal site-packages is not writeable
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

### Steps to reproduce

the new update of your page on github made me confused with too many installations options 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
> The new update of your page on github made me confused with too many installations options

Just use the first method in this case. `pip install sherlock-project`
