### ISSUE TITLE
ParrotOS package out of date (0.14.3 on repository)

### ISSUE THREAD

**Issue by xicor0** [sherlock-project/sherlock#2243]
### Site URL

https://github.com/sherlock-project/sherlock/issues/new?assignees=&labels=site+support+request&projects=&template=site-request.yml&title=Requesting+support+for%3A+

### Additional info

Update Available!
You are running version 0.14.3. Version 0.15.0 is available at https://github.com/sherlock-project/sherlock
ERROR:  string indices must be integers, not 'str'
how can I fix this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
How did you install Sherlock and what distro/os

**Comment by xicor0** [comment]
for parrot os and also i have tried reintalling it.

**Comment by xicor0** [comment]
know when i run sherlock user123 it shows error:
A problem occurred while checking for an update: list index out of range
ERROR:  Bad response while accessing data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json'

**Comment by skyler-saville** [comment]
Same problem for me as well. Tried reinstalling using apt on Parrot OS, but same issue. I removed it and installed it using pipx, which works as expected.

**Comment by ppfeister** [comment]
What distro/os?

Judging by 0.14.3, are you by chance on Parrot?

**Comment by xicor0** [comment]
yes I installed it using sudo apt-get install, then using this repo, installed sherlock https://github.com/sherlock-project/sherlock in install

**Comment by ppfeister** [comment]
You still haven't confirmed what distro but I'm going to assume Parrot under the circumstances. I'm also not too sure what method the second half of that sentence is trying to indicate.

Parrot however seems to be out of date, and that package is maintained by a third party (not us). While normally not necessary, in your case, I would recommend a quick `apt remove sherlock` then follow the [instructions for pip/pypi](https://github.com/sherlock-project/sherlock?tab=readme-ov-file#installation) (use pip rather than pipx) to install a first-party version.

**Comment by xicor0** [comment]
pipx install sherlock-project
⚠️  File exists at /root/.local/bin/sherlock and points to /root/.local/bin/sherlock, not
    /root/.local/pipx/venvs/sherlock-project/bin/sherlock. Not modifying.
  installed package sherlock-project 0.15.0, installed using Python 3.11.2
    - sherlock (symlink missing or pointing to unexpected location)
⚠️  Note: '/root/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your PATH is
    updated. Run `pipx ensurepath` to automatically add it, or manually modify your PATH in your shell's config file (i.e.
    ~/.bashrc).
done! ✨ 🌟 ✨
this is the error I am facing know

**Comment by ppfeister** [comment]
Can you copy the output from the install commands here? That sounds very much like an environmental problem leading to a failure to install, and the output might clarify what specifically
