### ISSUE TITLE
Flag needed to disable file output

### ISSUE THREAD

**Issue by ppfeister** [sherlock-project/sherlock#2249]
### Discussed in https://github.com/sherlock-project/sherlock/discussions/2247

___

<div type='discussions-op-text'>

<sup>Originally posted by **ovalofficer** August  7, 2024</sup>
Hi, I'm making a web wrapper for Sherlock but I want to disable the file output. Is there a switch I can use to turn it off without editing Sherlock's source?

I couldn't find out how to do it. Sorry if it's something obvious</div>

___

This flag is to be a temporary feature, becoming the default in 0.16.0.

**Comment by Jhonatanbb** [comment]
[empty.txt](https://github.com/user-attachments/files/16577023/empty.txt)

**Comment by ntexe** [comment]
#2263
