### ISSUE TITLE
Sherlock is not working

### ISSUE THREAD

**Issue by JLHMV19** [sherlock-project/sherlock#2258]
### Installation method

Kali repository (via apt)

### Description

when I try to use sherlock with any username the next lines are showed
![Captura de pantalla -2024-08-14 23-55-43](https://github.com/user-attachments/assets/3186a290-669f-48a7-9c88-6886f3ca9b6b)

### Steps to reproduce

sherlock user123

### Additional information

sherlock was installed by default in parrot OS, the version showed is the next one
![Captura de pantalla -2024-08-14 23-56-35](https://github.com/user-attachments/assets/b9179f75-822a-4c01-b3f6-898951ef2f5f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
Sherlock is on 0.15.0, and that version is available on the Kali repository. With an update, that error should subside.

**Comment by neoparker10** [comment]
Also the requirements.txt file is missing

**Comment by ppfeister** [comment]
@neoparker10 That file no longer exists.

**Comment by SaAbyy** [comment]
I have the same problem and understand how to fix it i think, but i am on parrot os and it seems that the packages for sherlock aren't up to date for the parrot source list.

I continue to be in 14.3 even after the update.

**Comment by Tarvel** [comment]
> I have the same problem and understand how to fix it i think, but i am on parrot os and it seems that the packages for sherlock aren't up to date for the parrot source list.
> 
> I continue to be in 14.3 even after the update.

how did you fix this?

**Comment by ppfeister** [comment]
@SaAbyy @Tarvel I would recommend uninstalling sherlock and reinstalling via pypi (pip/[pipx](https://pipx.pypa.io/stable/installation/)). You should already have pip but pipx is nice to have. Not too sure what the update frequency is for Parrot but it's fallen quite a bit behind.

I'll probably be removing Parrot from the list given the long delay

**Comment by JLHMV19** [comment]
I reinstalled sherlock with pipx, the issue is fixed, thanks for your help
