### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Gs-gcs** [sherlock-project/sherlock#2261]
### Installation method

Debian

### Description

When i run sherlock i get that same error 
![SHERLOCK](https://github.com/user-attachments/assets/64dc8446-4e72-4cdf-b1b1-df87704df876)

### Steps to reproduce

1. Run sherlock
2. Bam

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
I don't believe Sherlock is on Deb 12 yet, so going to assume Deb 13/Trixie

0.15.0 is available on the deb trixie repositories and you'll just need to update. You're likely on 0.14.3 judging by the error message.

**Comment by Gs-gcs** [comment]
> I don't believe Sherlock is on Deb 12 yet, so going to assume Deb 13/Trixie
> 
> 0.15.0 is available on the deb trixie repositories and you'll just need to update. You're likely on 0.14.3 judging by the error message.

How do i update? i dont know how to..
