### ISSUE TITLE
python3 sherlock.py invalid syntax

### ISSUE THREAD

**Issue by stewargm** [sherlock-project/sherlock#229]
pi@raspberrypi:~/sherlock $ python3 sherlock.py johb
  File "sherlock.py", line 78
    Fore.GREEN + f"] {title}" +
                            ^
SyntaxError: invalid syntax
pi@raspberrypi:~/sherlock $ 

How do I fix ... thanks G

**Comment by monraPH** [comment]
I got the same problem too.

**Comment by stewargm** [comment]
Previous threads have sand that he should only work on python 3.6 or above my default python is 3.5 but I’m having trouble making python 3.7 my default
