### ISSUE TITLE
PIP installing error 

### ISSUE THREAD

**Issue by zegwei** [sherlock-project/sherlock#2295]
### Installation method

PyPI (via pip)

### Description

open cmd running : pip install --user sherlock-project

### Steps to reproduce

G:\sherlock-master>pip install --user sherlock-project
Collecting sherlock-project
  Using cached sherlock_project-0.15.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: PySocks<2.0.0,>=1.7.0 in e:\programdata\anaconda3\lib\site-packages (from sherlock-project) (1.7.1)
Requirement already satisfied: certifi>=2019.6.16 in e:\programdata\anaconda3\lib\site-packages (from sherlock-project) (2022.12.7)
Requirement already satisfied: colorama<0.5.0,>=0.4.1 in e:\programdata\anaconda3\lib\site-packages (from sherlock-project) (0.4.6)
Collecting openpyxl<4.0.0,>=3.0.10 (from sherlock-project)
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting pandas<3.0.0,>=1.0.0 (from sherlock-project)
  Using cached pandas-2.2.2-cp310-cp310-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: requests<3.0.0,>=2.22.0 in e:\programdata\anaconda3\lib\site-packages (from sherlock-project) (2.28.2)
Collecting requests-futures<2.0.0,>=1.0.0 (from sherlock-project)
  Using cached requests_futures-1.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting stem<2.0.0,>=1.8.0 (from sherlock-project)
  Using cached stem-1.8.2.tar.gz (2.9 MB)
  Preparing metadata (setup.py) ... done
Collecting et-xmlfile (from openpyxl<4.0.0,>=3.0.10->sherlock-project)
  Using cached et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: numpy>=1.22.4 in e:\programdata\anaconda3\lib\site-packages (from pandas<3.0.0,>=1.0.0->sherlock-project) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\programdata\anaconda3\lib\site-packages (from pandas<3.0.0,>=1.0.0->sherlock-project) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\programdata\anaconda3\lib\site-packages (from pandas<3.0.0,>=1.0.0->sherlock-project) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in e:\programdata\anaconda3\lib\site-packages (from pandas<3.0.0,>=1.0.0->sherlock-project) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.22.0->sherlock-project) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in e:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.22.0->sherlock-project) (3.7)
Collecting urllib3<1.27,>=1.21.1 (from requests<3.0.0,>=2.22.0->sherlock-project)
  Using cached urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
**ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 
![Screenshot_2](https://github.com/user-attachments/assets/847c36a6-5916-4044-a24e-583da3895df3)
'e:\\programdata\\anaconda3\\lib\\site-packages\\numpy-1.23.5.dist-info\\METADATA'**

### Additional information

sd

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ibnaleem** [comment]
Use a Python virtual environment:
```
G:\sherlock-master> py -m venv myvenv
G:\sherlock-master> myvenv\Scripts\activate
(myvenv) G:\sherlock-master> pip install sherlock-project
```
If you're still facing issues, remove the `--user` flag in your installation:
```
G:\sherlock-master> pip install sherlock-project
```

**Comment by zegwei** [comment]
Thanks a lot for reply i have successfully install and it is working now . I am newbie my head explode with simple coding, take me sometime to understand :D, for those having same issue may follow the step : 
(1) from the downloaded folder run CMD from folder path
(2) in CMD, use "cd" code to reach "scripts" path
(3) in CMD, enter the "activate" to Python virtual environment
(4) in CMD, run "pip install sherlock-project"

**Comment by ibnaleem** [comment]
@zegwei could you close this issue as completed?
