### ISSUE TITLE
run  shelock user123 get error bad response while access data file url

### ISSUE THREAD

**Issue by Hallr841** [sherlock-project/sherlock#2298]
### Installation method

Other (indicate below)

### Description

A problem occurred while checking for an update: list index out of range
ERROR:  Bad response while accessing data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json'.

### Steps to reproduce

(sherlock-env) ➜  sherlock_project git:(master) ✗ sherlock username123
A problem occurred while checking for an update: list index out of range
ERROR:  Bad response while accessing data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json'.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ibnaleem** [comment]
Your URL is wrong. The correct one is:
```
https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock_project/resources/data.json
```
Not
```
https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json
```
The correct path is `/master/sherlock_project/` and not `/master/sherlock/`. Re-clone the repository to use the correct URL.

**Comment by givowo** [comment]
I installed sherlock on a parrotOS vm with `sudo apt install sherlock` as seen on https://sherlockproject.xyz/installation and have the same issue
![image](https://github.com/user-attachments/assets/0b2da4f2-ea84-40aa-9207-6255c95acbfd)

**Comment by ibnaleem** [comment]
Install sherlock via `pipx` and not the package manager.
```
$ sudo apt remove sherlock
$ sudo apt install pipx
$ pipx install sherlock-project
```

**Comment by JrVolt** [comment]
@givowo is right.
The correct one, at least not 404, at the moment seems is https://raw.githubusercontent.com/sherlock-project/sherlock/refs/heads/master/sherlock_project/resources/data.json 
Can you patch it ?

**Comment by ibnaleem** [comment]
Sherlock is outdated in the apt package manager, and this cannot be patched without the maintainer. For now, use `pipx` since it's up-to-date.

**Comment by givowo** [comment]
@ibnaleem that makes more sense than just telling me to install it via a different method. I
The version on pipx worked perfectly fine.

**Comment by JrVolt** [comment]
You right it's broken in apt, but It will install It correctl and download all the requires files, if you run It like `sherlock --local user123` It works fine, during installation It download data.json

Can you add a new checkbox, or some setting idk, similaro to `--local` 

It possibile also possibile to download the results ? 
Honestly don't know, i haven't tried yet.

@givowo of you want and easy and dirty fix to run sherlock (APT version) correctly in CLI creata a new alias in .bashrc like `Sherlock alias="sherlock --local"` and run "Sherlock user123" 
Or add manually `--local` when needed.

**Comment by ibnaleem** [comment]
That's not a fix. The `--local` flag forces `sherlock` to use the local `data.json` file which is not recommended as defined in [sites.py L10-L112](https://github.com/sherlock-project/sherlock/blob/master/sherlock_project/sites.py#L110-L112):
```
The default data file is the live data.json which is in the GitHub repo. 
The reason why we are using  this instead of the local one is so that the user has the most up-to-date data. 
This prevents users from creating issue about false positives which has already been fixed or having outdated data.
```
As previously stated, use `pipx` to install `sherlock` since it's up-to-date unlike `apt`:
```
$ sudo apt uninstall sherlock
$ sudo apt install pipx
$ pipx install sherlock-project
```

**Comment by ppfeister** [comment]
Closing as the apt package is on par with upstream (at least on Debian 13, Sid, and Ubuntu 24.10, 25.04).

Note that at the time of writing the ParrotOS package is stagnant and nonfunctional. Users of ParrotOS should first check to see if the package has since been brought up to date, otherwise, install via pipx or another method.
