### ISSUE TITLE
Can't connect to most websites

### ISSUE THREAD

**Issue by haruhiko156** [sherlock-project/sherlock#230]
Almost all the websites return "Error Connecting"
[-] ResearchGate: Illegal Username Format For This Site!
[+] Twitch: https://m.twitch.tv/s******s
[-] Error Connecting: DeviantART
[-] DeviantART: Error!
[-] Error Connecting: TripAdvisor
[-] TripAdvisor: Error!
[-] Error Connecting: LiveJournal
[-] LiveJournal: Error!
[-] Error Connecting: Patreon
[-] Patreon: Error!
[-] Error Connecting: BuzzFeed
[-] BuzzFeed: Error!
[-] Error Connecting: 9GAG
[-] 9GAG: Error!
[-] Error Connecting: SourceForge
[-] SourceForge: Error!
[-] Error Connecting: Crunchyroll
[-] Crunchyroll: Error!
[-] Error Connecting: Pixabay
[-] Pixabay: Error!
[-] Error Connecting: GoodReads
[-] GoodReads: Error!
[-] Error Connecting: Wix
[-] Wix: Error!
[-] Error Connecting: Flickr
[-] Flickr: Error!
[-] Error Connecting: Investing.com
[-] Investing.com: Error!
[-] Error Connecting: Giphy
[-] Giphy: Error!
[-] Error Connecting: MyAnimeList
[-] MyAnimeList: Error!
[-] Error Connecting: Wattpad
[-] Wattpad: Error!
[-] Error Connecting: TradingView
[-] TradingView: Error!
[-] Error Connecting: Unsplash
[-] Unsplash: Error!
[-] Error Connecting: Issuu
[-] Issuu: Error!
[-] Error Connecting: Telegram
[-] Telegram: Error!
[-] Error Connecting: Discogs
[-] Discogs: Error!
[-] Error Connecting: Pexels
[-] Pexels: Error!
[-] Error Connecting: Codepen
[-] Codepen: Error!
[-] Error Connecting: Instructables
[-] Instructables: Error!
[-] Error Connecting: Pastebin
[-] Pastebin: Error!
[-] Error Connecting: Taringa
[-] Taringa: Error!
[-] Error Connecting: Dribbble
[-] Dribbble: Error!
[-] Error Connecting: BitBucket
[-] BitBucket: Error!
[-] Error Connecting: AskFM
[-] AskFM: Error!
[-] Error Connecting: last.fm
[-] last.fm: Error!
[-] Error Connecting: Disqus
[-] Disqus: Error!
[-] Error Connecting: Rajce.net
[-] Rajce.net: Error!
[-] Error Connecting: Tinder
[-] Tinder: Error!
[-] Error Connecting: Basecamp
[-] Basecamp: Error!
[-] Error Connecting: osu!
[-] osu!: Error!
[-] Error Connecting: GitLab
[-] GitLab: Error!
[-] Error Connecting: Docker Hub
[-] Docker Hub: Error!
[-] Error Connecting: Itch.io
[-] Itch.io: Error!
[-] Error Connecting: CreativeMarket
[-] CreativeMarket: Error!
[-] Error Connecting: Foursquare
[-] Foursquare: Error!
[-] Error Connecting: Kongregate
[-] Kongregate: Error!
[-] Error Connecting: Houzz
[-] Houzz: Error!
[-] Error Connecting: MixCloud
[-] MixCloud: Error!
[-] Error Connecting: HackerNews
[-] HackerNews: Error!
[-] Error Connecting: Kaggle
[-] Kaggle: Error!
[-] Error Connecting: Gitee
[-] Gitee: Error!
[-] Error Connecting: Codecademy
[-] Codecademy: Error!
[-] Error Connecting: Trip
[-] Trip: Error!
[-] Error Connecting: 500px
[-] 500px: Error!
[-] Error Connecting: Gumroad
[-] Gumroad: Error!
[-] Error Connecting: ProductHunt
[-] ProductHunt: Error!
[-] Error Connecting: AngelList
[-] AngelList: Error!
[-] Error Connecting: VSCO
[-] VSCO: Error!
[-] Error Connecting: Newgrounds
[-] Newgrounds: Error!
[-] Error Connecting: Pokemon Showdown
[-] Pokemon Showdown: Error!
[-] Error Connecting: Letterboxd
[-] Letterboxd: Error!
[-] Error Connecting: We Heart It
[-] We Heart It: Error!
[-] Error Connecting: VirusTotal
[-] VirusTotal: Error!
[-] Error Connecting: Photobucket
[-] Photobucket: Error!
[-] Error Connecting: Rate Your Music
[-] Rate Your Music: Error!
[-] Error Connecting: Trakt
[-] Trakt: Error!
[-] Error Connecting: Myspace
[-] Myspace: Error!
[-] Error Connecting: Aptoide
[-] Aptoide: Error!
[-] Error Connecting: DEV Community
[-] DEV Community: Error!
[-] Error Connecting: Venmo
[-] Venmo: Error!
[-] Error Connecting: boingboing.net
[-] boingboing.net: Error!
[-] Error Connecting: NameMC (Minecraft.net skins)
[-] NameMC (Minecraft.net skins): Error!
[-] Error Connecting: Gravatar
[-] Gravatar: Error!
[-] Error Connecting: IFTTT
[-] IFTTT: Error!
[-] Error Connecting: Repl.it
[-] Repl.it: Error!
[-] Error Connecting: Launchpad
[-] Launchpad: Error!
[-] Error Connecting: iMGSRC.RU
[-] iMGSRC.RU: Error!
[-] Error Connecting: Star Citizen
[-] Star Citizen: Error!
[-] Error Connecting: Cloob
[-] Cloob: Error!
[-] Error Connecting: Codementor
[-] Codementor: Error!
[-] Error Connecting: HubPages
[-] HubPages: Error!
[-] Error Connecting: Coderwall
[-] Coderwall: Error!
[-] Error Connecting: ReverbNation
[-] ReverbNation: Error!
[-] Error Connecting: About.me
[-] About.me: Error!
[-] Error Connecting: YouNow
[-] YouNow: Error!
[-] Error Connecting: WebNode
[-] WebNode: Error!
[-] Error Connecting: MeetMe
[-] MeetMe: Error!
[-] Error Connecting: Designspiration
[-] Designspiration: Error!
[-] Error Connecting: Plug.DJ
[-] Plug.DJ: Error!
[-] Error Connecting: Carbonmade
[-] Carbonmade: Error!
[-] Error Connecting: ColourLovers
[-] ColourLovers: Error!
[-] Error Connecting: EyeEm
[-] EyeEm: Error!
[-] Error Connecting: Ello
[-] Ello: Error!
[-] Error Connecting: HackerOne
[-] HackerOne: Error!
[-] Error Connecting: YouPic
[-] YouPic: Error!
[-] Error Connecting: Jimdo
[-] Jimdo: Error!
[-] Error Connecting: ImageShack
[-] ImageShack: Error!
[-] Error Connecting: Contently
[-] Contently: Error!
[-] Error Connecting: Keybase
[-] Keybase: Error!
[-] Error Connecting: Smashcast
[-] Smashcast: Error!
[-] Error Connecting: devRant
[-] devRant: Error!
[-] Error Connecting: KanoWorld
[-] KanoWorld: Error!
[-] Error Connecting: Crevado
[-] Crevado: Error!
[-] Error Connecting: Kik
[-] Kik: Error!
[-] Error Connecting: BLIP.fm
[-] BLIP.fm: Error!
[-] Error Connecting: House-Mixes.com
[-] House-Mixes.com: Error!
[-] Error Connecting: Mastodon
[-] Mastodon: Error!
[-] Error Connecting: Signal
[-] Signal: Error!
[-] Error Connecting: CashMe
[-] CashMe: Error!

Please solve this problem.

**Comment by Jamim** [comment]
Can you describe your environment?

**Comment by alessandrolio** [comment]
i have the same problem. im running a clean linux installation with the latest drivers and updates. Aprox 3/4 of those sites gave me back error connecting

**Comment by hoadlck** [comment]
I wonder if you are at an IP address that has been banned?  I have had problems like this on my own server when sending e-mails: some e-mail providers have blocked a range of IP addresses because they have been used by spammers.

Could you try running Sherlock thru a VPN?  The ```--proxy``` option will let you do that from the command line.

**Comment by DanBrown47** [comment]
@hoadlck I ran sherlock through a VPN still the problem persists

**Comment by hoadlck** [comment]
Perhaps you have old versions of the requirements, and they do not actually work with Sherlock.

First, run ```pip freeze``` to get a list of all the Python modules that you have installed.  Note that there may be Python modules in here that Sherlock does not need: this lists everything installed.  Next, isolate out the modules that Sherlock needs.  That gives you the list of versions you are using.

Attached below is what I see when I go thru this process.  What versions of Modules you do have?

```
(505)% pip freeze
asciidoc==9.0.dev1
beautifulsoup4==4.6.0
bs4==0.0.1
certifi==2018.11.29
chardet==3.0.4
colorama==0.4.1
cx-Freeze==5.1.1
Django==2.1.4
django-modelcluster==4.3
django-taggit==0.23.0
django-treebeard==4.3
djangorestframework==3.9.0
draftjs-exporter==2.1.5
html5lib==1.0.1
idna==2.8
lxml==4.3.1
piexif==1.1.2
Pillow==5.3.0
PyQRCode==1.2.1
pyserial==3.4
PySocks==1.6.8
pytz==2018.7
requests==2.21.0
requests-futures==0.9.9
six==1.12.0
soupsieve==1.7.3
stem==1.7.1
torrequest==0.1.0
Unidecode==1.0.23
urllib3==1.24.1
wagtail==2.4
webencodings==0.5.1
Willow==1.1
XBee==2.3.2
(506)% cat requirements.txt
beautifulsoup4
bs4
certifi
chardet
colorama
idna
lxml
PySocks
requests
requests-futures
soupsieve
stem
torrequest
urllib3
```

**Comment by MariusMez** [comment]
I Had same problem on first use and solved it using these command : `pip3 install -U -r requirements.txt` (I recommend to use a conda environment before upgrading all required modules)

**Comment by hoadlck** [comment]
Suspect that this was an environment issue.
