### ISSUE TITLE
Issue whit Sherlock tool

### ISSUE THREAD

**Issue by fleeingsnail** [sherlock-project/sherlock#2305]
### Installation method

Kali repository (via apt)

### Description

Hi, i was trying to use sherlock but looks like some directories are missing to me, i've already use it like 1 year ago and i never had that type of issue; i've just started learning sht about those things so please don't get mad to me.
(i already thanks the ones that want help me).

I've putted the screenshot down here of the cmd whit sherlock directories so you can tell me if is actually missing something or i'm just stupid :

![Untitled design(1)](https://github.com/user-attachments/assets/f51b8eac-3345-433c-a31d-deb6ff2d95b9)

### Steps to reproduce

1) I opened the cmd
2) Then i entered the desktop from cmd
3) I typed git-clone plus the link (sorry if i've putted the wrong installation method on the help request, like i've already said i've just started study and i was just looking for some fun)
4) I entered sherlock, and then i've opened all what i was able to open, but i've not see nothing that i found useful, so i'm here

### Additional information

I'm on a Oracle VM, Kali ISO

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ibnaleem** [comment]
You don't need to clone this repository if you're not a contributor as stated in the [GitHub installation section](https://sherlockproject.xyz/installation):
```
While this method uses the official repository, it’s not an officially supported installation method. 
This method is recommended for contributors, packagers, and other users who need access to the source code.
```
Delete the repository directory and the binary that you installed from `apt` (see #2298) and re-install using `pipx`:
```
$ rm -rf sherlock
$ sudo apt remove sherlock
$ sudo apt install pipx
$ pipx install sherlock-project
```

**Comment by fleeingsnail** [comment]
HI Ibnaleem! thanks for your help and your time, i've do what you told me to do and now i can use Sherlock.
Very kind by you

Cheers and have a good day/evening
