### ISSUE TITLE
Requesting support for: Atcoder

### ISSUE THREAD

**Issue by melan-variya** [sherlock-project/sherlock#2314]
### Site URL

https://atcoder.jp/

### Additional info

username can be found like this https://atcoder.jp/users/{username}
if you assign me this task i can add atcoder .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MR-VL** [comment]
Created PR to solve this issue https://github.com/sherlock-project/sherlock/pull/2315
