### ISSUE TITLE
False positive for: 8tracks Amino Bikemap Contently Fiverr HackTheBox HackenProof (Hackers) HudsonRock Kick Vero babyRU mastodon.cloud LibraryThing Lichess NitroType ProductHunt Strava TLDR Legal

### ISSUE THREAD

**Issue by Vikranth3140** [sherlock-project/sherlock#2318]
### Additional info

All the below mentioned sites are wrongly detecting a profile for Vikranth3140
Here is a list of all the sites you mentioned:

1. 8tracks
2. Amino
3. Bikemap
4. Contently
5. Fiverr
6. HackTheBox
7. HackenProof (Hackers)
8. HudsonRock
9. Kick
10. Vero
11. babyRU
12. mastodon.cloud
13. LibraryThing
14. Lichess
15. NitroType
16. ProductHunt
17. Strava
18. TLDR Legal

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alokranjan609** [comment]
@Vikranth3140 is Vikranth3140 a valid name for the above websites you listed?

**Comment by Vikranth3140** [comment]
> @Vikranth3140 is Vikranth3140 a valid name for the above websites you listed?

No, it is not a valid name.

**Comment by sumitsingh3072** [comment]
Please Raise the issue for one site at a time.

**Comment by ppfeister** [comment]
Reference https://github.com/sherlock-project/sherlock/pull/2360#issuecomment-2469513882 for closure info
