### ISSUE TITLE
False positive for:  8tracks

### ISSUE THREAD

**Issue by sumitsingh3072** [sherlock-project/sherlock#2332]
### False Positive for 8tracks

I have encountered an issue where 8tracks is returning false positives for nearly all usernames tested.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gauravsinghrajputt** [comment]
Assign me for this issue 
I will do contribute in it and solve this issue

**Comment by sumitsingh3072** [comment]
I've already fixed the issue. The PR approval is pending
