### ISSUE TITLE
Sherlock text requirements

### ISSUE THREAD

**Issue by FlowerStar526** [sherlock-project/sherlock#2336]
### Installation method

PyPI (via pip)

### Description

$ python3 -m pip install -r requirements.txt
ERROR: Could not oper requirements file: [Erno 2] No such file ir directory: 'requirements txt'

### Steps to reproduce

$ python3 -m pip install -r requirements.txt
ERROR: Could not oper requirements file: [Erno 2] No such file ir directory: 'requirements txt'

### Additional information

Hello everyone, 
I'm new with sherlock. I do with windows 10 cloudshell. Maybe enyone could help me step by step  to find username? I tried many times, but looks like that text requirements  doesn't work. Thank you

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SCP-iota** [comment]
I think this seems to be the wrong command for installing Sherlock. [The installation guide] says to use this command to install from PyPI:

```sh
pip install --user sherlock-project
```

**Comment by sainishwanth** [comment]
Did you clone the github repo and run this command inside the sherlock directory? You need the project files to use-

```sh
$ python3 -m pip install -r requirements.txt
```

If you do not have the project files then use this to install:

```
pipx install sherlock-project
```

or

```
pip install sherlock-project
```

**Comment by sainishwanth** [comment]
There is no requirements.txt file to install the requirements.

If you would like to run the app from source after cloning it, you can follow the instructions under 'Github'

[https://sherlockproject.xyz/installation](url)

**Comment by ppfeister** [comment]
There is no requirements.txt.

Installing from source (via GitHub) is an unsupported method.

Windows likes to be special and all comments should be prefaced with `python3 -m`. So, `python3 -m pip install sherlock-project` and `python3 -m sherlock-project user123`.
