### ISSUE TITLE
data.json file access error [Bad Response]

### ISSUE THREAD

**Issue by shivaganesht** [sherlock-project/sherlock#2351]
### Installation method

PyPI (via pip)

### Description

![image](https://github.com/user-attachments/assets/056ca9d8-0593-473d-aa8e-96ce235f919e)

**I encountered an issue while trying to access the data.json file from the Sherlock project. Below are the details to help reproduce the bug:**

**What I was trying to do:** I was running the Sherlock tool to collect information about specific usernames on various platforms.

**What I expected to happen:** I expected the tool to download and access the data.json file successfully, allowing the program to run without any interruptions.

**What actually happened:** Instead of successfully accessing the data.json file, I received an error message stating: "Bad response while accessing data file URL https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json.This suggests that the file may not be accessible or may have been moved or deleted.

**Comment:** I checked the URL in my browser, and it seems to return an error, which indicates that the file may no longer be available. This issue could impact users trying to run the tool, as it relies on this data file. Please investigate the status of the data.json file and consider providing an alternative or a local copy option to ensure functionality.

### Steps to reproduce

**Install Sherlock:**
Open your terminal or command prompt.
Run the command: pip install sherlock.

**Run Sherlock:**
In the terminal, execute the command: sherlock <username>, replacing <username> with any username you wish to search for.

**Observe the Output:**
Monitor the terminal output as the tool attempts to access the data.json file.

**Error Encounter:**
Note the error message that appears, specifically: "Bad response while accessing data file URL https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json.

**Check URL Manually:**
Open a web browser and navigate to https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json.
**Confirm if the file is accessible or if an error (e.g., 404 Not Found) is displayed.**

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Danila-Kovalenko** [comment]
Same here, my version is 0.14.4, and, sadly, it will not work

**Comment by ppfeister** [comment]
@Danila-Kovalenko 0.14.4 is long out of date and that behavior is expected due to a refactor. You should update your install.

_Note that the Parrot repositories are out of date, so I would recommend using any other source. Trying to get an update pushed there sometime soon_

**Comment by AshleyDownBelow** [comment]
@ppfeister both pipx and pip say 0.14.4 is latest despite updated package on PyPi
![image](https://github.com/user-attachments/assets/7a07707e-bcff-4f1a-bc53-ce2ca45d584e)

**Comment by ppfeister** [comment]
That would seem to be a local issue unfortunately and not one with Sherlock. I would however recommend trying `--no-cache` for pipx or `--no-cache-dir` for pip. @AshleyDownBelow Also applicable to @Danila-Kovalenko and @shivaganesht 

Failing that, you'd have to set a higher verbosity and read through the logs. Setting no-cache may very well solve it though.

**Comment by shivaganesht** [comment]
> What version of the tool are you running? (--version)

sherlock 0.14.4
Python HTTP for Humans.:  2.31.0
Python:  3.7.6

**Comment by shivaganesht** [comment]
> @ppfeister both pipx and pip say 0.14.4 is latest despite updated package on PyPi ![image](https://private-user-images.githubusercontent.com/186914657/381891265-7a07707e-bcff-4f1a-bc53-ce2ca45d584e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzQ1NzMsIm5iZiI6MTczMDYzNDI3MywicGF0aCI6Ii8xODY5MTQ2NTcvMzgxODkxMjY1LTdhMDc3MDdlLWJjZmYtNGYxYS1iYzUzLWNlMmNhNDVkNTg0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMTQ0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWRjN2YxMzI0Yzc4ZDYyZTVkZjhjOWZiZTkwNjRjMDBiMjc2MmI3NWVmMGI0NzE4ZWYwNWQ4ZTliYWUxYjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HgML4rqpCnbAsJmkDTdStuovqQm_bUyCWuRL3N39nEk)

Yes, I am having the same issue here.

**Comment by shivaganesht** [comment]
> That would seem to be a local issue unfortunately and not one with Sherlock. I would however recommend trying `--no-cache` for pipx or `--no-cache-dir` for pip. @AshleyDownBelow Also applicable to @Danila-Kovalenko and @shivaganesht
> 
> Failing that, you'd have to set a higher verbosity and read through the logs. Setting no-cache may very well solve it though.

![image](https://github.com/user-attachments/assets/1bea32d8-5496-45a9-b245-11698dc105e6)
I'm getting this error now. did I do it correctly? or guide me on how to execute this?

**Comment by shivaganesht** [comment]
> > That would seem to be a local issue unfortunately and not one with Sherlock. I would however recommend trying `--no-cache` for pipx or `--no-cache-dir` for pip. @AshleyDownBelow Also applicable to @Danila-Kovalenko and @shivaganesht
> > Failing that, you'd have to set a higher verbosity and read through the logs. Setting no-cache may very well solve it though.
> 
> ![image](https://private-user-images.githubusercontent.com/69391183/382568298-1bea32d8-5496-45a9-b245-11698dc105e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzQ5MzAsIm5iZiI6MTczMDYzNDYzMCwicGF0aCI6Ii82OTM5MTE4My8zODI1NjgyOTgtMWJlYTMyZDgtNTQ5Ni00NWE5LWIyNDUtMTE2OThkYzEwNWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDExNTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MDcwMzU5ODM4M2UxMmE1Y2Q3MzdmNzhjM2I3NmMzZDA4OWQxNDFlYTllNjJiMDg0NmRmNjI3NjhkYzc3OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uAY3PtL5YzaVoLK4WQovUtHbU3uiGNwRdOxBAFRdVhM) I'm getting this error now. did I do it correctly? or guide me on how to execute this?

![image](https://github.com/user-attachments/assets/5c428eb4-3d30-4f1f-a451-9354ebaf8564)

I'm not getting how to do it...

**Comment by ppfeister** [comment]
Let me be more specific --

```bash
# If using pipx
pipx upgrade sherlock-project --pip-args="--no-cache-dir"
# If using pip
pip install sherlock-project --upgrade --no-cache-dir
```

Can't say for sure if this will be what sets you right, but it's at least worth trying. I also have no idea what oddities might be present on the Windows side of things.

**Comment by shivaganesht** [comment]
> Let me be more specific --
> 
> ```shell
> # If using pipx
> pipx upgrade sherlock-project --pip-args="--no-cache-dir"
> # If using pip
> pip install sherlock-project --upgrade --no-cache-dir
> ```
> 
> Can't say for sure if this will be what sets you right, but it's at least worth trying. I also have no idea what oddities might be present on the Windows side of things.

![image](https://github.com/user-attachments/assets/a930d805-101b-43e7-af9d-a658e7477336)

I tried. No Luck. 🥲

**Comment by bytexenon** [comment]
> sherlock 0.14.4 Python HTTP for Humans.: 2.31.0 Python: 3.7.6

Hello,

This issue seems to be related to your Python version. The latest versions of Sherlock no longer supports Python 3.7, so Pip automatically selects the latest compatible version, which unfortunately uses a broken GitHub URL for the `data.json` file.

To resolve this, try upgrading your Python version by running:

```bash
sudo apt update
sudo apt install python3
```

(or an alternative depending on your distribution). After upgrading, reinstall the package and it should work

**Comment by ppfeister** [comment]
Oh god, good catch @bytexenon 

Didn't realize he was on 3.7. That went EOL almost a year and a half ago.

Those commands only work for deb + derivs but he can probably just get the latest from their website https://www.python.org/downloads/windows/

**Comment by FabriciusFab** [comment]
Same here, used both docker and pipx. Versions is 0.15

**Comment by bytexenon** [comment]
Hi @FabriciusFab,

Is the issue still persisting?

If so, as a _temporary_ workaround, you can use the `--local` parameter to fetch the site list from the system like this:

```sh
sherlock --local hello
```

But this isn't ideal, as the list is updated frequently. Could you check the error message you're getting and let me know exactly which URL it fails to access? It might be one of these:

1. `https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock_project/resources/data.json`
2. `https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json`

Additionally, could GitHub be blocked in your country? Try opening the URL from the error message in your browser to see if you can see any data in there

**Comment by vadim2179** [comment]
> Hi @FabriciusFab,
> 
> Is the issue still persisting?
> 
> If so, as a _temporary_ workaround, you can use the `--local` parameter to fetch the site list from the system like this:
> 
> ```shell
> sherlock --local hello
> ```
> 
> But this isn't ideal, as the list is updated frequently. Could you check the error message you're getting and let me know exactly which URL it fails to access? It might be one of these:
> 
> 1. `https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock_project/resources/data.json`
> 2. `https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json`
> 
> Additionally, could GitHub be blocked in your country? Try opening the URL from the error message in your browser to see if you can see any data in there

№ 2 (https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json)

**Comment by vadim2179** [comment]
404: Not Found

**Comment by bytexenon** [comment]
> 404: Not Found

Looks like you're running an old version of Sherlock (latest is `v0.15.0`). The URL you mentioned (`https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json`) isn’t valid in newer Sherlock versions. They've updated the file structure, causing older versions to throw errors. The new URL for `data.json` is `https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock_project/resources/data.json`.

Here's what you can do: Run `pipx install sherlock-project --force` (or use another method based on how you installed Sherlock—[`pipx` is recommended](https://sherlockproject.xyz/installation)) to ensure you have the latest version of Sherlock. Check it with `sherlock --version`. If it’s still on `v0.14.1` or similar, your Python might be outdated, check it using `python3 --version` or `python --version`, if it doesn't show `Python 3.9` or upwards, update your Python by following these steps:

- **Windows 10/11**:
  - Get the installer from [Python's site](https://www.python.org/downloads/windows/).
  - Run it and proceed as directed.
  - Check your version with `python3 --version` (or `python.exe --version`)—should be 3.9+.
  - If not, restart and try again.
- **Linux**:
  - **Debian/Kali/Ubuntu**:  
    - Run `sudo apt update` and `sudo apt upgrade python3`.
  - **Arch/EndeavourOS/Manjaro**:
    - Run `pacman -Syy` and `pacman -S python3`.
  - **Fedora**:
    - Run `sudo dnf check-update` and `sudo dnf upgrade python3`.
  - Confirm with `python --version` that it shows 3.9+.

Once updated, try installing Sherlock again. You might also find [this page helpful](https://sherlockproject.xyz/installation).

If you're **sure** you have the latest Sherlock version, check if `https://raw.githubusercontent.com` is blocked in your network. Test with:
```
curl https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock_project/resources/data.json
```
(or `curl.exe` on Windows) and see if you get a response [like this one](https://github.com/user-attachments/assets/9ab6d160-81be-4205-93be-7a0363853496).

If **none** of the methods above work, try using Sherlock with the `--local` option like this:
```
sherlock --local username_goes_here
```
As I've mentioned before, this workaround isn't ideal. The local `data.json` on your system updates only when the Sherlock package itself is updated, which, frankly, doesn't happen often. That's why pulling the remote file from GitHub is recommended and the default behavior of Sherlock.

/thread

**Comment by ppfeister** [comment]
Very thorough. @bytexenon's response is pretty much all there is too it.

Locking this thread to keep it clean and clear. Issues that are NOT solved by @bytexenon's response should open a new thread.

Note that only [the most recent version](https://github.com/sherlock-project/sherlock/releases) is actively supported, and if you're unable to upgrade to the latest version following the above guide, it's more than likely a local issue and not a bug with Sherlock (i.e. having the wrong version of Python installed).
