### ISSUE TITLE
No module named 'torrequest'

### ISSUE THREAD

**Issue by bialybudyn** [sherlock-project/sherlock#236]
Hi,
similar problem to module "requests_futures"

Traceback (most recent call last):
  File "sherlock.py", line 25, in <module>
    from torrequest import TorRequest
ModuleNotFoundError: No module named 'torrequest'

**Comment by sdushantha** [comment]
@bialybudyn 
Did you install all the modules before running the Sherlock?
You can install all the modules by running this:
```bash
pip3 install -r requirements.txt
```

**Comment by bialybudyn** [comment]
Thank You for reply,
yes I install all requirements.

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (4.6.0)
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: certifi in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (2018.8.24)
Requirement already satisfied: chardet in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: colorama in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (0.4.1)
Requirement already satisfied: idna in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6)) (2.7)
Requirement already satisfied: lxml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7)) (3.7.3)
Requirement already satisfied: PySocks in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8)) (1.7.0)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9)) (2.22.0)
Requirement already satisfied: requests-futures in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10)) (1.0.0)
Requirement already satisfied: soupsieve in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11)) (1.9.1)
Requirement already satisfied: stem in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12)) (1.7.1)
Requirement already satisfied: torrequest in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13)) (0.1.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14)) (1.23)
Requirement already satisfied: futures>=2.1.3; python_version < "3.2" in /usr/lib/python2.7/dist-packages (from requests-futures->-r requirements.txt (line 10)) (3.2.0)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve->-r requirements.txt (line 11)) (1.5)

I also checked request module in system
python3-requests is already the newest version (2.21.0-1).

**Comment by sdushantha** [comment]
>  Requirement already satisfied: torrequest in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13)) (0.1.0)

I am a little confused because in the log above, it says `python2.7` but for me, it says `python3.7`. You have to use `pip3` so that the modules get installed for python3.

Try this instead:
```bash
python3 -m pip3 install -r requirements.txt
```

**Comment by bialybudyn** [comment]
I tried
 `python3 -m pip3 install -r requirements.txt`
I got this:
`root@kali:~/sherlock# python3 -m pip3 install -r requirements.txt
/usr/bin/python3: No module named pip3` - so it refers to python 3.7
I also tried:
`root@kali:~/sherlock# pip3 install -r requirements.txt --isolated`
and I had:
`.../usr/local/lib/python2.7/dist-packages...` still in lib/python 2.7/.

**Comment by sdushantha** [comment]
@bialybudyn Sorry, my bad. 
This is the command:
```bash
python3 -m pip install -r requirements.txt
```

**Comment by bialybudyn** [comment]
i think it work's :)
Thank You! 

![Zrzut ekranu z 2019-07-14 21-14-42](https://user-images.githubusercontent.com/36791311/61188236-6b6d6e00-a67c-11e9-81f3-da0cdd443b4a.png)
