### ISSUE TITLE
False positive for: 8tracks.com

### ISSUE THREAD

**Issue by elvirvelagic** [sherlock-project/sherlock#2363]
### Additional info

sherlock --dump-response --site 8tracks iwhihwasdlhsakdhl 
[*] Checking username iwhihwasdlhsakdhl on:

+++++++++++++++++++++
TARGET NAME   : 8tracks
USERNAME      : iwhihwasdlhsakdhl
TARGET URL    : https://8tracks.com/iwhihwasdlhsakdhl
TEST METHOD   : message
Results...
RESPONSE CODE : 403
ERROR TEXT    : "available":true
>>>>> BEGIN RESPONSE TEXT
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}body{display:flex;flex-direction:column;height:100vh;min-height:100vh}.main-content{margin:8rem auto;max-width:60rem;padding-left:1.5rem}@media (width <= 720px){.main-content{margin-top:4rem}}.h2{font-size:1.5rem;font-weight:500;line-height:2.25rem}@media (width <= 720px){.h2{font-size:1.25rem;line-height:1.5rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);background-repeat:no-repeat;background-size:contain;padding-left:34px}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "8tracks.com",cType: 'managed',cRay: '8e1a920a9ab9929a',cH: 'sA2scngfgXTsDm0bmOkYWjIc3dsgjIjBHYUx_t0orVY-1731456959-1.2.1.1-xTuc5H0IuaiLdL.tjV9pNkFlcPsi3Z.f9sxyYbET4pmpQg32GEraa6FyXZjcsHUd',cUPMDTk: "\/users\/check_username?login=iwhihwasdlhsakdhl&format=jsonh&__cf_chl_tk=2dZNfD.UdcaD8pVch9NFn0gNjHMwJqccGAxlcxZSmtI-1731456959-1.0.1.1-uywsXZzAKCzNpeEeMKYZBmf52WVUmO3Uq9onO6bfz7Y",cFPWv: 'b',cITimeS: '1731456959',cTTimeMs: '1000',cMTimeMs: '390000',cTplC: 0,cTplV: 5,cTplB: 'cf',cK: "",fa: "\/users\/check_username?login=iwhihwasdlhsakdhl&format=jsonh&__cf_chl_f_tk=2dZNfD.UdcaD8pVch9NFn0gNjHMwJqccGAxlcxZSmtI-1731456959-1.0.1.1-uywsXZzAKCzNpeEeMKYZBmf52WVUmO3Uq9onO6bfz7Y",md: "amLrghQuzjDtuxMThQI2whMi9CiIwH.iYVU__rKZC4Y-1731456959-1.2.1.1-Jm6ZcBHGhd.a0BtrNcd4nTepqxZ6jQqC_CpM_8tHtzfo1GLLzr0yF774br14MIK51KuNoaSdEVQ5rN3IL2RCtN5VaLKxufi3rV3b5Se6Syaybi5CKTIy_ukDP0sSai60JZAqsPF4WtrOsC3P1.gKFHTQXQhJ4z76gVY2tsCJC4T1CGhGoikvY1gH.SA9I1B8m3wP.q27j955zxxIWd4cekofi_icQTCo9G7vKZFgfsZrqdu2fg3ScutLz_t27cbCmR_mBGSisdGQl_67E1Qg.qem68Z7mnEkqU6ZTUWjWBSQHi793yEmYQfZdzeFrVcMpR8y3fJ3vXmKTIAGsn_ZE4zSQq7iRsynEgm25sj9nqf5C8rWBiRjtqlne.7bjVpxfk3JxRVQ1Qx6uDlW0gzroyMo3B1h6QG5xTh5pVh62VRIR_OVrjCsC7XG7hvOet12Cq7oUm_jao_019.4jhSkOktPosaNS2AkidA0GmokgCbiEXnwJfn3leVQRrW8qXcIhSC3RpDD.wNR6pRsvO9wjOMnheEtPlQX8XCRQG1A0NvFH3jzfH0hptccvtbVR2PLjI0p8SZpDyO3SgHOK1.BaXy_JIhhdDCIOIMIijwsH4r5IoTGRAaaz04f0XFZoa91s_e1zACwikJlUkWixNG0k4O.TGX48pZxZT5Q7ZP9wT9RPFkEZEN9W4m.RYqbTrBoS0lJ28_I4QbykZobV0malVw2GJuU4uuzJrP4QcGNOO1q0vqdoybq2wWrSpIYYFPa5KNeEI5iJl7tt7mA_c9J17x782TxV69BORJ.9muXiIxJiC9FW6qlAlUuGQr05Z6S76n4IhrzVkVpZA.YoWMP8ffZ.CvLCWfxNRzW6g96rBpRJFtfs2c__3B_DYjbpYQ244JENhFbulEm_rtX4kisr9eEyDdhufoPQq41DkOao3imlWDOGfvl6SKTzPFzO8o14WC8Zvtye7TwlIBmXSCURwcI1hbL8dSIu03LbXJieoDz6ufPGT2Adxf3buXyuM.cCAi1EtnQC74b29sNBJl7mvxwSDsXPBzyqUwS2vU28zIZgBO6QiUJT5uooSCinmx8BjSZTyvtAzEgsmPvxGTKRZ20jzJnsPgaIHqbF8SfLEhpr2Ztw7eZYtTuO_2La.fG_2qDZ6NHPkD5kqXSxkSzHOBUp0pKhGW73Wcgp3dUUlbY1urBztwGAlmtNRi02jDNIvdL1a5Rmp.oQn8FNDDt9awp4qzfS.vgr9_2lLYI3hpB0Ruwm6R3bHBIfSjhfDtN1vLlpKkXQ_D8tQrAhMhRC1hlSTYKPmI8Y5E9FNPrBHFoUPJW3MFbkMYfFMkmvNobzCICVOhWt4vFYtK.WtbhGSyhts0HGbzawKvyzERO_hFSEG1yFVC9DrCVazBmG_J7umiSj8dziQ6jThjKGKKWpjsMSyZ.qoiiDHkC7AF5jY2hcrs9WRrnDS3OLvWODCnutrxvubyAJDa9ThgiN8twh2iY4s3WSYF6xwBhMeA2tAuzegYbgrKKh7_JY8OCEe0vucZOwGtKzT5c3Ff3uj6P3iF7k64JVeW6fP8qk_NNgu23P_qZrmry6XAmlSBKfGpyP_TPqQcmo_YaWzNaSdOxRKHoT1kWwsHalddmme9JKk5cTf0xBVlaBGRtHBDhlf9tu_mpgcjLOK4XtBIIpK0f_vXnEhupnd055xL.rH30Ul.A8G61EZUHdi8CNVumODRwp0W4hJCH3QhcUSZHf_nZ29.kIcXYFkCw9v73L160IZjzmVrHkMN56dQ4c.hajop8z9NGXawgZhaLHkeVKb7P2H.perDO_2M6a7xQvjiUWQUL_fK2XCUSyfDHxL5srn.CL0nUZrQ0PZ6._UqcVGtKamKOnn6.J2qtiL70Z6jKhe9JNYzF8uNJSS7.kDeKl_Dz2uSmkL_4rM8GpHcLw07cMFedKiIytEgXU8vg6amegbMDJKmDODSutNWWr30HQHoLi3KMhDiogWkx8VlINJQo30bIDEK5IkYfFkN2GeNm00Lubfh9MwROfNEKalgIeO67cUrKWkUsK3Vhr7YdJ8i5rD9FkJgAUcCL5F9fCQu4e9UA6yZYPaH3NdkQ4YmsPPAjxJgyfVieEQLLtvs3U9L3GKJiCNLLuiaRc4RPaBVclqsd6Vbs_T9_KvrI.8C6H2X3Jk_KQmTUbW4oNBSKJqm.AzddlkXSc_OWBr_s4X.JCrPO1rUznKvpsBpmtEh0kNtKZTRPBM5y4dAAvCD9YBUKGglNWncFVzWm.jwIK0Hi7qq.aXDsQ4IjAiHzSSPvda1bWPKDu.Xl2NIHKyl_lWfNRZ_vvsu04.zCsxW_mkZspLUqhiuLZJFYGMClxk1rdt3s5ETr_QvCoI.h9lxpMPb6gAkWqZjnctj9qKkXJ4VC6snzVyO5msKvipD1dsPFvS1rYUXKu.IphCfs753Bbc5I80AFNYjAIugXUz0JVgx3toSG5yf_6mUV64WSBqV8c.pJHNyUsqZO2VC3whJoSlsOCh2SrD5XZdu8uvXE9Zt7Y7GaqvmFj7_nPAzZ2hqA6DVZbboi5qhrpnkoqOI8En6vA_mPeEM9RnqZdKQxmYBnBAouVTh8eVtqXeLvckJopRFi9QB9.4.vj7YZTsGvQF4FdY.R4yyS37.lisJqdIVWMZ0",mdrd: "EEO5FBznpr9mInK98vQ76VPE18IKMGgG.FmS0KTwNMI-1731456959-1.2.1.1-M_hQ_4VxOMwMq1GU3ZIDDqRFHG3UCv0AAwSvTg5vDd1p09PzL1F2anK7Wu_E0Ux5Z0OIdaG.c6rUqKf7KUG5YqGwl90UIV3Nfw_Dk_yJ8qAQsAgpRBPuAuba2l5VGtTXHfhzmZ9domGO.1V.dk2kpjbuU1LJ3tByCKGQ6EeBQ22lEumPwMRF0yTq9Be03ngscGzO0zmSYHoT6upS8juOOAXX8bUh.D_oQpaka9h8Uxsah7ocJpCn_YEtf_TQ.rgQk8gbQo6ItM.UVVzwpEXGtJfKSFkuVttRao9rlDL7hHd051QgcvQWhREcEJHb36Br_.A1Hv6X58KraYUEyP0CnKASa3bNJ6dyiznr1u9rM6q5Q.UD.Trdf2JcFK1J.rtyvNsbBr5tdBtQEzxtxhkpqupi8URrPAZlMjevOrlGpkGc63Igdv5x3UhdrAfbeXrpWZxLF9S7nIJmzw4gkeIIYnBFOfuIDsAmvgakSRnmCsLejyy23F.hWX0UlsVVj0PSTz0eWbq0e0s3OelLLZkfSY0zXGwu8q1E4VgjZi2_iyKkxrkucp06k.0O5OiWy1IfcIXdx7w_loY2DPDf.Wis9GeHs2nAyhtDabvXjUxB6jv9q00KDEzcFWxusVbbTghvotxsItCnmDFST1W0YBoxdCwZChE7irR4ur_V7jmz7fqTpM38E29oQMMbF9YCI.BFRx8x6E1ZRiQKK7RD3dnOnJpF1YYQH3IyG0g_M.NrZWOCBkzTDhohHwnhSmi5q42orKT7yoxF1RLiM4DwE83vXtWLQjoJJLV_AMOr0MYqcBEFlAl2H4is96wYq9KWHDQzMlZXyUigJ4z7Jhxi2FaST5ERY0JoTeRQw134lL9uXvkGVjVdjTk8Y5uEAvrFriIl8uoGUaCyt7aTAsnRvg0Qv5zzUlRnTKiY_ipUxla859_pckROmQuRHv5RH3CnvezmfuoeWXP3jNH5HuQXPYYDzTd5u.R65LZRwpL3.KGpe_SMgnwxVs270OOnvG9fU2tAJYDDiZDkhXy40PVw7l9dooGE06Y2S61qyVvxTJEHgr93.WNMkCcxbuP_WbrsUqaZIN9MfyUESZGYvPkmKL49BydyX42lQ._GVjGmu5rO8YZPR_f0EK.LJCgIeLunlKGkfHFE8BYtC0edqjtHorzATobglhjH6g11KqjDFEpMMVxgjRCR6iKRlwgYHfSkaKtaavgaJ7ftmfu.3qXXytflkcoeQ5BWX8q4WfEIxljwJ3kLgRPpevfzI55lEOGW4zJXMCForS6fRXQD8lqHGJP7eMaA4FnIRQpc7d5nQEQAsYfi.gWerWub.xmr1ezmfmf6kaBYVF5L47WWjjuNihpwRaFur9pHDIW9yvCIrq8HA3oCNIDGA8NwL5CrZJs44B81ZEI534qPeAnG6fYPHs.YhoEWkU.1RePbMcHVXoD3gUeOT4Vm.l3INvkCqTzbjCP8TzV9mKUhdP6_sFwWwVeTXr0vSr9ww8h5QevL271oVycXmDZcSK4FKIMYuC3UlUcqi8fWu__cwwHjiEJD_FkzbqD0qBRsYH3rxYkalrLvnMih7IoRtWXrwrDnVCeJRn4yFJOMIEUlhJW1ovwXiXLnW7gicR0OPNpeNtz18Ou68Y6NNE_zjhj2LtEOX2WoG1gtP7.LxlFpYjlVtHeo0FoaEHimEIk7EEIf07p3eYYL1ryvr_SOBc58Bh4zj_OM_pA5CJb09GI2T49phitp59Fbd18mWYikJB6sDO6zskqtbTbo2nvsyT6OXEkhs0FT5qkLwbYz_HPPOxEz.chtLSQqvn4kxKWu5WX_WXEJ5szZ43uN5kCHp42KqHgAi7AkzuGRLCt6beEJFZBA1YMbmClNF4U2UQRF4UFXJu3EvHmB7WE.GEwuehlvv42yII3XG2POqobxVfwqZEFpxgi.KK8m54aiCiTVJJzu5tyiSmQpYDjKBYlmmq39L3mXNpohwnY9QyHjpvHbJ2oS1nl4rnjlR39CdeR1dVQ8drG9ZIIMVrjGhHO6mKB_vjiZ9Wqgx787_nP2DPE9_5ltchFFt0lujyk1BIvN69P1yrKqP8tUP4FbiNjwdJfbzpMDW3NCX.lx1kOnx8foENa1OR6cQNjOu0_4_j5EVRxJszXcl6hbpWw.YCQxM2GfBCUnfRRsBM54SSI2S0r1UC8K903pgLQRbbK7h318foAN.jqVi2L0KFelqYiPCPsoPz1JYi1b3kntf.C5pVbOvQwp4sijcNzxPqXCHZJO9ZdG1uCI4D7UEFPVu1fPOvmMn5Kn3thtPa6xM85WBgOKT4fw41TuFufccHzpk6ZcPQzoWqSxdZutWd5PYY28xRt1bw1hqIWvD1S9"};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=8e1a920a9ab9929a';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/users\/check_username?login=iwhihwasdlhsakdhl&format=jsonh&__cf_chl_rt_tk=2dZNfD.UdcaD8pVch9NFn0gNjHMwJqccGAxlcxZSmtI-1731456959-1.0.1.1-uywsXZzAKCzNpeEeMKYZBmf52WVUmO3Uq9onO6bfz7Y" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
<<<<< END RESPONSE TEXT
VERDICT       : Claimed
+++++++++++++++++++++

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ppfeister** [comment]
Fixed. Should be reflected in 0.15.1 (in a few days maybe)
