### ISSUE TITLE
ModuleNotFoundError 

### ISSUE THREAD

**Issue by owlsoul0** [sherlock-project/sherlock#243]
Running on termux and I cannot find what is wrong... It just says:
```
File "sherlock.py", line 21, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by jasonlin1222** [comment]
Did you install the required module in requirements.txt? 
[requirements.txt](https://github.com/sherlock-project/sherlock/files/3389658/requirements.txt)

**Comment by sdushantha** [comment]
@owlsoul0 
You need to install all the modules needed for Sherlock.
Just run:
```bash
pip3 install -r requirements.txt
```

**Comment by sdushantha** [comment]
or try
```bash
python3 -m pip install -r requirements.txt
```

because that worked for someone in [another issue](https://github.com/sherlock-project/sherlock/issues/236#issuecomment-511228238)

**Comment by luger19** [comment]
I have exactly the same problem on a Raspberry Pi 3B+ with Python 3.7.0 installed.
`python3 -m pip install -r requirements.txt` did'nt work for me. `pip3 install -r requirements.txt` installed the requirements but the error `ModuleNotFoundError: No module named 'requests'` is still there. So what should we do? Is it possible to install the modules manually?

**Comment by sdushantha** [comment]
@owlsoul0 @luger19 
The problem might be that you have a version of `requests` which is not compatible with Sherlock.
We might need to specify the version in the `requirements.txt`.

For now, try this:
```bash
python3 -m pip install requests --upgrade
```

**Comment by luger19** [comment]
I figured it out: `sudo pip install requests --upgrade` worked. I did this with some other modules too (colorama, requests_future and torrequest) and now everything works fine!

**Comment by sdushantha** [comment]
@luger19 Just a tip, never install python modules with `sudo`.
Here is why, https://askubuntu.com/a/802594

Also, I have broken my python before because I used sudo.

**Comment by owlsoul0** [comment]
I tried all of this (thanks for replying), but nothing worked. I think there's something wrong with my termux. I installed sherlock on my Windows and it works properly. Although I wanted to have it on my phone, I am happy with it working.

**Comment by Krishnazy** [comment]
python3 sherlock.py
Traceback (most recent call last):                           File "sherlock.py", line 24, in <module>
    from requests_futures.sessions import FuturesSession   ModuleNotFoundError: No module named 'requests_futures'

**Comment by ac3mcl0ud** [comment]
I was able to fix this with help of this video tutorial....
https://www.youtube.com/watch?v=DI_M6PhIXLM&feature=youtu.be

**Comment by xkatsu** [comment]
pip3 install requests_futures will solve, basic of python
