### ISSUE TITLE
Modulenotfound

### ISSUE THREAD

**Issue by nitroxnoob** [sherlock-project/sherlock#246]
Traceback (most recent call last):
  File "sherlock.py", line 24, in <module>
    from requests_futures.sessions import FuturesSession
ModuleNotFoundError: No module named 'requests_futures'

**Comment by nitroxnoob** [comment]
Please help me out!

**Comment by sdushantha** [comment]
@nitroxnoob What OS are you running?

**Comment by Lionde002** [comment]
parrot security os

**Comment by Lionde002** [comment]
Traceback (most recent call last):
File "sherlock.py", line 24, in
from requests_futures.sessions import FuturesSession
ModuleNotFoundError: No module named 'requests_futures'

**Comment by sdushantha** [comment]
This is really strange because it works on Manjaro Linux

**Comment by hoadlck** [comment]
Can you see what version of the various modules you are running?  I am running 2.21.0 of "Python HTTP for Humans"

Perhaps you have an old enough version that Sherlock is not compatible with it.

**Comment by Lionde002** [comment]
Soo what can i do for it...?..(i'm working python 3.6.7) on parrot security
linux

**Comment by sdushantha** [comment]
@Lionde002 Could you please tell us what version of requests you have installed?

**Comment by Lionde002** [comment]
Ohh i use parrot linux..is it work great on kali linux..?

**Comment by johnmillstead** [comment]
I am having the same problem. MacOS Mojave, Python 3.7.3

**Comment by johnmillstead** [comment]
This fixed it...

python3 -m pip install -r requirements.txt
 instead of pip install -r requirements.txt

**Comment by sdushantha** [comment]
@nitroxnoob Were you able to fix the problem you were having?

**Comment by hoadlck** [comment]
I am closing this out. It appears to be an installation issue.

**Comment by photoemulator** [comment]
I know it's closed, but I had the same issue and the fix I found was to run the python script included in the download of the git, "install_packages.sh"

**Comment by saadat99** [comment]
Same issue on windows, python 3.7.3
```
(venv) PS C:\Users\sam\dev\sherlock> py .\sherlock.py --help
Traceback (most recent call last):
  File ".\sherlock.py", line 24, in <module>
    from requests_futures.sessions import FuturesSession
ModuleNotFoundError: No module named 'requests_futures'
```

**Comment by IronVenom** [comment]
@saadat99 You can correct this error on windows by simply running this : 
`pip install requests_futures`

**Comment by saadat99** [comment]
@IronVenom `request` and `request_features` are installed. When I type `py sherlock.py --help` program exits with error but when I type `python sherlock.py --help` it works fine. That's weird. I didn't know those are different

**Comment by IronVenom** [comment]
Those are different. Does it work now after installing requests_futures?

**Comment by saadat99** [comment]
> Those are different. Does it work now after installing requests_futures?

The packages were installed before through `requirements.txt`. It is working with `python` command.
The `py` command is causing the issue. It throws this error.
```
Traceback (most recent call last):
  File ".\sherlock.py", line 21, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
again the command is causing the issue. packages are installed

**Comment by IronVenom** [comment]
Just install the packages that you don't have using pip. Don't run the package on a virtual environment and use the base of conda or python.

**Comment by und3fined404** [comment]
> This fixed it...
> 
> python3 -m pip install -r requirements.txt
> instead of pip install -r requirements.txt

# python3 -m pip install -r requirements.txt
/usr/bin/python3: No module named pip

**Comment by p0wnage** [comment]
> This fix works 100% for Parrot OS.
> 
> python3 -m pip install -r requirements.txt
> instead of pip install -r requirements.txt

**Comment by ac3mcl0ud** [comment]
I was able to fix this with this video tutorial
http://bit.ly/2UfCYHE

**Comment by jthomas2234** [comment]
@p0wnage tried that but still getting this 

- Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7'
Consider using the `--user` option or check the permissions.
### When trying to upgrade 
- You are using pip version 19.0.3, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

- DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages/pip-20.1-py2.7.egg (20.1)

any other things i should try?

**Comment by kajnet** [comment]
Had this same issue.
This fixed it for me.
python3 -m pip install -r requirements.txt
However, after this I got a new error that I was missing 'TorRequest'.
pip install torrequest
Now it works.

**Comment by HAWKM0TH** [comment]
Thank you so much, it worked for me as well.
