### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by pete7628** [sherlock-project/sherlock#252]
I got a KeyError :

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\sherlock-master\she
rlock.py", line 615, in <module>
    main()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\sherlock-master\she
rlock.py", line 606, in main
    **results[site]['url_user'],**
KeyError: 'url_user'

when executing 

sherlock.py -fo MyResults --csv riyov

on Windows 7.

**Comment by hoadlck** [comment]
This problem happens during the write to the CSV.  There are various results that are gathered during the query for the existence of a given site, and they are always expected to exist in the results dictionary.  However, if a given user name has an illegal format for a given site, then the query is not even attempted.  Which leaves some keys in the dictionary undefined.

The solution is to define these keys even in the case where the username has an illegal format.

See #254

**Comment by hoadlck** [comment]
Thanks for finding the bug!

We need to figure out how to test these other options on the command line.
