### ISSUE TITLE
syntax error on mac os mojave

### ISSUE THREAD

**Issue by aarondavid545** [sherlock-project/sherlock#253]
I Have tried multiple versions of python and every time i'm getting the same error message.
what do thing i'm doing wrong?
<img width="624" alt="Screen Shot 2019-07-15 at 3 15 47 PM" src="https://user-images.githubusercontent.com/52803315/61257180-e6e32400-a73d-11e9-8354-68c63d36c58e.png">
<img width="624" alt="Screen Shot 2019-07-15 at 3 15 47 PM" src="https://user-images.githubusercontent.com/52803315/61257193-f5314000-a73d-11e9-86e0-0b7dd364dff3.png">

**Comment by hoadlck** [comment]
The Git command cannot be executed in the Python interpreter.  Do you have Git installed? Run the git commands in a command window.

**Comment by sdushantha** [comment]
@aarondavid545 
Please watch this video, this will help you :)
https://streamable.com/6jdm2

**Comment by Cookizza** [comment]
I am having this too:

     ==> python sherlock.py testuser123
  File "sherlock.py", line 78
    Fore.GREEN + f"] {title}" +
                            ^
SyntaxError: invalid syntax

**Comment by sdushantha** [comment]
@Cookizza,your syntax error is different from @aarondavid545.
The syntax error in this issue is because the user ran the `git` command in the interpreter and not in the command line.
