### ISSUE TITLE
trouble installing requirements

### ISSUE THREAD

**Issue by gmason96** [sherlock-project/sherlock#257]
stops at line 10 help? mac os

![Screen Shot 2019-07-17 at 1 06 26 AM](https://user-images.githubusercontent.com/51420548/61337924-39e8d400-a82f-11e9-9383-3dc8e99caebf.png)

**Comment by hoadlck** [comment]
You need to be using Python 3.6 or later.  Your screenshot shows you are using 2.7.

**Comment by sdushantha** [comment]
@hoadlck We really need to add some code like you mentioned in #212, to check for the python version they are using to run Sherlock.

**Comment by VShaikh** [comment]
sudo apt-get install python3-distutils
sudo python3 get-pip.py
python3 -m pip install -r requirements.txt

**Comment by hoadlck** [comment]
Closing out this issue as it is a user environment problem...
