### ISSUE TITLE
Mixcloud always returns statusCode 200 and does not contain errorMsg.

### ISSUE THREAD

**Issue by tdh8316** [sherlock-project/sherlock#258]
Hi, I ran sherlock with this command and the result is:
```
(sherlock) C:\Users\dongtak\Downloads\sherlock-master>python sherlock.py hey_sherlock_xyz --site Mixcloud
                                              ."""-.
                                             /      \
 ____  _               _            _        |  _..--'-.
/ ___|| |__   ___ _ __| | ___   ___| |__    >.`__.-""\;"`
\___ \| '_ \ / _ \ '__| |/ _ \ / __| |/ /   / /(     ^\
 ___) | | | |  __/ |  | | (_) | (__|   <    '-`)     =|-.
|____/|_| |_|\___|_|  |_|\___/ \___|_|\_\    /`--.'--'   \ .-.
                                           .'`-._ `.\    | J /
                                          /      `--.|   \__/

[*] Checking username hey_sherlock_xyz on:
[+] MixCloud: https://www.mixcloud.com/hey_sherlock_xyz
1.1207261085510254
```

Sherlock found the user `hey_sherlock_xyz` on Mixcloud but [mixcloud.com/hey_sherlock_xyz](https://www.mixcloud.com/hey_sherlock_xyz) does not exist.

And Mixcloud always returns code 200. Besides, does not contain errorMsg.
```cmd
>>> r = request(method="GET", url=" https://www.mixcloud.com/hey_sherlock_xyz")
<Response [200]>
>>> "Page Not Found" in r.text
False
``` 

Therefore, Mixcloud is always showing false positive!

**Comment by hoadlck** [comment]
Yeah, I am seeing the same thing.  It appears that they have changed their website.  Before, they rendered their "Page Not Found" error message in HTML.  Now, they must be creating that text with javascript.

I think that we are going to have to remove this site.

**Comment by sdushantha** [comment]
> I think that we are going to have to remove this site.
Agreed.

**Comment by hoadlck** [comment]
It turns out that they have an unauthenticated API available. So, I converted over  to that.

Thanks for finding the bug!
