### ISSUE TITLE
Facebook Illegal Username Issue

### ISSUE THREAD

**Issue by irazasyed** [sherlock-project/sherlock#262]
Sherlock seems to be throwing this `Illegal Username Format For This Site!` error for a bunch of valid usernames that are already claimed.

Here are some usernames that are valid and owned yet it fails:
- [cnn](https://www.facebook.com/cnn/)
- [bbc](https://www.facebook.com/bbc/)
- [id.co](https://www.facebook.com/id.co/)
- [MINI.uk](https://www.facebook.com/MINI.uk/)
- [lifo.mag](https://www.facebook.com/lifo.mag/)
- [lukonet](https://www.facebook.com/lukonet/)

**Comment by originalmrkoww** [comment]
I'm having similar issues with names I know are correct.

**Comment by LameLemon** [comment]
It seems the regex validation was made with the Facebook guidelines in mind. 

* Usernames can only contain alphanumeric characters (A–Z, 0–9) and periods ("."). They can't contain generic terms or extensions (.com, .net).
* Usernames must be at least 5 characters long.
* Periods (".") and capitalization can't be used to differentiate usernames. For example, johnsmith55, John.Smith55 and john.smith.55 are all considered the same username.

The usernames above that are less than 5 characters (bbc, cnn) long seem to be an exception to that rule. The regex is however wrong in the way it checks for `.com`, `.net` and `.org` (wrongly catches lukonet)  and it does not allow periods (".") as a valid character(id.co). I can submit a PR with these corrections. 

P.S. @ghost do you have any other usernames that might be exceptions?

**Comment by LameLemon** [comment]
Since the pull request has been merged, this issue is resolved.
