### ISSUE TITLE
Wiki for contributing has broken example

### ISSUE THREAD

**Issue by jaredgoodman03** [sherlock-project/sherlock#274]
https://github.com/sherlock-project/sherlock/wiki/Adding-Sites-To-Sherlock shows a buzzfeed link to taken and not-taken usernames, but someone took the not-taken username so it should be updated.

**Comment by hoadlck** [comment]
The link for Canva was taken as well. I fixed them both.

I don't really understand how this is happening. Is there some automated process that just scrapes usernames?  Or, some lurker at Sherlock that it just being a pain?

Ah, well.  Thanks for the notice.
