### ISSUE TITLE
Have Sherlock fetch data.json from web

### ISSUE THREAD

**Issue by sdushantha** [sherlock-project/sherlock#283]
Since we keep on updating `data.json`, I personally think it would be better if we make a separate repo with the data and then tell Sherlock to get the raw JSON from the that repo. This would let the user have the most updated version of the `data.json`.

One disadvantage of this is that Sherlock would be a little slower because it has to send a request to fetch the JSON data.

Also, this would allow other devs to use JSON data for their own script.

What are your thoughts?

**Comment by irazasyed** [comment]
+1 and it'll help other implementations as well.

As far as fetching the file is concerned, you should consider caching it for a brief period of time (hourly?) with an option to clear cache/force refresh. This should resolve the additional request issue which isn't required as the data doesn't change so often. Even once a day is more than enough but hourly will be great. I'm already doing this with my PHP implementation. So it saves that one additional request when I'm doing multiple queries.

**Comment by TheYahya** [comment]
It's great @sdushantha, we should have a separate repo and deploy it with github pages for now.

**Comment by sdushantha** [comment]
@TheYahya I have created the repo and added the JSON data. Could you deploy it with GitHub pages?

**Comment by TheYahya** [comment]
Now it's available on [https://sherlock-project.github.io/sherlock-data/data.json](https://sherlock-project.github.io/sherlock-data/data.json)
