### ISSUE TITLE
Find username on Linkedin

### ISSUE THREAD

**Issue by waghcwb** [sherlock-project/sherlock#289]
It will be nice if sherlock can find usernames on Linkedin.

**Comment by sdushantha** [comment]
You can make a PR if you want :)

**Comment by waghcwb** [comment]
@sdushantha,

Okay, I'll make a PR soon as I can. I'm little bit busy at work, and I need to understand how can I add a new site to sherlock.

**Comment by Alexandros-Kordatzakis** [comment]
Hey @waghcwb !

I saw this issue and couldn't resist. Would you mind if I make that P.R. ? I have already a tested version ready for Linedin...

**Comment by waghcwb** [comment]
@Alexandros-Kordatzakis 

Of course you can do it. I'm still busy at work, I'll take a while to develop this. Feel free to open a PR :boom:
