### ISSUE TITLE
Variable `proxy` defined but not used.

### ISSUE THREAD

**Issue by tdh8316** [sherlock-project/sherlock#292]
https://github.com/sherlock-project/sherlock/blob/4f3f15cfd084c2a7dc026f206f9e4d20e1931307/sherlock.py#L565-L571

I think variable `proxy` is declared for use as an argument of function `sherlock`. But it is not used.
I'm not sure if this is the intended action.

And I'm making a PR to improve code quality and will include your suggestion to that PR.

**Comment by tdh8316** [comment]
```python
        # We try to ad a random member of the 'proxy_list' var as the proxy of the request.
        # If we can't access the list or it is empty, we proceed with args.proxy as the proxy.
        try:
            random_proxy = random.choice(proxy_list)
            proxy = f'{random_proxy.protocol}://{random_proxy.ip}:{random_proxy.port}'
        except (NameError, IndexError):
            proxy = args.proxy

        results = {}
        results = sherlock(username, site_data, verbose=args.verbose,
                           tor=args.tor, unique_tor=args.unique_tor, proxy=args.proxy, print_found_only=args.print_found_only)
```
@hoadlck @sdushantha 
May I replace the `args.proxy` argument of the Sherlock function with `proxy`?

**Comment by hoadlck** [comment]
This has been incorporated into #590.
