### ISSUE TITLE
Potential dependency conflicts between sherlock and chardet, idna and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [sherlock-project/sherlock#295]
Hi, _**sherlock**_ directly and transitively introduced multiple versions of chardet, idna and urllib3.

As shown in the following full dependency graph of  **_sherlock_**, sherlock directly requires _**chardet**_ (the latest version), _**idna**_ (the latest version) and _**urllib3**_ (the latest version), while the installed version of **_requests_**(2.22.0) requires  _**chardet>=3.0.2,<3.1.0**_, _**urllib3>=1.21.1,<1.26**_ and _**idna>=2.5,<2.9**_.

According to pip's “first found wins” installation strategy, _**chardet 3.0.4**_, _**urllib3 1.25.3**_ and _**idna 2.8**_ are the actually installed versions

Although the first found package versions _**chardet 3.0.4**_, _**urllib3 1.25.3**_ and _**idna 2.8**_ just satisfy their corresponding later dependency constraints (_**chardet>=3.0.2,<3.1.0**_), (_**urllib3>=1.21.1,<1.26**_) and (_**idna>=2.5,<2.9**_), it will lead to a build failure once developers release a newer version of _**chardet**_, _**urllib3**_ and _**idna**_.

### Dependency tree--------
```
sherlock(version range:)
| +-beautifulsoup4(version range:)
| +-bs4(version range:)
| | +-beautifulsoup4(version range:)
| +-certifi(version range:)
| +-chardet(version range:)
| +-colorama(version range:)
| +-idna(version range:)
| +-lxml(version range:)
| +-pysocks(version range:)
| +-requests(version range:)
| | +-chardet(version range:>=3.0.2,<3.1.0)
| | +-idna(version range:>=2.5,<2.9)
| | +-urllib3(version range:>=1.21.1,<1.26)
| | +-certifi(version range:>=2017.4.17)
| +-requests-futures(version range:)
| | +-requests(version range:>=1.2.0)
| | | +-chardet(version range:>=3.0.2,<3.1.0)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:>=1.21.1,<1.26)
| | | +-certifi(version range:>=2017.4.17)
| | +-futures(version range:>=2.1.3python)
| +-soupsieve(version range:)
| +-stem(version range:)
| | +-cryptography(version range:)
| | +-mock(version range:)
| | +-pycodestyle(version range:)
| | +-pyflakes(version range:)
| | +-pynacl(version range:)
| | +-tox(version range:)
| +-torrequest(version range:)
| | +-PySocks(version range:>=1.5.7)
| | +-requests(version range:>=2.11.0)
| | | +-chardet(version range:>=3.0.2,<3.1.0)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:>=1.21.1,<1.26)
| | | +-certifi(version range:>=2017.4.17)
| | +-stem(version range:>=1.4.0)
| | | +-cryptography(version range:)
| | | +-mock(version range:)
| | | +-pycodestyle(version range:)
| | | +-pyflakes(version range:)
| | | +-pynacl(version range:)
| | | +-tox(version range:)
| +-urllib3(version range:)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Fix your direct dependencies to be **_chardet>=3.0.2,<3.1.0_**, **_idna>=2.5,<2.9_**,  **_urllib3>=1.21.1,<1.26_** and **_requests==2.22.0_**, to remove this conflict. 
  
 I have checked this revision will not affect your downstream projects now.

2.	Remove your direct dependency _**chardet, urllib3 and idna **_, and use _**chardet**_ transitively introduced by request.

@   Please let me know your choice. I can submit a PR to solve this issue.
Build a good dependency ecosystem for python projects is our common goal ^_^.
Build a good dependency ecosystem for python projects is our common goal.

@hoadlck  May I pull a request to solve this issue?

**Comment by sdushantha** [comment]
@NeolithEra 
A PR would be appreciated :)
