### ISSUE TITLE
Username with Space

### ISSUE THREAD

**Issue by T2brozz** [sherlock-project/sherlock#296]
How I can search a Username with a Space

**Comment by hoadlck** [comment]
You just need to quote the user name on the command line.  Here is an example using a Git Bash shell on Windows 10:
```
python -u sherlock.py --site twitter "name space"
```

Keep in mind that there are probably many sites that do not allow spaces in the user name.  Sherlock does not have many of the validity checks configured, so a name that may claim to be available might actually  be illegal.

**Comment by T2brozz** [comment]
Thanks

**Comment by rama25** [comment]
`python sherlock "username"`
this command works for username with spaces and extracts info about users from all the sites which are in sites.md
