### ISSUE TITLE
File "sherlock.py", line21, in <module>

### ISSUE THREAD

**Issue by TechGirl007** [sherlock-project/sherlock#300]
Hi.  Having problems with the following feedback basic search paramater:

```
python3 sherlock.py user
```
```
Error message is as follows:
Traceback (most recent call last):
File "sherlock.py", line 21, in <module>
import requests
ModuleNotFoundError:  No module named 'requests'.
```

Can anyone help me to solve this?  Thanks.

**Comment by sdushantha** [comment]
Hey @TechGirl007 

Have you installed all the required modules by running this command?
```bash
$ pip3 install -r requirements
```

**Comment by TechGirl007** [comment]
Hi @sdushantha 
Yes.  :(  Did it twice - so not sure if that is the problem!  Says all installed!

**Comment by dewjiguang** [comment]
i met the same problem with you, so,have you solve it ?

**Comment by TechGirl007** [comment]
Hi @dewjiguang   Yup...still same problem. There is no module called requests.  I install the module into python but the installation seems to go to a file of python2.7 that came with Kali originally.  I have a few other ideas to install the module in python 3.7.  But at the moment...it I'm still getting the same reading even with the new request module that I installed.  Any help would be appreciated!  Thanks

**Comment by hoadlck** [comment]
You need to have the dependencies installed for Python 3.7.  If you are actually running the pip for Python 2.7, the dependencies will not change for Python 3.7.

Try typing the following:

```
% pip3 --version
pip 19.0.3 from c:\python36\lib\site-packages\pip (python 3.6)
```

Your results will be different, but it should show you the version of Python and where the main Python engine is installed.

**Comment by Arsaamkhan** [comment]
Same problem here for me , I'm on UBUNTU 19.04 with python3.7
Error:
Traceback (most recent call last):
  File "sherlock.py", line 21, in <module>
    import requests
  File "/home/qphy/.local/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

**Comment by Arsaamkhan** [comment]
@hoadlck the message in terminal is displayed as
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (1.24.1)

and i had installed all the packages that are mentioned in the requirements.txt
with the same command you mentioned above.
on which system have u tested sherlock  ?
after that i had tried sherlock in Termux (Android App) and it worked.

**Comment by hyunwoo8960** [comment]
try running sherlock on Parrot os it worked for me

**Comment by hoadlck** [comment]
This issue appears to be an environmental issue rather than a problem with Sherlock itself.  It also has been hanging out for some time.  So, I am closing it out now to remove the clutter.

**Comment by Csql2** [comment]
I have the same error
