### ISSUE TITLE
Error Connecting for most websites (Failed to establish a new connection: [Errno -2] Name or service not known' in urllib3

### ISSUE THREAD

**Issue by Berghopper** [sherlock-project/sherlock#301]
I believe this might be a partial duplicate of #230, however, because of lack of information and error output I made my own issue just to be safe.

With the latest python3.7.3 and the correct requirements I constantly run into the issue of websites not connecting.
Specifically this happens after trying to connect to Bandcamp, subsequently, all other urls following bandcamp fail as well.

I printed the `requests.exceptions.ConnectionError` at line 128 as well as the future object class.
For some reason, urllib3 seems to fail finding the name or service (so this might be a DNS issue?).

Further details below (snippet from e.g. YouTube):  

```
[-] Error Connecting: YouTube
[-] YouTube: Error!
{'errorType': 'response_url', 'errorUrl': 'https://www.zhihu.com/people/{}', 'rank': 0, 'url': 'https://www.zhihu.com/people/{}', 'urlMain': 'https://www.zhihu.com/', 'username_claimed': 'blue', 'username_unclaimed': 'noonewouldeverusethis7', 'request_future': <Future at 0x7f318072ce80 state=finished raised ConnectionError>}
<Future at 0x7f318072ce80 state=finished raised ConnectionError>
HTTPSConnectionPool(host='www.zhihu.com', port=443): Max retries exceeded with url: /people/berghopper (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f318070c2e8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
<Future at 0x7f318072ce80 state=finished raised ConnectionError>
```

**Comment by Berghopper** [comment]
Small update: adding and removing bandcamp or other urls from `data.json` does not work and urllib consistently fails after around 10-15 websites.
Also, adding a time.sleep does not work either (tried this because of possibly too many requests at once?)

**Comment by Alexandros-Kordatzakis** [comment]
Same issue here. After the first ~15 sites, almost every other that follows has the message: 
[-] **Error Connecting:** <source/website>
[-] **<source/website>:** Error!

**Comment by hoadlck** [comment]
Can you try it now with the latest content on master (version 0.10.0)? In #471, I placed a limit on the number of threads that can be allocated. And, it did not seem to make any difference on performance.

Other people have been having other symptoms, but I wonder if this bug may have been what you have been seeing.

**Comment by Berghopper** [comment]
> Can you try it now with the latest content on master (version 0.10.0)? In #471, I placed a limit on the number of threads that can be allocated. And, it did not seem to make any difference on performance.
> 
> Other people have been having other symptoms, but I wonder if this bug may have been what you have been seeing.

It seems to work fine, albeit very slow because of the insane amount of DNS requests (I don't think our home router likes me).

**Comment by hoadlck** [comment]
Yay! Glad that it is working.

**Comment by Alexandros-Kordatzakis** [comment]
Works great for me! Same speed as always, but with correct results and no errors!! [Maybe +2,3 seconds ,but thats nothing
Thank you!
