### ISSUE TITLE
Error Line 628 

### ISSUE THREAD

**Issue by allepicondor** [sherlock-project/sherlock#310]
sherlock Username$ python3 sherlock.py user123
Traceback (most recent call last):
  File "sherlock.py", line 620, in <module>
    main()
  File "sherlock.py", line 374, in main
    f"{requests.__description__}:  {requests.__version__}\n" + \
AttributeError: module 'requests' has no attribute '__description__'
Computer:sherlock Username$ 

Im probably being an idiot and messed something up

**Comment by Beall619** [comment]
Compare your requests version to the current

**Comment by hoadlck** [comment]
@allepicondor are you still having problems?

**Comment by hoadlck** [comment]
This looks like a case of not having the proper dependencies installed.  Since we have not heard anything back, I am closing the issue.
