### ISSUE TITLE
question cant run sherlock

### ISSUE THREAD

**Issue by dewjiguang** [sherlock-project/sherlock#311]
![image](https://user-images.githubusercontent.com/41632105/63416612-541b6080-c432-11e9-96a0-8c32e0e3a13b.png)

**Comment by dewjiguang** [comment]
when i run python3 sherklock.py username,i received this msg:
Traceback (most recent call last):
  File "sherlock.py", line 22, in <module>
    from colorama import Fore, Style, init
ModuleNotFoundError: No module named 'colorama'

**Comment by LameLemon** [comment]
Make sure you're using the latest version and have installed all the requirements before starting
```bash
git pull
python3 -m pip install -r requirements.txt
```

**Comment by legendaryvampire51** [comment]
it worked man. thanks
