### ISSUE TITLE
Alphabetise data.json

### ISSUE THREAD

**Issue by LameLemon** [sherlock-project/sherlock#312]
Now I understand this it probably not critical but it would be nice if data.json were in alphabetical order. It makes finding the website you are looking for much easier in the output and just looks neater. 

I could submit a PR with data.json in the correct order, it would be nice to include this as a requirement in the contributing guidelines for future PRs too. 

Love the work done on this project : )

**Comment by Beall619** [comment]
I could make a quick script for that. I'll post it here tomorrow.

**Comment by hoadlck** [comment]
After merging a new site, we are supposed to run the [site_list.py](https://github.com/sherlock-project/sherlock/blob/master/site_list.py) script.  This gets the ranking of the various sites, and also sorts the JSON.

So, the sorting is already covered.
