### ISSUE TITLE
NEW MAINTAINERS WANTED!

### ISSUE THREAD

**Issue by sdushantha** [sherlock-project/sherlock#313]
@TheYahya, @hoadlck, @irazasyed  and I are really busy and are not able to actively maintain this project by replying to issues and reviewing PRs frequently, so we would really appriciate it if we could get a few people to help us maintain this project 😃 

The only thing we are asking is that you don't mess up the project 🙏 
> With great power, comes great responsibility.

If you would like to become a maintainer, just contact @TheYahya via email (check his profile).

Thank you, hope you guys have a great day!

**Comment by sdushantha** [comment]
Its been a while now, I think I'll just close it

**Comment by jcs090218** [comment]
I am willing to help out! I also want to work on project [api](https://github.com/sherlock-project/api). I am learning both `Django` and `React.js`.

**Comment by ClassicVWnetwork** [comment]
Thanks for your interest in our project I'm personally not a programmer but
do have other computer skills and what to learn more about programming. I'm
an entrepreneur and I'm always thinking of things that could help in the
advancement of technology and human kind to make the world a better place.
I'm looking for a small team people to work on The Killscam Protocol and
the projects you're working on could greatly contribute to the protocol.
Please reach out from to me on the team chat channel or on telegram so we
can chat more. https://chat.killscam.org or https://t.me/thekillscamprotocol

**Comment by jcs090218** [comment]
> I am willing to help out! I also want to work on project api. I am learning both Django and React.js.

@TheYahya Does this project still need the maintainer? Thanks!

**Comment by TheYahya** [comment]
Yes dear @jcs090218,

I answered you [here](https://github.com/sherlock-project/api/issues/1#issuecomment-753644423),
And also you can contribute to [this](https://github.com/sherlock-project/sherlock) project.
