### ISSUE TITLE
Program stucks after "Filmogs" check

### ISSUE THREAD

**Issue by MinePro120** [sherlock-project/sherlock#323]
That's about it. After Filmogs is checked, the program halts.

**Comment by MinePro120** [comment]
Edit : sometimes it stops after Canva too.

**Comment by LameLemon** [comment]
Are there any error messages, if so can you paste them here? Does it do this for other usernames?

**Comment by MinePro120** [comment]
No error messages. It just stops. No matter the username. I'm using kali 2019.3 with all the requirements installed and python is up to date.
