### ISSUE TITLE
False positive on Ebay, Duolingo, Tiktok and Trip Skyscanner

### ISSUE THREAD

**Issue by r4msolo** [sherlock-project/sherlock#325]
The script shows false results on these sites: **Ebay**, **Duolingo**, **Tiktok** and **Trip Skyscanner**

**Comment by rcaballerog** [comment]
Can you give us an example?

**Comment by hoadlck** [comment]
What user names did you use?   

Ebay, Duolingo, and Tiktok work fine with the test data.

Trip Skyscanner did have a problem.  It appears that the error response text changed.  I converted it to use the HTTP Status code method, and it looks to be working now. I will push a PR for that later on today....

**Comment by hoadlck** [comment]
Trip was fixed with #328.

**Comment by LameLemon** [comment]
Ebay, Duolingo and Tiktok worked for all the usernames I tried it against including my own accounts. There seems to be no issue there. 

@r4msolo  can you provide some usernames that you tried out that failed?

**Comment by r4msolo** [comment]
> Ebay, Duolingo and Tiktok worked for all the usernames I tried it against including my own accounts. There seems to be no issue there.
> 
> @r4msolo can you provide some usernames that you tried out that failed?

it really works, but it's bringing false results, I tested it with my own nick `r4msolo` and the script show me a positive result, I don't have an ebay or duolingo account. But Trip and Tiktok were fixed in my new test!

**Comment by LameLemon** [comment]
### Duolingo
For Duolingo, when checking in the browser `https://www.duolingo.com/r4msolo` initially loads and then immediately redirects to `https://www.duolingo.com/errors/404.html`. I have verified this with other usernames as well, It seems to do this for every non-existent username under 11 characters.

I have just checked their username requirements and it is only up to and including 10 characters. The unclaimed username Sherlock uses is much longer (`noonewouldeverusethis7`) which was why it redirected to the 404 page. I've not been able to find a method to detect unlcaimed usernames yet.

### Ebay
As far as ebay is concerned I've not found any issue yet. I checked for `r4msolo` which was not found. It seems to work with the existing test cases too.

**Comment by hoadlck** [comment]
I added a check for valid Duolingo usernames.  And, updated the fail username in the tests.

But, they must have done some changes to their site.  For the "response_url" detection method, I would expect a 301 redirect.  But, the site now returns a 200 regardless of the existence of user.

**Comment by hoadlck** [comment]
The sites that are not working were removed in #342.
