### ISSUE TITLE
Codepen False Negative/Trip False Positive

### ISSUE THREAD

**Issue by theLMGN** [sherlock-project/sherlock#326]
![image](https://user-images.githubusercontent.com/12257112/65722187-a5f37e00-e0a3-11e9-9a69-676ab5c5da78.png)

![image](https://user-images.githubusercontent.com/12257112/65722337-fc60bc80-e0a3-11e9-95da-fc8ba98cbbeb.png)

**Comment by hoadlck** [comment]
Sherlock is getting a HTTP 403 status returned from Codepen.  Yet, if I check from my own browser, I get a clean 200.  I tried changing Sherlock's user agent string, and that did not make any difference either.

Needs more research....

**Comment by hoadlck** [comment]
Just merged #328 to fix Trip.

**Comment by LameLemon** [comment]
Codepen does not seem to work without JavaScript, there's currently no way to emulate a browser through sherlock so it would not be possible to get usernames from here. I could not find any other way to get around it, maybe till be we find a solution Codepen should be taken off the list?

![codepen-js](https://user-images.githubusercontent.com/35942108/65944728-43dfa380-e42a-11e9-801f-1dbf4bd190c9.png)

**Comment by theLMGN** [comment]
Even without JS, it responds with the correct status code 

![image](https://user-images.githubusercontent.com/12257112/66025878-6daece00-e4ef-11e9-9ab5-be8381d583d7.png)

**Comment by LameLemon** [comment]
Interesting, just played around with it myself. It seems codepen.io returns status code 403 to Sherlock. I was able to get code 200 and code 404 for existing and non-existing usernames respectively in cURL. However any request with Sherlock, even with using the same headers, returns 403.

 Working cURL command, this only preforms a header request just like Sherlock.
```
curl -I 'https://codepen.io/jenny' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Cache-Control: max-age=0' -H 'TE: Trailers'
```

**Comment by FilippoDeAngelis** [comment]
I did some testing on my own, outside Sherlock. I tried making a pure get request, one with the same user agent Sherlock uses, and one using the exact same headers on the previous comment.
All returned a 403 response. I'm suspecting a problem in the requests library.

Posting my code for completeness:
```
import requests

url = "https://codepen.io/thelmgn"
requests_inst = requests.Session()
response = requests_inst.get(url=url, headers={
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
        'Cache-Control': 'max-age=0',
        'TE': 'trailers'
    })
print(response)
```

**Comment by hoadlck** [comment]
The sites that are not working were removed in #342.

Yes, I think that in the end we will have to revamp Sherlock to behave more like a browser.  I have used Selenium with ChromeDriver to automate/test some things...Sherlock could do this too.  I am not sure how the support is on Linux. There is much to investigate before we go there.
