### ISSUE TITLE
KhanAcademy false positive

### ISSUE THREAD

**Issue by platonbjs** [sherlock-project/sherlock#344]
![image](https://user-images.githubusercontent.com/48056193/67565775-84c79100-f726-11e9-94a2-c2d84d3a3474.png)
![image](https://user-images.githubusercontent.com/48056193/67565818-990b8e00-f726-11e9-863e-47bc7267633a.png)

Tested with several false usernames. Sherlock always found a user registered

I'm comparing the curl response and its seem identicals. I think the body of the response is builded by a javascript. The response code is 200 so we can't use error_code. 

I am working with this project for first time. Has another errorType than error_code, message or response_url?

**Comment by rcaballerog** [comment]
Tested with several false usernames. Sherlock always found a user registered

**Comment by hoadlck** [comment]
They must have just changed their website.  It was working last weekend: I purged all of the sites with erroneous results.

It also looks like 500px has also changed.

It is going to take a deeper re-design of Sherlock to work with sites like this.  Until then, we will have to remove these sites from the list.

**Comment by hoadlck** [comment]
I moved Kahn Academy to the removed sites list.  On closer look, 500px is working...it must have flaked out before.

Thanks for letting us know. :)

**Comment by platonbjs** [comment]
Thank you guys
