### ISSUE TITLE
Lxml

### ISSUE THREAD

**Issue by YourManz** [sherlock-project/sherlock#347]
Not sure if this is a script problem, but when I use the python3 command, it does it’s thing then says “can’t  roll back lxml, was not uninstalled.”

**Comment by LameLemon** [comment]
Can you try to update lxml via pip?
```
pip3 install --upgrade lxml
```

**Comment by hoadlck** [comment]
This is an issue with your environment, not with Sherlock itself.

I did not see many hits for this error message on Google, but it appears to be an issue with the install of lxml.  [One](https://github.com/netbox-community/netbox/issues/864) person that had this problem ended up upgrading pip and setuptools, and then updated the requirements again.

I would try uninstalling lxml and make sure that it was gone.  Then install it again.
