### ISSUE TITLE
python3 sherlock.py

### ISSUE THREAD

**Issue by Krishnazy** [sherlock-project/sherlock#349]
python3 sherlock.py
Traceback (most recent call last):                           File "sherlock.py", line 24, in <module>
    from requests_futures.sessions import FuturesSession   ModuleNotFoundError: No module named 'requests_futures'

_Originally posted by @Krishnazy in https://github.com/sherlock-project/sherlock/issues/243#issuecomment-552005002_

**Comment by hoadlck** [comment]
This is an issue with your environment, not Sherlock itself.  Did you try any of the suggestions in the other thread?
