### ISSUE TITLE
Getting several syntax errors when trying to open sherlock.py

### ISSUE THREAD

**Issue by MeowDieKatze** [sherlock-project/sherlock#352]
kilian@R61i:~/sherlock$ python3 sherlock.py -h
  File "sherlock.py", line 66
    Fore.GREEN + f"] {title}" +
                            ^
SyntaxError: invalid syntax

**Comment by MeowDieKatze** [comment]
[http://i.imgur.com/INRPO6Z.png](url)
Screenshot cause ^ not accurate.

**Comment by sdushantha** [comment]
@MeowDieKatze Which python version are you using? You have to use Python3.6 or above for Sherlock to work.

**Comment by MeowDieKatze** [comment]
kilian@R61i:~/sherlock$ python -V
Python 2.7.12
kilian@R61i:~/sherlock$ python2 -V
Python 2.7.12
kilian@R61i:~/sherlock$ python3 -V
Python 3.5.2
kilian@R61i:~/sherlock$ python3.6 -V
Python 3.6.8
kilian@R61i:~/sherlock$ python3.6 sherlock.py -h
Traceback (most recent call last):
  File "sherlock.py", line 22, in <module>
    from colorama import Fore, Style, init
ModuleNotFoundError: No module named 'colorama'
kilian@R61i:~/sherlock$

**Comment by MeowDieKatze** [comment]
<a href="http://i.imgur.com/17fTyCq.png">
  <img src="http://imgur.com/17fTyCql.png" />
</a>

**Comment by MeowDieKatze** [comment]
and this is my OS info:

<a href="http://i.imgur.com/2Urhcuq.png">
  <img src="http://imgur.com/2Urhcuql.png" />
</a>

**Comment by sdushantha** [comment]
![Screenshot 2019-11-11 at 17 59 36](https://user-images.githubusercontent.com/27065646/68605631-0bad9500-04ad-11ea-82d4-c750c9c8677f.png)
@MeowDieKatze  You are missing `colorama`. Try this:
```
pip3 install -r requirements.txt
```

Or this:
```
python3 -m pip install -r requirements.txt
```
