### ISSUE TITLE
Make Sherlock Available On PyPi

### ISSUE THREAD

**Issue by ghost** [sherlock-project/sherlock#353]
Hi,

Would be nice to use the awesome project Sherlock as a library and document it ...

Cheers,
X

**Comment by hoadlck** [comment]
Yes, it would.  There is work ongoing to update Sherlock so that it can be packaged like a normal Python module.  This will allow it to be placed on PyPi.  But, it is not done yet.

**Comment by x0rzkov** [comment]
Here is a good example of modularity https://github.com/iojw/socialscan

I started to do it https://github.com/x0rzkov/sherlock but it sounds that you are further in the task.

Do you need some help ?

Cheers,
X

**Comment by hoadlck** [comment]
Umm... What is this technique that you are using with socialscan?  100% accurate?  Sherlock has always been fragile in its detection of usernames.  If you have a technique that is better, this could change everything!

**Comment by x0rzkov** [comment]
Yes, I agree with you, both are fragiles.... I worked on golang version of sherklock, https://github.com/tdh8316/Investigo, and false-positives are high. It was just to put you this repo to awareness... When do you think the refactoring gonna be ready ?

**Comment by hoadlck** [comment]
I might have something by the end of the month.  Thanksgiving should give me some time to concentrate on this...it is hard to find time with work.

**Comment by yhay81** [comment]
Are there any updates or outlook for this issue?

**Comment by yhay81** [comment]
@hoadlck @sdushantha
If I would make PRs for this, do you think you have time to check it?
I know there are many concerns about maintaining because you seems busy.
Or shall I fork this repo and release as another project on MIT license?

**Comment by fharper** [comment]
Sorry to ask, but any plans for that?

**Comment by sdushantha** [comment]
I am currently developing a newer version of Sherlock that will be modular so that it can be available on PyPi, have an Python and web API and possibly a web interface. Therefore I will be closing this as this is not something I will be doing with the current version of Sherlock
