### ISSUE TITLE
False positive for MeetMe

### ISSUE THREAD

**Issue by Alar31000** [sherlock-project/sherlock#354]
I checked with fake names and everytime it says that there is an existing profile. They have changed their website. It's meet.me not meetme.com !

**Comment by hoadlck** [comment]
You are going to have to provide some details.

When I try to connect to meet.me, I get a warning about the certificate not matching.  The certificate does say meetme.com.  Even when I go thru to meet.me, I get a re-direct to meetme.com.  So, I don't think that their website has changed.

As far as detection goes, the site is working for the tests.  Username `blue` is found, while `noonewouldeverusethis7` is not.  I tried some other random usernames, and those are detected properly.

We have seen problems with different geographic areas.  Not sure if that is what is going on.  Or, perhaps there is something about your environment?

**Comment by Alar31000** [comment]
![20191113_065855](https://user-images.githubusercontent.com/46691211/68762082-73fe9280-05e3-11ea-94fb-d20b204b0d69.jpg)
![20191113_065322](https://user-images.githubusercontent.com/46691211/68762109-7fea5480-05e3-11ea-9013-06feb6b72f65.jpg)
![20191113_065728](https://user-images.githubusercontent.com/46691211/68762154-9db7b980-05e3-11ea-8ac7-1590761ca942.jpg)
![20191113_065128](https://user-images.githubusercontent.com/46691211/68762218-bc1db500-05e3-11ea-957e-f0ee4c52d118.jpg)

**Comment by Alar31000** [comment]
Here are my tests ! Let me know what you think ? I checked the "oktsetset1241123" username twice with different results !! Without mentioning the other fake users that gave me a fake positive.

**Comment by hoadlck** [comment]
I tried `oktsetset1241123` 4 times while looking scanning all of the sites.  Every time Sherlock reported that the username did not exist.  I also tried doing a query for just the MeetMe site like the following:
```python -u sherlock.py --site meetme oktsetset1241123```
I probably did that 20 times, and it was always good.

Try the following command:
```python3 -u sherlock.py --site meetme oktsetset1241123 --csv```
This will generate a csv file called `oktsetset1241123.csv`.  What do you see for the response time and the http_status?

What is your network situation?  I am guessing that something is being blocked or is getting in the way.

**Comment by Alar31000** [comment]
On first try it says the following "username,name,url_main,url_user,exists,http_status,response_time_ms
Oktsetset1241123,MeetMe,https://www.meetme.com/,https://www.meetme.com/Oktsetset1241123,yes,200,385"

**Comment by Alar31000** [comment]
On second try it says the following "username,name,url_main,url_user,exists,http_status,response_time_ms
oktsetset1241123,MeetMe,https://www.meetme.com/,https://www.meetme.com/oktsetset1241123,no,302,270" so http status is 302 and response time is 270. So why when i write the first character in uppercase it gives me a false positive ? Otherwise it says that it's not found !

**Comment by hoadlck** [comment]
I think that there is something intermittent with your connection.  Something is getting in the way every once and a while.

Open up the sherlock.py file.  If you are using the latest version, insert a print statement as I show in the below screenshot (this is in the body of the main sherlock() function):

![image](https://user-images.githubusercontent.com/1666888/68860676-9d84f000-06af-11ea-9260-0af8068ed3f7.png)
This alteration will print out the information coming from the response.

Run the command
``` python3 -u sherlock.py --site meetme oktsetset1241123 --csv```
over and over.  We are looking for what the text is when you get a 200 response.

I am suspicious that your ISP may be inserting some web page instead of the true result from the request.  It does not make much sense that the site would be returning a 200 status for you, but not for me.

**Comment by Alar31000** [comment]
When i added the code ! It gave an indentation error of some sort ! So what you can do is to try with a fake username with the first letter on uppercase !! Try "Oktsetset1241123" Instead of trying "oktsetset1241123" . Thank you 😊

**Comment by hoadlck** [comment]
I thought that you were entering the same username and were getting different results?  But, you are actually changing the capitalization of the first letter?

Yes, their appears to be some issue with the MeetMe site where if the first character of the username is uppercase, it never finds the existing username.  You can make any other character upper case, and it finds it fine: it looks like it is only the first character that causes the problem.

I am not sure what their username rules are.  In general, I cannot think of any time where a site will care about capitalization in their usernames: they would not want to allow users to have names that were so similar.  Maybe Sherlock should always convert the username to lower case before doing the query?

This is going to take more research.

**Comment by LuisMayo** [comment]
> Yes, their appears to be some issue with the MeetMe site where if the first character of the username is uppercase, it never finds the existing username

Just to add some more info. It is actually the opposite, when the first letter is uppercase it finds the name.

``` Powershell
PS C:\Users\luism\Documents\sherlock> python3 -u sherlock.py --site meetme oktsetset1241123 --csv

[*] Checking username oktsetset1241123 on:
[-] MeetMe: Not Found!
PS C:\Users\luism\Documents\sherlock> python3 -u sherlock.py --site meetme Oktsetset1241123 --csv

[*] Checking username Oktsetset1241123 on:
[+] MeetMe: https://www.meetme.com/Oktsetset1241123

**Comment by sdushantha** [comment]
MeetMe has been removed in 087de2e
