### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by Shashank-003** [sherlock-project/sherlock#356]
Hey,

while executing the sherlock, i get following error.
Please help me out as im new to linux

```
sansforensics@siftworkstation -> ~/sherlock 
$ sudo python sherlock.py --help
Traceback (most recent call last):
  File "sherlock.py", line 21, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "sherlock.py", line 21, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by sdushantha** [comment]
@Shashank-003 It looks like you are missing the dependency `requests`.
Have you installed all the dependencies? If not, run this command:
```bash
sansforensics@siftworkstation -> ~/sherlock 
$ python3 -m pip install -r requirements.txt
```
This should install all the dependencies that is needed for Sherlock to work properly.

If that does not fix your problem, and you are using Kali Linux, Ubuntu, Debian or a Linux distribution that uses `apt` as it's package manager, you should try to reinstall `apt_pkg` by running the command below:

```
sansforensics@siftworkstation -> ~/sherlock 
$ sudo apt install --reinstall apt_pkg
```

Source: https://askubuntu.com/questions/480908/problem-with-update-manager-no-module-named-apt-pkg-in-ubuntu-13-10-having-i#comment1741427_1063420

Please do let me know if it work. If not, we will try to find a solution :)

**Comment by Shashank-003** [comment]
Thanks a lot, Siddharth

I have tried your suggestion. it cleared the issue but new one has arised.

$ sudo python3 sherlock.py --help
  File "sherlock.py", line 66
    Fore.GREEN + f"] {title}" +
                            ^
SyntaxError: invalid syntax

Can you let me know why this one is occuring?
                                     Regards,
                                           Shashank Borude.
                                            +91-9420427079

**Comment by sdushantha** [comment]
@Shashank-003 You are most likely getting that error because you are not using Python3.6 or higher. You **must** use Python3.6 or higher in order for Sherlock to work properly.


I think you are using Ubuntu, Kali Linux or Debian, so I would advice you to read [this](https://www.tecmint.com/install-python-in-ubuntu/) article which shows you step by step instructions on how to install Python3.6 if you do not have it installed on you computer

Article: https://www.tecmint.com/install-python-in-ubuntu/

**Comment by Shashank-003** [comment]
Dear Siddhartha

Thank you for your help. I was using python 3.5 and my pip3 was having some
issues. so updating python and reinstalling pip3 solve the problems. Thanks
a lot.
                                     Regards,
                                           Shashank Borude.
                                            +91-9420427079

**Comment by sdushantha** [comment]
No worries :)
