### ISSUE TITLE
Change/Disable Colours

### ISSUE THREAD

**Issue by tautology0** [sherlock-project/sherlock#358]
For those of us who don't use dark terminals (because white text on black leaves visual after images if you're astigmatic) the colours make the output impossible to see.

Can we have a switch to change the colours or disable them rather than them being hardwired?

**Comment by sdushantha** [comment]
> Can we have a switch to change the colours

@tautology0 This seems like a very good idea. @hoadlck also mentioned a while back that it would be nice to remove the colors

**Comment by Scoder12** [comment]
I can work on this

**Comment by Scoder12** [comment]
Added this in #463

**Comment by sdushantha** [comment]
Closing this issue as it has been fixed in #463 by @Scoder12 :)
