### ISSUE TITLE
demo link in readme.md

### ISSUE THREAD

**Issue by Niagara1000** [sherlock-project/sherlock#359]
In the readme.md file , when I click on the Demo link, a message pops up saying that it is not a secure connection and that criminals might steal information. Anyone else have this issue ?

**Comment by hoadlck** [comment]
Their SSL certificate expired on 2019-11-23.  They are using Let's Encrypt, but they must not have set up the cron job that automatically renews it.

I am not sure what to do with this.  If they don't renew the certificate somewhat soon, we should probably remove the link.

@FlorianDietz You added the link to elody.com originally.  Do you know what is up with the site?

**Comment by dpieski** [comment]
@hoadlck You can close now. They have a new cert as of 2019-11-24.
