### ISSUE TITLE
ERROR: Cannot uninstall 'stem'.

### ISSUE THREAD

**Issue by demonshead** [sherlock-project/sherlock#360]
Found existing installation: stem 1.6.0
ERROR: Cannot uninstall 'stem'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by hoadlck** [comment]
What does this have to do with Sherlock?  It sounds like some issue with your environment.

I would try StackOverflow.  I found this question that may be similar: [PIP: “Cannot uninstall 'ipython'. It is a distutils installed project and thus we cannot accurately determine…”](https://stackoverflow.com/questions/50421287/pip-cannot-uninstall-ipython-it-is-a-distutils-installed-project-and-thus-w)

**Comment by sdushantha** [comment]
Closing this because it has nothing do with Sherlock

**Comment by peaceful-asura** [comment]
> Found existing installation: stem 1.6.0
> ERROR: Cannot uninstall 'stem'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

open a new terminal 
type: sudo apt-get install python-stem

If the result is : Package python-stem is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-stem

Then type: 
sudo apt-install python3-stem 

It will solve your problem.
