### ISSUE TITLE
macOS invalid JSON loaded from file?

### ISSUE THREAD

**Issue by alt-romes** [sherlock-project/sherlock#380]
<img width="735" alt="Screenshot 2019-11-30 at 21 30 25" src="https://user-images.githubusercontent.com/21295306/69906259-a61c3c80-13b8-11ea-9ab3-f5fc86aafe0a.png">

**Comment by hoadlck** [comment]
There were some regular expression checks for Twitter and Instagram that were added on master which had a bad format.  They made the JSON invalid.

I just remove the entries for now and pushed that onto master.  The change that was added needs to be tested before it is merged in.
