### ISSUE TITLE
Bad Json? No len?

### ISSUE THREAD

**Issue by krionical** [sherlock-project/sherlock#382]
Fails on arch linux derivative with the following:

sudo python3 sherlock.py user123
Traceback (most recent call last):
  File "sherlock.py", line 612, in <module>
    main()
  File "sherlock.py", line 575, in main
    results = sherlock(username, site_data, verbose=args.verbose,
  File "sherlock.py", line 168, in sherlock
    executor = ThreadPoolExecutor(max_workers=len(site_data))
TypeError: object of type 'NoneType' has no len()

**Comment by hoadlck** [comment]
There were some regular expression checks for Twitter and Instagram that were added on master which had a bad format.  They made the JSON invalid.

I just remove the entries for now and pushed that onto master.  The change that was added needs to be tested before it is merged in.
