### ISSUE TITLE
Username checks on Flightradar24 returns false positves

### ISSUE THREAD

**Issue by LameLemon** [sherlock-project/sherlock#388]
Usernames that result in a false positive:
* with a dot (.) - e.g. "jeb.brooks" (#371 )
* longer than 20 characters ending with a number e.g. "abcdefghijklmsnopqrt7"

I am unable to find a way to register a specific username on their website nor can find a source on what username limitations they check for. If I do I'll update this issue and work on a regex check.

**Comment by roopeshvs** [comment]
@sdushantha 
I think this was fixed at some point and not closed?

**Comment by sdushantha** [comment]
@roopeshvs Ah okay thanks for letting me know 👍
