### ISSUE TITLE
 Add search "chess.com"

### ISSUE THREAD

**Issue by torerobo** [sherlock-project/sherlock#391]
```
  "Chess": {
    "errorMsg": "Missing page... somebody made a wrong move.",
    "errorType": "message",
    "rank": 539,
    "url": "https://www.chess.com/ru/member/{}",
    "urlMain": "https://www.chess.com/ru/",
    "username_claimed": "blue",
    "username_unclaimed": "noonewouldeverusethis7"
  }
}
```

**Comment by sdushantha** [comment]
@torerobo Since you have already put together the JSON data, could you make a PR instead of creating an issue?

Also, make sure you have tested that they your error checking returns the correct results.

Thanks :)

**Comment by torerobo** [comment]
> @torerobo Since you have already put together the JSON data, could you make a PR instead of creating an issue?
> 
> Also, make sure you have tested that they your error checking returns the correct results.
> 
> Thanks :)

1. Yes, I checked the results, everything is fine.  
2. I'm new to Github, alas, I won’t figure out (I have a Termux smartphone) how to create a "PR".

**Comment by sdushantha** [comment]
@torerobo No problem I can do it my self and thank you for adding putting together the JSON data 👍
