### ISSUE TITLE
Sites with false positives when searching for a nickname.

### ISSUE THREAD

**Issue by torerobo** [sherlock-project/sherlock#392]
Bad.

https://www.producthunt.com/

https://www.gumroad.com/

https://virgool.io/

https://www.wattpad.com/

https://basecamphq.com

https://buymeacoff.ee/

https://repl.it/

https://vsco.co/

UPD: Perhaps the main reason, my user agent is Termux / RU.  Check for a short time.

**Comment by ndtreviv** [comment]
Add imgur to this. It returns a blank profile page if the name doesn't actually return a positive result, and that blank page is picked up as a false positive by the checker.

**Comment by sdushantha** [comment]
I believe these false positives have been fixed.
