### ISSUE TITLE
Add search "my_mail.ru"

### ISSUE THREAD

**Issue by torerobo** [sherlock-project/sherlock#411]
https://my.mail.ru/list/nick/
*nick - any nickname

Alexa Rank 55.

**Comment by Czechball** [comment]
I noticed that you can check the usernames also under /mail, such as:

https://my.mail.ru/mail/nick/

However, these are different than from /list:

https://my.mail.ru/list/nick/

How does this work? Are there multiple "areas" of users?

**Comment by torerobo** [comment]
Yes, these are "several areas" that belong to the same portal "mail.ru".  For example, mail, games, news - one nickname.  Work, hobbies, etc. - is another nickname (usually this is one person).

**Comment by torerobo** [comment]
![1](https://user-images.githubusercontent.com/35532898/71268208-77f99f00-235d-11ea-9281-616d0ede86fe.png)

![2](https://user-images.githubusercontent.com/35532898/71268594-5cdb5f00-235e-11ea-9051-e27d65f1fb59.png)

```
  "my.mail.ru_old": {
    "errorMsg": "Предложить создать Мир",
    "errorType": "message",
    "rank": 54,
    "url": "https://my.mail.ru/list/{}",
    "urlMain": "https://my.mail.ru/",
    "username_claimed": "nickname",
    "username_unclaimed": "noonewouldeverusethis7"
  },
  "my.mail.ru_new": {
    "errorMsg": "Предложить создать Мир",
    "errorType": "message",
    "rank": 54,
    "url": "https://my.mail.ru/mail/{}",
    "urlMain": "https://my.mail.ru/",
    "username_claimed": "nickname",
    "username_unclaimed": "noonewouldeverusethis7"
  },  
```
Please add to Sherlock

**Comment by sdushantha** [comment]
I appreciate the work you put into the research, but f you have found the correct data that is needed to be added to our `data.json` please create a PR instead.
