### ISSUE TITLE
Adding Strava and StravaClub

### ISSUE THREAD

**Issue by Thomas-Smyth** [sherlock-project/sherlock#413]
I have been looking into adding [Strava](https://www.strava.com/), a social media site for runners, cyclists, rowers, etc., to the site lists, however, the current detection methods seem to be insufficient and therefore if the addition is to be made then a further discussion on how it can be implemented is required.

Strava has vanity URLs that can be used to find users, for example, mine is `https://www.strava.com/athletes/thomassmyth3141`. However, when a vanity URL is used a `301` redirect is used to redirect to my non-vanity URL, in my case `https://www.strava.com/athletes/37350156`, which has a `200` status code.

When an invalid vanity URL is used, for example, `https://www.strava.com/athletes/thomassmyth3142`, a `302` redirect is used to redirect to the Strava home page `https://www.strava.com/`, which also has a `200` status code.

Note the behaviour differs when you're logged in, so if you're testing this make sure you logout first!

Similar behaviour exists for Strava Clubs.

**Using the current detection methods:**
 * **HTTP Status** - This detection method follows redirects, so in either case, the status code is `200` and therefore cannot be used to detect whether a username exists.
 * **Response URL** - This detection method does not follow redirects, however, it only deems a URL valid if the status code is within the range `200 <= r.status_code < 300`, which is false in either case and therefore cannot be used to detect whether a username exists.
 * **Error Message** - No suitable error message is displayed when not logged in and therefore this method cannot be used to detect whether a username exists.

I think the best solution would be to implement into the Response URL detection method to allow the `data.json` file to specify specific status codes to look for in order to deem the page valid or not and hence whether the username exists. 

What are other's thoughts on the matter?

**Comment by realprogrammer5000** [comment]
The string `By signing up for Strava, you agree to the <a href='/legal/terms'>Terms of Service</a>.` seems to work as an error message.

```bash
$ curl -s -L https://www.strava.com/athletes/noonewouldeverusethis7 | grep "By signing up for Strava, you agree to the <a href='/legal/terms'>Terms of Service</a>."
By signing up for Strava, you agree to the <a href='/legal/terms'>Terms of Service</a>.
$ curl -s -L https://www.strava.com/athletes/thomassmyth3141 | grep "By signing up for Strava, you agree to the <a href='/legal/terms'>Terms of Service</a>."
```

**Comment by roopeshvs** [comment]
@sdushantha 
Think we should close this. StravaClub seems to be working with Strava usernames only.
