### ISSUE TITLE
Add search "Audiojungle"

### ISSUE THREAD

**Issue by torerobo** [sherlock-project/sherlock#419]
```
  "Audiojungle": {
    "errorType": "status_code",
    "rank": 4533,
    "url": "https://audiojungle.net/user/{}",
    "urlMain": "https://audiojungle.net/",
    "username_claimed": "blue",
    "username_unclaimed": "noonewouldeverusethis7"
  },
```

**Comment by torerobo** [comment]
I noticed that through **Tor** (Orbot / Android) this site returned the real nickname “**Not Found**”, and not “error”.  Perhaps some added Internet resources skip real nicknames due to the use of Tor.  Usually, if the site is not friends with Tor, a "connection error".  Maybe such information should be added to the **wiki**?

**Comment by Czechball** [comment]
I just tested the username checking through regular Tor browser on Windows as well as the -t option in Sherlock. Both are working fine.

**Comment by torerobo** [comment]
What does it mean that it’s working fine?  If there is no access to the site, usually returns "error".  In a specific example: Termux / Orbot / output node Spain / "Not Found!"
