### ISSUE TITLE
Sherlock long work when the site is inaccessible

### ISSUE THREAD

**Issue by torerobo** [sherlock-project/sherlock#430]
My ISP is blocking access to the "pling" site (I think this is the case for the entire location ru).

Because of this, Sherlock is slow: the delay due to stumbling on the pling site is 5-7 minutes - unacceptable.
Also in ru location, the Internet provider blocks "telegram", however, sherlock quickly gives an "error" and run further.

The simplest solution is to remove the site from "data.json", sherlock works for less than a minute.  But in the future, the addition of such sites is possible, which makes sherlock clumsy.  Perhaps in the check suite algorithm, you should add "response delay time from the site = X sec", there is no answer to give an "error" and run further.

log sherlock/termux "pling"
```
Error Connecting: HTTPSConnectionPool(host='www.pling.com', port=443): Max retries exceeded with url: /u/pumbo/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xa1c14710>: Failed to establish a new connection: [Errno 110] Connection timed out'))
[-] Pling: Error!
```
It seems to me worthy of discussion.

**Comment by hoadlck** [comment]
Pull request #403 has added a timeout to avoid the long delay.  But, I have not examined it.

In the end, I do not think that we should include sites that have such horrible performance.  It does no one any good to have sites that no one is interested in slowing down interesting results.

There is a point where it is just not valuable to have results from every site.  Some users are not going to care.  We may be beyond that point now.  The sites that Sherlock tracks needs to have tags to allow the user to narrow their focus (e.g. popular, books, video, sports, news, ...).

I am just trying to get thru the restructure so we will be in a better place to add more fundamental features.

**Comment by torerobo** [comment]
Yes, the patch works successfully.  I confirm.
