### ISSUE TITLE
wikidot always responds as found

### ISSUE THREAD

**Issue by Jan200101** [sherlock-project/sherlock#431]
I've tested sherlock with various names and found that wikidot is always shown to have an account with those names even if they do not exist

**Comment by torerobo** [comment]
I also drew attention to this, for example, YandexMarket almost always gives out "found" on a nonexistent nickname.  However, if you do not change anything, then YandexMarket on the same nonexistent nickname will give out "not found".  Perhaps the site always behaves differently.

**Comment by LameLemon** [comment]
Wikidot works as expected for me, below is a list of usernames I tried both found and not found.
```
blue: Found
jenny: Found
peskypotato: Not Found
noonewouldusethis7: Not Found
lamelemon: Not Found
```

Which usernames did you find give false positives so I can test them out. Thanks : )

**Comment by Jan200101** [comment]
testing was done on 35e8dd97e630740243661fd83a22da23f9376428
Originally when making this Issue it happened like stated before
`
[+] Wikidot: http://www.wikidot.com/user:info/radiden
`
a account is stated to exit when it doesn't
now that behavior seems to have reverted to how its intended without a change, perhaps
`
[-] Wikidot: Not Found!
`
I do not know what changed but I piped 7 other attempts into files and can confirm all of them are shown to have a WikiDot account so its not just something name specfic

I'll append to this issue if I find what caused it
