### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by AL3INO** [sherlock-project/sherlock#443]
Everything was working fine on the previous build, now that I have upgraded I am receiving this error - `
Traceback (most recent call last):
  File "sherlock.py", line 649, in <module>
    main()
  File "sherlock.py", line 613, in main
    timeout=args.timeout)
  File "sherlock.py", line 255, in sherlock
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/requests_futures/sessions.py", line 138, in head
    return super(FuturesSession, self).head(url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 568, in head
    return self.request('HEAD', url, **kwargs)
  File "sherlock.py", line 59, in request
    return super(ElapsedFuturesSession, self).request(method, url, hooks=hooks, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests_futures/sessions.py", line 105, in request
    return self.executor.submit(func, *args, **kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 160, in submit
    self._adjust_thread_count()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 181, in _adjust_thread_count
    t.start()
  File "/usr/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread`

**Comment by hoadlck** [comment]
I am thinking that the naive way that Sherlock spawns a thread for all sites at the beginning of the query is overwhelming some people's computers. We now have enough sites that we are hitting this limit for a larger set of users.  This is probably the same problem noticed in #323. 

This is something I am working on in the restructuring.

Could you try removing many of the entries in the data.json?  A smaller number of sites means less threads.

**Comment by AL3INO** [comment]
> I am thinking that the naive way that Sherlock spawns a thread for all sites at the beginning of the query is overwhelming some people's computers. We now have enough sites that we are hitting this limit for a larger set of users. This is probably the same problem noticed in #323.
> 
> This is something I am working on in the restructuring.
> 
> Could you try removing many of the entries in the data.json? A smaller number of sites means less threads.

Ahh okay, that makes sense. I added a couple of my own sites, which is probably causing my Rasperry Pi to wig out. I will remove them for now, how long do you think it will take to solve this issue?

cheers

**Comment by hoadlck** [comment]
Well...it won't take long, but I am tied up with my regular job.  I should have enough time over Christmas Holiday.

**Comment by MinePro120** [comment]
#323 was resolved and closed.

**Comment by AL3INO** [comment]
> Well...it won't take long, but I am tied up with my regular job. I should have enough time over Christmas Holiday.

Hey man, do you have any update on this? 

Merry Christmas :’)

**Comment by hoadlck** [comment]
Can you try it now with the latest content on master (version 0.10.0)?  In #471, I placed a limit on the number of threads that can be allocated.  And, it did not seem to make any difference on performance.

**Comment by AL3INO** [comment]
> Can you try it now with the latest content on master (version 0.10.0)? In #471, I placed a limit on the number of threads that can be allocated. And, it did not seem to make any difference on performance.

It works great, thanks!
I'm surprised it has no effect on performance - my pi can run a full scan in 45 seconds now, though I hadn't timed it previously.

**Comment by hoadlck** [comment]
It is a Christmas miracle! :-) 

Well...actually, I guess it is not that surprising.  Trying to spawn so many threads ends up using too many resources.  Which can end up causing a given thread to be even slower than normal.  On my Windows 10 PC, there were some sites that did not detect usernames under the old version: Sherlock found more sites with a harder limit of threads.

Unfortunately, the tests invoke Sherlock with a limited number of sites multiple times.  So, an individual test never spawned so many threads at one time...they were spread out over multiple invocations to cover the entire list.  While it was fine for functionality, it missed this case.
