### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by YOCE19** [sherlock-project/sherlock#447]
![Screen Shot 2019-12-12 at 9 44 31 PM](https://user-images.githubusercontent.com/58838309/70781992-621b2700-1d2a-11ea-92b1-421b4d0dc435.png)

Sorry ahead of time if this post doesn't belong here. Sherlock worked perfect for me last night but today I got this error at the end. Im guessing its environmental but can anyone tell what I might be doing wrong? I've been searching non stop all day trying to figure it out so I'm posting this as my last resort. Any help would be greatly appreciated. Thanks in advance.

**Comment by Vincentimetr** [comment]
Hello, I got the same error:

`vince@DESKTOP-VJRUP2I:~/sherlock$ python3 sherlock.py Vincentimetr

[*] Checking username Vincentimetr on:
[-] ResearchGate: Illegal Username Format For This Site!
Traceback (most recent call last):
  File "sherlock.py", line 649, in <module>
    main()
  File "sherlock.py", line 613, in main
    timeout=args.timeout)
  File "sherlock.py", line 229, in sherlock
    if net_info["errorType"] == 'status_code':
KeyError: 'errorType'
`

**Comment by boschhd** [comment]
There is an error in the data.json. Search for an additional space `" errorType"` and remove the space

**Comment by Vincentimetr** [comment]
Thank you, line 2125 @YOCE19
