### ISSUE TITLE
Running into exceptions midway

### ISSUE THREAD

**Issue by anshumanv** [sherlock-project/sherlock#450]
Running into these exceptions midway of the execution, also verified that I own `anshumanv` on about.me but it still shows Not Found, did I miss anything?

![image](https://user-images.githubusercontent.com/21009455/70858770-6021b580-1f2e-11ea-8566-d6bf7c4b84b6.png)

**Comment by sdushantha** [comment]
@anshumanv Hmmm...strange, I just ran Sherlock with `anshumanv` and had no errors. I am pretty sure it has to be something with your environment.

Also, could you please create a seperate issue about the false positive on about.me?
