### ISSUE TITLE
File "sherlock.py", line 24, in <module>     from requests_futures.sessions import FuturesSession ModuleNotFoundError: No module named 'requests_futures'

### ISSUE THREAD

**Issue by jzr54732** [sherlock-project/sherlock#462]
File "sherlock.py", line 24, in <module>
    from requests_futures.sessions import FuturesSession
ModuleNotFoundError: No module named 'requests_futures'

**Comment by sdushantha** [comment]
@jzr54732 Have you made sure that you have installed all the needed dependencies?
Run the command below to install all the needed dependencies:
```
python3 -m pip install -r requirements.txt
```

**Comment by luger19** [comment]
I had the same problem and `sudo python3 -m pip install -r requirements.txt` worked for me. You can try `sudo pip3 install requests_futures` as well.

**Comment by sdushantha** [comment]
@luger19 I advice you not to install python packages with `sudo`.
Source: https://askubuntu.com/a/802594

**Comment by ArbitCode** [comment]
@sdushantha
it works perfectly after installing needed dependencies.
python3 -m pip install -r requirements.txt

**Comment by on1yyou** [comment]
python3 -m pip install -r requirements.txt  worked fine. thank you :)

**Comment by und3fined404** [comment]
# python3 -m pip install -r requirements.txt
/usr/bin/python3: No module named pip

**Comment by Petraconsulting** [comment]
I had a similar issue I did the following and it worked:
pip install --upgrade pip 
python3.8 sherlock.py --help

for some I was receiving an error that my pip was 8.0.1 even though I had pip 20.0, but upgrade seemed to fix the problem.  Also, instead of merely using 'python3' I used 'python3.8' which is the latest version I have installed in addition to python2.7.  Hope that helps!!

**Comment by fixitfeelex** [comment]
> @jzr54732 Have you made sure that you have installed all the needed dependencies?
> Run the command below to install all the needed dependencies:
> 
> ```
> python3 -m pip install -r requirements.txt
> ```

I have tried that and gotten this /usr/local/bin/python3: No module named pip
and I am using Kali Linux.

**Comment by sdushantha** [comment]
@fixitfeelex Looks like you need to install `pip`. You can easily do that by running this command:
```bash
sudo apt install python3-pip
```

**Comment by fixitfeelex** [comment]
> @fixitfeelex Looks like you need to install `pip`. You can easily do that by running this command:
> 
> ```shell
> sudo apt install python3-pip
> ```

I have tried that but, I get this 

```shell
Unable to locate package python3-pip
```
I am now trying to use Ubuntu because Kali Linux wouldn't work. Sorry if this causes misunderstanding or any trouble.

**Comment by sdushantha** [comment]
@fixitfeelex This might help you, https://askubuntu.com/a/1061488/782646
Also check the comment of that answer ^^

**Comment by fixitfeelex** [comment]
> @fixitfeelex This might help you, https://askubuntu.com/a/1061488/782646
> Also check the comment of that answer ^^

I have figured it out, thank you very much. I have a question, did you develop this? I went to Null Byte for help but that didn't work at that time but I think I saw you in the comments?

**Comment by sdushantha** [comment]
@fixitfeelex Yup, I did indeed create Sherlock, but with the help of @hoadlck and many other developers, we were able to improve it with many features :)

**Comment by fixitfeelex** [comment]
> @fixitfeelex Yup, I did indeed create Sherlock, but with the help of @hoadlck and many other developers, we were able to improve it with many features :)

This software is very amazing, you did very well. Thank you.

**Comment by fixitfeelex** [comment]
> @fixitfeelex Yup, I did indeed create Sherlock, but with the help of @hoadlck and many other developers, we were able to improve it with many features :)

Null Byte used whois, I need to install that I'm guessing?

**Comment by sdushantha** [comment]
@fixitfeelex Hmmm...thats strange. `whois` is not needed for Sherlock to work

**Comment by fixitfeelex** [comment]
> @fixitfeelex Hmmm...thats strange. `whois` is not needed for Sherlock to work

He did not use it in the sherlock directory, he used it to search information on something. Can I use sherlock to do that without whois installed?

**Comment by sdushantha** [comment]
@fixitfeelex The `whois` command that he uses is used to get info about the site which the user uses. Sherlock does not do this. So this means who you have to install the command `whois` do get this information.

**Comment by fixitfeelex** [comment]
> @fixitfeelex The `whois` command that he uses is used to get info about the site which the user uses. Sherlock does not do this. So this means who you have to install the command `whois` do get this information.

Since I can look up accounts with sherlock, what can I do with the found accounts?

**Comment by sdushantha** [comment]
@fixitfeelex You can learn about the user's interests, style of writing, where they are from, info about family, etc.

You can do many things with type of information. If you are trying to find a missing person, then this can lead you up to clues. Or if you trying to so social engineer someone, then you can use this info to trick them multiple ways.

In the end of the day, be careful and make sure you use this information for ethical purposes :)

**Comment by fixitfeelex** [comment]
> @fixitfeelex You can learn about the user's interests, style of writing, where they are from, info about family, etc.
> 
> You can do many things with type of information. If you are trying to find a missing person, then this can lead you up to clues. Or if you trying to so social engineer someone, then you can use this info to trick them multiple ways.
> 
> In the end of the day, be careful and make sure you use this information for ethical purposes :)

It won't load past "HackerRank" any reason why?

**Comment by ac3mcl0ud** [comment]
I was able to fix this with this video tutorial
http://bit.ly/2UfCYHE

**Comment by grahulprouhit** [comment]
python3 -m pip install -r requirements.txt when i use this cmmd thet show me
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
wat to do ? how to fix this

**Comment by sdushantha** [comment]
@grahulprouhit Make sure that you change your directory to the sherlock folder first.
```
cd sherlock
```
Then run the command you previously ran:
```
python3 -m pip install -r requirements.txt
```

**Comment by Enimassej** [comment]
> I had the same problem and `sudo python3 -m pip install -r requirements.txt` worked for me. You can try `sudo pip3 install requests_futures` as well.

sudo python3 -m pip install -r requirements.txt  >> This one works for me. Thanks!
