### ISSUE TITLE
File "sherlock.py", line 22, in <module>     from colorama import Fore, Style, init ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by ArbitCode** [sherlock-project/sherlock#468]
while executing by "python3 sherlock.py --help" there shows an error. 
![Screenshot from 2019-12-21 17-46-32](https://user-images.githubusercontent.com/35590355/71307873-95407300-241a-11ea-8075-242c4312224c.png)

**Comment by sdushantha** [comment]
@ArbitCode Are you sure you have installed all the needed dependencies? Because it looks like you have not installed `colorama`. 
Run this command:
```
python3 -m pip install --user -r requirements.txt
```

If the command above did not fix the issue, try running:
```
python3 -m pip install --user colorama
```

**Comment by ArbitCode** [comment]
thank you,sir
