### ISSUE TITLE
Excessive CPU Usage

### ISSUE THREAD

**Issue by 0xAL3INO** [sherlock-project/sherlock#474]
Hey mate. 

Is there any way I can limit the CPU power used by the script? 

I am running on a raspberry pi 3 B+, and running 3 scans simultaneously maxes out my CPU to 100%. I need to reduce this, even if it means the scans will take a longer time.

Cheers

**Comment by hoadlck** [comment]
When doing the change to limit the number of threads, I was thinking that it would be better to adjust the maximum number based on the computer's capabilities.  But, I am not quite sure how to do that calculation.  The `requests-futures` module allocates 8 workers by default.  And, in any case, I have been concentrating on the restructuring.

Could you try changing the number of workers in Sherlock, and see how that behaves?  Just look in the main Python file for the variable `max_workers` (In the current release, it is located [here](https://github.com/sherlock-project/sherlock/blob/master/sherlock.py#L195)).  Change the 20 to something lower, and see how acceptable it is.

If this works out, then perhaps we can do more research to figure out good algorithm to calculate `max_workers` based on the computer capabilities.  Or, perhaps we can just add a new command line option so the user has control.

**Comment by AL3INO** [comment]
> 
> 
> When doing the change to limit the number of threads, I was thinking that it would be better to adjust the maximum number based on the computer's capabilities. But, I am not quite sure how to do that calculation. The `requests-futures` module allocates 8 workers by default. And, in any case, I have been concentrating on the restructuring.
> 
> Could you try changing the number of workers in Sherlock, and see how that behaves? Just look in the main Python file for the variable `max_workers` (In the current release, it is located [here](https://github.com/sherlock-project/sherlock/blob/master/sherlock.py#L195)). Change the 20 to something lower, and see how acceptable it is.
> 
> If this works out, then perhaps we can do more research to figure out good algorithm to calculate `max_workers` based on the computer capabilities. Or, perhaps we can just add a new command line option so the user has control.

I have knocked the max workers down to 5. This reduces the CPU usage to about 20% per scan, and takes about 20 seconds longer. 

I am wondering if there is any ways we can improve the efficiency of the script.

**Comment by DavidVu96** [comment]
created PR https://github.com/sherlock-project/sherlock/pull/601 to fix this issue

**Comment by DavidVu96** [comment]
@AL3INO can you please check out the PR and test to see if you get better efficiency?

**Comment by sdushantha** [comment]
I am currently working on a newer version of Sherlock which will use `asyncio`. This will improve the performance of Sherlock. Since this is not in scope for the current major version of Sherlock, I will be closing this
