### ISSUE TITLE
issues with installing requirements.txt 

### ISSUE THREAD

**Issue by smfreak** [sherlock-project/sherlock#496]
I keep getting this issue when downloading the requirements

![Screen Shot 2019-12-30 at 6 20 29 AM](https://user-images.githubusercontent.com/37509422/71579952-b402d180-2acc-11ea-8134-310f9830dbde.png)

I do have python3 and pip installed

**Comment by JIGEQIU** [comment]
I also encountered the same problem

**Comment by JIGEQIU** [comment]
I also encountered the same problem,Try using "pip3 install torrequest"

**Comment by smfreak** [comment]
still having the same problem 

> I also encountered the same problem,Try using "pip3 install torrequest"

**Comment by sdushantha** [comment]
@paulodiovani

**Comment by LameLemon** [comment]
Looks like git.torproject might have been down for a while, have you tried again since then?

**Comment by liubin12345** [comment]
I also encountered the same problem, is there anyone who can solve the problem ?

**Comment by gaaaaaaavin** [comment]
I'm having the same issue too

**Comment by ristiluomasami-stack** [comment]
Close
