### ISSUE TITLE
Add option "--update" to Sherlock

### ISSUE THREAD

**Issue by torerobo** [sherlock-project/sherlock#501]
Those users who installed Sherlock in the past may not be aware of new changes / features in the updated program, including updating the data.json database, and this in turn reduces Sherlocka’s competition with other similar OSINT tools.

I suggest adding the option "**--update**".

Example.
`python3 sherlock.py --update # calls regular update.sh, which says the following.`

update.sh
```
#!/bin/bash
git clone https://github.com/sherlock-project/sherlock.git && cp -r sherlock/. . || rm -rf sherlock

```
This will automatically update sherlock and no duplicates.

**Comment by sdushantha** [comment]
After the restructuring has been done, Sherlock will be added to PyPi. So people will be able to update Sherlock using ```pip``` after that. I think I would be nice to add Sherlock to the AUR as well.

**Comment by hoadlck** [comment]
Don't forget that Sherlock already has the ability to use the latest JSON file: one can point the Sherlock installed locally at the latest version on GitHub.  For example:
```
% python -u sherlock.py --json https://raw.githubusercontent.com/sherlock-project/sherlock/master/data.json --verbose hoadlck
```
Even if you don't want to do that, you can just type
```
% git pull origin master
```
on the command line, and you will update to the latest version.

**Comment by sdushantha** [comment]
Closing this because a solution has found 👍
