### ISSUE TITLE
No module named 'requests_futures' tried everything

### ISSUE THREAD

**Issue by und3fined404** [sherlock-project/sherlock#505]
when using `python3 sherlock.py user123`

> Traceback (most recent call last):
>   File "sherlock.py", line 24, in <module>
>     from requests_futures.sessions import FuturesSession
> ModuleNotFoundError: No module named 'requests_futures'
> 

whenusing `python sherlock.py user123`

  

> File "sherlock.py", line 66
>     Fore.GREEN + f"] {title}" +
>                             ^
> SyntaxError: invalid syntax
> 

Tried `sudo python3 -m pip install -r requirements.txt`

> /usr/bin/python3: No module named pip

Then Tried `sudo python -m pip install -r requirements.txt`

> Requirement already satisfied: beautifulsoup4>=4.8.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
> Requirement already satisfied: bs4>=0.0.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
> Requirement already satisfied: certifi>=2019.6.16 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
> Requirement already satisfied: colorama>=0.4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
> Requirement already satisfied: lxml>=4.4.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
> Requirement already satisfied: PySocks>=1.7.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
> Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
> Requirement already satisfied: requests-futures>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
> Requirement already satisfied: soupsieve>=1.9.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
> Obtaining stem from git+https://git.torproject.org/stem.git@b5aecb7#egg=stem (from -r requirements.txt (line 12))
>   Skipping because already up-to-date.
> Requirement already satisfied: torrequest>=0.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
> Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/dist-packages (from requests>=2.22.0->-r requirements.txt (line 7))
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/dist-packages (from requests>=2.22.0->-r requirements.txt (line 7))
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python2.7/dist-packages (from requests>=2.22.0->-r requirements.txt (line 7))
> Requirement already satisfied: futures>=2.1.3; python_version < "3.2" in /usr/lib/python2.7/dist-packages (from requests-futures>=1.0.0->-r requirements.txt (line 8))
> Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /usr/lib/python2.7/dist-packages (from soupsieve>=1.9.2->-r requirements.txt (line 9))
> Installing collected packages: stem
>   Found existing installation: stem 1.7.1.dev0
>     Can't uninstall 'stem'. No files were found to uninstall.
>   Running setup.py develop for stem
> Successfully installed stem
> 
> 

And still same issue

**Comment by sdushantha** [comment]
@und3fined404 Please do not run with `sudo`. 
So run it like this:
```
python3 -m pip install -r requirements.txt
```

**Comment by sdushantha** [comment]
@und3fined404 I just relised that you do not have `pip`.
You first have to install `pip`. I assume you are using Ubuntu, Debian or Kali Linux, so run this command to install `pip`:
```
sudo apt-get install python3-pip
```
