### ISSUE TITLE
Issues with Sherlock

### ISSUE THREAD

**Issue by Doty43** [sherlock-project/sherlock#507]
Sorry for my English.

I'm trying to follow this steps 

https://null-byte.wonderhowto.com/how-to/hunt-down-social-media-accounts-by-usernames-with-sherlock-0196138/

I've installed python 3.8, python 3.8.1 shell, git Bash, Gui..

When I used Git Bash to run the commands, there is a moment where it says "permissions denied", exactly after i run this: python3 -m pip install -r requirements.txt

What I'm doing wrong?

**Comment by sdushantha** [comment]
@Doty43 Could you please send a screenshot or a screen recording of what is happening?

**Comment by Doty43** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/59690547/72080069-007fb580-32f4-11ea-8ad3-a14fca6a4f81.jpg)

**Comment by Doty43** [comment]
I could run it in Cloud shell, but i have to setup a virtual env to install the package colorama every time.

**Comment by sdushantha** [comment]
@Doty43 Take a look at this: https://superuser.com/a/1486383
This seems to be a known problem on Windows: https://stackoverflow.com/a/57168165

**Comment by un1que00** [comment]
I had a similar problem, so I updated/installed a couple missing libraries and that seemed to fix some problems but I still get an error message 'failed to build wheel for lxml' and things go bad after this.
libxml2 is installed and another error asks if it is installed and that there is no xmlcheckversion function in libxml2.

**Comment by sdushantha** [comment]
@un1que00 I dont use Windows, so I cant be much help, but check this out: https://stackoverflow.com/a/33785756
