### ISSUE TITLE
Add search "swimming_forum"

### ISSUE THREAD

**Issue by torerobo** [sherlock-project/sherlock#512]
```
  "swimming_forum": {
    "errorMsg": "Пользователь не найден",
    "errorType": "message",    
    "rank": 1000000,
    "url": "http://forumswimming.ru/index/8-0-{}",
    "urlMain": "http://forumswimming.ru/",
    "username_claimed": "irina",
    "username_unclaimed": "noonewouldeverusethis7"
  },
```

**Comment by sdushantha** [comment]
The reason for closing this issue can be read in PR #569 
> I wont be merging this because it has a problem with usernames with a period in them. Similar forums like the one in this PR have been mentioned in #541 and they got removed because we were not able to find the criteria for a valid username on those forums.
