### ISSUE TITLE
Feature Request: site groups to query sites that have similar purpose/are similar

### ISSUE THREAD

**Issue by aslmx** [sherlock-project/sherlock#522]
Hi,

i opened a pull request to add some Mastodon instances. In case you are not aware how mastodon works: it is federated like email.
That means, there can be multiple persons having the same username on different instances. Hence this tool is even more useful to find available names across instances. Of course there are thousands of mastodon instances, i just added the most popular that turn up in some lists (from user count perspective). 

However, i realized it might be cool if these sites could be grouped. Actually as a user I would not want to find out all possible mastodon instances that sherlock supports and then add them via the "--site" command line flag. 

I would rather want to say "check all mastodon sites".

Hence a group flag could be useful. Also for other sites that form a logical group. 

I.e. github.com and gitlab.com could be grouped (with potential other Git-as-a-service providers) into a "git" group.

It could be an optional flag in the data.json, so that it is not required for small websites that are very unique in their purpose.

I imagine that then you could simply run

python3 sherlock --group mastodon TheUserNameIWantToQuery

and it presents me the results for all Sites flagged with "mastodon" in data.json.

Maybe that would be useful :-)

**Comment by hoadlck** [comment]
Yes, I think that Sherlock needs this type of support.  But, what I envision is tag support (GitHub calls them Topics).  

The idea is that each site would have a list of tags that provide some context for what each site was about.  For example, "news", "video", "social", "picture" would be example tags.  A site like YouTube would have tags for "social" and "video", while a site like Instagram would have tags for "social" and "picture".

This allows users to focus their searches into the areas that they care about.  And it avoids the very long search time as more and more sites are added to Sherlock.

This support is one of the things that would be very natural for the website implementation of Sherlock.

But...it is one of those features that I would rather have deferred until after the restructure.  The core logic of Sherlock that determines the list of sites to query (and queues them up) has to be completely torn up.  That will make features like this one easier to implement.

I propose that we use this issue as a placeholder for this support.

**Comment by aslmx** [comment]
Great! Sounds to me like you want to implement exactly what i was thinking about :)

**Comment by sdushantha** [comment]
I am creating a new version of Sherlock which will be a complete rewrite. This version includes catagories/tags. So that you as the user can search through the categories you have specified. Since this is something I will not be adding to the current version of Sherlock I will be closing this. When I will be releasing the new version onto GitHub is unknown as there quite a lot to do
