### ISSUE TITLE
Fix "379"

### ISSUE THREAD

**Issue by torerobo** [sherlock-project/sherlock#524]
https://github.com/sherlock-project/sherlock/pull/379/commits/f2eb4d22691cefc3f60202aeaeeec1a26188a09f

 ̶"̶G̶P̶S̶i̶e̶s̶"̶:̶ ̶{̶
̶ ̶ ̶ ̶ ̶"̶e̶r̶r̶o̶r̶T̶y̶p̶e̶"̶:̶ ̶"̶m̶e̶s̶s̶a̶g̶e̶"̶,̶
̶ ̶ ̶ ̶ ̶"̶e̶r̶r̶o̶r̶M̶s̶g̶"̶:̶ ̶"̶<̶t̶i̶t̶l̶e̶>̶G̶P̶S̶i̶e̶s̶"̶,̶
̶ ̶ ̶ ̶ ̶"̶r̶a̶n̶k̶"̶:̶ ̶7̶5̶4̶8̶6̶,̶
̶ ̶ ̶ ̶ ̶"̶u̶r̶l̶"̶:̶ ̶"̶h̶t̶t̶p̶s̶:̶/̶/̶w̶w̶w̶.̶g̶p̶s̶i̶e̶s̶.̶c̶o̶m̶/̶m̶a̶p̶U̶s̶e̶r̶.̶d̶o̶?̶u̶s̶e̶r̶n̶a̶m̶e̶=̶{̶}̶"̶,̶
̶ ̶ ̶ ̶ ̶"̶u̶r̶l̶M̶a̶i̶n̶"̶:̶ ̶"̶h̶t̶t̶p̶s̶:̶/̶/̶w̶w̶w̶.̶g̶p̶s̶i̶e̶s̶.̶c̶o̶m̶/̶"̶,̶
̶ ̶ ̶ ̶ ̶"̶u̶s̶e̶r̶n̶a̶m̶e̶_̶c̶l̶a̶i̶m̶e̶d̶"̶:̶ ̶"̶b̶l̶u̶e̶"̶,̶
̶ ̶ ̶ ̶ ̶"̶u̶s̶e̶r̶n̶a̶m̶e̶_̶u̶n̶c̶l̶a̶i̶m̶e̶d̶"̶:̶ ̶"̶n̶o̶o̶n̶e̶w̶o̶u̶l̶d̶e̶v̶e̶r̶u̶s̶e̶t̶h̶i̶s̶"̶

```
  "alltrails": {
    "errorType": "response_url",
    "errorUrl": "https://alltrails.com/members",
    "rank": 9682,
    "url": "https://www.alltrails.com/members/{}",
    "urlMain": "https://www.alltrails.com/",
    "username_claimed": "blue",
    "username_unclaimed": "noonewouldeverusethis7"
  },
```

**Comment by sdushantha** [comment]
Fixed :)
