### ISSUE TITLE
Pexels and Pixabay use Cloudflare

### ISSUE THREAD

**Issue by LameLemon** [sherlock-project/sherlock#528]
Both Pexels and Pixabay now use Cloudflare and I am unable to find a way around it. Tried making a request through curl with all the headers and cookie that my browser uses but still could not bypass Cloudflare. 

Both these sites currently give false negatives with Sherlock.

**Comment by hoadlck** [comment]
These sites have been removed with #556.  Thanks for reporting the problem.
