### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by avik1991** [sherlock-project/sherlock#530]
```
$ python3 sherlock.py -h
  File "sherlock.py", line 66
    Fore.GREEN + f"] {title}" +
                            ^
SyntaxError: invalid syntax
```

**Comment by LameLemon** [comment]
Hello, 

Have you cloned Sherlock straight from the master branch? Can you make sure there were no changes made locally to the code. I just fetched the latest commit and it worked for me on two different machines. 

: )

**Comment by hoadlck** [comment]
Looks like you are trying to run Sherlock with a version of Python before 3.6.  If you type, `python3 --version`, what do you get?

**Comment by PurpleViolentLocust** [comment]
> Looks like you are trying to run Sherlock with a version of Python before 3.6. If you type, `python3 --version`, what do you get?

I am getting the same error, my python version is 3.73.

**Comment by darjaallora** [comment]
I also got this error; replicates when calling "python" instead of "python3" on my home machine where "python" defaults to 2.6 even though python 3.7 is installed, for some ungodly reason.  Invoking "python3" works as expected.

**Comment by hoadlck** [comment]
Closing this out as it appears to be an install issue instead of something wrong with Sherlock.
