### ISSUE TITLE
requirements error!

### ISSUE THREAD

**Issue by RiFellz** [sherlock-project/sherlock#531]
```
root@kali:~/sherlock# python3 -m pip install -r requirements.txt
/usr/bin/python3: No module named pip
root@kali:~/sherlock# 
```

**Comment by JMS53** [comment]
> root@kali:~/sherlock# python3 -m pip install -r requirements.txt /usr/bin/python3: No module named pip root@kali:~/sherlock#

apt-get install python3-pip

**Comment by Mr1077** [comment]
Hi! I have the same issue, however, I use Manjaro Linux (based on arch) so the apt-get command won't work, do you have a solution for this that works on arch-based distros?

**Comment by JassonCordones** [comment]
I don't have a distro installed to test but if manjaro have not changed pacman as a package manager this could work:
```
pacman -Syu 
pacman -S python3-pip
```
