### ISSUE TITLE
Error while doing a phishing attack in linux using social engineering tool kit

### ISSUE THREAD

**Issue by Deepako0** [sherlock-project/sherlock#537]
I am cloning a website using social engineering toolkit.I am using ngrok to cover my ipaddress.When i did port forwarding and entering the ngrok link it is saying that ""connection from client to server is failed and make sure that website service is running on that host"".Please help me with this issue!!!!

**Comment by hoadlck** [comment]
You are doing a phishing attack? You are misusing Sherlock to do something illegal, are having problems doing your illegal action, and are asking for help?

Is this why Sherlock is so popular? Script Kiddies are using it to phish? How do you even use Sherlock to phish?

**Comment by sdushantha** [comment]
@Deepako0 Buddy...
1. I think you made an issue in the wrong GitHub repo.
2. Dont do anything illegal and don't ask for help to do something illegal because you wont be getting help.

**Comment by sdushantha** [comment]
Closing this as it is irrelevant
