### ISSUE TITLE
Web Interface?

### ISSUE THREAD

**Issue by skluthe** [sherlock-project/sherlock#540]
I'm currently putting together a scanning server that I can hit from a few different places and wanted to suggest putting together a web interface for this similar to SpiderFoot. 

It would be pretty beneficial to some users and could make adding sites easier depending on how you do things.

**Comment by hoadlck** [comment]
The restructure of Sherlock (#350) would enable one to include it like a normal Python module.  So, it can be downloaded on PyPi.

While I have made some progress, it is stalled right now.  Not enough free time after my day job...  But that development will make it easier to do what you are talking about.

**Comment by skluthe** [comment]
I've actually gotten a bit more familiar with python since I commented. Is there any way I could help?

**Comment by MilkyDeveloper** [comment]
Perhaps a better way would to be running it with a gui on heroku...

**Comment by MilkyDeveloper** [comment]
chriskiehl's Gooey is also a great option.

**Comment by JinooRoh** [comment]
Hello, i am recently joined Github. I was searching some software that I can contribute to. While I was searching, I saw 'Sherlock' which is attracted me. I have some knowledge about Python and HTML and CSS. May I contribute the web interface?

**Comment by SmritiAgrawal04** [comment]
Is this issue still open? I want to work on the Web Interface of the project.

**Comment by yhay81** [comment]
I want to work on this, too. I can provide the source code of #943 

> The restructure of Sherlock (#350) would enable one to include it like a normal Python module. So, it can be downloaded on PyPi.

But they seems to have no time to do it.
So, I am suggesting that I fork this repo and work there. 
https://github.com/sherlock-project/sherlock/issues/353#issuecomment-764962527

**Comment by miltos04** [comment]
I want to work on this issue too with my colleague. We want to get familiar with JavaScript in order to create the website.

**Comment by sdushantha** [comment]
I am currently developing a newer version of Sherlock that will be modular so that it can be available on PyPi, have an Python and web API and possibly a web interface. Therefore I will be closing this as this is not something I will be doing with the current version of Sherlock
