### ISSUE TITLE
False Positives when searching with email address

### ISSUE THREAD

**Issue by ndtreviv** [sherlock-project/sherlock#543]
When searching with an email address the following sites return false positives:

* twitter
* codechef
* coderwall
* IFTTT
* telegram

**Comment by sdushantha** [comment]
@ndtreviv Sherlock does not support searching with email address and it is stated in the description of the program:
> Hunt down social media accounts by **username** across social networks

So, unfortunately we wont be fixing this as searching by email is not a functionality of Sherlock.

--

I am closing this issue as it is not really relevant to Sherlock
