### ISSUE TITLE
git clone does not work

### ISSUE THREAD

**Issue by powderedsalt** [sherlock-project/sherlock#549]
whenever i try to clone it using the link, it doesn't work, it gives an error for he letter c in clone

**Comment by sdushantha** [comment]
@powderedsalt Could you please send a screenshot of what is happening?

**Comment by powderedsalt** [comment]
![Capture](https://user-images.githubusercontent.com/61220993/75003894-3f8a4600-541e-11ea-9748-5b8b3f979495.JPG)

**Comment by sdushantha** [comment]
1. Download the ZIP file, (Click [here](https://github.com/sherlock-project/sherlock/archive/master.zip))
2. Unzip the file by right clicking the file and clicking on **Extract all...**
3. Open CMD and the type `cd /path/to/folder/`, where **/path/to/folder/** is the path to where unzipped folder is located
4. Then install the dependencies for Sherlock by typing `python3 -m pip install --user -r requirements.txt`
5. Run Sherlock, `python3 sherlock.py username`

----

I am closing this issue as it is not related to Sherlock, but your environment and your setup.

**Comment by i0t4** [comment]
same happened to me, all of my bitcoins got hacked.
