### ISSUE TITLE
Can’t install dependencies

### ISSUE THREAD

**Issue by SirEnvious** [sherlock-project/sherlock#558]
![2DE68EAF-85D6-4141-B24B-FABE6D419B2B](https://user-images.githubusercontent.com/61590409/75555678-956d7800-5a34-11ea-8362-289ff6249018.jpeg)

I’m trying to install the requirements on my jailbroken iPhone using a terminal, trying to $ pip install gives back a “this command does not exist” I manually installed all the requirements but it didn’t make a difference.

**Comment by SirEnvious** [comment]
Okay I fixed the pip issue but now I’m getting this 
![58B58869-C9B8-4981-94ED-7E444ADD4D8A](https://user-images.githubusercontent.com/61590409/75558490-ce5c1b80-5a39-11ea-9054-cbe3e54f74c1.jpeg)

**Comment by hoadlck** [comment]
The problem you are having has nothing to do with Sherlock: it has to do with the dependencies on the computer you are trying to get setup.

The error message appears to be from a compile.  It is trying to compile something from libxml, and either the include search path is incorrect, or you do not have that dependency on your computer.

**Comment by Nano-AI** [comment]
Try running `pip install -r requirements.txt` instead of `python3 -m pip install -r requirements.txt`.

**Comment by hoadlck** [comment]
Closing this out as it appears to be an install issue instead of something wrong with Sherlock.
