### ISSUE TITLE
Results files saved to specific folder

### ISSUE THREAD

**Issue by nathanieloffer** [sherlock-project/sherlock#559]
Having just installed Sherlock I was surprised to see the results files are just jumbled in with everything else instead of being in their own Results folder.

Having a separate folder would keep things cleaner especially as you use it more and the number of files increases.

**Comment by hoadlck** [comment]
There is an option to save the results to a directory.  Below is an excerpt from the readme and the help for the tool:
```
  --folderoutput FOLDEROUTPUT, -fo FOLDEROUTPUT
                        If using multiple usernames, the output of the results
                        will be saved to this folder.
```

**Comment by nathanieloffer** [comment]
Thank you for highlighting that however as it states in the README "If using multiple usernames" I can use that option but if I search for single usernames multiple times I can't. I was just surprised that an option like this wasn't the default for any searches performed with the script

**Comment by hoadlck** [comment]
The option works regardless of the number of usernames that you use.  The help text is trying to convey that this option is useful if you have results from multiple usernames: be it one invocation of Sherlock with multiple usernames, or successive invocations of Sherlock each with one username.
