### ISSUE TITLE
Ebay and Dailymotion not working

### ISSUE THREAD

**Issue by GustavoMF31** [sherlock-project/sherlock#56]
Running `py sherlock.py  obviousfakeusernamethatdoesntexist` gives me a obviousfakeusernamethatdoesntexist.txt with https://www.dailymotion.com/obviousfakeusernamethatdoesntexist and https://www.ebay.com/usr/obviousfakeusernamethatdoesntexist. Opening the pages show no user. I'm from Brazil and the messages in the sites are displayed in portuguese. Maybe that's why it fails recognizing the error.

**Comment by aggiebill** [comment]
Probably need to add an accept-language http header to ensure consistent responses.

**Comment by hoadlck** [comment]
Aragh. Yeah, that is probably what is going on.  There are currently 46 sites where Sherlock does not get an explicit http error code, so it is looking instead for certain text in the web page.  I knew that this would be a problem if the individual site changed their error page in any way, but languages is another way that this can fail.

I have been wondering if the query logic for these types of sites could be changed. First, Sherlock could do a query for a name that certainly does not exist.  Next, it could query for the name it was really interested in.  And, then it could compare the two queries.  I think that this technique might also be problematic, as there could easily be differences in the responses.  For example, the error message might have the user name embedded in it.

**Comment by raphuchur** [comment]
Both of these are fixed.

**Comment by jcs090218** [comment]
@GustavoMF31 Are both the sites fixed? Can you confirm it? and if it does then we can close this issue?

**Comment by GustavoMF31** [comment]
I just tried again with all the new changes and ebay still gives me a false positive. I also get false positives from http://blackplanet.com and https://www.meetme.com/. No problems with Dailymotion anymore

**Comment by sdushantha** [comment]
Ebay and Dailymotion are working now :)
