### ISSUE TITLE
Mac OS X Catalina abort on launch

### ISSUE THREAD

**Issue by PythonB** [sherlock-project/sherlock#564]
On Mac OS X 10.15.3 when launching getting error
`[1]    3662 abort      python3 sherlock.py`

Python 3.7.6
All requirements installed from requirements.txt

**Comment by sdushantha** [comment]
Hi @PythonB,

Thank you for letting us know about this. It seems like a strange problem. 
I am also on Catalina, version 10.15.2, and havent seen any issues.
![Screenshot 2020-03-14 at 13 22 16](https://user-images.githubusercontent.com/27065646/76681768-dfd72300-65f6-11ea-9554-f6d54542e120.png)


I'll try updating to 10.15.3 and see if that changes anything.

**Comment by PythonB** [comment]
Updated. Nothing changed. Here's output
`$ python3 sherlock.py       
[1]    3702 abort      python3 sherlock.py`
`$ python3 sherlock.py --help
[1]    3670 abort      python3 sherlock.py --help`
`$ python3 sherlock.py username
[1]    3732 abort      python3 sherlock.py username`

**Comment by PythonB** [comment]
Important to mentions that in Google Cloudshell all works perfectly fine.

**Comment by sdushantha** [comment]
@PythonB Which shell are you using? (zsh, bash, fish, etc)
The reason why I am asking this is because I have never seen that abort error before.

**Comment by PythonB** [comment]
zsh

**Comment by hoadlck** [comment]
The problem you are having seems similar in flavour with one opened against [pip3](https://github.com/Homebrew/homebrew-core/issues/44996).

Are you able to run any Python script?

**Comment by PythonB** [comment]
Thank you @hoadlck .
> I found something that may be helpful!
> The asn1crypto python package imports libcrypto. I removed this package from my site packages
> /usr/local/lib/python3.7/site-packages and now pip3 works

It worked for me.
