### ISSUE TITLE
Randomly Generates a username for unclaimed username

### ISSUE THREAD

**Issue by luchiago** [sherlock-project/sherlock#568]
Related to: #165 
Using a little script and/or Faker package to do this. My idea is when a person wants to contribute with the new website, it has to run the generator first, which will test if it exists, and if not the person can put in the JSON. If you guys let me I can send a pull request

**Comment by deceitfulvision** [comment]
I don't think this is a big enough of a problem to be fixed, all it takes is adding a few numbers or some other obscure change, its really not that hard.

**Comment by hKQwHW** [comment]
It's happened in #165

**Comment by cclauss** [comment]
`import time ; f"user{time.time_ns()}".rstrip('0')` --> user1657191108413085

**Comment by sdushantha** [comment]
This has now been added to Sherlock last week :)
