### ISSUE TITLE
No color shown in output

### ISSUE THREAD

**Issue by Milestheotherone** [sherlock-project/sherlock#573]
I know when i put the usernames in the websites have a yellow-ish color and a "+" and "-" but after 
I installed gitbash and sherlock again there is no color in output

![77812283-9da2ec80-70a0-11ea-8e4f-1889c4bd87d9](https://user-images.githubusercontent.com/57683610/77812318-d216a880-70a0-11ea-99a4-7a018b008bc7.png)

**Comment by sdushantha** [comment]
@Milestheotherone  https://github.com/sherlock-project/sherlock/pull/71#issuecomment-451659107
