### ISSUE TITLE
Option to check for slight modifications of a username

### ISSUE THREAD

**Issue by Scar26** [sherlock-project/sherlock#574]
It might be useful to add an optional parameter that automatically checks for slight modifications of the username passed in

For example, given a username scar, it would automatically check for stuff like scar[1-100], sc4r, _5c4r e.t.c

Possible additions:

-  Another option to specify the levenshtein distance within which alternatives are to be generated
-  Option to only search a specific list of sites for the username

Is this something worth working on?
I would love to contribute it

**Comment by sdushantha** [comment]
@Scar26 I like your idea, but I dont think this is something we would like to add to Sherlock yet, but you are more than welcome to create a fork and add your idea, so that it can be used for your OSINT challenge :)

**Comment by Scar26** [comment]
Ok, Thanks!

Actually, I thought of proposing this feature so that people who stumble upon the challenge could automate the recon process. It's quite unlikely that a potential user would have my fork installed instead of the original repo.

Regardless, I'll create a fork and add the feature just in case. I'll let you know when it's done so it can be merged sometime in the future if it feels appropriate.

Thanks for the response!
