### ISSUE TITLE
Im not sure 

### ISSUE THREAD

**Issue by MrFreez-jpg** [sherlock-project/sherlock#575]
![Screenshot from 2020-04-02 00-49-23](https://user-images.githubusercontent.com/62614034/78215351-f269ad00-747c-11ea-9a75-32397ba679a6.png)

I got this message and I don't know what is means please help.

thank you.

**Comment by PoorPocketsMcNewHold** [comment]
Seems to be an issue when trying to import and download the modules in the requirements.txt on a certain [setuptools](https://pypi.org/project/setuptools/).
The issue being, that the specified [requests-futures](https://github.com/ross/requests-futures/blob/master/requirements-python-3.txt) module, has [requests](https://pypi.org/project/requests/) as a dependency, BUT that [requests module, have itself, setuptools has its dependency](https://github.com/psf/requests/blob/master/setup.py).
So, yeah, a bit of a dependency hell we have going on.
Either try again to set up sherlock, or install manually [setuptools](https://pypi.org/project/setuptools/) via `pip3 install setuptools`.

**Comment by sdushantha** [comment]
Closing this as a solution had been found.
