### ISSUE TITLE
Instagram do not works

### ISSUE THREAD

**Issue by fntkg** [sherlock-project/sherlock#578]
# Sherlock doesnt find any username for instagram.

I am looking for a user who has an instagram account but sherlock cannot find the account with the same username.

**Comment by sdushantha** [comment]
@fntkg This is a strange issue. Someone did email me about this but I haven't been able to figure out why this is happening. I am able to check if a username exists on Instagram on a seperate script, but it fails when using Sherlock.

**Comment by tech2blog** [comment]
Yes, Instagram is not visible in the output.

**Comment by richardgetz** [comment]
Okay I figured it out. Instagram has an extra measure in place that doesn't allow HEAD requests. I'll fork and make a pull request.

**Comment by hoadlck** [comment]
This has been included in #599 as there was a non-trivial merge in including #593.

**Comment by zencore77** [comment]
same issue

**Comment by demonshead666** [comment]
As of 9th June 2021, it still doesn't work for Instagram, displaying site not found

**Comment by moraddart5** [comment]
Still facing the same issue

**Comment by Akr0m** [comment]
Still facing the same issue

**Comment by jonathan-politzki** [comment]
Still facing this issue.
