### ISSUE TITLE
Torrequest error

### ISSUE THREAD

**Issue by itisgood2be** [sherlock-project/sherlock#580]
Traceback (most recent call last):
  File "sherlock.py", line 26, in <module>
    from torrequest import TorRequest
ModuleNotFoundError: No module named 'torrequest'

**Comment by itisgood2be** [comment]
When I try "python3 -m pip install -r requirements.txt" I get an this: Requirement already satisfied: beautifulsoup4>=4.8.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (4.8.2)
Requirement already satisfied: bs4>=0.0.1 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: certifi>=2019.6.16 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2019.11.28)
Requirement already satisfied: colorama>=0.4.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (0.4.3)
Requirement already satisfied: lxml>=4.4.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (4.5.0)
Requirement already satisfied: PySocks>=1.7.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (1.7.1)
Requirement already satisfied: requests>=2.22.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (2.23.0)
Requirement already satisfied: requests-futures>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 8)) (1.0.0)
Requirement already satisfied: soupsieve>=1.9.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 9)) (1.9.5)
Processing /root/.cache/pip/wheels/a3/1b/fa/3c533b58f796531853a1be08235439bc11594221011f472ebf/stem-1.8.0-py3-none-any.whl
Processing /root/.cache/pip/wheels/a1/ba/a5/6eab015df23a8c29eebaa04ce042bb744cccc0e83905740d88/torrequest-0.1.0-py3-none-any.whl
Installing collected packages: stem, torrequest
  Attempting uninstall: stem
    Found existing installation: stem 1.7.1
ERROR: Cannot uninstall 'stem'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by sdushantha** [comment]
@itisgood2be https://github.com/pypa/pip/issues/5247#issuecomment-381550610
