### ISSUE TITLE
PyPi support? 

### ISSUE THREAD

**Issue by Surohitt** [sherlock-project/sherlock#582]
Wondering if anyone here was planning on creating a pip package for this project? Not sure if there are any issues with doing this?

**Comment by hoadlck** [comment]
Yes, there is an issue for this on #353.  I have not made much progress on it this year, but it is in the queue.

Much of the restructuring has been done, but not quite enough.  We have actually talked about this the other day: I am going to merge my development branch to the main line to make t his all easier to track.
