### ISSUE TITLE
Error using sherlock Ubuntu on 16.4 ls 

### ISSUE THREAD

**Issue by Lawbott** [sherlock-project/sherlock#591]
So Sherlock does not work at this point and i get this error message. "sherlock.py", line 67
    Fore.GREEN + f"] {title}" +

$ cd sherlock
PC:~/sherlock# python3 sherlock.py --help 

any ideas would be great?

**Comment by hoadlck** [comment]
You must be using an earlier version of python.  Try running the following:
```python3 --version```
You need to be running 3.6 or later.

**Comment by Lawbott** [comment]
how would i update it. im running Python 3.5.2

**Comment by hoadlck** [comment]
There are multiple ways.  I am not sure which would work best for you.  

I searched for some examples, and found [this](https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get) answer in the Ubuntu forums.

You could also download the source, and compile it and install it manually.

I would search around and see which method you are the most comfortable with.
