### ISSUE TITLE
well now any ideas on this?

### ISSUE THREAD

**Issue by Lawbott** [sherlock-project/sherlock#592]
sherlock$ python3 sherlock.py
Traceback (most recent call last):
  File "sherlock.py", line 23, in <module>
    from colorama import Fore, Style, init
ModuleNotFoundError: No module named 'colorama'

I'm running the current version.

**Comment by tdh8316** [comment]
Please read the [readme file](https://github.com/sherlock-project/sherlock#installation).

You just have to install requirements:
```
python3 -m pip install -r requirements.txt
```

**Comment by Lawbott** [comment]
Thank You, so much that helped fix it.
