### ISSUE TITLE
TikTok False Positive

### ISSUE THREAD

**Issue by richardgetz** [sherlock-project/sherlock#594]
TikTok is triggering a false positive. This can be fixed by changing TikTok's errorType value to status_code in data.json.

**Comment by hoadlck** [comment]
This got fixed in some of the cleanup activity for the restructure development.  The fix was added in this [commit](https://github.com/sherlock-project/sherlock/commit/f2179ca7c91ee3b60ae1a3c993667467fe53694f), even though it looks like #595 was never merged.
