### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by gguljea** [sherlock-project/sherlock#596]
i keep running into the same error while trying to download sherlock

>>> $ git clone https://github.com/sherlock-project/sherlock.git
  File "<stdin>", line 1
    $ git clone https://github.com/sherlock-project/sherlock.git
    ^
SyntaxError: invalid syntax

**Comment by sdushantha** [comment]
Hi @gguljea,

Looks like you made a minor copy&paste error. The command that you have to run is this:
```
git clone https://github.com/sherlock-project/sherlock.git
```

Make sure you run the command above, in command prompt if your are using Windows or the Terminal if you are using macOS or Linux

**Comment by hoadlck** [comment]
I assume that everything is working fine.
