### ISSUE TITLE
add lastName in usrename

### ISSUE THREAD

**Issue by shubhamrangadal** [sherlock-project/sherlock#597]
How do I add Lastname to a username. ex: python3 sherlock Joe Goldberg. now it just considers joe as first username and Goldberg as the second username, but they are single username

**Comment by hoadlck** [comment]
I am not sure how many sites allow spaces in the username.  But, you need to quote the argument in the shell.  Like the following:
```
%  python3 sherlock "Joe Goldberg"
```
