### ISSUE TITLE
sherlock coding

### ISSUE THREAD

**Issue by someoneouttheretrying** [sherlock-project/sherlock#598]
after i type in all the codes to find a username using github sherlock, it says "(null): can't open file 'sherlock.py': [Errno 2] No such file or directory" this is after i typed in the name to find all social media platforms of someone. How do i resolve this issue?

**Comment by hoadlck** [comment]
As part of the restructure, the command to invoke Sherlock from the root of the Git repo has changed.  Now, you type `python sherlock` instead of `python sherlock.py`.

The commands have been updated in the readme.

**Comment by someoneouttheretrying** [comment]
i just tried it and it says "SyntaxError: invalid syntax"

**Comment by hoadlck** [comment]
I assume that this new error message is coming from Python?  Have you performed the installation instructions in the readme?  Are you running python 3.6 or later?
