### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by akhil220** [sherlock-project/sherlock#602]
$ python3 sherlock.py NeilBreen
bash: /c/Users/hp/AppData/Local/Microsoft/WindowsApps/python3: Permission denied
This is the output I received. What is the solution to this problem?

**Comment by hoadlck** [comment]
`python3` is the normal name on Linux.  You appear to be on Windows, so use `python`.

Do you have Python 3.6 or later installed?  And, have you used pip to install the requirements?

**Comment by akhil220** [comment]
> `python3` is the normal name on Linux. You appear to be on Windows, so use `python`.
> 
> Do you have Python 3.6 or later installed? And, have you used pip to install the requirements?

while using python instead of python3 
$ python sherlock.py NeilBreen
C:\Users\hp\AppData\Local\Programs\Python\Python38-32\python.exe: can't open file 'sherlock.py': [Errno 2] No such file or directory
this is the result.

I have Python 3.8 Installed and have used pip to install the requirements.

**Comment by hoadlck** [comment]
Unless you are in the `sherlock` module area, the command is as follows:
```
 $ python sherlock NeilBreen
```
You are not in the directory that has `sherlock.py`.  The above command allows you do execute the module directly.

**Comment by akhil220** [comment]
> Unless you are in the `sherlock` module area, the command is as follows:
> 
> ```
>  $ python sherlock NeilBreen
> ```
> 
> You are not in the directory that has `sherlock.py`. The above command allows you do execute the module directly.

how can I make it right?

**Comment by hoadlck** [comment]
Didn't it work when you ran `python sherlock NeilBreen`?

**Comment by akhil220** [comment]
> Didn't it work when you ran `python sherlock NeilBreen`?

No, it didn't work.

**Comment by hoadlck** [comment]
What error message did you get?

**Comment by hoadlck** [comment]
If you were doing this from scratch on Windows, then these would be the commands.
```
% git clone https://github.com/sherlock-project/sherlock.git
% cd sherlock
% python -m pip install -r requirements.txt
% python sherlock NeilBreen
```

**Comment by akhil220** [comment]
thank you
