### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by chromechris** [sherlock-project/sherlock#604]
I was getting the "permission denied" prompt on windows 10 with Git Bash when trying to install the requirements after cloning the repo. I bypassed this by installing mitproxy. Now however, I get permission denied when trying to run a "python3 sherlock.py username" command. Not sure how I can even fix this on my end?

**Comment by sdushantha** [comment]
To install the requirements, run this command:
```
pip install --user -r requirements.txt
```

If you are using the latest version of Sherlock all you have to do is run this:
```
python3 sherlock username
```
You dont need the ".py" extension.

**Comment by hoadlck** [comment]
If you are on Windows, you should use `python` not `python3`.

**Comment by sdushantha** [comment]
This issue is 2 months old and there doesn't seem to be any updates from @chromechris. I will assume that they have successfully fixed the issue that they were having. I am closing this so that the list of issues can be kept nice and tidy.
