### ISSUE TITLE
Hackertool.Nirsoft

### ISSUE THREAD

**Issue by satechi** [sherlock-project/sherlock#605]
Malwarebytes registering "notabug.org" as a trojan horse, I made multiple queries on Sherlock with the same results. After reviewing the list of websites that Sherlock searches against I noticed that this site is listed. Malwarebytes automatically removes the Trojan horse which subsequently removes the "requirements.txt" file from the Sherlock folder thereby rendering the tool useless. I have contacted Malwarebytes to confirm that the site is in fact malicious, please verify the same and remove if in fact the site is a trojan horse.

**Comment by hoadlck** [comment]
I gave the notabug.org site to [Virustotal](https://www.virustotal.com/gui/url/6b5322ae10243b9df2c720182490a76afe508b591fabc5b16e136bfe9fddb12b/detection), and it was listed as clean.  

I would tend to believe Virustotal, as many of the anti-virus vendors use them.  I do see Malwarebytes listed as one of the scans at Virustotal, and it did not flag notabug.org.

Let us know what you hear from Malwarebytes.

**Comment by sdushantha** [comment]
Closing this issue because there is a high chance that we will not get a reply from @satechi because it seems like a throw away account
