### ISSUE TITLE
Colourlovers.com false positive

### ISSUE THREAD

**Issue by enodr** [sherlock-project/sherlock#618]
This site reports false positive. Non existing user page returns a 410 status_code but sherlock reports the user as existing.

Edit: seems the status code is different when using curl or the browser. When the cookie is not correctly set the status is different and content is an obfuscated javascript. Maybe site should be just dropped or method should be changed.

**Comment by beamop** [comment]
They have an public API available that support xml and json response, here the endpoint for user "blue": https://www.colourlovers.com/api/lover/blue but the status code is 200 for non existing user too 😄

**Comment by realprogrammer5000** [comment]
This could still be done with Error Message detection.

**Comment by richardgetz** [comment]
My solution was to change the message search to a regex search to enable exacting if needed. I changed my local version around quite a bit so I don't want to initiate a pull request but that should fix your issue.

`  "ColourLovers": {
    "errorMsg": "^\\<\\?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"\\?\\>\n$",
    "errorType": "message",
    "use_cfscrape": true,
    "headers": {
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Host": "www.colourlovers.com"
    },
    "rank": 21271,
    "url": "https://www.colourlovers.com/lover/{}",
    "urlProbe": "https://colourlovers.com/api/lover/{}",
    "urlMain": "https://www.colourlovers.com/",
    "username_claimed": "blue",
    "username_unclaimed": "noonewouldeverusethis7"
  },`


`if re.search(error, r.text) is None:`

**Comment by hoadlck** [comment]
For now, I am removing the site.  It is not doing any good to anyone.  Perhaps in a future update, the detection methods may be expanded to detect this site.
