### ISSUE TITLE
ERROR:  Problem parsing json contents at 'file.json':  Missing attribute 'urlMain'.

### ISSUE THREAD

**Issue by 4bic** [sherlock-project/sherlock#619]
I get this error when running: 
`python3 sherlock -j data/file.json`

The JSON file has the following structure: 

`{
   "Evariste Ndayishimiye": {
      "username": "EvaristeNdayishimiye"
   },
   "Agathon Rwasa": {
      "username": "AgathonRwasa"
   },
   "Dieudonné Nahimana": {
      "username": "DieudonnéNahimana"
   },
   "Francis Rohero": {
      "username": "FrancisRohero"
   },
   "Léonce Ngendakumana": {
      "username": "LéonceNgendakumana"
   },
}`

**Comment by realprogrammer5000** [comment]
The `-j` parameter is for loading a site JSON file like [`sherlock/resources/data.json`](https://github.com/sherlock-project/sherlock/blob/master/sherlock/resources/data.json), not a list of usernames.

**Comment by 4bic** [comment]
From the documentation, [here](https://github.com/sherlock-project/sherlock#usage), 
I see the `j`, and `--json` are used to load the JSON file. 

![Screenshot 2020-05-21 at 09 20 34](https://user-images.githubusercontent.com/5486449/82531541-45d8ad00-9b48-11ea-990e-c7733aec5941.png)

**Comment by hoadlck** [comment]
@realprogrammer5000 is correct:  the `--json` option is for loading information on how a set of sites may be searched, not to describe a list of user's queries.

The [WIki](https://github.com/sherlock-project/sherlock/wiki/Adding-Sites-To-Sherlock) has a description of the format of the JSON file.

**Comment by 4bic** [comment]
👏🏽  thank you @hoadlck  and @realprogrammer5000,  went through the wiki and saw how of that was. I suppose I can close this up. 
How would then go about checking multiple usernames if need be?

**Comment by realprogrammer5000** [comment]
Just add multiple command-line arguments for each username.
