### ISSUE TITLE
No such file or directory: requirements.txt

### ISSUE THREAD

**Issue by Musixx** [sherlock-project/sherlock#621]
This is what the full issue looks like.

Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

I'm so lost, please help!

**Comment by hoadlck** [comment]
It looks like you are not in the right directory.

The commands from the readme are as follows:
```bash
% git clone https://github.com/sherlock-project/sherlock.git
% cd sherlock
% python3 -m pip install -r requirements.txt
```
Did you enter the `cd sherlock` command?

**Comment by Musixx** [comment]
Yes, afterward I had put in the previous line as shown, not sure why it isn't working.

**Comment by hoadlck** [comment]
What are you running? Linux?  Windows?

List the files in the directory that you are in.  You should be able to `cat` the requirements.txt file.

**Comment by Musixx** [comment]
Windows.

Sorry, I only have very limited knowledge of my computer software, I was running it on Cloud Shell. I tried copying the code on the installation section after downloading Python but it didn't seem to work as I kept getting an error if I recall correctly being labeled as a Syntax Error. So I simply went on google shell.

**Comment by Musixx** [comment]
Are we allowed to post videos here? I may be enabled to record the process.

**Comment by sdushantha** [comment]
@Musixx Yes, feel free to post a screen recording of what is happening
