### ISSUE TITLE
[FEAT] Output JSON format

### ISSUE THREAD

**Issue by maximousblk** [sherlock-project/sherlock#634]
It would be nice if sherlock could output the results in json format. This would help integrating sherlock with other tools.

example:

```jsonc
{
    "claimed": [
        {
            "name": "2Dimensions",
            "url": "https://2Dimensions.com/a/user123",
            "urlMain": "https://2Dimensions.com/"
        },
        {
            "name": "3dnews",
            "url": "http://forum.3dnews.ru/member.php?username=user123",
            "urlMain": "http://forum.3dnews.ru/"
        }
        // and so on
    ]
}
```

this would make importing data much easier. this feature then can be paired with other tools and APIs for specific sites which would help create a clear profile of the target which would help eliminate other users using the same username.

**Comment by hoadlck** [comment]
Ultimately, Sherlock can be integrated into a Python script like any other Python module.  When you run a query, you get a Python class back that has the information you are mentioning in this issue.  If you look at the [QueryResult()](https://github.com/sherlock-project/sherlock/blob/master/sherlock/result.py#L29) class, this is how results are passed back to the person doing the query.

There is still work to do to package Sherlock like a normal Python module.  And, other work to give a better interface when making a query.

**Comment by maximousblk** [comment]
I understand that sherlock can be integrated in any python script but when working with tools that are not made in python, we need a more widely used format. And a json output can easily be converted into many other formats.

**Comment by gorwh** [comment]
> It would be nice if sherlock could output the results in json format. This would help integrating sherlock with other tools.
> 
> example:
> 
> ```jsonc
> {
>     "claimed": [
>         {
>             "name": "2Dimensions",
>             "url": "https://2Dimensions.com/a/user123",
>             "urlMain": "https://2Dimensions.com/"
>         },
>         {
>             "name": "3dnews",
>             "url": "http://forum.3dnews.ru/member.php?username=user123",
>             "urlMain": "http://forum.3dnews.ru/"
>         }
>         // and so on
>     ]
> }
> ```
> 
> this would make importing data much easier. this feature then can be paired with other tools and APIs for specific sites which would help create a clear profile of the target which would help eliminate other users using the same username.
>

**Comment by viniciuspereiras** [comment]
Hello ,  @sdushantha.
I was really upset when you just said that nobody wanted to use a json output, since json is simply the most important if someone wants to integrate sherlock into some automation, not to mention that most cli tools have json output, so since you told the guy to do his solution, I did it here in 5 minutes and I wanted to share it in this issue for anyone who needs this implementation:
The code can receive stdint for usage with '|' in terminal or can be changed to recive some os.popen response.
```python
import json
import sys
sherlock_output = sys.stdin.read().strip('\n').splitlines()
dict_out = {}
del sherlock_output[0]
for result in sherlock_output:
	result = result.strip('[+] ')
	line_split = result.split(': ')
	dict_out[line_split[0]] = line_split[1]
print(json.dumps(dict_out))
```
To run:
```
python3 sherlock <username> | python3 to_json.py
```

**Comment by maximousblk** [comment]
Just an FYI for anyone visiting this in the future:

I eventually ended up switching to [maigret](https://github.com/torerobo/maigret). It's a fork of Sherlock which provides many more output formats and a lot more websites.
