### ISSUE TITLE
Couldn't access data file data.json

### ISSUE THREAD

**Issue by AC1370** [sherlock-project/sherlock#636]
Im having problems where know when i try to use Sherlock, the prompt problem while attempting to access data file, data.json, o im not sure whats wrong?

**Comment by hoadlck** [comment]
I am not clear what problem you are having.  Did you run the procedure in the readme file?  If so, what error message did you get?

**Comment by Devil-vx** [comment]
Im having problems where know when i try to use Sherlock, the prompt problem while attempting to access data file, data.json, o im not sure whats wrong. I am using in android termux .

**Comment by sdushantha** [comment]
Im closing this issue as it hasnt seen any activity and the author of this issue seems to have used a throw away account because the issue was created 2 days after the creation of the account and has not seen any activity since.
