### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by ViperNetwork** [sherlock-project/sherlock#638]
I want to make a permanent output folder for my results despite it being more than one
and
I also want to customize/shorten/add in the list of websites...I did some changes in sites.md file but didn't affect.
Please help

Overall I am Extremely satisfied with your work...I love it.

**Comment by LameLemon** [comment]
Hello, 
For the first part of your issue, I believe the following two parameters are what you're looking for. The output will be saved to the specified directory. Hope this helps.
```
  --folderoutput FOLDEROUTPUT, -fo FOLDEROUTPUT
                        If using multiple usernames, the output of the results
                        will be saved to this folder.
```
I'm not sure what you mean in the second half.

**Comment by realprogrammer5000** [comment]
```
--json JSON_FILE, -j JSON_FILE
                        Load data from a JSON file or an online, valid, JSON
                        file.
```
Is that what you're looking for?

**Comment by ViperNetwork** [comment]
Thank you very much
Just one last thing,
If I want to add a new website, should I just follow your coding format with previously entered websites?

**Comment by sdushantha** [comment]
@ViperNetwork 
> If I want to add a new website, should I just follow your coding format with previously entered websites?

Yup!
