### ISSUE TITLE
I need help installing Sherlock to Python on Windows

### ISSUE THREAD

**Issue by yeetyeot** [sherlock-project/sherlock#645]
Hi, I'm very new to the world of coding and programming stuff, so recently I've been using Python because I want to give a test drive to Sherlock. It's a shame to say I don't know how to install it. I already have pip. But the problem is when I did the code to download sherlock it says '_Syntax Invalid'___. I'm new to this please help.

**Comment by hoadlck** [comment]
Sherlock is not available via pip yet.  

Did you do the install process described in the [readme](https://github.com/sherlock-project/sherlock/blob/master/README.md)?  If so, when did you get that error message?

**Comment by sdushantha** [comment]
Closing this issue because I'm pretty sure we wont be getting a reply from the author of this issue. The issue was created on the day the account was created and the account has not seen any activity since. Could be a throw away account.
