### ISSUE TITLE
Couldn't access data file data.json 

### ISSUE THREAD

**Issue by Devil-vx** [sherlock-project/sherlock#646]
![Screenshot_20200615-194605](https://user-images.githubusercontent.com/64526625/84668223-fd42c280-af40-11ea-9a05-9cc5e02f61af.png)
Can u plzz help me with this

**Comment by realprogrammer5000** [comment]
Can you send a picture of the command that generated the error message?

**Comment by Devil-vx** [comment]
Next which command. I have read your readme but I tried, it doest install requirements.txt and there is no Sherlock.py
![Screenshot_20200616-093441](https://user-images.githubusercontent.com/64526625/84730747-b4c4ec80-afb4-11ea-8730-85df959b5b21.png)

**Comment by Devil-vx** [comment]
Next which command. I have read your readme but I tried, it doest install requirements.txt and there is no Sherlock.py
![Screenshot_20200616-093945](https://user-images.githubusercontent.com/64526625/84731078-6106d300-afb5-11ea-888f-180ee91f6a75.png)

**Comment by hoadlck** [comment]
Per the readme, the command is `python sherlock` if you are running it in this directory.  

Of course, it looks like you had errors when running pip, so I am not sure if it will work even after you run the right command.

**Comment by sdushantha** [comment]
Closing this as it is not an issue related to Sherlock. If you still are facing this issue, try asking on StackOverflow or [r/learnpython](https://www.reddit.com/r/learnpython/)
