### ISSUE TITLE
Bug: False positive for 3 websites

### ISSUE THREAD

**Issue by GandelXIV** [sherlock-project/sherlock#647]
3 False positive websites:
https://www.liveleak.com/
https://forum.redsun.tf/
https://www.twitter.com/

**Comment by sdushantha** [comment]
Upon taking a look at liveleak, I think it no longer has the ability for us to look at it's users because I cant find any username on the website. Is it the same for you or am I missing something?

**Comment by sdushantha** [comment]
I will be removing https://forum.redsun.tf/ from `data.json` because from looking at many of the usernames, it seems like random digits are added to the end of the usernames. This means that it pretty much impossible to check if a username exists on that website.

**Comment by sdushantha** [comment]
For Twitter, we have to find another method of detecting the existance of the usernames because whenever I try to send a request to twitter.com/username I get this message:

> Something went wrong, but don’t fret — let’s give it another shot.

I will have to do further research into this to find a fix for this.

**Comment by GandelXIV** [comment]
> Upon taking a look at liveleak, I think it no longer has the ability for us to look at it's users because I cant find any username on the website. Is it the same for you or am I missing something?
Indeed

**Comment by GandelXIV** [comment]
The twitter issue could is being resolved in https://github.com/sherlock-project/sherlock/issues/541

**Comment by jepunband** [comment]
Yes, false positives still there after doing git pull to the latest.
1. liveleak
2. redsun
3. twitter
4. ko-fi

**Comment by sdushantha** [comment]
> 4. ko-fi

@Luidiblu Since you added ko-fi, could you take a look at this?

**Comment by Luidiblu** [comment]
Sure! I can take a look! And fix the ko-fi false positive

**Comment by sdushantha** [comment]
@Luidiblu @jepunband I have fixed the false positive for ko-fi in 2a26f0b

**Comment by sdushantha** [comment]
Okay, I'm just gonna put this list here so that we can keep track of the sites that have been listed in this thread:

- [x] LiveLeak
- [x] redsun
- [ ] Twitter
- [x] Ko-fi

---

- [x] = has been fixed or removed

**Comment by jepunband** [comment]
@sdushantha ok, now it works! no more false positives.

**Comment by morgulbrut** [comment]
1. Wikipedia
2. Tinder

seem somehow fishy too. 

www.gotinder.com/@randomuser just shows a "this user may have changed his name" site
and wikipedia.org, as it should, shows a "wanna add this user?" site

**Comment by sdushantha** [comment]
@morgulbrut I think it would be wise to add regex support for the error messages so that we can use multiple error messages.
Example: `(Error1|Error2)`

**Comment by billyb2** [comment]
Fixed Twitter by changing to the mobile Twitter URL.
https://github.com/sherlock-project/sherlock/pull/684

**Comment by sdushantha** [comment]
@morgulbrut The response you are getting from Tinder might be the correct response because if I try the username "sara" it actually shows an account: **https://tinder.com/@sara**

**Comment by rodrigograca31** [comment]
I'm having lots of false positives. 

I don't know how you guys check if the user exists or not but when I manually check the found URLs a good portion says "user not found 404".

Here are some examples:
https://www.investing.com/
https://opencollective.com/
https://www.tiktok.com/
https://www.wikipedia.org/

tiktok would be a very important one to get fixed....🤔

**Comment by sdushantha** [comment]
Tinder has been fixed in #697, thanks to @roopeshvs

**Comment by sdushantha** [comment]
Wikipedia has been fixed in #698, credits to @roopeshvs

**Comment by sdushantha** [comment]
Closing this issue as all the sites mentioned in this issue has been dealt with 👍
