### ISSUE TITLE
Should we add adult websites?

### ISSUE THREAD

**Issue by sdushantha** [sherlock-project/sherlock#654]
Hey guys!

Recently I found out that Sherlock has been used by [TraceLabs CTF](https://www.tracelabs.org/getinvolved/ctf/) participators. This means that Sherlock is being used to find missing people, which is awesome!!

This got me thinking, should we add support for adult websites? Because thinking from an investigator's point of view, I would want to know if my subject who committed an offense, has accounts on adult websites. Why? So that I could know if they might have left some traces there.

My plan is to create another repo, similar to [sherlock-data](https://github.com/sherlock-project/sherlock-data), but specifically for adult websites. The reason why I want to separate the adult websites from the main list of sites is because the last thing I want to happen to you is that you are at work and you use the `--browse` option and a bunch of adult websites open up on your work computer.

I do not want to maintain the adult website list because I do not feel comfortable in doing so. So after I create the repo,  if any of you guys want to maintain it, feel free to shoot me an email and I will give your write access to the repo which is dedicated to the adult websites.

Let me know what you guys think, I am open to ideas! :)

**Comment by Niroshan23** [comment]
The idea is Good sir


Sir If you don't mind

What about idea of searching for a
person/account using email-id instead of name, So that it may be precise.

**Comment by Luidiblu** [comment]
Very good idea! 

We can add more features later, but, if u agree with me... more info is better then less info....

**Comment by Luidiblu** [comment]
> Hey guys!
> 
> Recently I found out that Sherlock has been used by [TraceLabs CTF](https://www.tracelabs.org/getinvolved/ctf/) participators. This means that Sherlock is being used to find missing people, which is awesome!!
> 
> This got me thinking, should we add support for adult websites? Because thinking from an investigator's point of view, I would want to know if my subject who committed an offense, has accounts on adult websites. Why? So that I could know if they might have left some traces there.
> 
> My plan is to create another repo, similar to [sherlock-data](https://github.com/sherlock-project/sherlock-data), but specifically for adult websites. The reason why I want to separate the adult websites from the main list of sites is because the last thing I want to happen to you is that you are at work and you use the `--browse` option and a bunch of adult websites open up on your work computer.
> 
> I do not want to maintain the adult website list because I do not feel comfortable in doing so. So after I create the repo, if any of you guys want to maintain it, feel free to shoot me an email and I will give your write access to the repo which is dedicated to the adult websites.
> 
> Let me know what you guys think, I am open to ideas! :)

Why not just a query param? `--adult`?

**Comment by sdushantha** [comment]
@Luidiblu That's a great idea!! In the data.json file we could have a value called "NSFW" and it can have a Boolean value. The command line flag could be `--nsfw`

**Comment by Luidiblu** [comment]
Sure!
If the key "nsfw" is in the data.json file, you only can see it if insert the flag `--nsfw`

**Comment by hoadlck** [comment]
@sdushantha Remember that we talked about the general technique of grouping sites of a similar theme in #522.  I don't think that we can add a command line option for every grouping of website:  the command line list would explode.

Implementing tags would provide just one command line option to filter the search.  For example, if the user wanted to search for a certain name on video sites, then the command would be as follows:
```
% python3 sherlock --tag video user123
```

As far as adult sites in Sherlock, I did not think we were going to do that.  Or at least, not as a default.  Any user can use the `--json` option to pass a JSON file with adult sites in it.  If they do that, then no special option or tag is required:  the site list would already have nothing but adult sites.

It would probably be a good idea to make the `--json` option additive: when the user has one of these options, it adds to the list of sites (instead of replacing them).  This would allow people to use the option multiple times to build up a super-list of sites.

**Comment by Luidiblu** [comment]
@hoadlck Do you agree with me that instead of passing a json file, the person can change the local json??
We are complicating something that should be simple, many parameters, make things confusing, I agree with you, we can review and make the parameters more comprehensive

**Comment by sdushantha** [comment]
> Remember that we talked about the general technique of grouping sites of a similar theme in #522. I don't think that we can add a command line option for every grouping of website: the command line list would explode.

@hoadlck Very true, I agree with you.

> It would probably be a good idea to make the --json option additive: when the user has one of these options, it adds to the list of sites (instead of replacing them). This would allow people to use the option multiple times to build up a super-list of sites.

This seems like a great idea

Should I go ahead and create the adult site repo? @Luidiblu, would like you maintain it?

**Comment by Luidiblu** [comment]
Sure @sdushantha !

**Comment by Luidiblu** [comment]
@satznova can we close this issue now?

**Comment by sdushantha** [comment]
@Luidiblu I'm guessing you were trying to mention me, but yes, I'll lose this now

**Comment by snakepeek** [comment]
add bdsm sites as well

**Comment by sept11pg** [comment]
Have the "Porn Sites" been added yet" ??

and do you have one for "Dating Sites" ??
