### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by Soy-5auce** [sherlock-project/sherlock#657]
"$ python sherlock sp0rm" results in "bash: /c/Users/camer/AppData/Local/Microsoft/WindowsApps/python: Permission denied" and i havent been able to find a helpful explanation as to why. I'm new to programming, especially in py so sorry for any rookie mistakes!

**Comment by sdushantha** [comment]
Hey @Soy-5auce, are you using the command prompt or [Git for Windows](https://gitforwindows.org/)?

**Comment by sdushantha** [comment]
I hope you find a solution to your the issue you are having. I am sure there are many tutorials on YouTube which will guide on how to fix this issue. If YouTube doesnt help, try posting your issue onto [r/python](https://www.reddit.com/r/python)


I am closing this issue as it has nothing to do with Sherlock.
