### ISSUE TITLE
ERROR: Cannot uninstall 'stem'. 

### ISSUE THREAD

**Issue by DnDRogue** [sherlock-project/sherlock#658]
When I run the:

`$ python3 -m pip install -r requirements.txt`

command to finish setting up Sherlock, I get the following error while trying to uninstall stem:

```
Attempting uninstall: stem
Found existing installation: stem 1.7.1
ERROR: Cannot uninstall 'stem'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

I've tried locating packages named stem but I can't find any. What am I supposed to do here?

**Comment by sdushantha** [comment]
Hey there @DnDRogue, I have never seen that type error before.
You could try uninstalling `stem` first, `python3 -m pip uninstall stem`, and then run `python3 -m pip install -r requirements.txt`?

Let me know what happens, I'm curious to know.
