### ISSUE TITLE
Error please help

### ISSUE THREAD

**Issue by Itzkashi** [sherlock-project/sherlock#660]
![Screenshot_20200630-020941_Termux](https://user-images.githubusercontent.com/67024848/86071476-40d81900-ba77-11ea-8bc0-d4025ea6fb3b.jpg)
![Screenshot_20200630-020915_Termux](https://user-images.githubusercontent.com/67024848/86071508-54837f80-ba77-11ea-978c-eb9584998f66.jpg)

**Comment by sdushantha** [comment]
Hey @Itzkashi :)

Try following these steps:
1. Download the repo: `git clone https://github.com/sherlock-project/sherlock`
2. Go into the sherlock directory: `cd sherlock`
3. Install the needed dependencies: `python3 -m pip install -r requirements.txt`
4. Run sherlock: `python3 sherlock username`

**Comment by Itzkashi** [comment]
![Screenshot_20200703-020824_Gallery](https://user-images.githubusercontent.com/67024848/86422003-be986080-bcd3-11ea-8504-9c2e6d6d8953.jpg)

**Comment by Itzkashi** [comment]
I got this working thanks
