### ISSUE TITLE
python: can't open file 'sherlock.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by moran04** [sherlock-project/sherlock#661]
i have tried luanching and downloading this code dozens of times and i even tried renaming the compressed folder

**Comment by YMA198** [comment]
I had the same problem but when you look you will see there is _another_ subfolder called sherlock inside the sherlock folder. Good Luck!

**Comment by sdushantha** [comment]
Hey @moran04,

Try following these steps:
1. Download the ZIP file from here: https://github.com/sherlock-project/sherlock/archive/master.zip
2. Unzip it using whatever method that suits you
3. Open your terminal and run `cd /path/to/sherlock/
4. Then install the needed dependencies by running `python3 -m pip install -r requirements.txt`
5. Then run you are good to go! `python3 sherlock username` **Note: There is no '.py' at the end**

**Comment by 10ke5h** [comment]
"Python3 sherlock username" worked for me on Termux
