### ISSUE TITLE
Unknown Error Type/Invalid Syntax

### ISSUE THREAD

**Issue by TheErik009** [sherlock-project/sherlock#662]
ejb@myssol:~/sherlock$ python3 sherlock
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sherlock/__main__.py", line 10, in <module>
    import sherlock
  File "sherlock/sherlock.py", line 376
    raise ValueError(f"Unknown Error Type '{error_type}' for "
                                                             ^
SyntaxError: invalid syntax

**Comment by sdushantha** [comment]
Hey!

Could you please send me the output of this command:
```
python3 --version
```

**Comment by TheErik009** [comment]
> Hey!
> 
> Could you please send me the output of this command:
> 
> ```
> python3 --version
> ```

ejb@myssol:~$ python3 --version
Python 3.5.3

**Comment by sdushantha** [comment]
In the [Installation](https://github.com/sherlock-project/sherlock#installation) section, it states that you have to have Python 3.6 or above. This is so that f-strings are onlhy compatible with Python3.6 or above.

So to fix the issue you are having, you must install Python3.6 or a later version.
