### ISSUE TITLE
-bash: python3: command not found

### ISSUE THREAD

**Issue by veryniceusername** [sherlock-project/sherlock#668]
When i try to install the requirements i get the error -bash: python3: command not found

Im using kali linux terminal on windows and i have the newest version of python

**Comment by sdushantha** [comment]
Thats strange. What is the output of `python --version` ?
If the version is something like `3.x.x`, then try installing the requirements like this: `python -m pip install -r requirements.txt`

**Comment by veryniceusername** [comment]
Yeah if i do that i get the error -bash: python: command not found

**Comment by sdushantha** [comment]
Looks like you did a mistake when installing Python. Could be that Python is not in your `$PATH`. I unfortunately can't help you with installing python, but there are many YouTube videos which explains very well on how you can properly install it.

Closing this as it has nothing to do with Sherlock.
