### ISSUE TITLE
Issue with downloading Shrelock on Python with Windows 10

### ISSUE THREAD

**Issue by MicrowaveMaster** [sherlock-project/sherlock#671]
I installed have Python 3.8 (Including pip3) and everytime i try to download sherlock I get a Syntax Error ? I'm new to the coding and really don't know what to do...

**Comment by sdushantha** [comment]
Did make sure to install the needed dependencies? If you haven't, just run the command below:
```
python3 -m pip install -r requirements.txt
```

If this doesnt fix the problem, could you send a screenshot or copy and paste the error message you are getting?

**Comment by MicrowaveMaster** [comment]
I finally got it to work using the google cloud shell, thanks for the reply
