### ISSUE TITLE
Program locks up randomly on Zomato accounts

### ISSUE THREAD

**Issue by Column01** [sherlock-project/sherlock#673]
For some reason, my search locks up on some Zomato accounts.
Using the username `testing123`, it locks up after `Zhihu` (which in the config is `Zomato`).
I have no idea why this happens as sometimes it works for other usernames and sometimes it doesn't work for those same usernames.

![img](https://i.imgur.com/jNLdsju.png)
Space below the last item just has a blinking cursor like it's stuck.

**Comment by Column01** [comment]
For now, I just removed it from my sites list

**Comment by sdushantha** [comment]
@Column01 I also noticed that yesterday. It took around 20 seconds for Zomato to load. I thought it must have just been something to do with my wifi. 

I will remove Zomato because it causes of this strange problem.

**Comment by sdushantha** [comment]
Closing because this issue has been fixed in the latest commit: db878ab
