### ISSUE TITLE
pip3 problem

### ISSUE THREAD

**Issue by QairexStudio** [sherlock-project/sherlock#675]
hi bros. i got this problem. how can i solve it. i was research solved it but i wasnt found anything.
problem:
`AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv23_METHOD'`
when i wrote i get that error: `pip3 install -r requirements.txt`

**Comment by sdushantha** [comment]
Try out this answer:
**https://stackoverflow.com/a/43267158/9215267**

![image](https://user-images.githubusercontent.com/27065646/88473472-28480b00-cf1e-11ea-8e7c-ff20099bcd10.png)

---

Also make sure to run `pip` like this:
```
python3 -m pip
```

**Comment by QairexStudio** [comment]
> Try out this answer:
> **https://stackoverflow.com/a/43267158/9215267**
> 
> ![image](https://user-images.githubusercontent.com/27065646/88473472-28480b00-cf1e-11ea-8e7c-ff20099bcd10.png)
> 
> Also make sure to run `pip` like this:
> 
> ```
> python3 -m pip
> ```

Dude i was solved my problem but thanks
