### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by jimbokali** [sherlock-project/sherlock#687]
Is anyone able to help me figure out why my username searches do not write a .txt file?  In my sherlock directory, there is another sherlock folder where sherlock.py is.  I am new to Linux so I don't know if I have to give execute permissions to the new folder, or if i should just uninstall/reinstall.  Please let me know if anyone can help, thanks!

**Comment by sdushantha** [comment]
Could you send us the full command you typed in and the error that you got?

**Comment by YeaToast** [comment]
Did you try using sudo?

**Comment by jimbokali** [comment]
I've tried using sudo but I get a different error.  Without using sudo i get an output, just not a .txt file so I can't nano.  
My input:
python3 sherlock.py sg0nk

Output:
Traceback (most recent call last):
  File "sherlock.py", line 634, in <module>
    main()
  File "sherlock.py", line 597, in main
    with open(result_file, "w", encoding="utf-8") as file:
PermissionError: [Errno 13] Permission denied: 'sg0nk.txt'

**Comment by sdushantha** [comment]
@jimbokali 
You wrote the wrong command.
This is what you are supposed to run:
```
python3 sherlock sg0nk
```

Note that there is *no* `.py` at the end of `sherlock`

**Comment by jimbokali** [comment]
I get the same error when writing python3 sherlock sg0nk

**Comment by sdushantha** [comment]
@jimbokali Could please send a screenshot of what is happening?

**Comment by jimbokali** [comment]
@sdushantha 

![sherlock1](https://user-images.githubusercontent.com/68930996/88853987-99a5e900-d1be-11ea-8c30-efc8f73645d0.JPG)
![sherlock2](https://user-images.githubusercontent.com/68930996/88853990-9ca0d980-d1be-11ea-8214-828a826fc421.JPG)
[](url)

**Comment by hoadlck** [comment]
I suspect that this is the permissions of the directory.  Run the following command and see who owns the sherlock directory and the containing files.
```
pi@maa:~/sherlock $ ls -l ../ .
```
Did you clone the repository under sudo?  That would cause the files  to not be owned by your normal user level, so there would be a complaint.

**Comment by jimbokali** [comment]
@hoadlck It is owned by root, so that is definitely it, thanks so much, I'll close the issue now

**Comment by sdushantha** [comment]
That makes much more sense. Since you were using Kali I assumed everything was root by default, but then I remembered that in the latest update the introduced normal users because people started to use Kali as a daily driver.

**Comment by jimbokali** [comment]
@sdushantha Yeah I should have been more clear in my original post as to what steps I took.  Thank you for all your help too!

**Comment by schmidtBalint** [comment]
Hi, Im getting the same error and I don't know how to change the ownership of the directory, Im a newbie and would apreciate if someone could help me out, thanks.

**Comment by Oakchris1955** [comment]
> Hi, Im getting the same error and I don't know how to change the ownership of the directory, Im a newbie and would apreciate if someone could help me out, thanks.

Linux or Windows?

**Comment by schmidtBalint** [comment]
I already solved it no problem thanks anyway i just needed to move the folder to system files using root.

**Comment by IliasOtaku** [comment]
> I already solved it no problem thanks anyway i just needed to move the folder to system files using root.

can u show me how to do same ? thanks

**Comment by mr-robot1552** [comment]
how would i change owner ship of the directory? im using the command python3 sherlock "username" i am seeing the list but i am getting an error message saying "PermissionError: [Errno 13] Permission denied:" to clone sherlock i used the sudo command
