### ISSUE TITLE
Can't install requirements.txt

### ISSUE THREAD

**Issue by cyborg411** [sherlock-project/sherlock#688]
**Hi**, does someone know how to solve my problem please.

When I execute $ python3 -m pip install -r requirements.txt I get this error in my terminal : https://i.imgur.com/YA08HOv.png

**Comment by sdushantha** [comment]
@cyborg411 Does this answer fix it?
**https://stackoverflow.com/a/43267158/9215267**

![image](https://user-images.githubusercontent.com/27065646/88473472-28480b00-cf1e-11ea-8e7c-ff20099bcd10.png)

**Comment by cyborg411** [comment]
Unfortunately, that doesn't work.
I get this error : https://i.imgur.com/ZHaZiNB.png
