### ISSUE TITLE
when to support in China?

### ISSUE THREAD

**Issue by xch1029** [sherlock-project/sherlock#69]
many websites in China.Maybe you can support one or two.like: weibo,gitee

**Comment by Czechball** [comment]
hello, could you please provide some sites (links) you would like to add? I'll try to add a support for them.

**Comment by xch1029** [comment]
> hello, could you please provide some sites (links) you would like to add? I'll try to add a support for them.

https://weibo.com/xiena(谢娜 is a superstar in China)

**Comment by Czechball** [comment]
hello, I've checked out weibo. it seems that you can't visit user profiles unles logged in (impossible to check with Sherlock) also when I try to visit the link you provided, I get a "page not found" error. However, gitee seems to list users fine, so I'll include that.

**Comment by xch1029** [comment]
> hello, could you please provide some sites (links) you would like to add? I'll try to add a support for them.

https://weibo.com/xiena        (谢娜 is a superstar in China)
https://gitee.com/tbmao2    (Gitee is a substitute for GitHub in China,in this case, tbmao2 is my name )
When I have time, I will provide you more websites

**Comment by xch1029** [comment]
https://www.zhihu.com/people/evanyou/
zhihu.com is a website like medium
evanyou is creator of vue

(many sites url dont contain username. That's bad news)

**Comment by Czechball** [comment]
Zhihu and Gitee added in #81

**Comment by sdushantha** [comment]
The Chinese sites have been added
