### ISSUE TITLE
Having trouble downloading requirements.txt

### ISSUE THREAD

**Issue by B1aCk0uT18** [sherlock-project/sherlock#691]
I typed in "python3 -m pip install -r requirements.txt" and it gave me the error shown in my screenshot. Thoughts on how to fix it?

![image](https://user-images.githubusercontent.com/58851990/89138221-e3693900-d508-11ea-8846-7755618bfa9f.png)

**Comment by sdushantha** [comment]
Does this answer fix it?
**https://stackoverflow.com/a/43267158/9215267**

![image](https://user-images.githubusercontent.com/27065646/88473472-28480b00-cf1e-11ea-8e7c-ff20099bcd10.png)


I'll be closing this issue because its a problem with your environment and not Sherlock
