### ISSUE TITLE
Always stops after LiveJournal

### ISSUE THREAD

**Issue by shikha-16** [sherlock-project/sherlock#692]
Any user I search for, the program stops working after 'LiveJournal', attaching screenshot below.
![image](https://user-images.githubusercontent.com/68149849/89302177-243b8c00-d688-11ea-9aac-f5a73eb2a015.png)

**Comment by sdushantha** [comment]
This could be because of some connection issues to the site from your internet because everything is fine when I tried it

**Comment by sdushantha** [comment]
If you encounter connection issues just try running Sherlock again. It usually has something to do with the speed of your internet connection
