### ISSUE TITLE
Image not working. 

### ISSUE THREAD

**Issue by Flairings** [sherlock-project/sherlock#701]
the image is broken or just doesnt work in CMD pls fix if possible

**Comment by sdushantha** [comment]
@Flairings Which image does not work?

**Comment by Flairings** [comment]
![image](https://user-images.githubusercontent.com/58793605/89642843-7ceb6e80-d8ac-11ea-8236-d093fd752277.png)

**Comment by sdushantha** [comment]
It was removed because it was unnecessary
