### ISSUE TITLE
It would more helpful if only found ones show in Terminal when searched for a username

### ISSUE THREAD

**Issue by avinashkranjan** [sherlock-project/sherlock#718]
When You Search for any username using sherlock.... <b>Found and Not Found </b>

![Screenshot (126)](https://user-images.githubusercontent.com/55796944/90004309-0a66fe00-dcb3-11ea-9078-af9aae820b5c.jpg)

<h3>It would be more helpful if only found ones gets shown... and a module be made to show all.</h3>

**Comment by hoadlck** [comment]
There is already an option `--print-found`.  Is this not what you want?

**Comment by avinashkranjan** [comment]
But Wouldn't be more helpful if it's prints only found by default, and all when mentioned..

**Comment by sdushantha** [comment]
> But Wouldn't be more helpful if it's prints only found by default, and all when mentioned..

I agree on this. I do find myself using the `--print-found` flag almost all the time. We could have a `--verbose` flag which shows the "**Not Found!**" sites.

**Comment by abyshekhar** [comment]
I would say displaying the count of the sites on which the username was found would also make sense.

**Comment by sdushantha** [comment]
@abyshekhar Could explain why this would be useful? I cant think of a reason why someone would want to know the number of sites. If you really wanted to know, you could always open up the text file that gets created and it has the count at the end.

**Comment by abyshekhar** [comment]
> @abyshekhar Could explain why this would be useful? I cant think of a reason why someone would want to know the number of sites. If you really wanted to know, you could always open up the text file that gets created and it has the count at the end.

Sometimes we create accounts on lot of websites for using some functionality as in when required and later forget the details. As a user of the sherlock project i would be curious to know that in how many sites i have an account with a username and then would go ahead and review them individually.
I just noticed that the text file does contain it but would be good if that is the first line to be displayed in the txt as well as the result in the terminal.

**Comment by sdushantha** [comment]
@avinashkranjan This is currently being worked on in #747

**Comment by sdushantha** [comment]
fixed in #747

**Comment by avinashkranjan** [comment]
> fixed in #747

Great..
