### ISSUE TITLE
Username for Facebook shows not found although it exists

### ISSUE THREAD

**Issue by abyshekhar** [sherlock-project/sherlock#725]
While exploring the feature i tried looking for the sites with my username and surprisingly facebook being the most common one shows as not found for the username 'abyshekhar'

**Comment by sdushantha** [comment]
I'll work on this later, but I think using the error message might be better than checking the status code. We could use this error message: **This page isn't available**

**Comment by sdushantha** [comment]
Seems like you need to sign up in order to check for usernames on Facebook. It's unfortunate that it's not working. We'll have to try and figure out another way because Facebook is a very important site

**Comment by roopeshvs** [comment]
![Screenshot (103)](https://user-images.githubusercontent.com/47831211/91056177-413dfc00-e643-11ea-8347-6f06c7e94e64.png)

Profiles that have this enabled, give correct responses and Sherlock is working fine if we consider this.

**Comment by roopeshvs** [comment]
@sdushantha I figured a hack to make it work using an URL like https://www.facebook.com/{}/videos/ which would say "You must log in to continue" if such a profile existed, else would give us a "This page isn't available" - which we can use as an error message. 

I can send in a PR for this if my previous PR be reviewed..

**Comment by sdushantha** [comment]
@roopeshvs Great find! Does that method still work if the account does not have any videos?

**Comment by roopeshvs** [comment]
@sdushantha Yes. It seems to be working. videos/ is available for all users irrespective of that.

**Comment by sdushantha** [comment]
Closing this issue as it has been fixed by @roopeshvs in #737
