### ISSUE TITLE
Errors on Facenama and Cloob

### ISSUE THREAD

**Issue by busybox11** [sherlock-project/sherlock#726]
The script outputs "Error Connecting" for those two platforms

**Comment by sdushantha** [comment]
@busybox11 That is not an issue with Sherlock. You are getting that error because your computer is unable to connect with the site. This could be because of slow internet connection.

**Comment by busybox11** [comment]
Well, I don't think this is an error from my computer, since it is running from Google Cloud Engine...

**Comment by sdushantha** [comment]
> Well, I don't think this is an error from my computer, since it is running from Google Cloud Engine...

@busybox11 The connection errors are not large problems. They tend to go away if you try running Sherlock a couple of times. The site might be a little slow to respond. It's not really a problem with Sherlock
