### ISSUE TITLE
Adding to bin

### ISSUE THREAD

**Issue by LiamTownsley** [sherlock-project/sherlock#733]
How would I add sherlock to the bin so I could type `sherlock user1 user2` anywhere on my Kali VM.

**Comment by sdushantha** [comment]
This will be possible after the restructure is has been completed. But in the meantime, you can follow this hacky method to achieve the same result.

Open up your terminal and run the following commands:
```console
$ mkdir -p ~/bin
$ git clone https://github.com/sherlock-project/sherlock ~/bin/sherlock
```

Now we need to create an alias. Open up `~/.bashrc` using your favorite text editor and add the text below to the file:
```bash
alias sherlock="$(which python3) ~/bin/sherlock/sherlock"
```

Close your terminal and reopen it. Now you will be able to run Sherlock by just running `sherlock`

Let me know how this goes :)

**Comment by sdushantha** [comment]
Since I got a thumbs from you, I assume it must've worked
