### ISSUE TITLE
How can we get access to the account if i may ask... 

### ISSUE THREAD

**Issue by HerbertDelima79** [sherlock-project/sherlock#741]
Is there anyway we can get the password linked to these accounts
Sorry I'm a newbie

**Comment by sdushantha** [comment]
@HerbertDelima79 No, that is not possible. Sherlock only finds sites where a user has an account. It does not crack the password to those sites. 

Just some advice; if I were you I would not try to crack other people's accounts as this is illegal.

**Comment by HerbertDelima79** [comment]
True though
Very illegal
Thanks
