### ISSUE TITLE
are you using user-agent  ?  its helps login for  sites.

### ISSUE THREAD

**Issue by kaankarakoc42** [sherlock-project/sherlock#746]
import requests as r
user_agent = {'User-agent': 'Mozilla/5.0'}#change tech python to mozilla 
username="username"
`s=r.get("https://www.tiktok.com/@"+username+"?lang=tr",headers=user_agent)`
c=s.status_code
if username in s.content.decode("utf-8"):
   print("[+] "+s.url)

**Comment by sdushantha** [comment]
Hey @kaankarakoc42, great question! If you look at lines 201-203 from `sherlock.py` , you will see that we do indeed use a user agent when doing the requests:
https://github.com/sherlock-project/sherlock/blob/75c51f545b2312118a74d788090d0825604c1915/sherlock/sherlock.py#L199-L203

Sometimes, we encounter sites which returns unreliable data when using a user agent, therefore we have an option in the `data.json` which allows us to set the headers of the request to nothing. If you look at Twitter from `data.json`, you can see that we have set the user agent to nothing:
https://github.com/sherlock-project/sherlock/blob/75c51f545b2312118a74d788090d0825604c1915/sherlock/resources/data.json#L1607-L1616
