### ISSUE TITLE
Small thing: invalid link in sherlock wiki.

### ISSUE THREAD

**Issue by mehtaarn000** [sherlock-project/sherlock#753]
In the wiki section of this repository, specifically the 'Adding Sites to Sherlock' page, [found here](https://github.com/sherlock-project/sherlock/wiki/Adding-Sites-To-Sherlock), on the data.json file listed, GitHub returns a 404 not found error. Easy fix by changing the URL from [https://github.com/sherlock-project/sherlock/blob/master/data.json](https://github.com/sherlock-project/sherlock/blob/master/data.json), to [https://github.com/sherlock-project/sherlock/blob/master/sherlock/resources/data.json](https://github.com/sherlock-project/sherlock/blob/master/sherlock/resources/data.json). Thanks!

**Comment by sdushantha** [comment]
@mehtaarn000 I have fixed it now. Thank you for letting us know :)
