### ISSUE TITLE
Using other data to find social media

### ISSUE THREAD

**Issue by Prajwal-Koirala** [sherlock-project/sherlock#756]
Hello;
I was wondering if u guys could support a feature where someone could use a email or a phone number to find social media.
- prajwal

**Comment by sdushantha** [comment]
We don't plan to support phone numbers and emails any time soon.  But in the meantime, you can use [email2phonenumber](https://github.com/martinvigo/email2phonenumber) and [socialscan](https://github.com/iojw/socialscan)
