### ISSUE TITLE
"$ python3 -m pip install -r requirements.txt" returns "/usr/bin/python3: No module named pip"

### ISSUE THREAD

**Issue by Yeetomeister** [sherlock-project/sherlock#757]
![Skjermbilde](https://user-images.githubusercontent.com/62328907/93190564-cf3d6c00-f743-11ea-82f6-53b7502837e4.PNG)
I'm all new to using linux, and i have it currently installed on a virtual computer. All help would mean a lot.

**Comment by sdushantha** [comment]
@Yeetomeister You need to install `pip` first. I'm guessing that you are using Ubuntu or a distro that uses `apt`.
Run the commands below to install `pip`
```
$ sudo apt update
$ sudo apt install python3-pip
```
