### ISSUE TITLE
otzovik

### ISSUE THREAD

**Issue by Prajwal-Koirala** [sherlock-project/sherlock#759]
someone remove it.

**Comment by sdushantha** [comment]
@Prajwal-Koirala I am closing this issue as it lacks information. The title tells us nothing and the the description contains no detail. By just saying "someone remove it" tells us nothing about why we should remove that site.

In the future, please put more effort in the issues you create.

**Comment by hihouhou** [comment]
Could you remove it ?

```
bash /tmp/toto.sh
otzovik.com
blue noonewouldeverusethis7
507 507
507 507
507 507
507 507
507 507
507 507
507 507
507 507
507 507
507 507
507 507
507 507
507 507
507 507
507 507
```

```
cat /tmp/toto.sh
#§/bin/bash
echo "otzovik.com"
echo "blue noonewouldeverusethis7"
while true ; do echo $(curl -o /dev/null -w "%{http_code}" -s "https://otzovik.com/profile/blue") $(curl -o /dev/null -w "%{http_code}" -s "https://otzovik.com/profile/noonewouldeverusethis7"); sleep 10;done
```

there is no diff between exist or not...
