### ISSUE TITLE
linkedin false positive

### ISSUE THREAD

**Issue by Flairings** [sherlock-project/sherlock#762]

**Comment by 700sid** [comment]
Yes i also got false positive in linked in i dont know why but i got false positive

**Comment by satrio-hw** [comment]
Hi, this is my first time in this project...
I tried to look in at this issue, and I found that, we are unable to open link profile without authentication (login or checkpoint using captcha if no valid session)..

I tried to execute `python sherlock -l noonewouldeverusethis7 --print-all` with my personal LinkedIn profile session, and `requests` content returned the same result (text and status_code) whether username claimed or not..
LinkedIn will redirect URL to https://www.linkedin.com/in/unavailable/ for unclaimed username, I'm trying to look a way to handle this (with assumption authentication problem handled) but still got nothing for now..

I'm not quite sure, but I think whether facilitate LinkedIn search with API from LinkedIn or remove LinkedIn from `data.json`.. Please kindly give me a feedback, in case there is something that I miss..

cc: @sdushantha

**Comment by 700sid** [comment]
> Hi, this is my first time in this project...
> I tried to look in at this issue, and I found that, we are unable to open link profile without authentication (login or checkpoint using captcha if no valid session)..
> 
> I tried to execute `python sherlock -l noonewouldeverusethis7 --print-all` with my personal LinkedIn profile session, and `requests` content returned the same result (text and status_code) whether username claimed or not..
> LinkedIn will redirect URL to https://www.linkedin.com/in/unavailable/ for unclaimed username, I'm trying to look a way to handle this (with assumption authentication problem handled) but still got nothing for now..
> 
> I'm not quite sure, but I think whether facilitate LinkedIn search with API from LinkedIn or remove LinkedIn from `data.json`.. Please kindly give me a feedback, in case there is something that I miss..
> 
> cc: @sdushantha 

Bro removing linked in is the best option i thought, because linked in not create link through username, they create link through some another algorithm, so trying to solve this issue is waste of time, i think.

Even if you want to find a solution, best of luck.

**Comment by hoadlck** [comment]
We have already had problems in linkedin, and it was removed to the [bad area](https://github.com/sherlock-project/sherlock/blob/master/removed_sites.json).  What is it doing back in Sherlock?

We have enough problems as it is:  why re-include problems we already discovered?

**Comment by 700sid** [comment]
> We have already had problems in linkedin, and it was removed to the [bad area](https://github.com/sherlock-project/sherlock/blob/master/removed_sites.json).  What is it doing back in Sherlock?
> 
> We have enough problems as it is:  why re-include problems we already discovered?

That's right

**Comment by sdushantha** [comment]
> What is it doing back in Sherlock?

I think there was a PR a few months ago where someone was able to find a fix for the false positive and it seemed to work then. 

I think it's best we just remove it again and never add it back because as @700sid stated:
> linked in not create link through username, they create link through some another algorithm, so trying to solve this issue is waste of time, i think.
