### ISSUE TITLE
Instagram false positive

### ISSUE THREAD

**Issue by Flairings** [sherlock-project/sherlock#764]

**Comment by satrio-hw** [comment]
hi @Flairings , I would like to try to solve this, can you provide me with an example of false positive case?
I've tried `python3 sherlock -l blue` and `python3 sherlock -l noonewouldeverusethis7`. Both give appropriate output (return "not found" and status "available" for username "noonewouldeverusethis7", status "claimed" and return an active link for username "blue")

**Comment by tdh8316** [comment]
Could you check why Instagram returns false positive to Sherlock?
When I send the get request using Python and the requests library, it returns 404 appropriately.

```python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get("https://instagram.com/noonewouldeverusethis7")
<Response [404]>
>>>
```

And therefore, Instagram is also available for [Investigo](https://github.com/tdh8316/Investigo).
