### ISSUE TITLE
Web interface - service 2 - search if the username is available so that user can use it.

### ISSUE THREAD

**Issue by JinsooRoh** [sherlock-project/sherlock#767]
Generally user is also interested to know if the username is already claimed by others or not.

if the username is unclaimed then the user can have same username at different platforms.

**Comment by bG9sIHVyIGhvbW8** [comment]
Sherlock already does that.

If a username is claimed, it'll let you know. If a username is unclaimed/prohibited, it'll be excluded from the results (unless you use --print-all).
