### ISSUE TITLE
question: "has anyone checked the validity of the results by querying own credentials" ? 

### ISSUE THREAD

**Issue by marxenegls** [sherlock-project/sherlock#770]
i can confidently say i do not have a gotinder account, no wattpad , no  facebook nor twitter account  yet my gmail has,  it seems ..
But How  ?
 are mx records publicly available, scrapers and spammer or there's some related connection to anyone i might have emailed or even called ..
but the app/script  doesn't run checks via "mxtools" ,"riskiq" or at "haveibeenpawned"  it asks the sites themselves if members/users are registered and have a an actual account and page to access it..
right ?

i can only imagine how uncomfortable a situation one could land in by jumping to conclusions

**Comment by sdushantha** [comment]
> has anyone checked the validity of the results by querying own credentials?

Yes, and I have found some false positives but they are in the processes of being fixed.
