### ISSUE TITLE
A few websites are showing false positive for any email address.

### ISSUE THREAD

**Issue by foo2rama** [sherlock-project/sherlock#771]
Hello,

I found some errors when doing a search via email address.  I double checked these with multiple obviously fake email addresses.

These sites seem to be showing false positives with any email address.  I verified that any email address in the URL bar will show a valid page.

facenama.com
cloob.com
rusfootball.info

These sites when manually searching say no account with that email yet show a positive. I am not sure what is going on here, it is not showing with an obviously fake email, this one may be ok.
trello.com 

These give back an error that username has invalid characters
opennet.ru

These give back no user
freelance.habr.com

**Comment by hoadlck** [comment]
Sherlock does not check for e-mail addresses: only usernames.

**Comment by foo2rama** [comment]
Right but a user name that looks like an email address  can happen on those sites and throws a false positive.  So put in input validation on the program?

I am not 100% sure that this is an edgecase.

**Comment by hoadlck** [comment]
If I try Football: https://www.rusfootball.info/user/thing@/ a user name is found.
If I try Football: https://www.rusfootball.info/user/thing/ a user name is not found.

If you look at the actual page, it acts like there is a user, but it does not show the username.  So, going by this one site, it appears that the site itself is not rendering the page properly.

It will take more research to see what is going on with the other sites you mentioned.  If the "@" is not valid for a username, we could add a regex check to make that an illegal name for that site.
