### ISSUE TITLE
4PDA false positive

### ISSUE THREAD

**Issue by mehtaarn000** [sherlock-project/sherlock#784]
While I was researching the Instagram false positive issue, I ran `python3 shelock.py iaugduygdfuygeuirbwiufbehibfiuwbefhewf`, which I literally just mashed my keyboard for, and it showed me a result for 4pda.ru. After going to the link, the website returned a "no search results". How do we investigate and solve these kinds of false positives?

**Comment by hoadlck** [comment]
It is all about digging into a given site.  

Sometimes, if you research, you can find documentation for acceptable usernames.  If we have that, then we can make a regular expression to filter them out.

Not sure if what you have found is something like that, or just a regular false positive.  We have certainly seen times where the site returns a different response for a unsupported username than it does for an illegal one.

**Comment by mehtaarn000** [comment]
Ok, great. I'll definitely look into that and try to find some sort of documentation.
