### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by fartboy789** [sherlock-project/sherlock#790]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "sherlock/__main__.py", line 32, in <module>
    import sherlock
  File "sherlock/sherlock.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

I get this error code whenever I try to use sherlock. These past weeks sherlock has worked wonderfully and had no issues in the slightest but all of a sudden it completely had stopped working and said my Python was outdated and that I needed 3.6 to use it. Then I installed 3.6 but then this issue just continues to appear. I use sherlock on a Kali Linux VM.  Now it just gives me this error code whenever I try to use it now. Would appreciate any help.

**Comment by sdushantha** [comment]
> ModuleNotFoundError: No module named 'requests'

It seems like you are missing the `requests` module. Make sure you have installed all the needed dependencies by running `python3 -m pip install -r requests.txt` from the `sherlock/` directory.

I am closing this issue as it is an issue with your environment and nothing to do with Sherlock.
