### ISSUE TITLE
When I use the command python3 sherlock user123 it just leaves a blank line and says the path again

### ISSUE THREAD

**Issue by YoBot389** [sherlock-project/sherlock#805]
The title is the entire problemo

**Comment by sdushantha** [comment]
@YoBot389 Could you please provide a screenshot of what is happening?

**Comment by YoBot389** [comment]
![image](https://user-images.githubusercontent.com/67032293/97103837-ce3f1900-16b7-11eb-818b-e174a016883d.png)
@sdushantha there you go

**Comment by sdushantha** [comment]
You have to run `python3 sherlock`. Notice that the `.py` extension is **not** included

**Comment by hoadlck** [comment]
Since this in Windows, I expect that `python` is correct.  But, you must not have Python installed correctly on your PC.  In any case, this is not an issue with Sherlock itself:  it is a problem with your environment.

**Comment by YoBot389** [comment]
![image](https://user-images.githubusercontent.com/67032293/97108445-44eb0f00-16d6-11eb-95cc-16bed8da46d9.png)
@sdushantha

**Comment by YoBot389** [comment]
@hoadlck 
I am sorry if I am annoying but could you please tell me a specific solution to install and stuff my (python) not sherlock.
