### ISSUE TITLE
False Negative with 'response_url' errorType

### ISSUE THREAD

**Issue by pkubiak** [sherlock-project/sherlock#806]
Hi,
I have noticed that some websites use case-insensitive usernames and perform redirect to the correct version when needed. 

Example:
```
https://profiles.wordpress.org/Blue/ -- 301 -> https://profiles.wordpress.org/blue/
```

Such situation is not correctly handled with `errorType == "response_url"`, which assume that redirect indicate UNCLAIMED username.

Using below testcase I found that affected websites are:

- PSNProfiles.com
- Quora
- ResearchGate
- VK
- WordPressOrg

```python
def test_username_case_normalization(self):
    for site, site_data in self.site_data_all.items():
        username = site_data["username_claimed"]
        url = site_data["url"].format(username.capitalize())

        headers = {
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0',
        }
        r = requests.get(url, headers=headers, allow_redirects=False)
        location = r.headers.get('Location')

        if location and username in location:
            self.username_check([username.capitalize()], [site], exist_check=True)
```

Problem probably has been introduced by: #128

**Comment by hoadlck** [comment]
Yet other websites are sensitive to case.

Perhaps we need a new attribute to a site?  Something that indicates if case matters in the username?  Then we could just adjust the case to always be lower before doing the query?  But, I think there are cases where the site will make the first letter capitalized, and the rest lower case.

This requires some thought.

**Comment by sdushantha** [comment]
Closing as we no longer use response_url
