### ISSUE TITLE
Having issues with starting sherlock

### ISSUE THREAD

**Issue by tomazcajnar** [sherlock-project/sherlock#811]
When I execute python3 sherlock.py username
it gives me bash: python3: command not found

Adding screenshot.

https://prnt.sc/v776fn

**Comment by stefangal** [comment]
Hi. Try: 
```
python sherlock.py username
```

instead "python3 sherl..."
as you installed the dependencies with 
python -m pip install ...

**Comment by sdushantha** [comment]
Since you are running sherlock from `~/sherlock`, make sure **not** to include the `.py` extension. So this is the command which you want to be running:
```
python sherlock username
```
