### ISSUE TITLE
Redirection when adding new website

### ISSUE THREAD

**Issue by mehtaarn000** [sherlock-project/sherlock#818]
In the midst of adding [Nitro Type](https://www.nitrotype.com/) to Sherlock, I was testing the website's response to an invalid username. However, the website redirected me back to the home page. For example, when I enter in the url for an already existing user [https://www.nitrotype.com/racer/blue](https://www.nitrotype.com/racer/blue) everything works fine. However if I enter [https://www.nitrotype.com/racer/noonewouldeverusethis](https://www.nitrotype.com/racer/noonewouldeverusethis), I'm redirected. How would you add this response in the data.json file?

**Comment by h20190563** [comment]
Have added the support for NitroType in #817

**Comment by mehtaarn000** [comment]
Ok great.
