### ISSUE TITLE
opennet reports false positive for usernames containing "-"

### ISSUE THREAD

**Issue by Grelo4ka** [sherlock-project/sherlock#825]
Example: SoulU4o-eUI7n

**Comment by pkubiak** [comment]
It also generate false negative for usernames containing "_". Example: https://www.opennet.ru/~RenamedUser_875743914

**Comment by pkubiak** [comment]
Fixed in https://github.com/sherlock-project/sherlock/pull/807/commits/6bd827b481fa6e4ffda0e772a6efb2f448ddd710
