### ISSUE TITLE
username doesn't find similar names

### ISSUE THREAD

**Issue by Meleeman01** [sherlock-project/sherlock#830]
i'll tried to look for my username, and it doesn't find variations i've noticed, but also, the urls in specifically some accounts are listed by userid rather than by username, if you happen to know a user id that would be helpful depending on the site you want to search, but i think having a similar names options would improve this.

**Comment by pkubiak** [comment]
Good idea :+1: Could you provide some examples of such variations?

**Comment by Meleeman01** [comment]
so i'm thinking something like numbers or common phrases, and capital or differen't casing matches added onto a user and ids and variations like "thisisusername" "username012" "itsmeusername" "ItSmeUsERnaME!" for finding a user_id some pages have consistent profiles and leave that information out in the open. i think it would be difficult to implement user_id association to names, and it might not be necessarily advantagous to sherlock and end up being noise.

**Comment by darvell** [comment]
You'd hit rate limiting really quick and how do you programmatically say how people change their usernames? If anything, I'd argue that you should starting with the email of your target and find the different aliases they use and use them. Sherlock doesn't exactly get to fuzzy match and we can't code the many stupid names people put online.

There was some ideas with using https://github.com/soxoj/socid_extractor to allow cross referencing but it seems the PR died for the most part.

**Comment by sdushantha** [comment]
Closing this because it is something we won't be adding to sherlock. If you really want this feature, you can always create your own script that generates alternative usernames and then passes them to Sherlock.
