### ISSUE TITLE
unable to use sherlock

### ISSUE THREAD

**Issue by badushaebrahim** [sherlock-project/sherlock#863]
## Checklist

- [ yes] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug
![Screenshot from 2020-11-13 12-46-21](https://user-images.githubusercontent.com/63869474/99039983-5bd2a200-25ae-11eb-9874-cfe2a37fe9e0.png)

## Description

WRITE DESCRIPTION HEREbro unable to install i use ubentu 2020 version

**Comment by sdushantha** [comment]
This is not a bug. This is the command you should be running:
```
python3 -m pip install -r requirements.txt
```
You accidently added a `$` in front of the command.
