### ISSUE TITLE
when i am doing python3 pip install -r requirements.txt

### ISSUE THREAD

**Issue by mrrobot-clone** [sherlock-project/sherlock#864]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [x] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE
it's showing this error:
ERROR: could not open requirements file: [ERRNO 2] no such file or directory: 'requirements.txt'

**Comment by sdushantha** [comment]
> If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)
