### ISSUE TITLE
ModuleNotFoundError: No module named 'requests_futures'

### ISSUE THREAD

**Issue by Niphasio** [sherlock-project/sherlock#865]
## Checklist

- [ x ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ x ] I've verified that I'm running the latest version of Sherlock
- [ x ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "sherlock/__main__.py", line 29, in <module>
    import sherlock
  File "sherlock/sherlock.py", line 20, in <module>
    from requests_futures.sessions import FuturesSession
ModuleNotFoundError: No module named 'requests_futures'

**Comment by sdushantha** [comment]
You checked off this from the checklist but it looks like you haven't tried checking for other similar bug reports because issue has been brought up many times in the past.
> - [x] I've checked for similar bug reports including closed ones

<br>
<br>

This also has nothing to do with Sherlock. The issue has to do with your environment.
