### ISSUE TITLE
Add type hints to all functions and methods.

### ISSUE THREAD

**Issue by jithin-renji** [sherlock-project/sherlock#869]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

Although this isn't *exactly* a feature request, it is the closest one I could find in the issue templates.

While adding type hints does not necessarily add any *new* functionality to Sherlock, it does improve the readability of the code quite significantly. If this is fine as per your code style requirements, I could work on it.

On the same note, it would also be extremely beneficial to have a `STYLE-GUIDE.md` file to document the accepted code style for this project, to keep everything consistent.

**Comment by jithin-renji** [comment]
@sdushantha shall I proceed with adding type hints?

**Comment by sdushantha** [comment]
Hey @jithin-renji,

Sorry for getting back to you so late.
I do agree that adding a style guide would be beneficial. Feel free to create a PR about the type hints and I'll review once I get some time :)

**Comment by jithin-renji** [comment]
> Sorry for getting back to you so late.

That's okay.

> Feel free to create a PR about the type hints and I'll review once I get some time :)

Great! I'll work on that.

**Comment by ppfeister** [comment]
Closing as types are _mostly_ added in recent versions, at least on the portion of the code that's exposed for scripted use

Some parts are incomplete but they are minor. PEP 561 compliance will come with #2277
