### ISSUE TITLE
Travellerspoint false positive

### ISSUE THREAD

**Issue by double128** [sherlock-project/sherlock#883]
## Checklist
- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a seperate issue for each site)

## Description
I've noticed recently that the site "Travellerspoint" always returns false positives for usernames. To my recollection, this was not occurring as of about 2-3 weeks ago. It seems that userpages on this site are returning 404s now, resulting in false positives.

```
python3 sherlock --site Travellerspoint blue
[*] Checking username blue on:
[+] Travellerspoint: https://www.travellerspoint.com/users/blue

python3 sherlock --site Travellerspoint noonewouldeverusethis7
[*] Checking username noonewouldeverusethis7 on:
[+] Travellerspoint: https://www.travellerspoint.com/users/noonewouldeverusethis7
```

**Comment by sdushantha** [comment]
This site has been dealt with and Sherlock no longer returns false positives :)
