### ISSUE TITLE
Script Hangs

### ISSUE THREAD

**Issue by zer0systems** [sherlock-project/sherlock#885]
## Checklist

- [ x] I'm reporting a bug in Sherlock's functionality
- [x ] The bug I'm reporting is not a false positive or a false negative
- [x ] I've verified that I'm running the latest version of Sherlock
- [x ] I've checked for similar bug reports including closed ones
- [x ] I've checked for pull requests that attempt to fix this bug

## Description

Whenever the -u switch (independent Tor circuit per request) is used the script hangs indefinitely and no hits are returned. I cannot re-create this issue when using the -t option, which appears to function correctly. I have attempted to alter the --timeout option when using the -u switch to no avail, assuming it may have been waiting on a request. Tor is installed and in the system PATH. Not really sure.

sherlock.py 0.13.0
Python HTTP for Humans.: 2.24.0
Python: 3.8.6

**Comment by zer0systems** [comment]
Some quick additional info: I Wiresharked the script's output and it's definitely using Tor, sending requests, and receiving them, but no out. All that is displayed is: "Checking username <user-name> on:" and a blinking cursor below. I've waited for hours and still no display/output.

**Comment by hoadlck** [comment]
Yes, there are problems with this support.  See "Tor Support On Windows & Linux" #373 for the details.

Do you have an instance of the Tor browser running when you do the Sherlock query?
