### ISSUE TITLE
-b

### ISSUE THREAD

**Issue by aertist** [sherlock-project/sherlock#887]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

-b is not working

**Comment by xsync3d** [comment]
This seems to have been solved. See #912

**Comment by xsync3d** [comment]
This seems to be in the works. See #912
