### ISSUE TITLE
If --csv output is chosen, output folder is ignored

### ISSUE THREAD

**Issue by agentzex** [sherlock-project/sherlock#888]
## Checklist

- [x ] I'm reporting a bug in Sherlock's functionality
- [x ] The bug I'm reporting is not a false positive or a false negative
- [x ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [x ] I've checked for pull requests that attempt to fix this bug

## Description

If csv flag is chosen, the output folder is being ignored. The result will be 2 files - the .txt file which will be stored in the chosen output folder and a .csv file which will just be stored in the current running path.
I expected that the csv file will be in the same outputfolder chosen by the user. lines 639-640 in sherlock.py

**Comment by hoadlck** [comment]
Thanks for the bug report.  It is fixed now.
