### ISSUE TITLE
Unable to update to latest site list

### ISSUE THREAD

**Issue by tonyscardina** [sherlock-project/sherlock#898]
I ran the update and the list of sites wasn't updates. I pulled the list from github and entered it into a new sites.md list, but i'm still getting results from the _old_ list that hangs after Zhihu

This is the command I ran to update: **python3.8 -m pip install -U -r /home/tony/Downloads/sherlock/requirements.txt**

**Comment by sdushantha** [comment]
Running the command above only updates the modules that are needed for Sherlock to run. If you want the latest version of Sherlock, you have to reclone or download it from this repo. We currently do not have an option to forcefully update Sherlock from the command line.
