### ISSUE TITLE
'__main__' issue

### ISSUE THREAD

**Issue by Astrofluke** [sherlock-project/sherlock#899]
## Checklist

- [ x] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

I've followed the instructions to install this tool into my Linux machine. But after running;

$ python3 sherlock --help

I get; 

/usr/bin/python3: can't find '__main__' module in 'sherlock'

Any help is appreciated. Thank you!

**Comment by VirenderNayal** [comment]
Hi,

I followed the instructions and install the tool in my system.

I ran the command :

$ python3 sherlock --help

I got the expected result with no problems.
I am using Kali Linux 2020 version on my system.

May I know which linux machine are you using?

**Comment by Astrofluke** [comment]
> Hi,
> 
> I followed the instructions and install the tool in my system.
> 
> I ran the command :
> 
> $ python3 sherlock --help
> 
> I got the expected result with no problems.
> I am using Kali Linux 2020 version on my system.
> 
> May I know which linux machine are you using?

Hey Virender, 

I'm using Kali 2020.3

**Comment by VirenderNayal** [comment]
> > Hi,
> > I followed the instructions and install the tool in my system.
> > I ran the command :
> > $ python3 sherlock --help
> > I got the expected result with no problems.
> > I am using Kali Linux 2020 version on my system.
> > May I know which linux machine are you using?
> 
> Hey Virender,
> 
> I'm using Kali 2020.3

I am also using the same version.

**Comment by Rovetown** [comment]
I'm on Windows and still get that error
