### ISSUE TITLE
Hi! I want to instal Sherlock in My iPad. Which program can help me?

### ISSUE THREAD

**Issue by bobafet779** [sherlock-project/sherlock#900]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [x] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE

**Comment by hoadlck** [comment]
Your question is the very definition of a tech support question.  You can search Google for Python IDEs on an iPad.  [Here](https://medium.com/dev-genius/my-top-python-ides-for-ipad-3f777023155c) is an early hit I saw on Google.
