### ISSUE TITLE
500px.com - false positive

### ISSUE THREAD

**Issue by goorkamateusz** [sherlock-project/sherlock#901]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [ ] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a seperate issue for each site)

## Description

https://500px.com/p/
False positive report.

Status form page: 200;
Message on page: "This page is no longer available";
I also tested for a completely random username.

**Comment by skandix** [comment]
I've been seeing this myself, one fix I've had in mind was to look at the responses on sites, for like 500px where it will respond with 200 OK if the username is valid or not. However, it will return ``This page is no longer available`` in the HTML, which I've seen on other sites from before, where one has to look for a certain string that will change depending on if the user/entity exists or not.

**Comment by maatiug** [comment]
The page is loaded async... In first request answer contain almost only JS script, so is realy dificult to analysing.

**Comment by sdushantha** [comment]
500px has been removed due to the false positives and because fix wasn't able to be found
