### ISSUE TITLE
Jeuxvideo.com 

### ISSUE THREAD

**Issue by ChaosJesus** [sherlock-project/sherlock#904]
## Checklist

- [x ] I'm reporting a website that is returning **false positive** results
- [x ] I've checked for similar site support requests including closed ones
- [ x] I've checked for pull requests attempting to fix this false positive
- [ x] I'm only reporting **one** site (create a seperate issue for each site)

## Description

WRITE DESCRIPTION HERE
http://www.jeuxvideo.com/profil/chaosjesus?mode=infos

I ran the script often this night and this site was very often false Positive

**Comment by enodr** [comment]
Hi,

I confirm this website can return 403 status from some IPs which is interpreted as user existing. Can the logic be improved for this site?
