### ISSUE TITLE
[site_list.py] change numbering to reduce commit size

### ISSUE THREAD

**Issue by jguddas** [sherlock-project/sherlock#909]
letting the markdown renderer do the counting lets us reduce commit size and avoide possible merge conflicts.

---

```
1.
1.
1.
```
renders to:

1.
1.
1.

**Comment by jguddas** [comment]
Should be close if #911 is merged.

**Comment by sdushantha** [comment]
That is really smart! I have merged #911 which fixes this issue 👍
