### ISSUE TITLE
Twitter always returns "not found!" Even though the username exists

### ISSUE THREAD

**Issue by Cheeewa** [sherlock-project/sherlock#913]
## Checklist

- [x] I'm reporting a website that is returning **false negative** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false negative
- [x] I'm only reporting **one** site (create a seperate issue for each site)

## Description

For example, I can access these following Twitter accounts using mobile.twitter.com/username 
To name a few: officialmcafee, avast_antivirus, Deadpool, etc. But the results in Twitter field are always Not Found!
I also checked the data.json and the URL seems to be correct.

**Comment by thesusian** [comment]
I just wanted to point out that the problem is still present

**Comment by sdushantha** [comment]
Twitter has been fixed :)
