### ISSUE TITLE
Different outputs on CloudShell

### ISSUE THREAD

**Issue by goorkamateusz** [sherlock-project/sherlock#915]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

I have a lot of false positive answer when I use Sherlock on Cload Shell, for example:
- Instagram;
- Quizlet;
General `status_code` and `message` `errorType` conditions site.

When I run Sherlock on Win10 number of false positive are smaller.

I forked repo and commit some changes but I've problem with tested, because I don't know what tests are correct.

Is a configuration problem? Can I do something with that or use other cloud shell?

![image](https://user-images.githubusercontent.com/52463898/102897236-f654b980-4467-11eb-8895-f8757a7f9c3b.png)

**Comment by sdushantha** [comment]
This is an odd behavior and I am pretty sure it has been fixed as we use another endpoint to do the checking :+1:
