### ISSUE TITLE
no validation of sites.md and data.json in pull request workflow

### ISSUE THREAD

**Issue by jguddas** [sherlock-project/sherlock#918]
We should check:

1. When a PR alters the `data.json` that it is done so in accordance with the formatting provided by `./site_list.py`.
2. When a PR adds or removes support for a site that the `sites.md` file is updated and formatted correctly.

Possible solution:

Adding a `site_list.py` step to the PR workflow with a new `--fail-on-update` option that exits with status code `1` when the formatting differs.

**Comment by sdushantha** [comment]
We have now added a Github Action for this :partying_face: 
The `site_list.py` automatically gets executed when a PR is made where `data.json` is modified
