### ISSUE TITLE

Pass

### ISSUE THREAD

**Issue by anonimus1125** [sherlock-project/sherlock#924]
## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [ ] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by hoadlck** [comment]
Looks like an attempt to generate activity against this user id to make it look more legit.  I reported the id.
