### ISSUE TITLE
Can we have a GUI

### ISSUE THREAD

**Issue by Couragecoininc** [sherlock-project/sherlock#930]
## Checklist

- [x ] I'm reporting a feature request
- [ x] I've checked for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

**Comment by KingWilliamWC** [comment]
What sort of data would you like to see presented in the GUI to the user, would it just be the results or an input box where you enter the username (or usernames) and see the results

**Comment by ClassicVWnetwork** [comment]
Yes I think If you had pwa or even on a website being able to enter user name and get the results would possibly bring more users into the project and possibly more contributing to the development.

**Comment by KingWilliamWC** [comment]
@ClassicVWnetwork A website you say? interesting, I'll have a look at getting that implemented, thanks for the suggestion!

**Comment by ClassicVWnetwork** [comment]
I would love to offer a web address if your interested https:// sherlock.killscam.org I have others to just let me know.

**Comment by YeaToast** [comment]
> I would love to offer a web address if your interested https:// sherlock.killscam.org I have others to just let me know.

website doesn't exist, also it sounds like a scam

**Comment by robertsaustin** [comment]
no it does not exist yet im offering it to use for the project and I'm not scam

**Comment by robertsaustin** [comment]
temp site up

**Comment by robertsaustin** [comment]
there you jackie website is there

**Comment by danbeech** [comment]
Last week I knocked together a simple express server that spins up a child process of sherlock. Linked it with a simple front end using Vue (text field and a button, table to display results, button to open links in new tab).
Host on digitalocean droplet and it works fine as a personal API! 
Doesn't scale though (at least my implementation doesn't), after a couple of concurrent child processes you'll get gateway timeouts coming at you from all directions haha.

**Comment by sdushantha** [comment]
A web GUI is being worked on https://github.com/sherlock-project/api/pull/2
