### ISSUE TITLE
Deleting .txt

### ISSUE THREAD

**Issue by JosephCordero** [sherlock-project/sherlock#932]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE
I'm pretty new to this kind of stuff and I'm not too sure but is there a way to delete the .txt files from the ppl you looked up or no?

**Comment by KingWilliamWC** [comment]
You couldn't just go to where the file is stored and press delete on the keyboard?

**Comment by JosephCordero** [comment]
> You couldn't just go to where the file is stored and press delete on the keyboard to delete the file?

I'm new to this stuff so don't officially know what you mean but I tried to remove them and I'm getting permission denied

**Comment by KingWilliamWC** [comment]
What OS are you on (just curious)?

**Comment by JosephCordero** [comment]
I'm on windows using Kali Linux
