### ISSUE TITLE
help to solve sherlock running problem

### ISSUE THREAD

**Issue by beesuns** [sherlock-project/sherlock#933]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [x] My question is not a tech support question.

## Problem
First try:
```
kali@kali:~/Templates/sherlock$ python3 sherlock user123
A problem occured while checking for an update: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/sherlock.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f37b4f1d400>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/resources/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f37b4f2cbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I assumed that maybe it was my network that caused the problem, then I tried with --proxy. Of course I have always used proxy to get access to the internet and it worked just fine. `kali@kali:~$ chromium --proxy-server="socks5://127.0.0.1:1089"`
```
kali@kali:~/Templates/sherlock$ python3 sherlock user123 --proxy socks5://127.0.0.1:1089
A problem occured while checking for an update: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/sherlock.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f70bc8df400>: Failed to establish a new connection: [Errno 111] Connection refused'))
Using the proxy: socks5://127.0.0.1:1089
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/resources/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f70bc8eebe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
## Sherlock version
```
kali@kali:~/Templates/sherlock$ python3 sherlock --version
sherlock 0.14.0
Python HTTP for Humans.:  2.25.0
Python:  3.9.1
```
## Question

1. what caused the problem?
2. how to fix it?

## Is there any chance that this was due to Kali Linux? Because sherlock kept not working after I reinstalled kali linux, however, it worked flawlessly on my mac.

**Comment by sdushantha** [comment]
This is an issue with your environment and not Sherlock.

**Comment by harithalsultan** [comment]
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  name 'requests' is not defined
how can i solve it

**Comment by MrDakrEntity** [comment]
> ERROR: Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json': name 'requests' is not defined how can i solve it

i have the same exact problem

**Comment by BaddarkSky** [comment]
> > ERROR: Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json': name 'requests' is not defined how can i solve it
> 
> i have the same exact problem

i have also the problem
