### ISSUE TITLE
Add ruqqus.com

### ISSUE THREAD

**Issue by IThinkImOKAY** [sherlock-project/sherlock#934]
- [x] I'm requesting support for a new site
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked that the site I am requesting has not been removed in the past and is not documented in [removed_sites.md](https://github.com/sherlock-project/sherlock/blob/master/removed_sites.md)
- [x] The site I am requesting support for is not a pornographic website
- [x] I'm only requesting support of **one** website (create a seperate issue for each site)

## Description

URL: https://ruqqus.com

**Comment by IThinkImOKAY** [comment]
This project is 100% dead, so no need for this issue anymore.

**Comment by IThinkImOKAY** [comment]
The last commit was over 100 days ago. A lot of bugs "being fixed", I see.

**Comment by hoadlck** [comment]
The project *is* mostly dead.  When it rises from its unquiet grave, it will be focused on bug fixes.
