### ISSUE TITLE
Traceback (most recent call last): File "sherlock.py", line 20, in <module>     from requests_futures.sessions import FuturesSession

### ISSUE THREAD

**Issue by Jannik44** [sherlock-project/sherlock#935]
whats this? [look in the title], it gives me this error:

`Traceback (most recent call last): File "sherlock.py", line 20, in <module>     from requests_futures.sessions import FuturesSession`

what i have to do?

**Comment by KingWilliamWC** [comment]
Have you installed the package requests_futures? if not run:
 `pip install requests_futures`
