### ISSUE TITLE
Shows not existing accounts

### ISSUE THREAD

**Issue by B4tuhanY1lmaz** [sherlock-project/sherlock#941]
Hello developers.
I installed this tool and started to hunting accounts and i saw a very important bug.
It shows some unexisting accounts for Badoo, ICQ, TikTok, Realmeye, Gravatar and Travellerspoint.
I tried with different usernames and it still shows this accounts and when i go to account link i getting a 404 error becouse there is no account with this name.

**Comment by Frany6710** [comment]
### Me too

there´s a list from all 404 websites

## Websites

- badoo.com
- 500px.com
- pling.com
- travellerspoint.com
- realmeye.com
- icq.im

## IMPORTANT NOTE!!!!!

### **`I use windows subsystem for linux`**

## Screenshot

![screen](https://user-images.githubusercontent.com/61435815/104081129-65256700-520b-11eb-965c-efeb0ed7c44b.png)

**Comment by thesusian** [comment]
Same problem on Linux.

**Comment by ttv-abook** [comment]
i also have the same issue until now i even reinstalled the repo

**Comment by Owl0007** [comment]
I want to lean all this.. am a beginning and have no idea about all this. I will really love to lean so i can bug hunter and earn some honest and legal funds.

**Comment by sdushantha** [comment]
Fixes have been made and Sherlock no longer returns any false positives :)
