### ISSUE TITLE
Created web interface (#540) and web API (#129) of sherlock

### ISSUE THREAD

**Issue by yhay81** [sherlock-project/sherlock#943]
I created web interface (#540) and web API (#129) of sherlock. And  I would love if someone use it.

https://socialpedia.net/
https://api.socialpedia.net/v0/redoc 

On the way to create this, I feel that it is pretty good if sherlock can be installed from pypi(#353) or just has installable structure. I think I can help for this if it is okay with maintainers.
If there are some demand, I can release the core part of api via GitHub as OSS (I used FastAPI as a framework.)

**Comment by Yey007** [comment]
I just want to let you know that I tried this and i got internal server errors.

**Comment by yhay81** [comment]
@Yey007 Thank you for replay. Sometimes it returns 500 in my env, too.
And this is server log `HttpError: request to https://api.socialpedia.net/v0/accounts/yhay81 failed, reason: getaddrinfo ENOTFOUND api.socialpedia.net`

I just change DNS record of api.socialpedia.net just today.
It seems fail of name resolution, and I guess it takes a few more hours to be stable.

**Comment by soxoj** [comment]
Do you consider other tools for a core of Socialpedia? I propose [Maigret](https://github.com/soxoj/maigret), it's a Sherlock fork with >2K sites, it [can be installed from pypi](https://pypi.org/project/maigret/) and there is [actual examples](https://github.com/soxoj/maigret-tg-bot) of using it as a library.

**Comment by yhay81** [comment]
@soxoj Thank you for introducing.
It seems good choice.

There are also some candidate.

- #954 : I also created pypi package. It is fork of sharlok.
- https://github.com/mxrch/GHunt
- https://github.com/qeeqbox/social-analyzer

I imagine it would be great if all information can gather in one website with all these tools.
But my project seems not popular or no demands so far.

**Comment by sdushantha** [comment]
I am currently developing a newer version of Sherlock that will be modular so that it can be available on PyPi, have an Python and web API and possibly a web interface. Therefore I will be closing this as this is not something I will be doing with the current version of Sherlock
