### ISSUE TITLE
Not Searching

### ISSUE THREAD

**Issue by JosephCordero** [sherlock-project/sherlock#946]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [ ] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

ASK YOUR QUESTION HERE
Hey I just recently started using Sherlock again and for some reason, it's not working anymore I typed in different names to see if it was just a name problem and it wasn't.  Any idea what I should do?

**Comment by Spl01ter** [comment]
Same here.
Been stuck here for 30 minutes...
 $ python3 sherlock.py --print-found sherlock-project         
[*] Checking username sherlock-project on:

[nothing...]

**Comment by Spl01ter** [comment]
$ python3 sherlock.py sherlock-project 
[*] Checking username sherlock-project on:

**Comment by sdushantha** [comment]
Thank you for letting us know about this issue. This issue was caused because Ebay taking way too long for returning a response. I have fixed this issue by removing Ebay from the list of supported sites.

**Comment by JosephCordero** [comment]
> Thank you for letting us know about this issue. This issue was caused because eBay taking way too long for returning a response. I have fixed this issue by removing eBay from the list of supported sites.

Okay, so it should be working now? or do I need to update it?
also thanks for getting back to us some people don't ever

**Comment by sdushantha** [comment]
@JosephCordero You don't need to update anything. Just rerun the Sherlock and everything should be working fine :)

**Comment by JosephCordero** [comment]
Okay thank you
