### ISSUE TITLE
timeout feature

### ISSUE THREAD

**Issue by MaKiPL** [sherlock-project/sherlock#949]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

Hi,
Looks like the sherlock has no timeout- meaning that it will try to make requests infinitely resulting in hanging whole process if some site is down. I can't also keyboardInterrupt the process- I need to close whole window/terminal to kill the script.
As for now the script is unusable for me as it hangs on some sites and I can't continue.

**Comment by hoadlck** [comment]
There is a `--timeout` option to set a smaller timeout.

But, yeah, it is a problem.  Some sites are very slow for some people (depending on where they are located).  This is an area that needs work.

**Comment by MaKiPL** [comment]
Unfortunately there's no such option. I cloned the repo today and tried using the `--timeout` but:
`sherlock.py: error: unrecognized arguments: --timeout`

**Comment by sdushantha** [comment]
@MaKiPL I just cloned the repo and tried running `python3 sherlock --timeout 3 sdushantha` and no errors were given.

By the way, it's `sherlock` and not `sherlock.py`

**Comment by MaKiPL** [comment]
Ok, I'm sorry, I was using old version- Cloned again and tried the --timeout feature, but it doesn't seem to actually work. 

I ran:
`python3 sherlock --timeout 1 --print-all makipl`
and it doesn't seem to care about it. It just freeze after several sites

**Comment by MaKiPL** [comment]
Okay, it started to work now. I don't know what happened. I'm closing the issue, I'm sorry.

**Comment by MaKiPL** [comment]
Sorry for spamming but actually timeout doesn't seem to work at all. I can record video- would that help?

**Comment by RPwnage** [comment]
So you're running 
```python3 sherlock --timeout <timeout_seconds> <your args here>```
and it doesn't make use of the given timeout?

**Comment by MaKiPL** [comment]
> 
> 
> So you're running
> `python3 sherlock --timeout <timeout_seconds> <your args here>`
> and it doesn't make use of the given timeout?

I'm deeply sorry- despite my experience I acted like a total newbie- of course it works correctly- it was purely my fault- I pulled the newest code but worked on the old one...
