### ISSUE TITLE
socialname as fork of sherlock

### ISSUE THREAD

**Issue by yhay81** [sherlock-project/sherlock#954]
## Question

Thank you for greatly helpful project.

I need pypi package of sherlock, so I created copy and released it as pypi package in another name; **socialname**.

GitHub: https://github.com/yhay81/socialname
PyPI: https://pypi.org/project/socialname/

I made much refactoring but functionality is almost same as sherlock.
It can be installed via `pip` and used from other scripts.
Especially, any check logic can be easily inserted per social sites.

If you maintainers like the structure or style of `socialname`,
I am willing to stop developing it and help you to merge it into `sherlock`. (only if you like)
Or I am even happy if just some part of them help sherlock.

hope you like it.

**Comment by sdushantha** [comment]
Thank you for you hard work! I am currently in the process of doing some cleanup in the code and the repo as a whole. At the same time, I am also developing a new version of Sherlock which will have better code and be available on PyPi and other package managers
