### ISSUE TITLE
ICQ False Positive

### ISSUE THREAD

**Issue by Spl01ter** [sherlock-project/sherlock#959]
## Checklist
- [* ] I'm reporting a website that is returning **false positive** results
- [ *] I've checked for similar site support requests including closed ones
- [ *] I've checked for pull requests attempting to fix this false positive
- [ *] I'm only reporting **one** site (create a seperate issue for each site)

## Description

WRITE DESCRIPTION HERE
Username: doorsandic
Output: https://icq.im/doorsandic
URL returns: "Profile not found"

**Comment by sdushantha** [comment]
ICQ no longer returns false positives.
