### ISSUE TITLE
Steamid.uk Cloudflare captcha

### ISSUE THREAD

**Issue by Spl01ter** [sherlock-project/sherlock#961]
## Checklist

- [x ] I'm reporting a website that is returning **false positive** results
- [x ] I've checked for similar site support requests including closed ones
- [ x] I've checked for pull requests attempting to fix this false positive
- [ x] I'm only reporting **one** site (create a seperate issue for each site)

## Description
Steamid.uk uses hCaptcha, resulting in false positives

**Comment by sdushantha** [comment]
Thank you for reporting this. I have removed Steamid.uk in 5352036e80253594ce79859c9310fa947e88c4b0
