### ISSUE TITLE
Short list of false positives

### ISSUE THREAD

**Issue by Spl01ter** [sherlock-project/sherlock#962]
## Checklist

- [x ] I'm reporting a website that is returning **false positive** results
- [ x] I've checked for similar site support requests including closed ones
- [ x] I've checked for pull requests attempting to fix this false positive
- [ ] I'm only reporting **one** site (create a seperate issue for each site)

## Description
Here are the false positives:
Steamid
Quizlet
NameMC
ICQ

**Comment by beaudierman** [comment]
I can confirm these and also add:
Chess
ProductHunt

**Comment by NaimVerboom** [comment]
> I can confirm these and also add:
> Chess
> ProductHunt

These exact same websites also give me false positives.

**Comment by paulvpm3** [comment]
Adding:

https://mobile.twitter.com/

Plus the ones above all seem to give me a false positive.

**Comment by vladmdigital** [comment]
fortnitetracker.com is also giving false positive.

**Comment by acheong08** [comment]
Here:
Cent
Chess
ICQ
ProductHunt
NameMC
Spotify
Steamid
Quizlet
TikTok
Twitter

All giving false positives

**Comment by GovindKrishnan** [comment]
Adding YouTube

**Comment by sdushantha** [comment]
> I'm only reporting one site (**create a seperate issue for each site**)
