### ISSUE TITLE
I created a video on Sherlock

### ISSUE THREAD

**Issue by Retro64XYZ** [sherlock-project/sherlock#963]
## Checklist

- [x] I'm asking a question regarding Sherlock
- [x] My question is not a tech support question.

**We are not your tech support**. 
If you have questions related to `pip`, `git`, or something that is not related to Sherlock, please ask them on [StackOverflow](https://stackoverflow.com/) or [r/learnpython](https://www.reddit.com/r/learnpython/)

## Question

https://www.youtube.com/watch?v=oUEHAhQRU_k

I have created a YouTube video related to installing and using Sherlock. Would this be something you all would be interested in adding to your website or to the README file for people to watch if they are interested in the project?

**Comment by sdushantha** [comment]
Thank you for taking the time and creating a YouTube video, I enjoyed watching it! Unfortunately adding a tutorial video to our README is not something we want to add.
