### ISSUE TITLE
Problem runing sherlock.py

### ISSUE THREAD

**Issue by TTVGrizzly** [sherlock-project/sherlock#966]
## Checklist

- [ ] I'm reporting a bug in Sherlock's functionality
- [ ] The bug I'm reporting is not a false positive or a false negative
- [ ] I've verified that I'm running the latest version of Sherlock
- [ ] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

sherlock.py: line 18: import: command not found
from: can't read /var/mail/requests_futures.sessions
from: can't read /var/mail/torrequest
from: can't read /var/mail/result
from: can't read /var/mail/result
from: can't read /var/mail/notify
from: can't read /var/mail/sites
sherlock.py: line 27: module_name: command not found
sherlock.py: line 28: __version__: command not found
sherlock.py: line 33: syntax error near unexpected token `('
sherlock.py: line 33: `class SherlockFuturesSession(FuturesSession):'

**Comment by RPwnage** [comment]
How did you execute Sherlock?
Did you execute `python sherlock`?
