### ISSUE TITLE
Can't install extra libraries included in requirement.txt

### ISSUE THREAD

**Issue by shantanurathod** [sherlock-project/sherlock#967]
I can't install the useful Libraries which are in requirements.txt through Command Prompt on my Windows 10 system. I cloned the repository , then wrote command "cd sherlock", then the last command to install libraries listed in requirement.txt. There are no errors but output is blank, my terminal didn't run the command. And also I checked that might be the it install libraries so I initiate the command to run the sherlock but it too didn't given same blank output when I pressed Enter. Please Help

**Comment by VirenderNayal** [comment]
Hi, @shantanurathod  

I have tried it.

I think pip is installed in python in windows and not in python3.

Try `python -m pip install -r ./requirements.txt`

Here is the Screenshot.

[
![Screenshot 2021-02-18 112418](https://user-images.githubusercontent.com/72212823/108312164-46d46300-71dc-11eb-8b71-1f93d8ec0513.png)
](url)

Hope it helps.

**Comment by shantanurathod** [comment]
Thanks a lot man! It solved my problem. Looking forward to learn from you
and follow programmers.
