### ISSUE TITLE
No module nAMED 3PIP , No moduled Named TorreQuest

### ISSUE THREAD

**Issue by Dats360** [sherlock-project/sherlock#968]
Hello, When I run the "script" In Kali linux I get this error And I don't know how to solve it :(, 
---------------------------------------------------------
                                                                                
┌──(dats360㉿dats360)-[~]
└─$ cd tools
                                                                                
┌──(dats360㉿dats360)-[~/tools]
└─$ git clone https://github.com/sherlock-project/sherlock
Clonando en 'sherlock'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 5084 (delta 3), reused 3 (delta 1), pack-reused 5072
Recibiendo objetos: 100% (5084/5084), 15.51 MiB | 5.08 MiB/s, listo.
Resolviendo deltas: 100% (3209/3209), listo.
                                                                                
┌──(dats360㉿dats360)-[~/tools]
└─$ cd sherlock                                
                                                                                
┌──(dats360㉿dats360)-[~/tools/sherlock]
└─$ python3 -m pip install -r requirements.txt
/usr/bin/python3: No module named pip
                                                                                
┌──(dats360㉿dats360)-[~/tools/sherlock]
└─$ python3 sherlock eldats                                                 1 ⨯
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dats360/tools/sherlock/sherlock/__main__.py", line 29, in <module>
    import sherlock
  File "/home/dats360/tools/sherlock/sherlock/sherlock.py", line 21, in <module>
    from torrequest import TorRequest
ModuleNotFoundError: No module named 'torrequest'
                                                                                
┌──(dats360㉿dats360)-[~/tools/sherlock]
└─$ remote: Counting objects: 100% (12/12), done.                                                                                                              1 ⨯
remote: Compressing objects: 100% (10/10), done.
remote: Total 5084 (delta 3), reused 3 (delta 1), pack-reused 5072
Recibiendo objetos: 100% (5084/5084), 15.51 MiB | 5.08 MiB/s, listo.
Resolviendo deltas: 100% (3209/3209), listo.
                                                                                
┌──(dats360㉿dats360)-[~/tools]
└─$ cd sherlock                                
                                                                                
┌──(dats360㉿dats360)-[~/tools/sherlock]
└─$ python3 -m pip install -r requirements.txt
/usr/bin/python3: No module named pip
                                                                                
┌──(dats360㉿dats360)-[~/tools/sherlock]
└─$ python3 sherlock eldats                                                 1 ⨯
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dats360/tools/sherlock/sherlock/__main__.py", line 29, in <module>
    import sherlock
  File "/home/dats360/tools/sherlock/sherlock/sherlock.py", line 21, in <module>
    from torrequest import TorRequest
ModuleNotFoundError: No module named 'torrequest'
                                                                                
┌──(dats360㉿dats360)-[~/tools/sherlock]
└─$        

--------------------------------------
:c Help me PLease ...

**Comment by sosolidkk** [comment]
The problem here is possibly because you didn't install any package at all. Your OS can't find pip to install the packages of the requirements.txt file. See the error message there:  `/usr/bin/python3: No module named pip`

**Comment by Dats360** [comment]
¡Thanks!
