### ISSUE TITLE
INPUT time bug.

### ISSUE THREAD

**Issue by asik124** [sherlock-project/sherlock#972]
## Checklist

- [x ] I'm reporting a bug in Sherlock's functionality
- [x ] The bug I'm reporting is not a false positive or a false negative
- [ x] I've verified that I'm running the latest version of Sherlock
- [x ] I've checked for similar bug reports including closed ones
- [ x] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE
When enter name of victim  (first  and  last name) 
This code run TWO time .
Ex- 
I enter name(first and last name)
$Python3 sherlock first-name last-name 
(This code RUNS TWO time on for first-name and on for last-name)
Show i got wrong information.
***plz fixed this bug ***
(This is my first bug reporting so .. if any fault by me .. plz comment)😄

**Comment by sdushantha** [comment]
This is not a bug. Sherlock does not support full names. It only supports username which should not have any spaces in them.
