### ISSUE TITLE
Instagram not found please make and update about it .

### ISSUE THREAD

**Issue by eldho-art** [sherlock-project/sherlock#977]
## Checklist

- [ ] I'm reporting a feature request
- [ ] I've checked for similar feature requests including closed ones

## Description

Not found please make and update about it .

**Comment by zangueblo** [comment]
how to do please I can not find Instagram afaik

**Comment by JDR11** [comment]
Instagram support was readded in commit 039debb.
Please close this issue.

**Comment by LittleOrion1** [comment]
Hi. Is Sherlock actually working on social medias like Instagram or Twitter? Because everytime I search, for example, my nickname, it never appears on those websites.
