### ISSUE TITLE
output time to long

### ISSUE THREAD

**Issue by white-glich** [sherlock-project/sherlock#978]
## Checklist

- [x] I'm reporting a bug in Sherlock's functionality
- [x] The bug I'm reporting is not a false positive or a false negative
- [x] I've verified that I'm running the latest version of Sherlock
- [x] I've checked for similar bug reports including closed ones
- [x] I've checked for pull requests that attempt to fix this bug

## Description

WRITE DESCRIPTION HERE

**Comment by Putnug1122** [comment]
i also face this kind of problem, what am i do is reinstalling the sherlock's

**Comment by jokerisme-123** [comment]
> i also face this kind of problem, what am i do is reinstalling the sherlock's

Try timeout it will ve faster and for reference watch networkchuck s video on youtube he has posted it recently
