### ISSUE TITLE
Allow Sherlock to search through Facebook much better

### ISSUE THREAD

**Issue by elsaversailles** [sherlock-project/sherlock#983]
## Checklist

- [x] I'm reporting a feature request
- [x] I've checked for similar feature requests including closed ones

## Description

Sherlock on Facebook is a bit hit or miss, specially if the user that your searching into changes his/her name. This make this script return false negative, because when you make Facebook account, your FB ID is permanent which is not effective if the user changes his/her name. Lastly, since there are many people that has the same name in Facebook. FB implemented  random number suffix to each FB profile ID which makes searching difficult.

**Comment by pranitspatil** [comment]
it can be enhanced by searching on Instagram first. 
step 1: finding an Instagram account.
step 2: get his name and profile image.
step 3: search on FB with the name and try to match his profile pic.

we can find them also with their bio.

**Comment by sdushantha** [comment]
With Sherlock's current structure your idea unfortunately cannot be implemented. I'm sure there are tool dedicated to Facebook OSINT which do what you have stated.
