### ISSUE TITLE
ProductHunt false positive

### ISSUE THREAD

**Issue by bsoyka** [sherlock-project/sherlock#988]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

Tested for false positives with a completely random username, one was ProductHunt. (Username `uevnfd5m7x6b83j8`)

**Comment by sdushantha** [comment]
this has been fixed
