### ISSUE TITLE
Spotify false positive

### ISSUE THREAD

**Issue by bsoyka** [sherlock-project/sherlock#989]
## Checklist

- [x] I'm reporting a website that is returning **false positive** results
- [x] I've checked for similar site support requests including closed ones
- [x] I've checked for pull requests attempting to fix this false positive
- [x] I'm only reporting **one** site (create a separate issue for each site)

## Description

Tested for false positives with a completely random username, one was Spotify. (Username `uevnfd5m7x6b83j8`)

**Comment by Dellsmell** [comment]
I can see this issue as well. Below are some of the usernames I tested.
I believe this issue has to do with Spotify's loading time when pulling up users. There again I might be 100% wrong.
##Usernames Tested
1. EliteGamer687
2. Dellsmell
3. Bobthebuilder
4. thisuserdoesnotexist245

**Comment by RealFinalCode** [comment]
The problem is that spotify loads the data of a user via JavaScript.

**Comment by sdushantha** [comment]
Spotify seems to have no false positive:
![image](https://user-images.githubusercontent.com/27065646/123540631-52163d00-d740-11eb-8234-70df36be0bc6.png)

Might have been a temporary issue.
