### ISSUE TITLE
DockerHub image is not getting updated

### ISSUE THREAD

**Issue by mxschmitt** [sherlock-project/sherlock#996]
The current one which is referenced in the README was last updated 2 years ago: https://hub.docker.com/r/theyahya/sherlock

Similar to #221

Action item: The DockerHub integration ([see here](https://docs.docker.com/docker-hub/builds/) for docs) needs to be updated so that automatic builds work. Maybe move it to a sherlock-project namespace on DockerHub?

**Comment by xescure** [comment]
Using Github Actions to build and push these images would solve this problem. Something like [this ](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md) should work flawlessly.

If the devs like the idea, I'll gladly make a pr.

**Comment by mxschmitt** [comment]
Docker Hub provides an automated solution to build and push the image, then there is no manual effort needed. Of course it's also implementable via GitHub Actions, but seems easier via the Docker Hub.

**Comment by xescure** [comment]
As far as I'm aware DockerHub doesn't natively support `armhf` and `arm64` images which are getting more and more important in the era of Raspberry Pis and M1 Macs. If we bother with fixing this whole thing, we might as well do it right.

**Comment by mxschmitt** [comment]
Good catch! Yeah then your approach would be the better one, I remember also things about that.

**Comment by sdushantha** [comment]
Hi @mxschmitt!

Thank you for letting me know about this issue. Unfortunately I have no experience with Docker but the maintainer of the Docker image is @TheYahya, so maybe he may be able to help out.

**Comment by ppfeister** [comment]
Sherlock is now on DockerHub under `sherlock/sherlock` with proper support
https://hub.docker.com/r/sherlock/sherlock

Documentation can be found via the Docker link on the README

Closing as resolved
